### ISSUE TITLE
Warnings on deploying with: php composer.phar install

### ISSUE THREAD

**Issue by ajira86** [movim/movim#1]
Just a short notice about those warning messages I received on deployment process, executing

``` sh
php composer.phar install
```

Returns

```
[...]

Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Writing lock file
Generating autoload files
```

**Comment by edhelas** [comment]
Linked with this issue https://github.com/reactphp/http/issues/24
We maybe have to change the composer.json to fix this

**Comment by edhelas** [comment]
This issue was moved to movim/movim#9

**Comment by edhelas** [comment]
After clearing the vendor directory and reinstalling everything this seems fixed ;)

**Comment by ajira86** [comment]
FYI: Still present in 0.10 with a fresh install
