### ISSUE TITLE
Atom feed : title -> content_link

### ISSUE THREAD

**Issue by axelos** [movim/movim#100]
Hello,

The tag #content_link (placeholder="http://myawesomewebsite.com/ or http://mynicepictureurl.com/") becomes the title of the article in the Atom feed.

By clicking on the title, it is redirected to the content of the link.

Cordialement, Axelos.

**Comment by edhelas** [comment]
I'm sorry I didn't understood the issue here.

**Comment by axelos** [comment]
Exemple :

Tu vas sur https://nl.movim.eu/?feed/edhelas@movim.eu avec Firefox, tu clic sur « S'abboner maintenant »

Dans les marques pages tu cliques sur l'article Movim + Munin, et tu tombes sur la page http://munin-monitoring.org/ au lieu de l'article.

**Comment by edhelas** [comment]
This issue was moved to movim/movim#3
