### ISSUE TITLE
Dialogs close according to position when mouse button is released

### ISSUE THREAD

**Issue by ltguillaume** [movim/movim#1003]
Dialog such as "Join a chatroom" are closed when clicking outside of it. This is fine, but apparently the cursor position when the left mouse button is _released_ (mouseup/touchend?) is used for this (instead of the position at the mousedown/touchstart event). As a result, e.g. when selecting text in a field, releasing the mouse button just a bit outside of the dialog will close it, and the user has to start all over again.

A simple fix would be to use the mouse cursor position at the mousedown/touchstart event.

**Comment by edhelas** [comment]
I can't actually reproduce the issue, in Dialog and Drawers selecting a text and releasing the click outside the element doesn't actually closes it :thinking:

**Comment by ltguillaume** [comment]
Edit a room, select your nickname starting from the right, then release the left mouse button to the left of the dialog.

I'm using (Ungoogled) Chromium

**Comment by ltguillaume** [comment]
Same goes for the `Add contact` dialog, for example:

![movim](https://user-images.githubusercontent.com/4777345/130370786-4e6f6b46-d17c-49a2-a053-24e8a1dad314.gif)

**Comment by edhelas** [comment]
Looks like Firefox and Chrome are not behaving the same way on that one :)

**Comment by edhelas** [comment]
This is a really specific edge case that is actually quite tricky to fix in Javascript, also only for Chrome based only browser. I'm not planning to fix it.

**Comment by ltguillaume** [comment]
I went through all the event listeners, disabled the ones most likely to cause the behavior, but I couldn't actually find it. Could you perhaps point me to the what listener triggers it? Perhaps I can fix it and create a PR.
