### ISSUE TITLE
Pubsub community publish problem

### ISSUE THREAD

**Issue by ticktostick** [movim/movim#1004]
Movim v0.19.1rc5 
ejabberd 21.01

1- Creating new node
2-Give who can publish to publishers
3-Give roles to  to 3 accounts as publishers
But
Only one of the publishers can publish, Owner and Others get "You cannot publish a post here"
subscription cannot done properly also st. nothing happens when trying to subscribe and st. it says It seems that this community doesn’t exists anymore after subscription is done

**Comment by ticktostick** [comment]
dug more

when user is not publisher the subscription works ok
when the user get publisher role then "It seems that this community doesn’t exists anymore"

**Comment by edhelas** [comment]
I followed the flow and everything seems to work as intended. Maybe try with a recent version of Movim.
Closing the ticket.
