### ISSUE TITLE
The creation of the database structure fails on a fresh install v0.19.1

### ISSUE THREAD

**Issue by Vertux** [movim/movim#1006]
I have started with a fresh install (git) and when I execute `php composer.phar movim:migrate` I get the following error:

```
> vendor/bin/phinx migrate --ansi
Phinx by CakePHP - https://phinx.org.

using config file phinx.php
using config parser php
using migration paths
 - /movim/database/migrations
using seed paths
 - /movim/database/seeds
warning no environment specified, defaulting to: movim
using adapter pgsql
using database movim
ordering by creation time

 == 20180314212906 CreateUrlsTable: migrating
ParseError: syntax error, unexpected ')' in /movim/vendor/illuminate/database/Schema/Grammars/PostgresGrammar.php:51
Stack trace:
#0 /movim/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/vhosts...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Illuminate\\Data...')
#2 /movim/vendor/illuminate/database/PostgresConnection.php(75): spl_autoload_call('Illuminate\\Data...')
#3 /movim/vendor/illuminate/database/Connection.php(235): Illuminate\Database\PostgresConnection->getDefaultSchemaGrammar()
#4 /movim/vendor/illuminate/database/PostgresConnection.php(62): Illuminate\Database\Connection->useDefaultSchemaGrammar()
#5 /movim/vendor/illuminate/database/Capsule/Manager.php(98): Illuminate\Database\PostgresConnection->getSchemaBuilder()
#6 /movim/src/Movim/Migration.php(21): Illuminate\Database\Capsule\Manager::schema()
[...CUT...]
```
PostgreSQL v9.6.22
PHP v7.3+/v7.4+

**Comment by Vertux** [comment]
I just did a a `git pull` and now `php composer.phar movim:migrate` runs fine. When I start Movim first everything looks fine, when I try to login it fails and the login page keeps endless reloading. The log shows the same ParseError like above:

```
movim.ERROR: ParseError: syntax error, unexpected ')' in /movim/app/widgets/Chats/Chats.php (line 28) Trace #0 /movim/src/Movim/Widget/Wrapper.php(35): Movim\Widget\Wrapper->loadWidget('Chats', true) #1 /movim/linker.php(39): Movim\Widget\Wrapper->registerAll(Array) #2 {main} [] []
movim.ERROR: setcookie() expects parameter 3 to be integer, array given in /movim/src/Movim/Cookie.php (line 43) Trace  [] []
PHP Warning:  setcookie() expects parameter 3 to be integer, array given in /movim/src/Movim/Cookie.php on line 43
```

**Comment by edhelas** [comment]
setcookie() expects parameter 3 to be integer

From https://www.php.net/manual/en/function.setcookie.php 

> Alternative signature available as of PHP 7.3.0:
> setcookie(string $name, string $value = "", array $options = []): bool

You don't have PHP7.3, Movim only support PHP 7.3 miniumum

**Comment by Vertux** [comment]
> You don't have PHP7.3, Movim only support PHP 7.3 miniumum

@edhelas That's not correct, I am running PHP 7.3x (and PHP 7.4x) also on the Apache side. Is it possible that a special PHP 7.3x setting triggers the error?  btw, do you have any idea regarding the ParseError ?

```
php --version
PHP 7.3.28 (cli) (built: Apr 30 2021 08:02:55) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.28, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.3.28, Copyright (c) 1999-2018, by Zend Technologies
```

Firefox console shows: 

`Das Cookie "MOVIM_SESSION_ID" wird in Zukunft bald abgelehnt werden, da es für das Attribut "SameSite" entweder "None" oder einen ungültigen Wert angibt, ohne das "secure"-Attribut zu verwenden. Weitere Informationen zum "SameSite"-Attribut finden Sie unter https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite. movim.xxxx.xx`

or in english

`The cookie "MOVIM_SESSION_ID" will soon be rejected in the future because it specifies either "None" or an invalid value for the "SameSite" attribute without using the "secure" attribute. For more information about the "SameSite" attribute, see https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite. movim.xxxx.xx`

P.S.: I am gonna do a new clean installation on the weekend to rule out any cursory errors on my part.

**Comment by Vertux** [comment]
> P.S.: I am gonna do a new clean installation on the weekend to rule out any cursory errors on my part.

@edhelas The new installation worked without any issue, sorry for the redundant issue report.
