### ISSUE TITLE
Does movim allow chats to be indexable via a search engine?

### ISSUE THREAD

**Issue by harryadel** [movim/movim#1008]
We're currently looking for a way to host our little technical community chat and we stumbled upon movim since we were looking for something that supports decentralized protocols (IRC or XMPP). 

Our criteria is as follows:
- Must be publicly accessible (indexed by search engines)
- Chats can be archived and saved for future use.
	This loops back to the first point if you can find it by a Google search, it's most likely to be 	cached by search engine and even by some 3rd party service (Wayback machine or archive.today). 
- Libre, decentralized and standards compliant network (IRC or XMPP).

Most of our searches so far has lead us to tools like Gitter and Spectrum which hits the mark when it comes to the first and second point but not so much on the third one. 

So, does movim support search engines indexing? Or can it be made to do so with expensive technical work arounds?
Also, given your experience with chats in general can movim be of a use in our situation or is it not suited for? If not, can you recommend other solutions? Thanks a lot for your help! :)

EDIT: just gave movim a test drive via https://mov.im/, is there a way to disable the social media aspects of the platform like news, explore and publish and only keep the chat part?

**Comment by poVoq** [comment]
Highly unlikely that Movim is the right tool for that.

The only thing that comes to my mind for those specifications is: https://github.com/indieweb/chat.indieweb.org

Edit: yes the social features can be disabled by the admin of a movim pod.

**Comment by harryadel** [comment]
@poVoq I see. Thanks a lot for your suggestion!

**Comment by edhelas** [comment]
No, and it's not the role of Movim? This can be done on the XMPP server level :)
