### ISSUE TITLE
Style Markdown-style quoted chat message

### ISSUE THREAD

**Issue by MaybeThisIsRu** [movim/movim#1013]
![image](https://user-images.githubusercontent.com/3974019/129446729-81ee39a7-11ef-4d0a-9100-3c4f5f5ab935.png)

The `>` portion should be styled as a blockquote. Most other clients do this.

**Comment by edhelas** [comment]
It should, is it encrypted message ?

**Comment by MaybeThisIsRu** [comment]
Yes, encrypted. This is when OMEMO on.

**Comment by edhelas** [comment]
I am not planning to re-add all the features of non-encrypted messages to encrypted ones as I need to implement things in PHP and Javascript side. This is not a "must have", therefore I prefer to keep the code simpler and don't add this feature for encrypted ones :p
