### ISSUE TITLE
Config not actually saved

### ISSUE THREAD

**Issue by MaybeThisIsRu** [movim/movim#1014]
On https://mov.im/?conf#config_widget_tab, saving the settings doesn't actually save them. For example, if you enable dark mode and navigate to some other view, such as chats, the dark mode won't apply.

Behaviour can be seen on both Chrome 92 and Firefox 91 on Windows 10.

**Comment by edhelas** [comment]
It does, what kind on XMPP server are you using ?

**Comment by MaybeThisIsRu** [comment]
Hmm, I'm using [Snikket](https://snikket.org/). What info would I need to take to them for this to be debugged at their end?

**Comment by edhelas** [comment]
I'm not 100% sure but Movim is using https://xmpp.org/extensions/xep-0049.html to save the configuration. Maybe this extension is not enabled on Snikket anymore (it's an old one).

**Comment by MaybeThisIsRu** [comment]
I'll check with them and see if they want to implement it at all. Thank you!
