### ISSUE TITLE
Reactions break styling with OMEMO on

### ISSUE THREAD

**Issue by MaybeThisIsRu** [movim/movim#1016]
With one reaction:

![image](https://user-images.githubusercontent.com/3974019/129446913-3a0ec9de-cf83-400e-a2b3-99bd62079fa5.png)

With many reactions:

![image](https://user-images.githubusercontent.com/3974019/129446919-937699ca-fba6-4373-9194-2481304b2f65.png)

With no reaction:

![image](https://user-images.githubusercontent.com/3974019/129446977-bce1477f-64ff-4d54-ac11-b2308631d122.png)

Notice the lock icon signalling OMEMO.

**Comment by edhelas** [comment]
This is a tricky one…
