### ISSUE TITLE
Visible Image Attachments for Blog Posts Summaries

### ISSUE THREAD

**Issue by psycotica0** [movim/movim#1018]
I've made a blog post and attached an image to represent the "social media" image.

What I would like is to show this image in the "summary" view in the news feed, along with the "Show More" button like you have it now.  If I include the image in the body at the top it's a bit weird, since people see the image, then they click "Show More" they're shown the image again on the next screen with some content below it. It seems like it would be nicer to just show them the content, at that point, and keep the attached image at the bottom like you already do.

Currently, in the "list" view there's no indication at all that there even is an attachment.

**Comment by edhelas** [comment]
This is a design choice, if the article is having a short text (< 700 characters https://github.com/movim/movim/blob/master/app/Post.php#L628)  the attached pictures are shown first.
