### ISSUE TITLE
Register no work

### ISSUE THREAD

**Issue by royalterra** [movim/movim#102]
hi I install first Movim for test in my server in one domain and look working . I delete all and install again in the definitive domain https://blablanet.eu all look OK but when I click register to API  no work any more

**Comment by royalterra** [comment]
I already check https://api.movim.eu/ I can't register my pod in the web not with a post request any one can help me please 
https://api.movim.eu/register/uri=https://blablanet.eu&rewrite that also report

{"status":404,"success":false}

**Comment by edhelas** [comment]
You have a button in the admin panel, did you tried this one too ?

**Comment by royalterra** [comment]
yes I try that too. I am wondering because before I make a install test with different domain but the seam IP if in anyway your system ban my ip. That can be more possible

**Comment by edhelas** [comment]
Ok I've removed your subscription, can you please try again ?

**Comment by royalterra** [comment]
OK I try again from the GUI and I got a message down in a pop up box say configuration update.
I believe now you will need to a probe manually

**Comment by royalterra** [comment]
Ok Good I login again and now say
Tu pod está registrado en la API
Tu pod no está validado aún

**Comment by edhelas** [comment]
Ok I'll try to validate it ASAP

**Comment by royalterra** [comment]
Hi edhelas sorry I not see your message in the chat before. Yes inboxw... I  have some dns problem after change provider anyway is a test domain. 
The domain blablanet.eu is the official we go to use.
Thanks

**Comment by royalterra** [comment]
Hi Edhelas I can confirm the API is working now . I see you link to the registration form from the partners
please consider add my registration form for new users https://blablanet.com/xmpp
