### ISSUE TITLE
Show current date (day) of messages when scrolling

### ISSUE THREAD

**Issue by ltguillaume** [movim/movim#1020]
It is currently really hard to find out the dates of messages:
1. The `li.date` is quite small and therefore easy to miss while scrolling through a room
2. Anywhere in between those `li.date`s there's nothing to show the date of the messages you're scrolling through.

I propose the following two improvements:
1. [For desktop] When hovering the mouse over the timestamp, show the date as tooltip, e.g. `Today` or `Wednesday, August 25`.
2. When scrolling through messages, show a tooltip underneath the `header` that shows the date of the messages below it, e.g. `Today` or `Wednesday, August 25`.

**Comment by edhelas** [comment]
I added the full date time when hovering the message time.
As I'm not planning to push more the feature further than that I prefer to close the ticket for now.

**Comment by ltguillaume** [comment]
> I added the full date time when hovering the message time.

This feature seems to be lost now.

**Comment by ltguillaume** [comment]
Thanks!
