### ISSUE TITLE
Ability to disable OMEMO

### ISSUE THREAD

**Issue by lllvvv** [movim/movim#1022]
Title pretty much says it all, and yes, it's a feature request.

I don't mean to sound ungrateful, because I know that adding OMEMO was quite the feat, and I think it's generally a great feature. But given that the introduction of OMEMO is causing quite a few UI an UX bugs, I was wondering if there shouldn't be an option to toggle it off, either per-user, or ideally at pod-level.

**Comment by edhelas** [comment]
You can click on the OMEMO lock button to disable it per contact.

**Comment by edhelas** [comment]
Regarding the fact that OMEMO is not enabled by default (you actually need to toggle it to start sending encrypted messages) to me such features will create some unnecessary UI overhead.
