### ISSUE TITLE
Support Message Styling (XEP-0393)

### ISSUE THREAD

**Issue by ChelonianEgghead** [movim/movim#1027]
Hello guys, firstly I'd just like to thank you all for the great work you've been doing on this platform! One improvement that I think would be really great though is the addition of support for XEP-0393 which would allow for Markdown-like message styling and I think would really help make the transition more seamless for normies coming from platforms like Discord. Here's the relevant spec: https://xmpp.org/extensions/xep-0393.html

**Comment by edhelas** [comment]
I kept the `/code` system for now as the `<pre>` messages were causing some troubles when edited
