### ISSUE TITLE
Update the Legals page

### ISSUE THREAD

**Issue by edhelas** [movim/movim#1029]
* The current Legals page is currently outdated https://api.movim.eu/accounts/legals
* The servers are now hosted at Netcup in Germany.
* The page CSS is broken and make the text hard to read.
* There is no mention of Google CAPTCHA during the registration process, GDPR issue

**Comment by ghost** [comment]
I suggest that the following be clearly stated in the privacy policy.
- How long to store an IP address
- How long to store messages(XEP-0313)
- How long to store uploaded files(XEP-0363)

**Comment by ghost** [comment]
Also, you might want to specify which country's laws apply and which court has jurisdiction. Currently, it is suggested that it is Germany, but it is not clearly stated.

**Comment by edhelas** [comment]
The legals page has been upgraded :)
