### ISSUE TITLE
Movim is not supporting XEP-0363 authorization header

### ISSUE THREAD

**Issue by mdosch** [movim/movim#1032]
Movim version: v0.19
XEP: https://xmpp.org/extensions/xep-0363.html

> Nov 25 15:59:29 files.mdosch.de:http_file_share debug   Missing or malformed Authorization header

So I can't upload files using the [new prosody http-upload module](https://prosody.im/doc/modules/mod_http_file_share)

**Comment by edhelas** [comment]
Fixed in master, will be available in the next release.
See https://github.com/movim/movim/commit/c769e962d21fb86190bf723c544ca353841d646e
