### ISSUE TITLE
ALPN Type ClientHello - issue and/ or featureRequest

### ISSUE THREAD

**Issue by sando38** [movim/movim#1035]
Hello there,
thank you for your efforts. It is an amazing project.
Currently I implement movim into our k3s cluster. While implementing it, I discovered an issue while logging to the server - which is not related to k3s.

I have a load balancer in front of an ejabberd xmpp server. 
The nginx loadbalancer listens on port 443 and distributes incoming traffic with ssl-prereading, searching for ejabberd xmpp listeners on type:
"xmpp-client"
"xmpp-server"

When I started to connect with the movim client to the server, I discoverd, that movim detects the correct SRV records "tls://xmpp.domain:443", however the request does not reach the ejabberd xmpp server.

For testing I disabled the ALPN type loadbalancing and now, when I call the xmpp server directly I can connect.

I use docker version Movim v0.20rc3.

So my question:

- Does movim support clientHello with [ALPN types](https://www.keycdn.com/support/alpn) "xmpp-client" and "xmpp-server"?
- If not, it would be great to implement, since the clients we are using all seem to support it and it is great to serve xmpp-clients also via port 443 alongside other services like STUN/ TURN, etc. 

Here is the load-balancing example from nginx:

```
stream {
    upstream k3s_traefik {
        server xxx.xxx.xxx.xxx:443;
    }
    upstream xmpp-c2ss {
        server xxx.xxx.xxx.xxx:5223;
    }
    upstream xmpp-s2ss {
        server xxx.xxx.xxx.xxx:5270;
    }
    map $ssl_preread_alpn_protocols $https {
        default k3s_traefik;
        "xmpp-client" xmpp-c2ss;
        "xmpp-server" xmpp-s2ss;
        "stun.turn" stunturnserver;
        "stun.nat-discovery" stunturnserver;
    }
    server {
        listen 443;

        ssl_preread on;
        proxy_pass $https;
        proxy_protocol on;
    }
}
```

Thank you very much in advance already!
Have a great evening!

**Comment by edhelas** [comment]
There was already a ticket opened about it there https://github.com/movim/movim/issues/947
I'll keep that one open. I'm not aware of that standard but might work on it one day.

**Comment by sando38** [comment]
Cool, thanks a lot! 
Wishing you a great evening.

**Comment by edhelas** [comment]
Closing the ticket as I'm not planning to add his feature anytime soon (not planned in the scope of the project)
