### ISSUE TITLE
PHP 8.1.1  deprecation note

### ISSUE THREAD

**Issue by lyn1337** [movim/movim#1038]
Might have something here, thrown to me via syslog:

`Jan 21 20:27:50 *REDACTED* movim[158719]: movim.ERROR: DOMElement::setAttribute(): Passing null to parameter #2 ($value) of type string is deprecated in /srv/movim/src/Movim/Template/Builder.php (line 183) Trace  [] []`

**Comment by edhelas** [comment]
It would be useful to have the whole stack trace
