### ISSUE TITLE
Broadcast to all “devices”

### ISSUE THREAD

**Issue by Hywan** [movim/movim#104]
Hello :-),

I am quite new with Movim and also with XMPP. Here is my issue:
- A client X is connected through Movim (so 1 device),
- A client Y is connected though weechat **and** Loqui IM (so 2 devices).

When Y writes something to X, X receives it. When X writes something to Y, Y receives it on Loqui IM, not on weechat. It seems like the message is not spread.

Do you know why? Is it an issue from Movim?

**Comment by royalterra** [comment]
I see some issues relate using Xabber in Android and when the seam user is Login in webchat and android in the seam. Also I not have idea if they are related in settings user changes fail many times

**Comment by edhelas** [comment]
There is a priority issue I think, Movim always send the messages to the raw JID (without the resource behind). Also if your server and clients supports message carbons (which is the case with movim.eu and Movim) everything should be synchronized.

**Comment by Hywan** [comment]
I am using xmpp.jp. How to know if it supports message carbons?

**Comment by edhelas** [comment]
There's no tools in Movim to do that but you can try to check with another tool. Or maybe just ask them directly :)

**Comment by edhelas** [comment]
This issue was moved to movim/movim#6
