### ISSUE TITLE
User names with / in it are not displayed correcty

### ISSUE THREAD

**Issue by poVoq** [movim/movim#1044]
If there is a user with the name "example/b" in a chat then Movim only displays "example" as the name.

This is a quite common issue when bridging to IRC channels via Biboumi as "/" is a common signifier in IRC for RELAYMSG users.

**Comment by edhelas** [comment]
Do you have some examples of rooms where this happens ? I'd like to reproduce.

**Comment by poVoq** [comment]
Rooms bridged to IRC servers that support RELAYMSG have this problem. For example:

xmpp:#offtopic@irc.freegamedev.net?join
