### ISSUE TITLE
Corrupted avatars

### ISSUE THREAD

**Issue by TheBluestBird** [movim/movim#1046]
Just updated to new Movim 0.20
Avatars look distorted, like here [Blue blog](https://chat.macaw.me/?blog/Blue)
I run Archlinux with php-fpm 7.4.28, people say it might matter that my my php7-imagick is 3.7.0-2

**Comment by lllvvv** [comment]
I have seen the same thing happening, and not only with avatars. Also running Arch, but in my case with php-fpm 8.1.3 and the same version of php-imagick. I can try and help debug this with some instructions, because this bug is breaking the experience and making movim near unusable.

**Comment by edhelas** [comment]
This seems to be caused by php-imagick indeed. I'm keeping this ticket open for a while.
If you find the real issue in php-imagick or an already opened ticket do not hesitate to put the link there.

**Comment by edhelas** [comment]
Hi, any news regarding that issue ?

**Comment by edhelas** [comment]
Closing this ticket as I cannot reproduce

**Comment by TheBluestBird** [comment]
I'm afraid this is something you will face in some time, pretty long knowing the freshness of apps in debian, but still limited.
I really have absolutely no Idea about PHP, I would like to help somehowm but I just have no Idea what and where do I do!

Can you take a look, can this be a solution? Can you please guide me if there is a way to test it?
https://stackoverflow.com/questions/30078090/imagewebp-php-creates-corrupted-webp-files

**Comment by edhelas** [comment]
Actually Movim is now only using Imagick and not GD anymore, so `imagewebp` is not even used in the code.
More investigation will be required. I don't have an easy way to reproduce that issue on my Debian :/

**Comment by TheBluestBird** [comment]
Sorry, my bad, is there any experiment I can conduct to help investigation?

**Comment by ghost** [comment]
Hello

Running Movim on Gentoo, I found after a tedious search that the issue comes from imagemagick version 7.x ( 7.1.0.13 in my case on Gentoo ). After a downgrade to imagemagick 6.9.12.59 my avatar is fine.

**Comment by TheBluestBird** [comment]
This feels like a very strange situation: there is a bug in upstream version of a very popular library little yet know about, and the only way out is to rollback... I still feel like I have just misconfigured something, it can't be this bad!

**Comment by TheBluestBird** [comment]
Interesting, I just have done some experiment, I have just ran command line conversion with `convert xxx.png xxx.webp` and the file happened to be fine. How relevant is it? May be we're blaming ImageMagick for no reason?

**Comment by lyn1337** [comment]
I set up a testing installation and built Imagemagick and Imagick (the extension) from it from source today, and I can confirm it seems to be causing the issue.
```
Imagick compiled with ImageMagick version | ImageMagick 7.1.0-53 beta Q16-HDRI x86_64 28a3af8a7:20221115 https://imagemagick.org
```
![image](https://user-images.githubusercontent.com/10338543/202642882-cdc1ed2f-3711-4969-b24c-37882f3da17e.png)

**Comment by lyn1337** [comment]
btw pls pm me if there's a need for any sort of access to the testing installation.

**Comment by TheBluestBird** [comment]
Do you think it's possible to separate this case from the rest of movim code base? I think it should be addressed to extension developer, but it might need minimal reproducible example

**Comment by edhelas** [comment]
Do you have some news regarding this issue ? Or can we close the ticket, and the related PR ?

**Comment by poVoq** [comment]
Can you please re-open? This is still a problem with ImageMagick 7.1.1-15 (from Fedora repos).

Edit: the source modification in the above linked PR still works to fix this.

**Comment by edhelas** [comment]
Debian (finally !) moved to Image Magic 7 and I can (finally !) reproduce the issue, reopening the ticket :)
