### ISSUE TITLE
Facebook/Meta links are broken.

### ISSUE THREAD

**Issue by rkarpuzov** [movim/movim#1047]
Please remove GET parameter ?fbcid=<key> because Facebook/Meta links can not be followed. 
FB/Meta adds this in the URL of every post.

**Comment by edhelas** [comment]
By doing this Facebook allow URLs to be tracked across the Internet. URLs should not be changed when they are shared.

The Movim URLs are legit and I'm not planning to change my Route schema to fit with the user tracking plan of a big american tech company.

**Comment by rkarpuzov** [comment]
The idea is to remove user tracking, may be the giant is not the only one tracker in the world.

**Comment by rkarpuzov** [comment]
fixed with the recently releases
