### ISSUE TITLE
 feature request - support on HTTP for local testing without TLS

### ISSUE THREAD

**Issue by amir28** [movim/movim#1048]
Hello, I recently setup my own Movim server but without XMPP server and SSL because I just want to use it as a client for connecting to public XMPP servers and it will only accessible within LAN. I'm using apache2, debian, postgresql

At first it seems everything works but when I enter my account(not when I open Movim webpage) it stuck in connecting status in the login button.
here is my configs:
```
# /etc/apache2/sites-enabled/000-default.conf
<VirtualHost *:80>
     ServerAdmin webmaster@localhost
     DocumentRoot /var/www/movim/public
</VirtualHost>



# /etc/apache2/conf-enabled/movim.conf
ProxyPass /ws/ ws://127.0.0.1:8080/
Alias / /var/www/movim/public/

<Directory /var/www/movim/public/>
    DirectoryIndex index.php
    Options +FollowSymLinks -Indexes
    AllowOverride FileInfo Options
</Directory>

<Location "/">
	Header set Access-Control-Allow-Origin "*"
</Location>



# /etc/systemd/system/movim.service
[Unit]
Description=Movim daemon
After=apache2.service network.target local-fs.target
[Service]
User=www-data
Type=simple
Environment=PUBLIC_URL=http://localhost/
Environment=WS_PORT=8080
EnvironmentFile=-/etc/default/movim
ExecStart=/usr/bin/php daemon.php start --url=${PUBLIC_URL} --port=${WS_PORT}
WorkingDirectory=/var/www/movim/
StandardOutput=syslog
SyslogIdentifier=movim
PIDFile=/run/movim.pid
Restart=on-failure
RestartSec=10
[Install]
WantedBy=multi-user.target
```

**Comment by edhelas** [comment]
I'm not sure if Movim is reachable on HTTP, even with local setup (like I do for development) it's now kind of required to have TLS enabled (at least with self-signed certificate).

**Comment by edhelas** [comment]
Closing the issue, no feedback for a while

**Comment by amir28** [comment]
so I think it's better to transform this issue to feature request

**Comment by jameskentTX** [comment]
Maybe it would be possible to disable SSL Verification, so we users can test movim with self signed certificates.
Such option could be in `.env` file, for example.
This idea is from:
https://medium.com/@erlandmuchasaj/starttls-stream-socket-enable-crypto-error-de7dea4e1a

I've just installed all needed software to run mavin, solved zillion :) errors with compilation and configuration of nginx, ejabberd, php, mavin, but this one final problem with self signed certificate I can't solve.
