### ISSUE TITLE
Login Tab is disabled

### ISSUE THREAD

**Issue by ShahnawazAzam** [movim/movim#1049]
I have installed Movim in my local LAN on  Ubuntu 21.04 as per instruction ref "https://github.com/movim/movim/wiki". My eJabberd instance is in same network and I am able to log in to eJabbered using ConverseJS and Gajim. Post Moviminstallation the log in tab is greyed as below.

![error](https://user-images.githubusercontent.com/101454539/158013907-6ea65a61-87e8-45b7-a1e0-7092a9ce631e.png)

After some time I see another error "Reconnecting to Server Movim cannot talk to server.

![error](https://user-images.githubusercontent.com/101454539/158013967-97d171cd-666f-4ee8-bfd4-36881863668c.png)

**Comment by edhelas** [comment]
Check the JS console, check the daemon, check your Apache/nginx configuration to see if the Websocket is correctly reaching the daemon.
This is a setup issue.
