### ISSUE TITLE
Movim crashes when opening rooms bridged via Biboumi and Matterbridge

### ISSUE THREAD

**Issue by poVoq** [movim/movim#1054]
Very strange issue.

Since updating today to the latest dev version of Movim an the 1.25 version of Matterbridge, Movim crashes when trying to enter such rooms i.e. IRC rooms bridged via Biboumi that also include a Matterbridge to other chatsystems.

The error message I see in the Movim daemon is:
`movim.ERROR: TypeError: Argument 1 passed to cleanupId() must be of the type string, null given, called in /var/www/movim/app/widgets/Chat/Chat.php on line 1362 in /var/www/movim/app/helpers/StringHelper.php `

It works fine with IRC clients and other XMPP clients.

It might be related to the fact that Movim doesn't seem to properly escape nicknames, so "user/bridge" as a nick, becomes just "user" in Movim.

However previously this did not cause Movim to crash, the only real difference I see is that Matterbridge updated their IRC library between 1.24 an 1.25.

Also on other IRC channels similarly bridged, but with Heisenbridge (to Matrix) and not Matterbridge the same type of "user/bridge" nicks seem to not crash Movim.

**Comment by poVoq** [comment]
Hmm, somehow the main crashing issue solved itself after restarting the IRC server.

But it would be still nice if Movim could escape nicknames correctly.

**Comment by edhelas** [comment]
Closing the issue. 
Can you please reopen a new issue with only one specific problem that you have and, if possible, a clear way of reproducing it (by providing a test account with a buggy chatroom for example).

**Comment by poVoq** [comment]
Yeah, this still happens randomly from time to time, but I can't reproduce it consistently.
