### ISSUE TITLE
Issue while posting fast

### ISSUE THREAD

**Issue by MrNewbie72** [movim/movim#1055]
There is an issue when posting fast on movim.

This happens when I write something fast and press post, even when editing a post if I edit something fast and press post it well post something wrong or simply not how I left it before hitting post.

Then I figured out that I have to wait until I get a check mark on the context title (see the image below) then press post which is inconvenient and new comers to movim wont know this since its not how things work on other platforms

![movim_issue](https://user-images.githubusercontent.com/52122485/165991980-8990c04b-b57b-40cf-bc12-93e801134d60.png)

I am using release version 0.20

**Comment by edhelas** [comment]
Actually the flow is made to publish from the server. What I can try to do is disable the publish button if the draft is not saved.
