### ISSUE TITLE
Movim error at opening of starting page "linker killed"

### ISSUE THREAD

**Issue by sando38** [movim/movim#1056]
hello hello,

I have set up a custom docker image based upon alpine linux, nginx and php 8.0 (I have the same issue however also when testing with 7.4) installing movim within. I use this image/ setup also for other php applications and they work.

I recieve the following error log, once I connect to movim:

```
Debug is enabled, check the logs in syslog or /movim/log/

--- Server Configuration - Apache ---
Enable the Secure WebSocket to WebSocket tunneling
# a2enmod proxy_wstunnel 
Add this in your configuration file (default-ssl.conf)
ProxyPass /ws/ ws://127.0.0.1:8080/

--- Server Configuration - nginx ---
Add this in your configuration file
location /ws/ {
    proxy_pass http://127.0.0.1:8080/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect off;
}

sEOBW5H0xm5tLL3YngQSrQLCLdsQ2gx6 : 1113 connected
sEOBW5H0xm5tLL3YngQSrQLCLdsQ2gx6 : linker killed 
sEOBW5H0xm5tLL3YngQSrQLCLdsQ2gx6 : 1113 deconnected
4GRkBaBm4iTMAoABIPiCkVLVzoGuRWwa : 1147 connected
4GRkBaBm4iTMAoABIPiCkVLVzoGuRWwa : linker killed 
4GRkBaBm4iTMAoABIPiCkVLVzoGuRWwa : 1147 deconnected
546KigHBcDVxNXuvjp947EmU0neuJx77 : 1159 connected
546KigHBcDVxNXuvjp947EmU0neuJx77 : linker killed 
546KigHBcDVxNXuvjp947EmU0neuJx77 : 1159 deconnected
```
Do you have a quick guess where the issue may be? The `/movim/log/` is empty unfortunately.

I only have the docker image locally on my machine, however can set up a repository on github for further investigations.

Thanks in advance already! Have a great evening.

P.S. Movim version is 0.20

**Comment by sando38** [comment]
Hello, would it help to provide you the image data?

**Comment by edhelas** [comment]
Try to launch your daemon with `-d -v` to enable debug and check what's wrong in the console output.

**Comment by sando38** [comment]
Hello,

thanks for your reply. Actually I did that. I use the following command to start the daemon:

`exec php /movim/daemon.php start --url=${MOVIM_DOMAIN:-http://localhost} --port=${MOVIM_PORT:-8080} --interface=${MOVIM_INTERFACE:-0.0.0.0} --verbose --debug`

The log in the initial post is the output I get from the console output. It occurs once I open the login page and then it constantly reloads with the pattern shown in the log above.

BTW: it should be "disconnected" not "deconnected" :)

**Comment by sando38** [comment]
Actually got it working now. I removed the nginx part of my image and now only have the php processor and movim file in the image.

Did not really change anything, though... may look into it further at another day. But for now: it works!

Do you want me to contribute the Dockerfile into your other repository?
