### ISSUE TITLE
Replies fail to show > fallback in Movim itself

### ISSUE THREAD

**Issue by poVoq** [movim/movim#1060]
See:
![Screenshot_20220518_000154](https://user-images.githubusercontent.com/940360/168909780-ccedcde0-722c-49da-89be-bf9a540f870e.png)

So it is a bit confusing when replying to users those messages do not work with XEP-0461 to not see the fall-back as in other clients.

**Comment by edhelas** [comment]
![image](https://user-images.githubusercontent.com/3726886/171709899-82469095-7406-4663-9123-fa3bd232beb1.png)

Fallback is working on other clients.
I don't get what is your issue.

**Comment by poVoq** [comment]
Yes, but not in Movim. So it is really confusing that it looks like you can make a proper reply, but since XEP- 0461 fails you just get nothing in Movim.

**Comment by edhelas** [comment]
![image](https://user-images.githubusercontent.com/3726886/171721377-fade4f77-dcc6-42cd-b3a2-f844d033e0ad.png)

Movim supports messages starting with quotes.
I don't get what is your actual issue there :thinking: 

Can you please provide a flow to show me how I can reproduce the issue ?

**Comment by poVoq** [comment]
See screenshot above, it very clearly shows the issue with goffi's post. I don't know how it can be more clear than that? You were even personally there when I made that screenshot.

**Comment by edhelas** [comment]
Did some fixes about it, can you please check if it fixes your issue ?

**Comment by poVoq** [comment]
I updated it and will try a bit. Not so easy to reproduce :)

**Comment by poVoq** [comment]
Seems to still happen with certain users even after this fix.

**Comment by edhelas** [comment]
![image](https://user-images.githubusercontent.com/3726886/185599677-cafe4f5a-f9a6-4ebe-a2ac-4e78cb78df89.png)

**Comment by edhelas** [comment]
This should be fixed by now. See also #1113
