### ISSUE TITLE
Feature: add telephone keypad to Audio Call?

### ISSUE THREAD

**Issue by ghost** [movim/movim#1063]
I use the mov.im client to call customer support lines (with jmp.chat).

Some customer support services require the caller (me) to type options on the keypad e.g. "if you want to talk to this department type 1, if you want to talk this other department type 2" or "type # to confirm".

There is no keypad on the pop up window when calling (Audio Call.)

Would adding a telephone keypad to the Audio Call pop up window be a possibility? 

https://en.wikipedia.org/wiki/Keypad

**Comment by edhelas** [comment]
This could be basically done by the implementation of XEP-0181: Jingle DTMF https://xmpp.org/extensions/xep-0181.html
It is actually a quite consequent feature (keypad, tone generation, tests...)

Is is something that would be required for your company and/or would you be interested to fund it ?

**Comment by ghost** [comment]
Hello, thanks for the quick reply. No. It is just for personal occasional use.Thank you for offering though.

**Comment by edhelas** [comment]
I'm closing this ticket, the feature is still valid. If someone is interested to fund the feature I'd be pleased to reconsider it.

**Comment by singpolyma** [comment]
This should use https://www.rfc-editor.org/rfc/rfc4733.html (which is supported by WebRTC) and not by anything XMPP specific, IMO, this is how Gajim, Snikket, and Cheogram Android support it.

@edhelas how much do you need to get this in for funding?

**Comment by singpolyma** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/RTCDTMFSender/insertDTMF is the main API for this

**Comment by edhelas** [comment]
> https://developer.mozilla.org/en-US/docs/Web/API/RTCDTMFSender/insertDTMF is the main API for this

Indeed, it was actually quite straightforward, thanks for the PR ! :)
