### ISSUE TITLE
Not linkifying xmpp: when Jabber ID includes a +

### ISSUE THREAD

**Issue by speedygonzales9** [movim/movim#1064]
Hi, 

I noticed Movim only linkifies xmpp: links without a `+` in a Jabber ID. For example, `xmpp:blah@example.com` is linkified and clickable but not `xmpp:+1234@quicksy.im`. Movim also linkifies `xmpp:cheogram.com` as well as chat rooms so they are clickable links. Can you please fix this so Movim linkifies Jabber ID's that includes a `+` in the Jabber ID's too? 

Thank you

**Comment by poVoq** [comment]
Does this also fix rooms starting with # ? I think I have seen the same issue on those and they are common with Matrix and IRC bridging.
