### ISSUE TITLE
Multiline Code Block Syntax

### ISSUE THREAD

**Issue by eevvoor** [movim/movim#1066]
The multiline code block syntax is neither indicated in the quick help on the right side bar nor in the linked markdown syntax documentation.

I would appreciate it in the side bar quick help. If this makes the quick help too dense at least the markdown syntax documentation should be updated to one that includes the multiline code block with three backticks.

**Comment by edhelas** [comment]
Fixed in https://github.com/movim/movim/commit/ca1bfe1747641be9f4fb7c683d6bc93d7b15fcea
