### ISSUE TITLE
Not displaying correct alias in profiles

### ISSUE THREAD

**Issue by speedygonzales9** [movim/movim#1067]
Hi, 

When I click on a `xmpp:` link in Movim to view their profile, it does not display the contact name (alias) on the title bar beside the back button. Instead it displays the "username" part of that Jabber ID and the whole Jabber ID directly below it. If I click on the pencil icon to edit that contact, I see the alias field already has a name that I previously set. For example: when I click on `xmpp:+12345678900@cheogram.com`, Movim goes to this Jabber ID's profile. On this page beside the back button at the top, it displays the "username" part (`+12345678900`) and the whole Jabber ID directly below it (`+12345678900@cheogram.com`.) Even though the contact name (alias) is set to "Andy" for instance, it still displays the "username" part as `+12345678900`. Attached are two screenshots of what I am describing to you: 
![Movim Jabber profile](https://user-images.githubusercontent.com/40548778/175135201-46f07c68-638c-446b-af49-8d07c59d4988.png)
![Movim edit contact](https://user-images.githubusercontent.com/40548778/175134318-29030117-6657-492a-ac15-518842d3d222.png)
I would like Movim to display their alias instead of the "username" part of their Jabber ID in the profile page, skipping the need to click on the pencil icon to see the alias. Is this possible? If not, I would like to make this a feature request please. 

Thank you.

**Comment by edhelas** [comment]
Yes, but actually no.
The Alias is only there to be displayed the the contact list or in the chat, those information only relies on the public data of the contact. Because there is no Vcard Movim then fallback to the username.

It's not a bug, it's a feature.

**Comment by speedygonzales9** [comment]
Hi @edhelas, 

Thank you for your response. It would make more sense to me to have the username part of a Jabber ID in the profile replaced with the roster name to maintain consistency, regardless if there is a vCard. Is this possible? Looking forward to your response. 

Thank you
