### ISSUE TITLE
Wrong link to stickers

### ISSUE THREAD

**Issue by M-Stenzel** [movim/movim#1069]
Hello,

first things first: thank you for this great software

I installed the latest version (0.20) manually (no docker, no package version), and run it behind an apache server

This is my systemd file

---
[Unit]
Description=Movim daemon
After=apache2.service network.target

[Service]
User=wwwrun
Type=simple
Environment=PUBLIC_URL=https://www.xy-space.de/movim
Environment=WS_PORT=6080
EnvironmentFile=-/etc/default/movim
ExecStart=/usr/bin/php daemon.php start --url=${PUBLIC_URL} --port=${WS_PORT}
WorkingDirectory=/srv/www/htdocs/movim
StandardOutput=syslog
SyslogIdentifier=movim
PIDFile=/run/movim.pid
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
---

This is my apache conf file

---
ProxyPass /movim/ws/ ws://127.0.0.1:6080/
Alias /movim/ /srv/www/htdocs/movim/public/

<Directory /srv/www/htdocs/movim/public/>
    DirectoryIndex index.php
    Options +FollowSymLinks -Indexes
    AllowOverride FileInfo Options
</Directory>

<Location /movim/>
    Header always set Access-Control-Allow-Origin "*"
</Location>
---

The problem is that the path to the stickers lacks the "/movim" directory

One example:
https://www.xy-space.de/stickers/meme/72d83ea55c430b7bcc557a5b698038c807ce7f4f.png

is a broken link, it should be
https://www.xy-space.de**/movim**/stickers/meme/72d83ea55c430b7bcc557a5b698038c807ce7f4f.png

All the stickers are not shown

![image](https://user-images.githubusercontent.com/76916440/178150554-3acdb7fa-f2dd-4478-bb35-2682a246a3f3.png)

I do need movim being served in a subdirectory (/movim), anyone with the same installation with successful display of stickers?

Regards, 

Martin

P.S. My /etc/default/movim file is empty, should there be anything in there?

**Comment by edhelas** [comment]
Movim is not developped to work in a subdirectory. I advise you to create a subdomain in your case and place Movim at the root, for example https://movim.x-y.space.de/ in your case :)
