### ISSUE TITLE
Message retracted carbons are ignored

### ISSUE THREAD

**Issue by truenicoco** [movim/movim#1075]
If movim receives this:

```xml
<message type='chat' to='test@localhost/movim7nW1Bh' from='test@localhost'>
    <sent xmlns='urn:xmpp:carbons:2'>
        <forwarded xmlns='urn:xmpp:forward:0'>
            <message to='REDACTED@telegram.localhost' type='chat' xmlns='jabber:client' from='test@localhost/slidge' id='1839202304'>
                <body>WILLBERETRACTED</body>
                <origin-id xmlns='urn:xmpp:sid:0' id='1839202304' />
                <delay xmlns='urn:xmpp:delay' stamp='2022-08-05T07:42:19+00:00' />
            </message>
        </forwarded>
    </sent>
</message>
<message type='chat' to='test@localhost/movim7nW1Bh' from='test@localhost'>
    <sent xmlns='urn:xmpp:carbons:2'>
        <forwarded xmlns='urn:xmpp:forward:0'>
            <message type='chat' xmlns='jabber:client' to='REDACTED@telegram.localhost' from='test@localhost/slidge'>
                <apply-to xmlns='urn:xmpp:fasten:0' id='1839202304'>
                    <retract xmlns='urn:xmpp:message-retract:0' />
                </apply-to>
            </message>
        </forwarded>
    </sent>
</message>
```

The "WILLBERETRACTED" is correctly displayed, but is not retracted in movim's UI. Something similar happens for message reactions, let me know if you want me to open another issue about it.

**Comment by truenicoco** [comment]
Just a thought about reactions:

When a 'forbidden' reaction emoji is sent by movim to slidge, [it replies](https://man.sr.ht/builds.sr.ht/manifest.md#artifacts) an `error` stanza. I think this is the standard way for a server to reply when a message could not be delivered. Movim seems to currently ignore that, maybe that's a cleaner way of restricting what can be used to react. Two problems I see are that the XEP does not mention that and that this seems to be specific to bridges, not something that can happen in pure XMPP

**Comment by edhelas** [comment]
> Just a thought about reactions:
> 
> When a 'forbidden' reaction emoji is sent by movim to slidge, [it replies](https://man.sr.ht/builds.sr.ht/manifest.md#artifacts) an `error` stanza. I think this is the standard way for a server to reply when a message could not be delivered. Movim seems to currently ignore that, maybe that's a cleaner way of restricting what can be used to react. Two problems I see are that the XEP does not mention that and that this seems to be specific to bridges, not something that can happen in pure XMPP

Can you please open a new ticket for that one, it's a different issue
