### ISSUE TITLE
internet connection via socks proxy

### ISSUE THREAD

**Issue by m00n-err0r** [movim/movim#1076]
Hi there!
I'm new to movim and php applications. I successfully installed movim and running it with apache2, but now I want tell to movim make outgoing internet and dns connections to xmpp servers through socks5 proxy and block non-socks outgoing connections.
How can I get it?
I hope I was able to get my point across, my english is not very good

**Comment by edhelas** [comment]
Socks5 proxy are not supported in Movim and I'm not planning to implement it anytime soon. 
Sorry :/
