### ISSUE TITLE
Account portability support XEP-0227?

### ISSUE THREAD

**Issue by poVoq** [movim/movim#1078]
See: https://docs.modernxmpp.org/projects/portability/

The XEP is supported by both ejabberd and prosody, and probably also Open fire.

**Comment by edhelas** [comment]
For now I'm not planning to implement it in Movim. 
I'm leaving the ticket open for now if someone would like to finance the integration.

**Comment by edhelas** [comment]
Do you know who is actually implementing it ?

**Comment by edhelas** [comment]
As this is a pure server feature and that there is specific tools for it (see https://migrate.modernxmpp.org/) I'm not planning to integrate it in Movim.
It's an account level feature, not a client level.
