### ISSUE TITLE
Chats/contacts and chatrooms sidebar button?

### ISSUE THREAD

**Issue by poVoq** [movim/movim#1081]
I find the current way of listing all 1:1 contacts an chatrooms a bit difficult to handle when there are a lot of them.

Ideally a Gajim like "workspace" custom sorting/tag feature could be added, but for now: Would it be possible to split the 1:1 contacts and the chatrooms into separate tabs via different sidebar buttons?

(This is btw similar to Discord which also has 1:1 contacts and chatrooms separated)

P.S.: this would also make it possible to support roster-groups for contacts

**Comment by edhelas** [comment]
I had some though about it and for the moment i don't have a way to make it any simpler than it's done actually.
Having such behavior will introduce many issues in the UI (redundancy, issues for mobiles etc...).

I know the current situation is not ideal, especially if you have a long list of users and/or chatrooms so another kind of solution might work.

**Comment by poVoq** [comment]
I understand if it is for technical reasons, but it would be really nice if some better / working solution could be found :+1:
