### ISSUE TITLE
Small improvements to invite link system?

### ISSUE THREAD

**Issue by poVoq** [movim/movim#1086]
Two small suggestions:

1. Add one of these common small "copy to clipboard" buttons next to the Movim link:
![grafik](https://user-images.githubusercontent.com/940360/189417963-40d14e4d-7320-4e4d-99b9-a402a4de0274.png)

2. Make the room name clickable with a `xmpp: ?join` URL so that people getting the link can also easily click and join with a non-Movim client:
![grafik](https://user-images.githubusercontent.com/940360/189418377-adb2a381-11e6-4d16-82af-5c09c3d33dfd.png)

P.S.: sometime the space behind the user inviting is missing like seen above (with Firefox), but it is hard to consistently replicate :-( Maybe an issue with the German translation only?

**Comment by edhelas** [comment]
Thanks, those were cool ideas :+1:
