### ISSUE TITLE
Corrected message does not disappear (and keeps coming back!)

### ISSUE THREAD

**Issue by truenicoco** [movim/movim#1091]
I edited the last message in a direct chat, from Gajim. The other party saw this:

![ERREUR MOVIM_5a8134b762b62e67fad07cda19539330a9aae810](https://user-images.githubusercontent.com/1313576/191940754-45f2a86e-1eac-4816-8bba-aa836b851f7a.PNG)

(yes this is cheesy) The "a mour" message has been corrected to "amour", so "a mour" should not be here anymore.

But the worst part is, that this "a mour" message seems to be coming back randomly once in a while in the chat

![Screenshot_20220923_122325](https://user-images.githubusercontent.com/1313576/191941193-856d2242-5c05-4043-bf15-6a22047ba855.png)

(cheesiness = over 9000) 

In my other clients (movim, gajim, and Conversations), I don't see anything wrong, and in the other party's other client (Conversations), nothing wrong either.

**Comment by edhelas** [comment]
Ping, is it still happening ?

**Comment by edhelas** [comment]
Closing as not be able to reproduce it and no feedback
