### ISSUE TITLE
Adhoc command result containing JIDs are not clickable

### ISSUE THREAD

**Issue by nicolascedilnik** [movim/movim#1095]
When the result of an adhoc command contains "jid-single" or "jid-multi" fields,
it would be nice if they were hypertext links.

Example stanza:
```xml
<iq id="3nU8Yq" type="result" xml:lang="en" from="dummy.localhost" to="test@localhost/movimo9rKMR">
    <command xmlns="http://jabber.org/protocol/commands" node="info" sessionid="XXX" status="completed">
        <x xmlns="jabber:x:data" type="result">
            <title>Component info</title>
            <field type="jid-multi" label="Users">
                <value>test@localhost</value>
            </field>
        </x>
    </command>
</iq>
```

Here test@localhost could open the test@localhost chat view.

One possible problem with this is that we don't know if the JID is a MUC, a component, or a "normal" client JID.
Opening the direct message view when clicking the JID sounds reasonable to me.

**Comment by edhelas** [comment]
In don't see how a HTML form input can be clickable :thinking: 
Would it be possible to have a working flow, then I can reproduce it and exactly see what you need?

**Comment by truenicoco** [comment]
:XMPP-sucks-meme.jpg:

Both forms AND results can be represented as `jabber:x:data`. But when type="result", I think there is no reason to display this as an HTML form… or am I mistaken somehow?

Results can also be expressed with the other `jabber:x:data` syntax ([the <reported... thing](https://github.com/movim/movim/issues/1093)), which I guess is less ambiguous, but I think this simpler form should work too? Doesn't the type="result" remove any ambiguity?

**Comment by edhelas** [comment]
Same here, I don't know where I can get such form

**Comment by truenicoco** [comment]
The adhoc command "List registered users" when you're configured as a slidge admin uses this type of result. The slidge component must have at least one registered user for the result to not be empty of course.
