### ISSUE TITLE
Certain localparts break the profile view page

### ISSUE THREAD

**Issue by emersonveenstra** [movim/movim#1097]
Another Cheogram bug, "shortcode" phone numbers like `87447` have a JID of `87447;phone-context=ca-us.phone-context.soprani.ca@cheogram.com`. These are displayed correctly on the chat page, but clicking "See the Profile" and going to `https://mov.im/?contact/87447%3Bphone-context%3Dca-us.phone-context.soprani.ca%40cheogram.com` breaks the page, the cloud animation doesn't go away and the ad-hoc commands shown are the ones for `xmpp:cheogram.com`
![Screen Shot 2022-10-06 at 7 06 24 AM](https://user-images.githubusercontent.com/5402360/194297656-4e0344fd-691e-4f08-9784-550463c4c2fe.png)

**Comment by edhelas** [comment]
This is related to the JID length, [66391c5c977dcc49d7b751f466ba4272f9471a0b](https://github.com/movim/movim/commit/66391c5c977dcc49d7b751f466ba4272f9471a0b) should have fixed it. I might do a proper fix later.
