### ISSUE TITLE
XEP0292 conformity (vcard4)

### ISSUE THREAD

**Issue by truenicoco** [movim/movim#1099]
Movim expects the vcard content to be part of the pubsub#event, but the spec is explicit about this event being only an "update notification" event, see [Example 6](https://xmpp.org/extensions/xep-0292.html#example-6).

**Comment by edhelas** [comment]
Not sure about that one, looks more a weird thing in the spec that need to be changed.

**Comment by edhelas** [comment]
I'm keeping the current behavior as the XEP seems to have a weird flow.
Movim is expecting to have the vCard as a payload inside the Pubsub notification directly, like for all the PEP related XEPs.
