### ISSUE TITLE
unconsistent design on "Chats"

### ISSUE THREAD

**Issue by tbeitter** [movim/movim#11]
![chats_tab](https://cloud.githubusercontent.com/assets/756334/8618218/4b83c5b0-270c-11e5-9452-b41825cfb97a.png)
On the "Chats" page there are one-to-one chats on the top of the list and MUC chats below. If I want to start a new one-to-one chat there is a big "+" on the bottom of the page and if I want to start a new MUC there is a little "+" on the top of the page. This is a bit confusing and not clear. Would be nice if both "+" Icons would be of a similar design, size and position. I would suggest to just add another little Icon on the top, maybe showing one person for one-to-one and 2 persons for MUC (as it is right now)

Best,
Til

**Comment by edhelas** [comment]
Thanks for the feedback ! Actually I was more thinking to implement one of the ideas of this page http://www.google.com/design/spec/components/buttons-floating-action-button.html#buttons-floating-action-button-transitions. What do you think ?

**Comment by tbeitter** [comment]
My goal would always be to reduce the needed clicks to a minimum. These floating buttons seem to be a nice looking way to solve that issue for small screens, on big screens I would just see a click more than it should need to achieve what I want :)

So, if the movim interface is built to work on both device classes this would be a fine way to go.

**Comment by edhelas** [comment]
Fixed in commit https://github.com/edhelas/movim/commit/7d9d5b15a6b5e2df01a487ccd8830734be03df72
