### ISSUE TITLE
[UX] Improve "Chats" and "Search" functions

### ISSUE THREAD

**Issue by anubister** [movim/movim#1102]
For a newcomer, starting a 1:1 chat is not obvious : neither the Chat panel nor the Search panel propose a clear function to add an given contact.
![screenMovim](https://user-images.githubusercontent.com/6146191/196527033-e3dc4aea-e186-465d-95c4-3215d1080177.png)

Some feedback :

1.  to extend the "+" function with a "Add contact" function, as available in Conversations : 

![addContact_Conversations](https://user-images.githubusercontent.com/6146191/196528382-20e89b0b-b186-4430-a3cd-b10c236a34ba.png)

2. to propose contacts seems a good idea but then split between users of the same server and rest of the world (or propose an option to make this separation)

3. to add an "Invite" function to generate a link toward a landing page like https://blabber.im/i/toto@tata.com to ease embarking of new friends.

(remarks based on Movim 0.21rc2)

**Comment by edhelas** [comment]
The search bar at the bottom allows you to search for JID, Movim will then try to propose you to chat with the contact and/or see his profile. I prefer to keep this flow better than showing a specific "Add contact" form.

The invite and split local/global functions are not planned for now. 
Thanks for the the feedbacks still :)
