### ISSUE TITLE
Use XEP-0223 for user config storage

### ISSUE THREAD

**Issue by mwild1** [movim/movim#1105]
**Problem**

Currently Movim uses the [historical XEP-0049](https://xmpp.org/extensions/xep-0049.html) for storing user config (such as light/dark mode).

Not all new servers support XEP-0049 (e.g. see #1014), which means config saving in Movim fails on those servers.

**Solution**

The recommended modern approach is to use PEP via [XEP-0223](https://xmpp.org/extensions/xep-0223.html).

**Comment by edhelas** [comment]
Good idea. Lets see if I can have some time to work on it.
