### ISSUE TITLE
Chat markers in MUC use message ID instead of stanza-id

### ISSUE THREAD

**Issue by truenicoco** [movim/movim#1106]
Cf https://xmpp.org/extensions/xep-0333.html#rules-muc

> if a MUC announces support for [Unique and Stable Stanza IDs (XEP-0359)](https://xmpp.org/extensions/xep-0359.html) then clients MUST always use the MUC-assigned id for Chat Markers

Instead, movim uses the message ID for chat markers even when a stanza-id is present. Conversations, which seems very strict about the spec, ignores chat markers sent by Movim. Dino seems to be more relaxed about the spec, so MUC chat markers work between Dino and Movim. But I have tested and dino is also happy when the spec is respected, so I think it's worth fixing this.

**Comment by edhelas** [comment]
Should be fixed :)
