### ISSUE TITLE
Own MUC whispers / PMs do not show on other clients and vice versa

### ISSUE THREAD

**Issue by lyn1337** [movim/movim#1108]
It seems as if there were some sync issues between Movim and other clients (Conversations, Gajim).

The PM I send to a nick in a room via Movim doesn't show elsewhere, and the other way around.
Doesn't seem to affect messages I receive.

**Comment by lyn1337** [comment]
![image](https://user-images.githubusercontent.com/10338543/201453578-c1e14823-fd93-4094-9d31-13cd7b538226.png)

**Comment by edhelas** [comment]
Looks fine to me.
Do you have a specific nickname that could bring issues ?

**Comment by lyn1337** [comment]
Hmm no, I don't think so.

**Comment by edhelas** [comment]
I'd need a proper way to reproduce the issue, I was not able to figure out that one so far.

**Comment by edhelas** [comment]
Closing as not reproducable

**Comment by lyn1337** [comment]
Had this issue occur to me again yesterday - I'm on commit 1c3c472 .
Sent a MUC PM with Gajim, the conversation popped up in  my Chats in Movim but only contained their replies.
