### ISSUE TITLE
Cannot login - Redirection loop

### ISSUE THREAD

**Issue by Tectu** [movim/movim#1109]
Hey guys,

We're currently evaluating movim for which I'd like to get it up & running on our own server(s).

Environment:
  - Movim `Skiff` release
  - PHP 7.4
  - PostgreSQL 13
  - Nginx 1.22.0
  - FreeBSD 13.1-RELEASE

After following the installation guide, we're presented with the movim login screen when navigating to the corresponding URL through a web browser.
The problem we're facing is that we seem to be stuck in a redirection loop after entering the login credentials & hitting the `Login` button.
Observing the network manager output of the web browser (in this case Firefox) shows that there is a 302 redirect to `/?disconnect`.

I've spent quite some time trying to figure out what's going wrong but couldn't track down any specific problem so far.

The daemon output (with `--debug`) just shows this on every redirect:
```plain
CYNIpF82g19xYc76SdpmapkhWaHdH8M1 : Picked DirectTLS
CYNIpF82g19xYc76SdpmapkhWaHdH8M1 : Connect to tls://nl.movim.eu:5223
CYNIpF82g19xYc76SdpmapkhWaHdH8M1 : <stream:stream xmlns:stream="http://etherx.jabber.org/streams" version="1.0" xmlns="jabber:client" to="movim.eu"> sent to XMPP
CYNIpF82g19xYc76SdpmapkhWaHdH8M1 : <?xml version='1.0'?><stream:stream id='7552667923752363355' version='1.0' xml:lang='en' xmlns:stream='http://etherx.jabber.org/streams' from='movim.eu' xmlns='jabber:client'> received
CYNIpF82g19xYc76SdpmapkhWaHdH8M1 : <stream:features><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1-PLUS</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>X-OAUTH2</mechanism></mechanisms><register xmlns='http://jabber.org/features/iq-register'/></stream:features> received
```

Nginx server config:
```plain
server {
    listen 80;
    server_name 192.168.7.49;

    index index.php;

    root /usr/local/www/movim/public;

    location / {
        try_files $uri /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php_fpm.sock;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location /ws/ {
        proxy_pass http://127.0.0.1:8080/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
    }

    # To avoid disconnecting after 60sec : 
    proxy_read_timeout 14400s;
    proxy_send_timeout 14400s;
    # (14400s is 4h)
}
```

No errors are showing up in neither the Nginx or PHP logs.

Could you guys point me towards the right direction for tracking down this problem?

Our server (host) running movim is located behind a HAproxy with TLS termination. Therefore, movim only receives plain HTTP. Furthermore, our proxy intentionally doesn't forward the source IP. Usually this wouldn't be a problem. Is there any reason to believe that it is in case of movim?

As a desperate measure I also tried to set the `X-Forwarded-Proto` header in the `/ws/` proxy config (the Nginx config above) from `https` to `http` but the same symptoms were observed.

**Comment by edhelas** [comment]
I don't think it should an issue in the server proxy side.
Looks like you have a crash in the daemon that basically kill it when the error is encountered. Check the `log/errors.log` in the Movim directory. You might found the origin of the error.

**Comment by Tectu** [comment]
Thank you for the fast reply!

The `log/` directory in the Movim directory is empty.
From what I can tell, the daemon itself is not crashing (at least from an OS process perspective). The deamon output also doesn't indicate anything going wrong (also not with `--debug`).
This should make no difference at all but for completion: I run the daemon in a `tmux` session (similar to `screen`).

**Comment by edhelas** [comment]
Check your browser logs then.
And the daemon just stop on this ?

    CYNIpF82g19xYc76SdpmapkhWaHdH8M1 : <stream:features><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1-PLUS</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>X-OAUTH2</mechanism></mechanisms><register xmlns='http://jabber.org/features/iq-register'/></stream:features> received

You don't have a `Linker killed` or something like this ?

**Comment by Tectu** [comment]
> Check your browser logs then.

Browser logs don't show anything warning or error like either.

> You don't have a Linker killed or something like this ?

Nope, nothing like that. Nothing indicating a failure of any kind.

I think this is a rare case where a video might help:

https://user-images.githubusercontent.com/1385320/200941652-4f2c6525-882d-47c0-9077-3b1600a6c1d1.mp4

Note: The warning visible in the browser's console is due to recording this in incognito/private mode. The message does not appear in a "normal" browser tab but the symptoms are the same.

Edit: In the meantime I tried with different web browsers on different operating systems just to be sure - same result in all cases.

**Comment by edhelas** [comment]
Could you try again with the latest tag ? https://github.com/movim/movim/tags

**Comment by Tectu** [comment]
Should I do a fresh install or try to upgrade/migrate from the current release install?

**Comment by edhelas** [comment]
What do you prefer, the result should be the same anyway if you got the release from GIT

**Comment by edhelas** [comment]
The deployment has been simplified and is now there https://github.com/movim/movim/blob/master/INSTALL.md#deployment

**Comment by Tectu** [comment]
I've performed the upgrade from `v0.20` (aka `Skiff`) to `v0.21rc3`. After updating the sources I've run `composer install`, then created the environment (`.env`) and ran `composer movim:migrate`. All of this seemed to succeed.

After this, I've launched the daemon again. Unfortunately, the symptoms are exactly the same:
- Endless redirection loop on the login page
- No warnings or errors in the browsers console

However, this time I do get the `linker killed` message from the daemon when setting both `DAEMON_DEBUG` and `DAEMON_VERBOSE` to `true`:
```
ZlM8e5jtZBnT39BziRGHvqAK04H9vFwp : 988 connected
ZlM8e5jtZBnT39BziRGHvqAK04H9vFwp : 1051 internal connected
ZlM8e5jtZBnT39BziRGHvqAK04H9vFwp : Picked DirectTLS
ZlM8e5jtZBnT39BziRGHvqAK04H9vFwp : Connect to tls://nl.movim.eu:5223
ZlM8e5jtZBnT39BziRGHvqAK04H9vFwp : <stream:stream xmlns:stream="http://etherx.jabber.org/streams" version="1.0" xmlns="jabber:client" to="movim.eu"> sent to XMPP
ZlM8e5jtZBnT39BziRGHvqAK04H9vFwp : <?xml version='1.0'?><stream:stream id='3827891694640331003' version='1.0' xml:lang='en' xmlns:stream='http://etherx.jabber.org/streams' from='movim.eu' xmlns='jabber:client'> received
ZlM8e5jtZBnT39BziRGHvqAK04H9vFwp : <stream:features><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1-PLUS</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>X-OAUTH2</mechanism></mechanisms><register xmlns='http://jabber.org/features/iq-register'/></stream:features> received
ZlM8e5jtZBnT39BziRGHvqAK04H9vFwp : linker killed 
ZlM8e5jtZBnT39BziRGHvqAK04H9vFwp : 988 deconnected
HQ6k8OBSeb9Wyyo44RlLH4sBSZr3EgnT : 1069 connected
HQ6k8OBSeb9Wyyo44RlLH4sBSZr3EgnT : 1080 internal connected
HQ6k8OBSeb9Wyyo44RlLH4sBSZr3EgnT : Picked DirectTLS
HQ6k8OBSeb9Wyyo44RlLH4sBSZr3EgnT : Connect to tls://nl.movim.eu:5223
HQ6k8OBSeb9Wyyo44RlLH4sBSZr3EgnT : XMPP socket launched
HQ6k8OBSeb9Wyyo44RlLH4sBSZr3EgnT : <stream:stream xmlns:stream="http://etherx.jabber.org/streams" version="1.0" xmlns="jabber:client" to="movim.eu"> sent to XMPP
HQ6k8OBSeb9Wyyo44RlLH4sBSZr3EgnT : <?xml version='1.0'?><stream:stream id='10705794085983497308' version='1.0' xml:lang='en' xmlns:stream='http://etherx.jabber.org/streams' from='movim.eu' xmlns='jabber:client'> received
HQ6k8OBSeb9Wyyo44RlLH4sBSZr3EgnT : <stream:features><mechanisms xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1-PLUS</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>X-OAUTH2</mechanism></mechanisms><register xmlns='http://jabber.org/features/iq-register'/></stream:features> received
HQ6k8OBSeb9Wyyo44RlLH4sBSZr3EgnT : linker killed 
HQ6k8OBSeb9Wyyo44RlLH4sBSZr3EgnT : 1069 deconnected
1pIjv19yqQV3SeXUYtz6h54mEei3fwFf : 1088 connected
1pIjv19yqQV3SeXUYtz6h54mEei3fwFf : 1100 internal connected
1pIjv19yqQV3SeXUYtz6h54mEei3fwFf : Picked DirectTLS
1pIjv19yqQV3SeXUYtz6h54mEei3fwFf : Connect to tls://nl.movim.eu:5223
1pIjv19yqQV3SeXUYtz6h54mEei3fwFf : XMPP socket launched
1pIjv19yqQV3SeXUYtz6h54mEei3fwFf : <stream:stream xmlns:stream="http://etherx.jabber.org/streams" version="1.0" xmlns="jabber:client" to="movim.eu"> sent to XMPP
1pIjv19yqQV3SeXUYtz6h54mEei3fwFf : <?xml version='1.0'?><stream:stream id='12275638089004016620' version='1.0' xml:lang='en' xmlns:stream='http://etherx.jabber.org/streams' from='movim.eu' xmlns='jabber:client'> received
```
(this just goes on forever until I kill the browser tab).

Also different to `v0.20` I actually get a `log/errors.log` file this time:
```
[2022-11-12T14:51:58.697700+00:00] movim.ERROR: stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name does not resolve in /usr/local/www/com.simulton.im/vendor/react/socket/src/TcpConnector.php (line 89)
Trace
 [] []
[2022-11-12T14:51:58.697995+00:00] movim.ERROR: stream_socket_client(): unable to connect to tcp://[2a03:4000:51:f44:4e1:2ff:fe00:4257]:5223 (php_network_getaddresses: getaddrinfo failed: Name does not resolve) in /usr/local/www/com.simulton.im/vendor/react/socket/src/TcpConnector.php (line 89)
Trace
 [] []
[2022-11-12T14:51:58.911363+00:00] movim.ERROR: Error: Call to undefined function Moxl\simplexml_load_string() in /usr/local/www/com.simulton.im/lib/moxl/src/Parser.php (line 57)
Trace
#0 [internal function]: Moxl\Parser->start()
#1 /usr/local/www/com.simulton.im/lib/moxl/src/Parser.php(49): xml_parse()
#2 /usr/local/www/com.simulton.im/linker.php(300): Moxl\Parser->parse()
#3 /usr/local/www/com.simulton.im/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): {closure}()
#4 /usr/local/www/com.simulton.im/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit()
#5 /usr/local/www/com.simulton.im/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}()
#6 /usr/local/www/com.simulton.im/vendor/react/stream/src/DuplexResourceStream.php(196): Evenement\EventEmitter->emit()
#7 /usr/local/www/com.simulton.im/vendor/react/event-loop/src/StreamSelectLoop.php(246): React\Stream\DuplexResourceStream->handleData()
#8 /usr/local/www/com.simulton.im/vendor/react/event-loop/src/StreamSelectLoop.php(213): React\EventLoop\StreamSelectLoop->waitForStreamActivity()
#9 /usr/local/www/com.simulton.im/linker.php(330): React\EventLoop\StreamSelectLoop->run()
#10 {main} [] []
```
So clearly I'm missing the `php-simplexml` extension.
After installing that, I am able to login :)

In the log above, there is also an error regarding failure of resolving an IPv6 address. This however is no surprise as the machine we're running Movim on does not have any IPv6 infrastructure.

May I suggest listing the `php-simplexml` extension as a dependency in the corresponding `INSTALL.md` documentation? One of the pains of deploying PHP applications is that some operating system / packages either pull in some extensions as dependencies by default or worse: They ship with them backed into the main package.
This is not the case on all operating systems (such as FreeBSD).

Thank you for your help on this. We should now be able to start our evaluation.
It's unclear to me why we didn't get the log file on `v0.20`. But I guess that's for you to worry about - Let me know if there's any information I can provide for your convenience.

Thanks again for your support!

**Comment by edhelas** [comment]
![image](https://user-images.githubusercontent.com/3726886/201480557-fa9e2d31-fc85-411d-9a5a-91ffeb84fa7d.png)

Last line
`php-xml` is a meta-package that is also installing `simplexml`.
No problem, I'm glad that the issue is now fixed ;)

**Comment by Tectu** [comment]
`php-xml` does not necessarily pull in `php-simplexml`. This is indeed the case on many platforms/packages but not universally the case. In case of the FreeBSD ports (packages), `php-xml` does not pull in `php-simplexml`.
`php-simplexml` is a separate or "standalone" extension.

**Comment by edhelas** [comment]
Ah I see, I'll see if I check it also with the dependencies, thanks for the feedback !

**Comment by Tectu** [comment]
Thank you too!
