### ISSUE TITLE
No system Notification on Firefox OS 2.5

### ISSUE THREAD

**Issue by vandys** [movim/movim#111]
Join and chat work fine, and new messages in a chat show up in the chat summary page.
But if the app is background it does not push a Notification to Firefox OS, so there's no
sign that there is new chat content until you check the app yourself.

I see the right kind of code in app/widgets/Notification/notification.js, but I never get
the notifications.

**Comment by eyome** [comment]
Same issue here with Z3c and the Foxfood program (FxOS 2.6)

**Comment by edhelas** [comment]
I'm closing this for now, I'm not planing to work on FFOS integration but I'm keeping an eye on the revival of FFOS project to see how Movim can fit with it ;)
