### ISSUE TITLE
Correctly react to reconnection prompts

### ISSUE THREAD

**Issue by poVoq** [movim/movim#1115]
It seems like Movim doesn't correctly respond to reconnection prompt made by Prosody's [mod_ping_muc](https://modules.prosody.im/mod_ping_muc.html).

It needs to implement reconnection when they receive a '333' status code, it would look something like this: https://xmpp.org/extensions/xep-0045.html#example-43

Thanks!

**Comment by edhelas** [comment]
Similar as #1164
