### ISSUE TITLE
[De] Locale: Typos

### ISSUE THREAD

**Issue by RainerBielefeld** [movim/movim#1126]
## Misspelled words:
Letzer   ->
Letzter   
erhälst   ->
erhältst   
Liebslingsraum   ->
Lieblingsraum   

---
I already proposed a [patch](https://github.com/movim/movim/compare/master...RainerBielefeld:movim:patch-1)

**Comment by edhelas** [comment]
Please directly submit your translations on Transifex as is it there where everything is happening, those files are generated :) https://www.transifex.com/movim/movim/messagespot-20/

You can close the ticket once it's ok ;)

**Comment by RainerBielefeld** [comment]
I currently won't learn transifex for such every now and then translation corrections.

**Comment by edhelas** [comment]
I fixed it myself on Transifex
