### ISSUE TITLE
Only the last news subscription survives a server restart

### ISSUE THREAD

**Issue by roughnecks** [movim/movim#1130]
Hi,

If I have more than one news subscriptions from the various communities in Movim, every time I restart my prosody server only the last subscribed one survives, while the other are removed.

**Comment by edhelas** [comment]
Movim is configuring 1000 items max on the node and Prosody doesn't allow it. So I'll have to workaround it by setting it to 'max'. (which is the correct behavior now)

**Comment by roughnecks** [comment]
Thanks!

**Comment by roughnecks** [comment]
Not sure if this is already live on mov.im.. In that case I can say it's still not working.

**Comment by edhelas** [comment]
Please provide me with credentials of an account on your XMPP server privately (you can find my JID pretty easily).

**Comment by edhelas** [comment]
`<text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>max_items: out of bounds</text>`

Your server PEP is configured with a max of 'one', for all the nodes where I publish, even with a max_items set to 'max'.
Please follow https://github.com/movim/movim/wiki/Configure%20prosody#pep-and-pubsub.

**Comment by roughnecks** [comment]
okay, I just set `pep_max_items = 256` the same as pubsub, let's hope this works.

**Comment by roughnecks** [comment]
sorry to bother you. After the changes to my config I restarted the server 2 times and only the subscriptions to my own pubsub survived, while one from nsfw.movim.eu was removed.

**Comment by roughnecks** [comment]
moreover looking at this page: https://prosody.im/doc/modules/mod_pep
The pep_max_items option sets a maximum value for how many items each node can be configured to keep. **It defaults to 256**.

So, even if it wasn't set earlier, it should have been 256 either way.

**Comment by roughnecks** [comment]
Zash from prosody MUC asked me to ask you, "how you got 'out of bounds' if you sent 'max', because you can only get that by sending a number."

**Comment by edhelas** [comment]
I'm always setting it to 'max' by now, see https://github.com/movim/movim/commit/bf45807bbd753fec1447f0bc2ff963030f2cf436

But your issue persist. max seems to be = 1 on your server.
