### ISSUE TITLE
Add widget showing server compatibility

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#1131]
It would be useful if users were able to check that their server is fully compatible with what Movim expects as features. This would also help XMPP administrators and Movim developpers debugging.

Conversations also has this feature and I find it very nice (Manage Accounts -> <Account> -> Menu -> Server Info).

**Comment by edhelas** [comment]
PR welcome ;)

**Comment by edhelas** [comment]
I already have a "degraded mode" for that that ask the user to contact the admin to do the changes.
I'm not planning to expose internal XMPP quirks to the users.
