### ISSUE TITLE
Use of insecure hashing function MD5

### ISSUE THREAD

**Issue by Joao-Felisberto** [movim/movim#1136]
The xmpp server nodes are identified using MD5 hashes. This function has already been deemed insecure, thus, we recommend it be upgraded or the system be rewritten.

Understandably this is a non issue, since the hashes are already hardcoded in https://github.com/movim/movim/blob/2d7846b55f775fcd5f63fa98b3d7790450d7c43f/lib/moxl/src/Xec/Handler.php#L116, but even then, this could be rewritten to be more in line with the norms.

This recommendation is part of a privately disclosed report, mapping to the id NF-004.

**Comment by edhelas** [comment]
I had a look and this system is actually entirely limited to that class only, the md5 hash is only used to map a hardcoded hash=>class array.

Bumping the hash complexity will not bring any improvement, the only good thing would be a rewrite but for now I don't see any good short term reasons to rewrite that part :)
