### ISSUE TITLE
Room members list improvement

### ISSUE THREAD

**Issue by Simounet** [movim/movim#114]
Hi there,
I really miss a UI enhancement about the room members list. In my opinion, it is really useful to be able to check it quickly and two clicks to get it is not that convenient.

Thanks anyway and keep up the good work.

**Comment by Simounet** [comment]
Hmmm, hello there. Did I missed something?

**Comment by christine-ho-dev** [comment]
Hi,

In order to lower the number of clicks to get to the room members list, we've replaced the attachment button (right top corner) with a members list button.

The attachment button is still there: before you type any message to send, you can enclose an attachment. 

The change has been deployed on https://nl.movim.eu/ :).

**Comment by Simounet** [comment]
I think we need to know who's there when we are talking. Clicking every time to see who you are interacting with is so painful. In my opinion, it could be great to use this new icon to toggle a users list on the right OR even nicer, a user preference to always expose this list by default.

**Comment by christine-ho-dev** [comment]
That's indeed the preferred end point but according to edhelas, having this list permanently displayed makes it some kind of mini roster and managing events related to that (status change and so on).
It also raise the problem of where to display that list, keeping in mind that it needs to looks nice on mobile as well (Movim is for now on a 2 panels system).

In short it's not an easy change to make but we'll keep that idea in mind.

**Comment by Simounet** [comment]
I'm totally understanding your point of view and I get it's not a small evolution but a really important one for this application's part.
