### ISSUE TITLE
SSL configuration insecure exception

### ISSUE THREAD

**Issue by FranciscoCunha97** [movim/movim#1145]
According to the code presented in the file UtilsHelper.php, we can see if the host of the URL request is the same one as the PHP server host, the SSL verification, which by default is turned on, is disabled in this scenario.

This leaves this communication open to Man-in-the-middle attacks from inside the PHP Host.

The reccomendations is part of a privately disclosed report, with the id MOV - 001

**Comment by edhelas** [comment]
I am wondering if this is really a security issue.
This would require to setup a SSL layer for a local-to-local request. It is also not possible to separate the client from the server for that specific case, so the requests made here will never pass on a network afaik.

**Comment by FranciscoCunha97** [comment]
The purpose of this change is to promote zero-trust environment inside Movim system

**Comment by edhelas** [comment]
Closing the issue as this is not actually something I'm planning, and willing, to change/fix
