### ISSUE TITLE
Regression publishing comments to open comment nodes on libervia-pubsub

### ISSUE THREAD

**Issue by singpolyma** [movim/movim#1150]
As of 8b1920d82b I believe can no longer comment on posts on `blog.jmp.chat` get error 

```xml
<error code='409' type='cancel'>
  <conflict xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
  <text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>configuration field &apos;pubsub#persist_items&apos; has a value of True which doesn&apos;t fit publish-options expected &apos;true&apos;</text>
  <precondition-not-met xmlns='http://jabber.org/protocol/pubsub#errors'/>
</error>
```

**Comment by singpolyma** [comment]
Confirmed, reverting to bf45807bbd753fec1447f0bc2ff963030f2cf436 fixes the issue for me

**Comment by edhelas** [comment]
I'm not sure if "True" is a valid configuration value though. I'll see what i can do on my side.

**Comment by goffi-contrib** [comment]
Hi, I wasn't aware of this issue. The use of `True` was a bug fixed month ago on Libervia Pubsub (cf. https://repos.goffi.org/libervia-pubsub/rev/70eddf92bf51). Please update, it should fix your issue.
