### ISSUE TITLE
Display the contact name when hovering over reactions in 1:1 chats 

### ISSUE THREAD

**Issue by speedygonzales9** [movim/movim#1151]
Hi, 

When I hover over an reaction in mov.im in a PM, it shows you their Jabber ID instead of the contact name. I would like it to show the contact name instead. I would like to make this a feature request please. 

Thank you

**Comment by edhelas** [comment]
![image](https://user-images.githubusercontent.com/3726886/215902321-7568b316-1428-4e12-9ca5-bd22f12a8b55.png)

I'm not sure if I get it :thinking:

**Comment by speedygonzales9** [comment]
![Message movim](https://user-images.githubusercontent.com/40548778/215914937-3a57b09d-14b5-48b0-8fec-f37d92acfc3e.png)
This happens in 1:1 chats when hovering over reactions.

**Comment by edhelas** [comment]
Ok got it

**Comment by speedygonzales9** [comment]
@edhelas could it use the name from my roster when the JID is known?
