### ISSUE TITLE
Doubled messages in history when changing notifications type

### ISSUE THREAD

**Issue by roughnecks** [movim/movim#1152]
Hi,
if you open the chatroom configuration panel, click on the edit button and change e.g. from "notify when quoted" to "always notify", then click on edit, all of your past history on that chatroom will have duplicate messages, like you can see here: https://i.imgur.com/EfnECPM.jpeg

**Comment by edhelas** [comment]
![image](https://user-images.githubusercontent.com/3726886/216172161-778b9096-84b2-4c21-a9d7-4e067ee75455.png)

Message duplication is an issue, but it's not this flow that is causing it (I cannot reproduce it on my other chatrooms), it is more related to the room itself afaik.

**Comment by edhelas** [comment]
The messages related fixes in 0.23 should fix those duplication issues. Do not hesitate to comment/reopen if you encounter the issue again.
