### ISSUE TITLE
WebRTC fails to initialize on Chromium browsers when encountering 'stuns' ICE server entry

### ISSUE THREAD

**Issue by enticedwanderer** [movim/movim#1154]
Audio calls via WebRTC in chromium based browsers fail to initialize due to an uncaught JS exception on client side.

Looking at the dev console looks like the ICE servers returned by jabber server include "stuns" entry and this causes the whole initialization to fail because it isn't a recognized protocol in chromium (even though there are other candidates). Trace:

```
Uncaught DOMException: Failed to construct 'RTCPeerConnection': 'stuns' is not one of the supported URL schemes 'stun', 'turn' or 'turns'.
    at init (https://movim.home.lan/cache/Visio_visio.js?t=1671988114:48:20)
    at Object.handle (https://movim.home.lan/scripts/movim_rpc.js?t=1671988114:66:44)
    at connection.onmessage (https://movim.home.lan/scripts/movim_websocket.js?t=1671988114:119:26)
movim_base.js?t=1671988114:79 Uncaught TypeError: Cannot read properties of null (reading 'style')
    at movim_base.js?t=1671988114:79:20
```

Jabber server I'm using returned the following ICE servers:
```
0 : {urls: 'stun:74.208.139.35:3478'}
1 : {urls: 'turn:74.208.139.35:3478', username: '<redacted>', credential: '<redacted>'}
2 : {urls: 'stuns:chatterboxtown.us:5349'}
3 : {urls: 'turns:chatterboxtown.us:5349', username: '<redacted>', credential: '<redacted>'}
```

Interestingly, firefox has no issues with the same jabber server, as it has an implementation to handle `stuns`.

I've tested this on my own instance of Movim and the official one at mov.im. The behavior is the same. Another quick test at https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ the issue is easily reproducible outside of movim as well.

Apparently, `RTCPeerConnection` constructor is initialized in all or nothing fashion. It doesn't tolerate any protocols it doesn't recognize.

So the question now is would it make sense to filter out stuns ICE entries in movim before the WebRTC is initialized? Or filter down to only those recognized (to cover any other new protocols that show up in the future)? I've tested this on my own hosted instance and it works great. If we wanted to keep support for `stuns` we would have to either do some kind of browser capability detection, so it can be conditionally allowed in Firefox or provide a manual toggle in movim settings to control the filter.

If you think either is a good idea happy to provide a PR.

**Comment by edhelas** [comment]
Ah indeed. Nice one.
Feel free to create a small PR for that one for sure :)

**Comment by enticedwanderer** [comment]
So I went to submit a PR and couldn't reproduce the problem. Apparently, newer chromium based browsers now support `stuns` just fine 😆 

See recent [RTCPeerConnection changes](https://chromium.googlesource.com/chromium/src/+/f4d463ca875f51c26a7de0e594eb1516f3e60111%5E%21/#F0)

Don't see a point in filtering the list any more, users can just upgrade to a newer version of a browser if they run into this issue.

**Comment by enticedwanderer** [comment]
Feel free to reopen if you feel otherwise and I can still submit the PR.
