### ISSUE TITLE
Can't run movim from master "Notification doesn't exist"

### ISSUE THREAD

**Issue by Arne19** [movim/movim#1156]
Hi, when installing movim form master I get this error:

[] movim.ERROR: Exception: Das angeforderte Widget 'Notification' existiert nicht. in /var/www/movim/src/Movim/Widget/Wrapper.php (line 78)
Trace
#0 /var/www/movim/src/Movim/Widget/Wrapper.php(146): Movim\Widget\Wrapper->loadWidget()
#1 /var/www/movim/src/Movim/Template/Builder.php(284): Movim\Widget\Wrapper->runWidget()
#2 /var/www/movim/app/views/login.tpl(1): Movim\Template\Builder->widget()
#3 /var/www/movim/src/Movim/Template/Builder.php(63): require('...')
#4 /var/www/movim/src/Movim/Controller/Base.php(115): Movim\Template\Builder->build()
#5 /var/www/movim/src/Movim/Controller/Front.php(104): Movim\Controller\Base->display()
#6 /var/www/movim/src/Movim/Controller/Front.php(18): Movim\Controller\Front->runRequest()
#7 /var/www/movim/public/index.php(50): Movim\Controller\Front->handle()
#8 {main} [] []

The Version v0.21rc5 works without a problem.

**Comment by edhelas** [comment]
Is it possible to know on which page exactly did you had this issue ? I can't reproduce it now.

**Comment by Arne19** [comment]
Sure: It was on https://interact.monocles.de

And sorry, I didn't to translate the error log...

**Comment by edhelas** [comment]
That's the only thing you did to have the error ? Visit the root page of this website ?

**Comment by Arne19** [comment]
Correction: It's just by entering the page interact.monocles.de
I'll try it again with the latest master in a minute

**Comment by Arne19** [comment]
the problem seems to be still there with the latest master and you see it, when you enter the page now.

**Comment by edhelas** [comment]
It looks like the problem was cache or browser related

**Comment by edhelas** [comment]
Yes it is indeed a cache issue.

https://github.com/movim/movim/commit/5e8ec346675bdf7e0db887aaf5b34b5389dc8412#diff-57af9c0da43bceb4d6c101613b83626da498a5474e4eeb560422721a74b4ebc8

Here the `Notification` widget was renamed to `Notif` so i looks like you don't have all the correct files from master :)

**Comment by Arne19** [comment]
Thanks for the clarification!
