### ISSUE TITLE
TypeError: ChatOmemoDB.db is null

### ISSUE THREAD

**Issue by meaz** [movim/movim#1158]
Hi,

I'm trying movim from a VM. Things seem to work fine, except from OMEMO in muc. Indeed, when I connect to a private muc, I don't see any messages there and I have this message in Firefox console:
```
Uncaught (in promise) TypeError: ChatOmemoDB.db is null
    promise https://movim.example.org/cache/ChatOmemo_chatomemo_db.js?t=1675946459:73
    getMessage https://movim.example.org/cache/ChatOmemo_chatomemo_db.js?t=1675946459:69
    decrypt https://movim.example.org/cache/ChatOmemo_chatomemo.js?t=1675946459:262
    appendMessage https://movim.example.org/cache/Chat_chat.js?t=1675946459:1054
    appendMessagesWrapper https://movim.example.org/cache/Chat_chat.js?t=1675946459:871
    handle https://movim.example.org/scripts/movim_rpc.js?t=1675946459:87
    onmessage https://movim.example.org/scripts/movim_websocket.js?t=1675946459:119
    init https://movim.example.org/scripts/movim_websocket.js?t=1675946459:94
    <anonymous> https://movim.example.org/scripts/movim_websocket.js?t=1675946459:283
    EventListener.handleEvent* https://movim.example.org/scripts/movim_websocket.js?t=1675946459:273
2 ChatOmemo_chatomemo_db.js:73:26
```

I don't see anything special in movim error log.

Also, I'm able to write, in this same muc, OMEMO encrypted messages that I can read from conversations or gajim. But in Movim, I can't read my own omemo messages that I wrote from movim...

I'm not too sure where to try to chase that issue... So any help would be appreciated!

**Comment by edhelas** [comment]
What is the return of `ChatOmemoDB.setup()` from the console ?

**Comment by meaz** [comment]
`ChatOmemoDB.setup()` gives this;

```
Promise { <state>: "fulfilled", <value>: undefined }
​<state>: "fulfilled"
​<value>: undefined
​
```

**Comment by edhelas** [comment]
So no error, this should actually create ChatOmemo.db. Do you have any specific configuration on your browser ?

**Comment by meaz** [comment]
ok I stop all firefox plugin, I don't have this error anymore, but I still can't decrypt omemo. 

In firefox console, I see

```
Uncaught (in promise) DOMException: No valid key or key range specified. 5 [ChatOmemo_chatomemo_db.js:76]
```

I do see encrypted messages now, but they're still encrypted...

**Comment by edhelas** [comment]
Ok, so which plugin broke the code ?

**Comment by meaz** [comment]
either ublock origin or privacy badger.

**Comment by edhelas** [comment]
I'm using Ublock Origin, so must be the other.
Would be interesting to know exactly what is the issue.

**Comment by ltguillaume** [comment]
Or uBlock with custom lists...

**Comment by meaz** [comment]
@edhelas if you want to test on our test instance: https://devchat.disroot.org

**Comment by edhelas** [comment]
The issue seems to come from the browser, not the instance itself afaik.

**Comment by meaz** [comment]
I've just tested with another browser, I still have the issue with: `ChatOmemo_chatomemo_db.js`

```
[Error] Unhandled Promise Rejection: DataError: Provided data is inadequate.
	(anonymous function) (ChatOmemo_chatomemo_db.js:76)
```

**Comment by edhelas** [comment]
Similar to #1261 for a part of it.
