### ISSUE TITLE
Movim registration process

### ISSUE THREAD

**Issue by royalterra** [movim/movim#116]
I am wondering if movim is a federate network or is a closed club when I as my server be include in the registration page is 2 months ago but I can see the seam registration pages for the seam people. At the end I need to believe I am hosting movim web for promote others xmpp servers

**Comment by edhelas** [comment]
What is your server ? You're talking about your Movim or XMPP one ?

**Comment by edhelas** [comment]
I can add a feature to allow you to put your own XMPP in the list from the admin panel.

**Comment by royalterra** [comment]
My XMPP server is blablanet.eu anyway if you look in http://blablanet.eu/?account there already publicity 4 servers I like many other people have to XMPP servers are using this Software and promoting it. I not believe is fair is promote services from only that 4 servers more when this look a community project. 

In the seam URL there a link in Spanish no Idea when my browser is English but say ¿Tu servidor aquí? Contáctanos para añadir el tuyo a la lista de servidores oficiales • https://movim.eu/ what means Your server here contact to MOVIM for ADD your server 

blablanet.eu and MOvim are offer in all the nodos of blablanet in France Social Network Community  Example you can find in https://blablanet.fr/mchat in English Community in https://blablanet.com/mchat
and like that in the Chinese, Israeli, Spanish Russian and so on different nodos . Front the moment we advert this software and using it I believe be include in the list with that 4 servers is fair. 

More of the domains of Blablanet have a External registration page but the generic is https://blablanet.com/xmppac we want only simple be include in the servers list of MOVIM

**Comment by edhelas** [comment]
It's perfectly fine for me. As I said I'll add a feature in the next release to allow you to add your own XMPP server on your own Movim pod. For the moment I'll just add you in the list of the 4 servers. What kind of server is it ? Do you support all the Movim features ?

**Comment by royalterra** [comment]
if is in the List of the 4 servers is fine for me. The server is a Openfire Server and by now all the features in MOVIM look to work. The server have also connectivity to others  networks like FB, Google , Aol, etc

**Comment by edhelas** [comment]
Ok I've just added you server, but I'm keeping this ticket open until I add the new feature in Movim.

**Comment by royalterra** [comment]
Thanks. I just change the registration from in https://blablanet.com/xmppac possible is more nice . That form allow register in blablanet.eu or in any other Jabber Server
