### ISSUE TITLE
Disable OMEMO completely for an account

### ISSUE THREAD

**Issue by ltguillaume** [movim/movim#1160]
When logging in on a new device or after clearing local storage, Movim always needs to create new encryption keys. On somewhat slower devices, I have found that this takes a looooong time. It can block the UI completely for as much as 30-40 seconds.

When people use OMEMO, they won't clear the local storage often, because that would remove the keys.

If people don't care about that (for example, I only use Movim with public MUCs) and clear local storage often, they'll be stuck with waiting for something they won't use anyway. Moreover, their account will get hundreds of fingerprints, one for every log-on, that can only be removed one by one.

Therefore I propose a simple switch to disable OMEMO end-to-end encryption for an account completely. This would clear existing encryption keys, prevent generation of new keys and stop showing the padlock in chats.

**Comment by edhelas** [comment]
I think I'll actually do the other way around, just disabled by default and you can enable it if required

**Comment by ltguillaume** [comment]
That sounds fine, too 🙂

**Comment by ltguillaume** [comment]
Logging in on several mobile devices now takes up to 4 minutes due to this.
- Everything freezes during this process, sometimes even the browser  UI itself.
- Sometimes the browser just crashes
- Almost every time the MUC bookmarks aren't loaded at all, even if generating the encryption keys finally finishes. Then, clicking the Chats button to try to reload the bookmarks brings the risk of having to wait for new encryption keys all over again.

Tested on Firefox/Mull and Chromium/Mulch.
