### ISSUE TITLE
[FR] Search through chats

### ISSUE THREAD

**Issue by ltguillaume** [movim/movim#1161]
It is currently almost impossible to search through chats: one might press the Home key in order to load the history (per 50 messages) a few times, then us the browser's "find in page" feature, but this is a cumbersome method that isn't even possible on (most) mobile devices.

Therefore, I'd like to list the following feature requests:
1. A proper way to search through all history available for a chat archived by the client
2. A way to jump to a message from the search results, in order to be able to read its context
3. Possibly a feature to search through all chats at once

I realize that these may be quite complex requests, but I also believe that they are an integral part of an IM client.

**Comment by edhelas** [comment]
This requires lots of work and it's not on my priority list for now.

**Comment by ltguillaume** [comment]
Understood
