### ISSUE TITLE
[FR] Add a message correction button

### ISSUE THREAD

**Issue by ltguillaume** [movim/movim#1162]
Movim support message correction by using the arrow up key. As such, this is a rather well hidden feature. Also, most softkeyboards on mobile devices do not have the option to send an ArrowUp key event.

As such, I propose a message correction button for the last message the user sent, just like the reaction and reply buttons. This would make the feature more visible and easier to access via mobile devices (without a hardware keyboard).

**Comment by edhelas** [comment]
![image](https://user-images.githubusercontent.com/3726886/221420868-869b10d2-3ad7-4008-953a-296b51b1760c.png)

On the top menu on mobile ;)
