### ISSUE TITLE
Implement XEP-0410: MUC Self-Ping (Schrödinger's Chat)

### ISSUE THREAD

**Issue by ltguillaume** [movim/movim#1164]
1. Very often I can open a MUC the normal way, as if I'm connected to it properly. However, there aren't any new messages. I won't get any feedback about the actual situation (the fact that the connection to the MUC has been lost) until I try to send a message myself.

    Even then, I only get a very short toast, which can be easily missed, that I'm not connected to the MUC and it might not even try to reconnect until I disconnect manually.

2. Along those lines, I often see MUCs as disconnected when I log in, even though they're set to "Join on connect".

For these issues, I propose the following solutions:

1. Show a permanent indicator of whether you're currently connected to the room, or at least a permanent indicator if you're not. I would love if if the chat widget isn't faded _during_ connecting, because it makes it impossible to continue reading/scrolling.

2. Implement retries for MUCs that can't be connected to right away upon log-in. (Improved) retries for rooms that are disconnected without the user's doing so.

**Comment by edhelas** [comment]
https://xmpp.org/extensions/xep-0410.html

**Comment by ltguillaume** [comment]
Additionally, whenever an XMPP server gets rebooted, the MUCs hosted by it get permanently disconnected in Movim.

**Comment by ltguillaume** [comment]
Any progress with this? It's still a very common issue with all MUCs.

**Comment by edhelas** [comment]
I have some other stuff happening in my life right now. It will be done when it will be done.
You are also free to contribute to the project to make things move faster :)

**Comment by ltguillaume** [comment]
Got it! Good luck with your house! 🙂

**Comment by edhelas** [comment]
For the moment I only did the basic behavior to disconnect if the MUC is not responding, I'll see later about maybe try to reconnect if possible.
