### ISSUE TITLE
Download link for video

### ISSUE THREAD

**Issue by Keuronde** [movim/movim#1167]
Hi,
When a video is share through XMPP, there is no button to download it, just a button to play it.
I know the issue is more related to the browser, because a decent browse should allow to save a file, but anyway. A download button for video would be nice, same kind as the one on picture.

Regards

**Comment by edhelas** [comment]
Actually for video uploaded from Movim the link is just bellow the video:

![image](https://user-images.githubusercontent.com/3726886/222493960-310efa23-743b-46d1-9651-1207f2d594d2.png)

For GIF shared it is not possible, but that is kinda the point of a GIF in the end.
