### ISSUE TITLE
compileOpcache fails with php8.1

### ISSUE THREAD

**Issue by ravermeister** [movim/movim#1183]
Hi, I installed the latest movim from the master branch as explained [here](https://github.com/movim/movim/blob/master/INSTALL.md), my PHP Version is:
```
www-data@machine:/usr/share/movim$ php -v
PHP 8.1.17 (cli) (built: Mar 16 2023 14:37:38) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.17, Copyright (c), by Zend Technologies
```
However somehow the compileOpcache is not running properly. I always get the following [error log](https://termbin.com/uxon) when starting the damon.php. I found out that the error reporting is [disabled](https://github.com/movim/movim/blob/master/app/helpers/UtilsHelper.php#L124) for the opcache compile process. 
To get the Error I changed the function temporarely from:
```
/**
 * Compile main files in Opcache
 */
function compileOpcache()
{
    error_reporting(0);
    foreach (listOpcacheCompilableFiles() as $file) {
        opcache_invalidate($file, true);
        yield @opcache_compile_file($file);
    }
    error_reporting(1);
}
```
to 
```
/**
 * Compile main files in Opcache
 */
function compileOpcache()
{
//    error_reporting(0);
    foreach (listOpcacheCompilableFiles() as $file) {
        opcache_invalidate($file, true);
//        yield @opcache_compile_file($file);
        opcache_compile_file($file);
    }
//    error_reporting(1);
}

```
and did a manual compile via `php daemon.php compileOpcache`. This is the output: https://termbin.com/1e4e

**Comment by edhelas** [comment]
Looks like its linked with https://github.com/php/php-src/issues/8846

**Comment by edhelas** [comment]
I don't a a clean solution for it yet. Do not hesitate to comment back if you have an idea.

**Comment by ravermeister** [comment]
according to the comment in [opcache_invalidate](https://www.php.net/manual/en/function.opcache-invalidate.php)
it will trigger a recompile. so wouldn't it be cleaner to check if the file is already in cache via [opcache_is_script_cached](https://www.php.net/manual/en/function.opcache-is-script-cached.php), and if so invalidate and otherwise compile?

I mean s.th like this:
```php
/**
 * Compile main files in Opcache
 */
function compileOpcache()
{
    error_reporting(0);
    foreach (listOpcacheCompilableFiles() as $file) {
        if (opcache_is_script_cached($file)) {
                opcache_invalidate($file, true);
        } else {
                yield @opcache_compile_file($file);
        }
    }
    error_reporting(1);
}
```
