### ISSUE TITLE
Roster details from another user on the same instance temporarily visible.

### ISSUE THREAD

**Issue by gnafuthegreat** [movim/movim#1187]
I encountered some disconcerting behavior today, and I wanted to make sure it was documented even though I'm sorry to say I wasn't able to gather a lot of information.  Here are the details:

I opened https://mov.im/ this morning (sometime between 10:00 AM and 12:00 PM Central Daylight Time) and signed in.  In my roster is the Cheogram bot, cheogram.com.  I have given the bot an alias of "JMP Settings", and that is how it usually appears in my conversation list and in my roster list under Search.  However, at some point today it changed to display the name "Bot - CHEOGRAM.com".  Furthermore, it appeared to be part of a group named "Soprani.ca" that I have not set.  I was logged into Movim with another account in another container tab, also with the Cheogram bot in its roster with the alias "JMP Settings", and it displayed correctly.  I only saw the incorrect alias under one of my two accounts.

I logged out, did a force refresh of Movim (Ctrl+Shift+R in Firefox), and logged back in.  The bot went back to being named "JMP Settings".

I shared this oddity in discuss@conference.soprani.ca, and another user confirmed that they had the Cheogram bot in their roster with exactly that alias and group assignment.  They also use the Movim instance at https://mov.im/.  This tells me that there was some information leak at some point today.  My account displayed roster information from another user of the same instance.

**Comment by edhelas** [comment]
I've reworked the old code around Roster handling, tell me if it fixes it for you.
