### ISSUE TITLE
Follow system time 12-hour or 24-hour format 

### ISSUE THREAD

**Issue by speedygonzales9** [movim/movim#1192]
Hi, 

In the mov.im instance, it does not seem to respect the time format on my Windows 10 laptop. I currently use 12-hour time format on my laptop. Other clients such as Dino, Gajim, etc., respects the Windows' time settings. I would like Movim to follow my time settings set in Windows as well to maintain consistency across my device. Can I make this a feature request please? 

Thank you

**Comment by edhelas** [comment]
I'm not sure if the browser can actually get this information.
Edit: Seems meh to me https://stackoverflow.com/a/63298936

I'm not planning to invest time (pun intended) in this kind of feature. Dates are also generated server side which add quite some complexity.
