### ISSUE TITLE
Restart tab-complete after the final nickname in given text pattern 

### ISSUE THREAD

**Issue by speedygonzales9** [movim/movim#1194]
Hi, 

When I use tab-completion in a MUC using the mov.im instance, it does not restart after it reaches the final nickname. For example: when in a MUC, there are the following nicknames: `silver`, `sing`, and `sip`. In the input, type `si`. Press the tab key to scroll through the list of nicknames in the input field. Once the list completes for the `si` text pattern (`sip`), pressing the tab key again does not restart the list. Pressing the tab key again should restart it at `silver`. This is helpful for when you accidentally pass the nickname that you want. Can I make this a feature request please? 

Thank you

**Comment by edhelas** [comment]
I'm planning to change this flow for something more convenient with a proper selection system based on https://github.com/xsf/xeps/pull/1281
