### ISSUE TITLE
Error when trying to start the daemon

### ISSUE THREAD

**Issue by chlogaba36** [movim/movim#1195]
Good afternoon,

I'm trying to install movim on my Ubuntu distribution with your tutorial (I chose to use Nginx and to set up postgresql database) but I failed to start the daemon at step 4 (php daemon.php start) and got the errors:

```
Generate and store the Push Notification VAPID keys
PHP Warning:  file_put_contents(/var/www/movim/cache/vapid_keys.json): failed to open stream: No such file or directory in /var/www/movim/src/Movim/Daemon/Core.php on line 59

In UnixServer.php line 89:
                                                                                                    
  Failed to listen on Unix domain socket "unix:///var/www/movim/cache/socketapi.sock": Unknown error 
```

I don't know how to solve this issue and I would be grateful if you could help me.

Best regards,
Chloé

**Comment by edhelas** [comment]
It seems that the daemon doesn't have the writing rights for the `cache` directory, please ensure that this step is properly applied https://github.com/movim/movim/blob/master/INSTALL.md#1-rights-check

**Comment by chlogaba36** [comment]
Thanks for your answer but I did write the permissions asked (I used the command given in the tutorial)

I did not think about it but I had an issue with the composer install step:

```
www-data@chloe-Inspiron-15-5518:~/movim$: composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/dbal 3.6.1 -> satisfiable by doctrine/dbal[3.6.1].
    - doctrine/dbal 3.6.1 requires composer-runtime-api ^2 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it
Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```

Should I try to use Composer 2?

Thank you in advance for your help.
Best regards,
Chloé

**Comment by edhelas** [comment]
Yes, composer 2 is required to setup Movim.
Normally all the recent Linux distributions should have it already packaged. Your distribution might be quite old.

If not: https://github.com/movim/movim/blob/master/INSTALL.md#if-you-have-to-install-manually-composer

**Comment by chlogaba36** [comment]
Thank you for your help, i upgraded my Ubuntu distribution to the latest version and it seems to have helped me.
However, I still can't access to my movim page, but I do not see any errors in the different instructions.

When I start the daemon:
www-data@chloe-Inspiron-15-5518:~/movim$ php daemon.php start

Please set at least one user as an admin once its account is logged in
To set an existing user admin
php daemon.php setAdmin {jid}

Movim daemon launched
Base URL: https://public-movim.url/

--- Server Configuration - Apache ---
Enable the Secure WebSocket to WebSocket tunneling
# a2enmod proxy_wstunnel 
Add this in your configuration file (default-ssl.conf)
ProxyPass /ws/ ws://127.0.0.1:8080/

--- Server Configuration - nginx ---
Add this in your configuration file
location /ws/ {
    proxy_pass http://127.0.0.1:8080/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect off;
}

--- Server Configuration - Caddy ---
Add this in your configuration file
handle /ws/* {
    reverse_proxy localhost:8080
}

Stickers compiled
Compiled po files
Files compiled in Opcache


Here is the my movim.conf file in var/www/movim/etc/nginx/conf.d directory, which could be false:

server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        server_name localhost;
        root /var/www/movim/public;

        location / {
                index index.php;
                add_header Access-Control-Allow-Origin *;
        }

        # Define a server side cache for the proxyfied pictures

        location /picture {
                include fastcgi_params;

                add_header X-Cache $upstream_cache_status;
                fastcgi_ignore_headers "Cache-Control" "Expires" "Set-Cookie";
                fastcgi_cache nginx_cache;
                fastcgi_cache_key $request_method$host$request_uri;
                fastcgi_cache_valid any 7d;
        }

        location ~ \.php$ {
                include fastcgi_params;
        }

        location /ws/ {
                proxy_pass http://127.0.0.1:8080/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto https;
                proxy_redirect off;
        }

}

When inspected my localhost:8080 page, it appears that i have a http error 426, and in the Console tab, it says: ndex):6736 crbug/1173575, non-JS module files deprecated.
(anonymous) @ (index):6736

I don't know how to solve this issue and I would be grateful if you could help me.

Thank you in advance for your help,
Best regards,
Chloé

**Comment by edhelas** [comment]
I'm sorry I don't have much time to do custom support here. Looks like you have deployment related issues. I invite you to join the support chatroom on [movim@conference.movim.eu](xmpp:movim@conference.movim.eu?join) and link your ticket there, some other people there might take some time to help you.

I'm leaving this ticket open for a while just in case someone might have some ideas to help.

**Comment by rkarpuzov** [comment]
` server_name localhost;` Here you must store your public FQDN. This must equal to your .env entry `DAEMON_URL`

**Comment by edhelas** [comment]
@chlogaba36 Did you figured out the issue ?

**Comment by edhelas** [comment]
Closing the issue because of no feedback on it
