### ISSUE TITLE
Add button not working in Role assignment

### ISSUE THREAD

**Issue by ticktostick** [movim/movim#1197]
Movim [v0.21.1]
Ubuntu 20
Chrome 111
firefox 111

Can not click on add button 
nothing happens
![movim bug](https://user-images.githubusercontent.com/80856666/232426189-d3230bbe-b141-4f5a-b070-430cf82ec548.jpg)

**Comment by edhelas** [comment]
I'd more information about the XMPP part there. Which Pubsub node, on which XMPP server, using which JID ?

**Comment by ticktostick** [comment]
its on-premises
hosted on ubuntu server 20
xmpp server ejabberd 23
installed movim [v0.21.1]
it was working on the same server on [Skiff 0.20]

**Comment by edhelas** [comment]
The best would be to check the related XMPP logs, you can enable it by launching the daemon with the following setting in the .env file:

```
DAEMON_DEBUG=true
DAEMON_VERBOSE=true
```

**Comment by ticktostick** [comment]
There is no log when clicking on add button
the problem is the button itself in the browser its not clickable

**Comment by ticktostick** [comment]
Checked Again 
The add button not working for Publisher Role
other Roles are added without problem (owner,.....)

**Comment by edhelas** [comment]
If I can't have any XMPP logs I can't do anything for you

**Comment by ticktostick** [comment]
I've found the log
The problem was nginx config
edited solved for now
