### ISSUE TITLE
Have you considered a Nix pkg or module?

### ISSUE THREAD

**Issue by toastal** [movim/movim#1199]
I’m not interested in containers when Nix/Guix can solve this issue without overhead and create a reproducible build (we can see [here](https://github.com/movim/movim_docker/blob/master/Dockerfile#L5) that the `Dockerfile` isn’t reproducible). I‘m considering getting the Nix pkg set up and maybe a module as well so a user could do `services.movim.enable = true` and have a working server like ‘magic’ (which would create a DB, connect the ports and open the firewall, add an Nginx server preconfigured with security headers etc.). Prosody and ejabberd modules (if its maintainers ever update it) could also have a `movimCompliance = true` option to make sure they are configured with Movim’s requirements.

Before I would touch any part of this though, I wanted to understand if this project already had such interest in it being within the project if it’s beyond the maintainer’s scope.

**Comment by edhelas** [comment]
I am not personally taking part of Movim packaging process, but it you're interested to do some Nix pkg for it, feed free to do it in a specific repository and I will link it to the official project if its considered stable enough :)

**Comment by toastal** [comment]
No worries. If the project isn’t sold on Nix, then it’s best to send these things to Nixpkgs.
