### ISSUE TITLE
Movim resets roster alias when open while adding phone contact in Cheogram.

### ISSUE THREAD

**Issue by gnafuthegreat** [movim/movim#1204]
I've run into a behavior that occurs when I have Movim open in a browser and try to add someone to my roster from Cheogram on my phone.  Here's the sequence of events:

1. Add phone contact to roster in Cheogram
2. In Movim, I get a notification that someone wants to chat with me
3. Contact in Movim now shows original alias (for example, JID +12345678910@cheogram.com has alias of "+12345678910" instead of "Friend's Name")

If I do not have Movim open when I add the contact in Cheogram, the contact shows up with my specified alias the next time I open Movim.  This seems to only happen when Movim is connected to the account at the same time that I add a phone account in Cheogram.

Testing has been done using the latest instance at mov.im.

I don't know if this is related to #1084, but it sounds similar but different enough that I figured I'd start with a new issue.

**Comment by edhelas** [comment]
Similar as #1084

**Comment by edhelas** [comment]
I just cannot reproduce, tried exactly your step and everything is sync perfectly for me.

1. Login using foo@movim.eu on Movim, Conversations and Pidgin
2. Add bar@movim.eu as a contact on Conversations, and test@movim.eu on Pidgin
3. Edit the contacts to change their aliases on Conversations and Pidgin
4. Movim correctly display the alias and group changes without having to logout/login

**Comment by gnafuthegreat** [comment]
My apologies; I completely misreported in my original comment.  I was trying to be more client-agnostic and was misremembering when this started occurring.

Cheogram has the ability to display [phone number]@cheogram.com JIDs with the system phone contact name for the corresponding phone number.  In recent releases of Cheogram, it now also sets the alias to the phone contact name when adding that JID to the roster.  This is where Movim is resetting the alias if it's open.

If Movim is closed when I add to the roster, other clients like Dino display the alias that was carried in from the phone contact.  The next time I open Movim, it displays that alias like any other.  But if Movim is open when the contact is added to the roster in Cheogram, Movim shows the notification that someone wants to chat and sets the alias back to [phone number] instead of [contact name].  That resets it on the roster, and other clients like Dino go from showing [contact name] back to [phone number].

All that to say, it does seem to be specific to the combination of Cheogram and Movim, and Movim has to be open for the issue to occur.
