### ISSUE TITLE
Wrong time in chat list when logging in 

### ISSUE THREAD

**Issue by speedygonzales9** [movim/movim#1205]
Hi, 

When I log into mov.im, it shows you the wrong time for 1:1 chats in the `Chats` list. However if I click on a chat to open that conversation, the time in the `Chats` list automatically corrects itself to the appropriate time for that chat. Can you fix this please? 

Thank you

**Comment by edhelas** [comment]
Yes, it's a cache issue

**Comment by edhelas** [comment]
This issue should be fixed by https://github.com/movim/movim/commit/73a43e320a6e74b1bcd0b16e3221626367b7e969 and the previous commits
