### ISSUE TITLE
Add support for mp3 files in small audio player in the chat 

### ISSUE THREAD

**Issue by speedygonzales9** [movim/movim#1206]
Hi, 

I regularly receive mp3 files throughout the day, so it would be very helpful if Movim's built in audio player could support mp3 files too. In the https://github.com/movim/movim/commit/2ed7cd6cca2389708d74e1dc08e649fc1b676cbc commit, it only supports ogg and opus audio files. Can I make this a feature request please? 

Thank you

**Comment by edhelas** [comment]
I'm not sure if MP3 are supported by all the browsers no ?

**Comment by speedygonzales9** [comment]
According to https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_delivery/Cross-browser_audio_basics#audio_codec_support
> Note: Nearly all browsers support MP3

**Comment by speedygonzales9** [comment]
Here is a better source: https://caniuse.com/mp3
It looks like mp3 is supported everywhere.
