### ISSUE TITLE
Running composer update in php8.1 has problems with several library versions

### ISSUE THREAD

**Issue by naxiangzi** [movim/movim#1208]
Running composer update in php8.1 has problems with several library versions. (commonmark,web-push,phpdotenv )
Update docker-compose related container is recommended.
`composer update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires league/commonmark 2.4.*, found league/commonmark[2.4.x-dev] but it does not match your minimum-stability and is therefore not installable. Make sure you either fix the minimum-stability or avoid updating this package to keep the one present in the lock file (league/commonmark[2.4.0]).
  Problem 2
    - Root composer.json requires minishlink/web-push ^8.0, found minishlink/web-push[dev-try-fix-test-once-more, dev-fix/tests, dev-master, 0.1.0, 0.2.0, 0.2.1, 0.2.2, v1.0, ..., v1.4.3, v2.0.0, v2.0.1, v3.0.0, v3.0.1, v3.0.2, v4.0.0, v4.0.1, v4.0.2, v5.0.0, ..., v5.2.5, v6.0.0, ..., v6.0.7, v7.0.0] but these do not match your constraint and are therefore not installable. Make sure you either fix the constraint or avoid updating this package to keep the one present in the lock file (minishlink/web-push[v8.0.0]).
  Problem 3
    - Root composer.json requires vlucas/phpdotenv ^5.5, found vlucas/phpdotenv[dev-master, 5.5.x-dev (alias of dev-master)] but these do not match your minimum-stability and are therefore not installable. Make sure you either fix the minimum-stability or avoid updating this package to keep the one present in the lock file (vlucas/phpdotenv[v5.5.0]).`

**Comment by edhelas** [comment]
You never have to run `composer update`.
The repository is coming with a composer.lock with dependencies that are tested and validated each time.

The only thing that you have to do is update the project (by doing `git  pull` for example, and do `composer install`.
