### ISSUE TITLE
cookies in login

### ISSUE THREAD

**Issue by royalterra** [movim/movim#121]
I observe some times if you have MOVIM in a Iframe the logout no works the user show a grey icon . Also in the principal page in the domain root is the seam issue.

You can change also to in both situations the status of the user

**Comment by edhelas** [comment]
I'm sorry I can't understand your problem.

**Comment by royalterra** [comment]
:edhelas  Sorry I just see your reply . Example I login in MOVIM I can use https://blablanet.com/mchat 
or https://blablanet.eu   The first link is a Iframe if a change the page and logout or close chrome browser the cookie is not delete and the session in php is open . When you go back again to login you like example change your status but not respond and show always a grey icon also you can't logout . You need to clean the cookies for the domain using the browser for login , logout and status work again correctly

**Comment by edhelas** [comment]
Movim has never been tested in an iframe and I think that this can be the cause of your issue.
Also it's the aim of a cookie to stay even if the browser is closed and reopen but the fact that your session is "disconnected" is another issue.

A small (maybe related) question. Do you have XDebug installed with PHP on your server ?
