### ISSUE TITLE
Add a server that is deployed as a standalone server

### ISSUE THREAD

**Issue by naxiangzi** [movim/movim#1210]
Some countries prohibit the connection to the official server, leading to the inability to log in, if you can deploy independently, do not need to connect to the official server list, even better.
A message is displayed in the upper right corner when you log in to the self-deployed server.
`Reconnection to the server... 
Movim cannot talk with the server,please try again later`

**Comment by edhelas** [comment]
This is the result of a server misconfiguration on your side, very likely in the Apache/nginx configuration and/or the Movim daemon didn't start. The browser notification says cannot connect to the Movim daemon.
