### ISSUE TITLE
During Jingle A/V RTP calls, Movim is not building `extmap` attribute correctly

### ISSUE THREAD

**Issue by goffi-contrib** [movim/movim#1213]
While doing a RTP call, Movim being the initiator, if the other peer send XEP-0294 `<rtp-hdrext>` elements like those:
```
<rtp-hdrext xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0" id="1" uri="urn:ietf:params:rtp-hdrext:ssrc-audio-level" senders="both"/>
<rtp-hdrext xmlns="urn:xmpp:jingle:apps:rtp:rtp-hdrext:0" id="3" uri="urn:ietf:params:rtp-hdrext:sdes:mid" senders="both"/>
```

Movim convert it to following SDP:
```
a=extmap:1 both urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 both urn:ietf:params:rtp-hdrext:sdes:mid
```
This is invalid and result in failed call:
- the `senders` value is used directly while it should be mapped to a `direction` value ("sendonly", "recvonly", "sendrecv", or "inactive"). This is most probably related to https://github.com/movim/movim/issues/1212
- the direction should not be put after a space, but after a `/`

Reference: https://datatracker.ietf.org/doc/html/rfc8285#section-8

Tested with Movim v0.21rc7

**Comment by edhelas** [comment]
Fixed in https://github.com/movim/movim/commit/b5b7aa03717b332d32bdb52360b783f31c354695
