### ISSUE TITLE
Sending file does not generate URL (Chrome/OS X)

### ISSUE THREAD

**Issue by Nyco** [movim/movim#122]
Chrome latest, OS X latest.

Steps to reproduce:
- select conversation
- click on file attachement icon (clipper)
- select file

Results:
- "NaN%" message in lightbox
- no URL shown
- no transfer progress

![screen shot 2016-01-27 at 12 11 27](https://cloud.githubusercontent.com/assets/25348/12611859/3a5b29be-c4ef-11e5-8b86-44fbd968a1d5.png)
![screen shot 2016-01-27 at 12 03 01](https://cloud.githubusercontent.com/assets/25348/12611861/3e7ddcda-c4ef-11e5-9d50-274d646bdc72.png)

Note: works fine on Firefox 43 and 44 on OS X latest.

**Comment by edhelas** [comment]
This is a known bug in Chrome on all the platforms https://productforums.google.com/forum/#!topic/chrome/sfAqeo4hDy8. Furthermore it's related to the server configuration (which is here configured to work with SPDY).
