### ISSUE TITLE
hard coded absolute path for symbolic links in html/public/cache/ js and css files?

### ISSUE THREAD

**Issue by poVoq** [movim/movim#1220]
It seems like Movim creates symbolic links for the .js and .css files in the `/html/public/cache` folder and at least in the Docker images these appear to result in a hard coded absolute path at `/var/www/html/app/...`

While this works inside the docker container, this breaks when trying to serve these files from an external Nginx where these files are at a different absolute path.

It appears that the official docker compose script gets around this by including an additional Nginx that forces these files inside to the same `/var/www/html/app/...` location, but otherwise this additional Nginx seems completely redundant.

I think the proper solution would be to make these symbolic links relative, something like `../../apps/...`

**Comment by poVoq** [comment]
Removing the symlinks results in the following error being displayed in the browser:

```
Warning
: symlink(): Permission denied in
/var/www/html/src/Movim/Widget/Base.php
on line
246
```

But apparently these cache files get rebuilt on a restart of the daemon / container.

I suspect that the issue is with DOCUMENT_ROOT being used to determine the absolute paths for these symlinks and as this is done inside the container the `/var/www/html/app/...` path is used.

See: https://yagudaev.com/posts/resolving-php-relative-path-problem/

**Comment by poVoq** [comment]
The likely culprit is this:
https://github.com/movim/movim/blob/1e545a6da8e4eb6039a56f1ae6d6083b71f194e5/src/Movim/Bootstrap.php#L95

As WIDGETS_PATH is used to construct the symlink path at the location mentioned above.

**Comment by poVoq** [comment]
Replacing the above line in Bootstrap.php with a relative path seems to work at first glance:

`define('WIDGETS_PATH', '../../app/widgets/');`

But I am probably overlooking something.

Edit: Yeah that breaks it pretty horribly after logging in.

**Comment by poVoq** [comment]
Changing this line:

https://github.com/movim/movim/blob/4e0c6f2f042d580b627fc39505cdd0bc2f1a6d13/src/Movim/Widget/Base.php#L241C13-L241C13

to

`$local = '../../app/widgets/' . get_class($this) . '/' . $filename;`

Seems to work and not have an immediate negative effect.

**Comment by poVoq** [comment]
Everything seems to work fine except that these strange things in the admin settings appear:

![image](https://github.com/movim/movim/assets/940360/91ba023f-650e-4e15-8ce5-5f0a51567007)

Might be unrelated though.

**Comment by edhelas** [comment]
I made the change, still don't get why you need it in Docker, but anyway

**Comment by poVoq** [comment]
Thanks!

This is a peculiarity with the php docker setup. From the inside of the container these files are at `/var/www/html` and for the daemon and the php-fpm process they appear like that, but the actual serving of the static files is not done in the same container, but rather by the host Nginx (or a separate Nginx container), which usually has a totally different file structure and thus these static files are very likely not at `/var/www/html/`.

I think this theoretically greatly simplifies the Docker setup and I'll open an issue on the movim_docker repo for it.

**Comment by edhelas** [comment]
Please do

**Comment by edhelas** [comment]
> Everything seems to work fine except that these strange things in the admin settings appear:
> 
> ![image](https://user-images.githubusercontent.com/940360/255289751-91ba023f-650e-4e15-8ce5-5f0a51567007.png)
> 
> Might be unrelated though.

See https://github.com/movim/movim/commit/a6fac667cfa0a803f15659937f8558ff13992fa2
