### ISSUE TITLE
WebSocket linker not sending any messages

### ISSUE THREAD

**Issue by NotNite** [movim/movim#1221]
Hi, I've been trying to deploy Movim over the past week or so, but cannot because the WebSocket never receives any messages on the client. This can be reproduced both **in Docker, in a standalone Debian install, and in my own NixOS derivation**. When logging in, the webpage sends messages and never receives any, and eventually the client from the website disconnects and reconnects:

![image](https://github.com/movim/movim/assets/44414597/462ce5fb-0e55-4b1d-aa1a-c1915105ed75)

This happened in the Docker container, and I then tried to shove it into NixOS (and failed because of weird daemon errors), so then I just set up a bare Debian box running only PostgreSQL, nginx, php-fpm and Movim. The logs have ranged from nonexistent to unhelpful (on the Debian box I get no logs, on Docker I just see it connecting and disconnecting, even with debug/verbose turned on).

Given that other people seem to be deploying Movim fine I think I may be haunted by the ghost of Movim past(?) but this seems strangely consistent to me, even breaking on platforms where consistency is the main idea (Docker). I'm completely out of ideas, any guidance on how to debug this would be appreciated (even if just editing print statements into certain files).

**Comment by edhelas** [comment]
Well here you need to give details on what webserver setup you have. 

Server configuration, daemon logs, anything that could help.

**Comment by NotNite** [comment]
Both of these setups I've tried with both direct connections, nginx on port 80, and nginx on port 443 (with certificates). None work. Interestingly, even with `DAEMON_DEBUG` and `DAEMON_VERBOSE` set, no debug/verbose logs seem to be written to stdout or created in `log`.

---

On the Debian server: fresh installation of Debian 12 where I `apt install`ed the listed dependencies in the install guide, along with PostgreSQL and NGINX. The NGINX config is [here](https://gist.github.com/NotNite/3a1e9869d4b7f8d73381e949b771ebd3) (adapted from the one in the repository + the Docker config). I have yet to put it into a systemd unit, so I'm just doing `php daemon.php start`. I made a `movim` user and cloned the source into `/home/movim/movim`, adding the web user to the movim group and making sure that group permissions were set for the log and public dir.

The env variables are:
```
DB_DRIVER=pgsql
DB_HOST=localhost
DB_PORT=5432
DB_DATABASE=movim
DB_USERNAME=movim
DB_PASSWORD=redacted # this is valid, as migrations complete

DAEMON_URL=http://movim/ # Connected over Tailscale
DAEMON_PORT=8080
DAEMON_INTERFACE=127.0.0.1
DAEMON_DEBUG=true
DAEMON_VERBOSE=true
```

I don't really know where php-fpm is logging to, but I'll look into that to get more insight.

---

On the Docker container: using the compose file in [the README](https://github.com/movim/movim_docker), with some modifications:

- `${PWD}` wasn't working so I replaced it with just `./`
- `DAEMON_URL` is now `http://docker-misc` (this is a valid address for me with my DNS configuration)
- DAEMON_DEBUG`/`DAEMON_VERBOSE` are now set to true
- I'm going off the `master` tag, but I tried `latest` and `0.22` (same on all 3)

I am using [the NGINX config linked in the README](https://gist.githubusercontent.com/kawaii/468f24135bc5cf817b922d8491276771/raw/bc0a881c5a505ffa677655f515502533d33b7174/movim.conf).

**Comment by edhelas** [comment]
No, the DAEMON_URL in Docker __MUST__ be the one set in the .env of Movim. 
I don't now exactly how you did setup your DNS or Docker but the architecture should follow this https://github.com/movim/movim/blob/master/INSTALL.md#general-architecture

The DAEMON_URL is used internally by Movim to generate all the links and paths. Actually we have an issue with Docker with it but the Docker set DAEMON_URL SHOULD overwritte the one you setin the .env (as well as all the other configuration, if they are set in the Docker container)... it is how DotEnv is actually working.

**Comment by NotNite** [comment]
Yes, they match. I made an .env in the `movim` folder mounted by the Docker container with the exact same contents of the compose file, but it happens with or without:

```
$ cat docker-compose.yml | grep "DAEMON_URL"
      DAEMON_URL: http://docker-misc
$ cat movim/.env | grep "DAEMON_URL"
DAEMON_URL=http://docker-misc
```

**Comment by edhelas** [comment]
So I don't know. Looks like you missed something in your server setup.

Try a raw deployment without Docker and see if adding Docker on top breaks something.

I'm closing this ticket as is doesn't seems to be Movim related. Feel free to continue the investigation/discussion on the main support chatroom: xmpp:movim@conference.movim.eu

**Comment by Finn10111** [comment]
Hey @NotNite - I am having the same issues, were you able to solve that issue in the meantime?
