### ISSUE TITLE
Infinite redirect loop when deployed on a subdirectory

### ISSUE THREAD

**Issue by dos1** [movim/movim#1222]
I just updated from 5414db28c28d72e65cb445c17a9a05a8968bf271 (between v0.21rc7 and v0.21rc8) to v0.22.2 and couldn't get Movim to run on `/jabber` subdirectory with Apache: it kept redirecting to `/jabber/news` in a loop. No such issue when deploying on root.

**Comment by edhelas** [comment]
I think I'll simply forbid subdirectory deployment. It's just too complicated to handle the URLs and basically it's always doable for the admin to declare a subdomain and add a certificate to it.

Also I it requires more test and specific configuration... which is not tested in the end
