### ISSUE TITLE
Remote avatar cache generation only tries once and never again

### ISSUE THREAD

**Issue by poVoq** [movim/movim#1223]
If for some reason the conversion to .webp (those stored in /html/public/cache) for remote avatars (both users and muc) fails, Movim never tries again to regenerate these even when completely disconnecting from a room, deleting it and reconnecting. Only on the very first try to ever connect to a room these are queried and converted to .webp for storage in the cache.

Artificial way to replicate it:

1. Join some new, never before seen remote muc and see most avatars get fetched correctly (but not all)
2. Go to /html/public/cache and do a rm *.webp
3. See all avatars replaced with the generated svg placeholders (only the personal avatar does get regenerated)
4. try like mad to trigger a regeneration of the avatars, but nothing you can do from within Movim can bring them back
5. Enter database and do a `truncate contacts cascade;` via psql
6. Reload Movim in the browser and see almost all avatars that were broken before regenerate.

I think ultimately there is something slightly fail-prone with fetching remote avatars and Movim just makes the issue worse by only ever trying once to fetch them and if it has any recollection of having previously connected with a MUC it just refuses to try and re-fetch and regenerate missing avatars in its cache.

**Comment by poVoq** [comment]
From the chat:

```
Try to comment line 110 and 115 in PresenceBufferSaver and try again
(the current master version)
```

I tried doing this, then I removed again all the .webp files in /html/public/cache and reloaded the browser & logging in and out, but no avatars were regenerated. 
Then I tried restarting the daemon to see if that would trigger a regeneration of the missing avatars, but also no difference.

**Comment by edhelas** [comment]
First, please never touch the cache. Movim is having its own internal system to keep track of it.

When doing a harsh rm on it, you basically cut links internally and create a mess.

**Comment by poVoq** [comment]
Yes, I am aware... this is only a way to 100% replicate the issue I was seeing before that many avatars never got cached at all and thus didn't have corresponding files in the /cache/ folder.

**Comment by poVoq** [comment]
Thanks!
