### ISSUE TITLE
Moderating a message includes a confusing reason

### ISSUE THREAD

**Issue by singpolyma** [movim/movim#1224]
```
<message xmlns="jabber:client" type="groupchat">
  <apply-to id="d5f5cb6d-1282-4564-8ddf-5c9dc9e57799" xmlns="urn:xmpp:fasten:0">
    <moderated xmlns="urn:xmpp:message-moderate:0" by="MUC/USER">
      <retract xmlns="urn:xmpp:message-retract:0" />
      <reason>Your contact attempted to retract a previous message, but it's unsupported by your client</reason>
</moderated>
</apply-to>
</message>
```

Shown in Gajim as: `This message has been retracted by USER. Reason: Your contact attempted to retract a previous message, but it's unsupported by your client` which is fairly confusing looking.

**Comment by edhelas** [comment]
What would seems to be a better message for you ?

**Comment by singpolyma** [comment]
Usually the reason is specified by the user doing the moderation, I often see "Spam" or "Abuse" used.  If you don't support the user supplying a message I guess even just "Moderated" would be fine?
