### ISSUE TITLE
Blog posts are sorted oldest first in profile view

### ISSUE THREAD

**Issue by truenicoco** [movim/movim#1226]
This seems to be a bug because depending on whose profile I check, the behaviour is not consistent. For some, blog posts appear as "most recent first", which I believe is what makes most sense, but for some others, it's the reverse order, eg:

![Screenshot_20230915_084424-1](https://github.com/movim/movim/assets/1313576/631465a4-eb13-4338-b7b8-5a6c4bb27262)

**Comment by edhelas** [comment]
Prosody server ?

Movim respect the order of the Pubsub items returned from the server, Prosody doesn't return the most recent first afaik.

**Comment by truenicoco** [comment]
> Prosody server ?

Yes, this user (and me) both use a prosody server. My server shouldn't matter here I guess, only theirs.

**Comment by edhelas** [comment]
Related to https://issues.prosody.im/1168
