### ISSUE TITLE
(some) inline image previews do not work

### ISSUE THREAD

**Issue by truenicoco** [movim/movim#1227]
For some HTTP uploaded images, the inline image preview, and the full screen zoom do not work.
![Screenshot_20230915_095633](https://github.com/movim/movim/assets/1313576/0e7b7df6-e150-4665-9fdc-2e156297f7b9)
![Screenshot_20230915_095641](https://github.com/movim/movim/assets/1313576/c8990590-edb9-43d4-b12b-ef16c40d849f)

Clicking on "upload.nicoco.fr" opens the image in another tab just fine.

I'm not sure where to look for more info, maybe this error in the JS console is related?

> Uncaught (in promise) TypeError: ServiceWorker script at https://movim.nicoco.fr/chat/the-muc%40conference.nicoco.fr/sw.js for scope https://movim.nicoco.fr/chat/the-muc%40conference.nicoco.fr/ encountered an error during installation.

**Comment by truenicoco** [comment]
This also happens with blog post attachments. I am not entirely sure under which conditions, but it does, sometimes.

**Comment by edhelas** [comment]
Check if the picture is not passing one of the if() in this file https://github.com/movim/movim/blob/master/app/widgets/Picture/Picture.php
