### ISSUE TITLE
Neither user JID or default server admin setting is respected in create new room dialog

### ISSUE THREAD

**Issue by poVoq** [movim/movim#1232]
The create a chatroom dialog pre-fills the "Chatroom ID" field with the MUC component domain from another vhost on my xmpp server that is unrelated to the user trying to create the room and also not mentioned as the default xmpp server in the Movim admin settings.

This is quite confusing for new users trying to create rooms, as they do not have permission to create rooms on that unrelated muc component.

This might be something in my ejabberd configuration, but I think it would be best if Movim would always suggest the muc component domain of the user's home server as they are most likely to have permission to create new rooms there.

**Comment by edhelas** [comment]
From what I see in the sourcecode the default servers are actually guessed from the user account host. So I'd need a real case to be able to reproduce it. If for example you have a Movim instance AND XMPP account where you have the issue.

**Comment by poVoq** [comment]
Is it possible that it takes the domain from the very first user that ever logged in instead?

I originally tested it with an account from another vHost as the initial user/admin and now all accounts seem to default to that user's muc component domain, despite being on a different vHost.

You can sign up on https://slrpnk.net for the combined XMPP & Lemmy account and it will work on https://movim.slrpnk.net where you should be able to see the issue when trying to create a new room.

**Comment by edhelas** [comment]
Cannot reproduce, the soucecode enforce the local services https://github.com/movim/movim/blob/master/app/Session.php#L133
