### ISSUE TITLE
Global MUC search broken

### ISSUE THREAD

**Issue by volpeon** [movim/movim#1236]
I noticed that the chatroom list is supposed to be populated with results from the global search API at https://search.jabber.network/docs/api. However, my list was always empty. Looking at the code, it seems that the wrong JID is used:

https://github.com/movim/movim/blob/69c07b7e9d0b9b54d5f0f5f80ae421c2fb4c1e03/src/Moxl/Stanza/Muclumbus.php#L37

It's `rodrigo.de.mucobedo@dreckshal.de`, but the documentation says it should be `api@search.jabber.network`.
Applying this change on my instance fixes the issue:
![grafik](https://github.com/movim/movim/assets/76151476/418f5744-8091-46c9-ab6a-c03d6c3897b6)

**Comment by poVoq** [comment]
Is this something that needs to be enabled? On my pod it seems to only search for mucs locally.

Edit: ah, I had to change the global admin setting and log out and in again for it to work.
