### ISSUE TITLE
Web Interface Issue

### ISSUE THREAD

**Issue by MobileTallent** [movim/movim#1238]
My Movim client redirects "news" page and it returns 404 error. someone can help me?
I used Apache2 and PostgreSQL. seems the Movim's route is not working.

**Comment by edhelas** [comment]
Did you just do a migration to the recent version ?
You need to configure your Apache server to add URL rewrite since the last version.

See https://mov.im/node/pubsub.movim.eu/Movim/a2d05925-0427-4f3f-b777-d20571ddddff

**Comment by edhelas** [comment]
Since 0.22 actually https://github.com/movim/movim/blob/master/CHANGELOG.md#v022
