### ISSUE TITLE
"[JID] is now member" error when clicked (when made channel member)

### ISSUE THREAD

**Issue by ltguillaume** [movim/movim#1239]
2 days ago I was made member of a couple of channels and thus got the message "[my JID] is now member". When I clicked the message, however, I got:

![image](https://github.com/movim/movim/assets/4777345/62a48b9e-a8f8-4780-83e6-acc74f463503)

There are no entries in the browser console.

**Comment by edhelas** [comment]
This should be fixed, this menu is not accessible anymore for those kind of messages
