### ISSUE TITLE
Back button not working in users' profiles 

### ISSUE THREAD

**Issue by speedygonzales9** [movim/movim#1241]
Hi, 

When I go to an user profile in `mov.im`, the back button beside their avatar does not work. Can you fix this issue please? 

Thank you

**Comment by edhelas** [comment]
Note to myself: This is related to the Tabs widget that build the tabs (and add the anchor in the URL) even if the tabs are not visible (in the Drawer)

**Comment by edhelas** [comment]
Should be fixed in master

**Comment by speedygonzales9** [comment]
Thanks, it's working now :)
