### ISSUE TITLE
Not showing push notification banner in Windows when the PWA is minimized 

### ISSUE THREAD

**Issue by speedygonzales9** [movim/movim#1242]
Hi, 

I am using Windows 10 Home. I installed Movim's PWA through Google Chrome and enabled push notifications. Unfortunately when the PWA is minimized and someone messages me, the notification banner doesn't appear in Windows (sometimes Movim's notification sound will not play.) However with my Google Chrome browser open **and** the PWA **closed**, the notification banner displays in Windows. My Google Chrome browser is up to date (`version 118.0.5993.89`). I would like notification banners to display in Windows when the PWA is minimized. Can you fix this issue please? 

Thank you

**Comment by edhelas** [comment]
What do you mean "minimized" ?
If the tab is unfocused but opened native notifications will be used. If the tab is closed, Movim is switching to push notifications.

Maybe in your case it seems that the tab is actually focused but "minimized" doesn't unfocused it.
In any cases I don't have a Windows to play with and it seems to be more of a "Windows PWA" strange behavior.

**Comment by speedygonzales9** [comment]
When I go to the `mov.im` website, there is a "Install Movim" button to the right of the URL address. If I click on it, it installs the Movim PWA and opens it up in a new window where I can minimize, maximize, or close the window. When I minimize the window, there is no notification banner that displays in Windows. Other websites that are PWA's display the notification banner when they are minimized. Can you please fix this?

**Comment by edhelas** [comment]
![image](https://github.com/movim/movim/assets/3726886/0aad6731-3fd9-4d27-b70f-a5f2f821726e)

I don't have Window right now. But on Chrome on Linux it works for me (Chrome PWA on top, Firefox in the bottom), even when I'm discussing with the person and its minimized. I'll check on Window when I'll have access to one.

**Comment by speedygonzales9** [comment]
Thank you for looking into this further. I appreciate this very much! :) Maybe I am doing something wrong.
