### ISSUE TITLE
click and scrool not working in Community page because of empty div

### ISSUE THREAD

**Issue by 1inguini** [movim/movim#1243]
There is empty div tag as a last child of body tag, which is making everything (scroll and every buttons except the post button) in the main tag, which is mostly everything visual except the sidebar, not working.

I'm using Firefox/118.0
 
* The region of the main tag
![main](https://github.com/movim/movim/assets/42938754/a6d4cfb3-52b4-475b-89b9-ee74129e626d)

* The empty div tag
![Community Page](https://github.com/movim/movim/assets/42938754/e4538762-5e92-4a3f-ba82-d27e0f2e10b6)

**Comment by edhelas** [comment]
Check your Firefox modules, disable the ones that are changing the DOM of the page and see if it solves the issue

**Comment by 1inguini** [comment]
[DeepL / MultiTranslate](https://addons.mozilla.org/ja/firefox/addon/deepl/) Addon was the culprit. Thank you for pointing out!
