### ISSUE TITLE
New concept of forums and blogs (Groups, Supergroup and Channels)

### ISSUE THREAD

**Issue by Pantyhose-X** [movim/movim#1245]
> Idea source https://code.briarproject.org/briar/briar/-/issues/1685

**General idea: The administrators of the group would have some general adjustments for the group, according to the group configuration a category is assigned.**

### Generic settings for group administrators:

* Give the possibility that the users of the group, add new users, or not.
* Allow users to send messages or not.
* Allow users to send images or not.
* Allow users to send files or not.
* Allow users to send music or not.
* Allow users to send audios or not.
* Allow users to send gif or not.
* Other settings...

Depending on the general settings of the group, categories could be assigned, the categories change according to the group's permissions.

### Category "Channels"
Category feature:

* Group members can only receive messages.
* All users can create a new "Channel" by default group permissions shown above.

For example, in a group that is not allowed to speak to its members and only administrators can speak, this category would be assigned since information is only received from administrators (for example, offers, or news about games, news, etc.)
In this case it would be good to give the possibility of self-publishing rss news for administrators.

### Category "Group"
Category feature:

* Group members can send and receive messages.
* Group members cannot add new users (Only administrators can do so)
* All users can create a new "Group" by default group permissions shown above.

### Category "Supergroup"
Category feature:

* Group members can send and receive messages.
* Group members can add new users.
* All users can create a new "Supergroup" by default group permissions shown above.

I think that would be better. More organized, cleaner. Regards

<img src=https://user-images.githubusercontent.com/42504385/165966010-068fc5a4-76a6-49da-a43c-a05e20726424.png width=70% />

**Comment by edhelas** [comment]
This is basically a c/c of the link above.

I don't have the time nore the motivation to try to understand how to adapt that to Movim. If you want to discuss such features please join our general discussion/support chatroom movim@conference.movim.eu
