### ISSUE TITLE
Autofocus input field after [Reply] from message context menu

### ISSUE THREAD

**Issue by ltguillaume** [movim/movim#1246]
When clicking on a message and then selecting [Reply], the input field is not automatically focused. It therefore requires an extra click on the input field before the user can start typing their reply.

Tested on mov.im instance in Chromium-based browsers.

**Comment by edhelas** [comment]
Works for me, as expected by the following line https://github.com/movim/movim/blob/master/app/widgets/Chat/Chat.php#L872

Tested on Firefox and Chrome.

Please reopen the ticket if you have a more specific way to reproduce the issue
