### ISSUE TITLE
Quick translation of messages and blog posts?

### ISSUE THREAD

**Issue by poVoq** [movim/movim#1247]
It would be really cool if Movim could add an option to configure a translation API (maybe Deepl and selfhostable LibreTranslate) similar to how Telegram supports in app translation: https://www.androidpolice.com/translate-telegram-messages/

Something like that is also supported by Mastodon and Akkoma these days and is very nice to easily translate foreign language blog posts as well.

The language can be autodetected by those APIs so it should be fairly easy to add to the message menu like on Telegram, and the target language can be autoselected from the browser language or be a profile setting. 

Just for e2ee encrypted chats it probably needs a warning that the message is send to an external service for translation.

I hope this feature request can be consider 😊

**Comment by ltguillaume** [comment]
Would Firefox's offline translation be of any help here?

**Comment by edhelas** [comment]
Each time I added a third party API I had to maintain and fix things because it broke somehow.
Last API I added was Twitter to have the tweets URLs previews... you know what happened.

@ltguillaume is summing up perfectly my point of view on this

If you want to translate things, you can use all the tools you have in your browser to do so.

**Comment by poVoq** [comment]
I strongly disagree on the suggestion that in browser translation tools work the same. It might work for blog posts, but definitely not in a chat where multiple languages are mixed. Nor do they work in a social media feed with multiple post languages being mixed.

Also Twitter is a really bad example because they intentionally broke their API access for business reasons, while providing API access is the sole "business" of translation tools and thus are highly stable to not break external tools utilizing them.

LibreTranslate is also fully open source and self-hosted so there is no external service that can break API access.
