### ISSUE TITLE
Cant create account

### ISSUE THREAD

**Issue by gunnakaa** [movim/movim#1248]
Hello
I cant create account. 
Want to see howe Dino works on my librem 5 Phone, but there is no way I get created an account. 
Is there something I do wrong or is this a known problem. By the way I live in Norway but well should not be the reason I think :)  
 

![Skjermbilde fra 2023-11-10 13-58-01](https://github.com/movim/movim/assets/91477719/757e6c6c-1cf9-45bf-bd42-13bf75ba09f1)

**Comment by edhelas** [comment]
It seems that the user already exists. Try a different nickname.
