### ISSUE TITLE
Still can create account

### ISSUE THREAD

**Issue by gunnakaa** [movim/movim#1249]
Hello 
I cant create account and is not because the user is already taken but I get Bad request.
![Skjermbilde fra 2023-11-13 18-11-15](https://github.com/movim/movim/assets/91477719/b9e0c478-5c56-4491-b6b3-4fbdb8a5737e)

When try again the user is already in use of course since I then made it before but got Bad request.
![Skjermbilde fra 2023-11-13 18-13-29](https://github.com/movim/movim/assets/91477719/6892c968-17a0-44b4-ae4a-f0586aed20a6)

Think this is an issue to look at.

**Comment by edhelas** [comment]
![image](https://github.com/movim/movim/assets/3726886/a85b8bf9-9da2-4661-ad1f-9369784b0b14)

Please disable your browser extensions, try with another browser and try again
