### ISSUE TITLE
Not working at Windows Xampp

### ISSUE THREAD

**Issue by MobileTallent** [movim/movim#1250]
![Screenshot_5](https://github.com/movim/movim/assets/21987622/4b82f3e0-8773-471d-b5a8-4dcd11dff7c2)

I was able to successfully install Movim on Xampp Windows. But the login screen returns "Unknown Error". And When I run "php daemon.php start", it says "Process pipes are not supported on Windows due to ehir blocking nature on Windows".

Movim cannot be used on Windows OS ?

**Comment by MobileTallent** [comment]
![Screenshot_6](https://github.com/movim/movim/assets/21987622/b02130ef-6f78-4227-b647-11bc412d9e45)

**Comment by edhelas** [comment]
It seems that the error in red is the cause of the problem indeed.

I'm not doing Windows support for Movim. I strongly advice you to launch a small Docker/VM/container and run Movim inside it. Windows can easily do that with Linux containers :)
