### ISSUE TITLE
PHP library for external use or simple HTTP API to send blog posts?

### ISSUE THREAD

**Issue by kevin2kevin2** [movim/movim#1251]
Hi.

I would like to do a plugin for SPIP (a quite popular CMS in France) to write blog post through it ([it already exists for Mastodon](https://contrib.spip.net/mastodon)). But, when it comes to XMPP, I am a complete noob. So I am looking for a simple solution to use (if it exists).

- [It does not seem to exist for WordPress](https://wordpress.org/plugins/tags/xmpp/), the currently most popular CMS.
- [The repo "Movim API"](https://github.com/movim/movim_api/) offers no documentation. Moreover, according to the short description, I assume (wrongly?) that it does not offer an interface to publish blog post.
- [PHP libraries for XMPP](https://packagist.org/search/?tags=xmpp) seem to be outdated. Moreover there are likely to be focused on the common XMPP usage, sending messages like IRC (I know XMPP is far better than that, but it is just a simple way to say it), and not sending blog posts as I would like.

In consequence, here comes my naive question: do you know a simple and documented way to connect to Movim and publish a blog post (in plain text, MarkDown or HTML) through a PHP (v7.4+) library or an HTTP API provided by Movim? Thanks.

**Comment by edhelas** [comment]
The Movim project goal is to only rely on XMPP for everything, Movim has some internal API between its UI and backend but its constantly changing and not made to be exposed.

The best way to publish content on "Movim" is to do it on the XMPP network directly.
Movim relies on this protocol for all its social interactions: https://xmpp.org/extensions/xep-0472.xml

Its basically Atom on XMPP Pubsub, there is a small Python tool that publish Atom 1.0 feeds on Pubsub for that, you can have a look at it https://github.com/edhelas/atomtopubsub
