### ISSUE TITLE
Quotes completely hidden

### ISSUE THREAD

**Issue by ltguillaume** [movim/movim#1252]
At times, quotes are completely hidden in Movim, while they are shown in other clients (using the same account). Example (in MUC xmpp:slidge@conference.nicoco.fr):

In Movim:
![image](https://github.com/movim/movim/assets/4777345/868b7ae3-d411-4cc0-aba2-56baabbe31f6)

The same messages in Gajim:
![image](https://github.com/movim/movim/assets/4777345/14db0b02-70d7-4e6c-9e2b-4c03ca61d959)

**Comment by edhelas** [comment]
Is the original message available on Movim ?
Because Movim cannot create a quote if the original message is not there.

**Comment by ltguillaume** [comment]
Not sure, hope I can still check, will do so later today. But even if it weren't the case, the original message is always embedded for backwards compatibility, right? Can't Movim at least extract it from there?

**Comment by ltguillaume** [comment]
Ok, so the original message of the _first_ quote **is not** available in the Movim history.
The original message of the _second_ quote **is** available in the Movim history.

**Comment by speedygonzales9** [comment]
> Is the original message available on Movim ? Because Movim cannot create a quote if the original message is not there.

I think this is still worth mentioning even though my messages are now gone in the MAM. Last week when I replied in `xmpp:general@channels.snikket.org` in mov.im it showed my reply. However when I disconnected and then connected to that MUC again, mov.im did not show my quote anymore (just my standard message.) This also happened in `discuss@conference.soprani.ca`.

**Comment by edhelas** [comment]
So it confirm my thought. When you reconnect Movim is clearing some MUC history in some cases, and the original message might be not loaded, so not quoted.

**Comment by ltguillaume** [comment]
> So it confirm my thought. When you reconnect Movim is clearing some MUC history in some cases, and the original message might be not loaded, so not quoted.

That's not true. I saw the original message for one of the two where the quote was missing.

![image](https://github.com/movim/movim/assets/4777345/c7e31e27-25f3-4a51-b6eb-221bfc02fe19)

it was posted only 8 hours before it was quoted (and on the same day I created this issue).

>Movim is clearing some MUC history in some cases

What are the conditions for this, and why?

**Comment by speedygonzales9** [comment]
> So it confirm my thought. When you reconnect Movim is clearing some MUC history in some cases, and the original message might be not loaded, so not quoted.
> That's not true. I saw the original message for one of the two where the quote was missing.

Me too - I saw the original message when I reconnected to the MUC.

**Comment by edhelas** [comment]
Ok, made a small investigation there.

It seems that those chatrooms doesn't support/implement XEP-0359: Unique and Stable Stanza IDs as stated in https://xmpp.org/extensions/xep-0461.html#business-id

```xml
<message to='miho@movim.eu/movimk6kijj' from='slidge@conference.nicoco.fr'>
    <result xmlns='urn:xmpp:mam:2' id='9fb80f6e-ba98-42e8-a09a-6732e03ed4e5' queryid='jj2DHdGhMeR8'>
        <forwarded xmlns='urn:xmpp:forward:0'>
            <delay xmlns='urn:xmpp:delay' stamp='2023-11-15T17:07:53Z'/>
            <message xmlns='jabber:client' type='groupchat' xml:lang='en' from='slidge@conference.nicoco.fr/raver' id='8708a532-7834-4520-b7df-aca5aa381833'>
                <reply xmlns='urn:xmpp:reply:0' to='slidge@conference.nicoco.fr/nicoco' id='1950cca8-9c22-4542-86df-dbcddd0ea437'/>
                <fallback xmlns='urn:xmpp:fallback:0' for='urn:xmpp:reply:0'>
                    <body end='253' start='0'/>
                </fallback>
                <html xmlns='http://jabber.org/protocol/xhtml-im'>
                    <body xmlns='http://www.w3.org/1999/xhtml'>&gt; One of the issues with this is that the connection between slidge and the XMPP server is unencrypted, so you have to add something hacky to have basic encryption anyway. I think someone here uses a SSH tunnel for this. But with a trusted XMPP server…<br/>
Yep here 😊✌️</body>
                </html>
                <body>&gt; One of the issues with this is that the connection between slidge and the XMPP server is unencrypted, so you have to add something hacky to have basic encryption anyway. I think someone here uses a SSH tunnel for this. But with a trusted XMPP server…
Yep here 😊✌️</body>
                <thread>801c0f07-4da2-422f-88eb-b21a1f30494d</thread>
                <occupant-id xmlns='urn:xmpp:occupant-id:0' id='N2g6FPXQgt/AnTR4lxKbHTbFMDvPJqqvYWbyN1O0xnM='/>
            </message>
        </forwarded>
    </result>
</message>
```

It means that Movim doesn't trust the reply and therefore cannot make a link between the two messages.

As for the fallback, I'm checking why its truncated.

Update: It seems that its on Prosody and that the stanza-id is truncated when the messages are retrieved via MAM

**Comment by Zash** [comment]
> ```xml
> <result xmlns='urn:xmpp:mam:2' id='9fb80f6e-ba98-42e8-a09a-6732e03ed4e5' queryid='jj2DHdGhMeR8'>
> ```

[XEP-0313 states:](https://xmpp.org/extensions/xep-0313.html#results)
> The result messages MUST contain a `<result/>` element with an 'id' attribute that gives the current message's archive UID (archived messages MAY also contain a XEP-0359 `<stanza-id>` element, but clients **MUST NOT** depend on it).

**Comment by edhelas** [comment]
Ok looks like I misunderstood something about MAM, I'll check what can I do
