### ISSUE TITLE
Login impossible with special character ł in JID

### ISSUE THREAD

**Issue by Nyco** [movim/movim#126]
A colleague could successfully create an account with dzoł@movim.eu but could not login.

**Comment by edhelas** [comment]
Merge with #106.

**Comment by vtexier** [comment]
Can not add a new chat room with special character in the JID : ğeconomicus@muc.jappix.com.
I am on https://nl.movim.eu/?chat and get an error message saying something like "bad chat room id"...
It is related to this issue, supporting full utf8 character set in JIDs.
But I can open a new issue if you prefer.
