### ISSUE TITLE
Not playing GIF animations 

### ISSUE THREAD

**Issue by speedygonzales9** [movim/movim#1260]
Hi, 

When someone sends me a GIF, the animation does not play in the chat view using `mov.im`. I tried clicking on the thumbnail preview to enlarge it. Unfortunately, the animation still doesn't play. However if open the GIF in a new tab, my browser (Google Chrome) plays the animation. I would like it to play the animation in `mov.im`. Can you please fix this issue? 

Thank you

**Comment by edhelas** [comment]
That's not a bug it's a feature.
Movim is protecting large images to be downloaded, including animated GIF (that can be very large).
