### ISSUE TITLE
Issues with decrypting own's OMEMO messages within MUC.

### ISSUE THREAD

**Issue by Chanakan5591** [movim/movim#1261]
Hello! So I have faced a challenge when trying to send an OMEMO messages and read them. I cannot see the messages that I just sent on movim on my own side (I don't know if others can decrypt them). But it basically shows
```
DOMException: No valid key or key range specified.
```

on `chatomemo_db.js` file. So I traced an error and found that the messages' ID are null. Those IDs are passed from `chatomemo.js` file, in the decrypt function, on this part:

```js
let resolvedId = message.mine
   ? message.originid
   : message.id;
```

apparently if the message is from yourself, it will use the originid element in message, but that doesn't exists, so it return null. I have tried changing them to simply

```js
let resolvedId = message.messageid;
```

and the messages are decrypted just fine. I don't know if there will be any issues that might arise from this modifications, so I am opening an issues just to check this.

**Comment by ManDay** [comment]
I think I may be having a similiar, probably the same issue, but it even extends a bit further. To reproduce:

2 Devices/Clients:
 - Monocles (OMEMO on)
 - Movim (on monocles.chat, OMEMO on)

Create a private chat in Movim. Then: *All* messages from Monocles (send encrypted) will refuse to show in Movim. And *all* encrypted messages from Movim (after you click the "encrypt" button) will also refuse to show in Movim itself.

![image](https://github.com/movim/movim/assets/1059827/babb20f5-a88f-40ad-a66e-d294d6beeac0)

shows the following messages, in order:

 1. sent from Monocles
 2. sent from Movim, unencrypted
 3. sent from Movim, after enabling encryption

The `DOMException` error only occurs on the message sent from Movim itself, though!

**Comment by ManDay** [comment]
I had no such problems in a 1-1-chat (however, all images refused to decrypt, but that's a separate issue).

**Comment by meaz** [comment]
I have the same issue: I can send OMEMO messages but I can not read my own message.

In Firefox console I can see that:
```
Uncaught (in promise) DOMException: No valid key or key range specified.
    promise https://myserver.org/cache/ChatOmemo_chatomemo_db.js?t=1703623138:76
    getMessage https://myserver.org/cache/ChatOmemo_chatomemo_db.js?t=1703623138:69
    decrypt https://myserver.org/cache/ChatOmemo_chatomemo.js?t=1703625068:262
    appendMessage https://myserver.org/cache/Chat_chat.js?t=1703625068:1047
    appendMessagesWrapper https://myserver.org/cache/Chat_chat.js?t=1703625068:884
    handle https://myserver.org/scripts/movim_rpc.js?t=1703623138:87
    onmessage https://myserver.org/scripts/movim_websocket.js?t=1703623138:119
15 ChatOmemo_chatomemo_db.js:76
```

- Once that message is sent, I see this is encrypted and I can not read it on movim.
- I can read that message from gajim (though I have a small icon that says that *trust is not decided*)
- If I send an encrypted message from gajim, I can not read it from movim.
- If someone else in the muc send an encrypted message from his/her client, I can read it from movim
- I have another user that tested all the previous steps: he got the exact same issue.

**Comment by exil0867** [comment]
+1
