### ISSUE TITLE
Misquoting when using Cheogram's threads feature

### ISSUE THREAD

**Issue by poVoq** [movim/movim#1262]
Cheogram automatically uses it's threads feature to link discussions together. But for some reason Movim interprets this as quotes and displays them as such.

As on the Cheogram side this is invisible, it is very easy to continue lengthy discussions without ever realizing that it constantly misquotes an unrelated messgage.

**Comment by ManDay** [comment]
> interprets this as quotes and displays them as such.

Probably should add, it interprets this as quotes of a message *other* than the one being replied to (likely the 1st message in the respective thread, though that is not apparent on the Movim side).
