### ISSUE TITLE
localhost movim http cannot connecting server

### ISSUE THREAD

**Issue by MobileTallent** [movim/movim#1264]
I installed Movim successfully on my local and it's now running with local domain - http://movim.local

I run this command
`php daemon.php start`

--url parameter does not work

Now my local movim client does not find any servers. so couldn't login with my movim.eu account on my local movim client.

How can my local movim client find the servers? Its impossible?

If I install XMPP server with another local domain, how are they connected?

**Comment by MobileTallent** [comment]
if I have one local movim client and one local XMPP server, how can they be connected each other?

**Comment by edhelas** [comment]
You need to follow the up to date INSTALL tutorial, especially that part https://github.com/movim/movim/blob/master/INSTALL.md#2-dotenv-configuration
