### ISSUE TITLE
quick question on 'meta data'

### ISSUE THREAD

**Issue by Cbarness** [movim/movim#1268]
![meta](https://github.com/movim/movim/assets/102334369/fa06c109-b9f6-4130-aab1-2145809657fa)

for the life of me i can not seem to find the file containing the meta info. I know i was in it to change pwa theme-color once but cant seem to find it now and am hoping i didn't accidentally delete it...

location would be appreciated. :)

**Comment by gnafuthegreat** [comment]
Looks like it's in `app/views/page.tpl`.  Is that what you're looking for?

**Comment by Cbarness** [comment]
i totally forgot about this! I must have checked everywhere EXCEPT in the views dir. Since you were helpful, can you tell me where the 'app name' variable is located?

**Comment by edhelas** [comment]
https://github.com/movim/movim/blob/master/src/Movim/Bootstrap.php#L72
