### ISSUE TITLE
Correct last message in a conversation

### ISSUE THREAD

**Issue by Nyco** [movim/movim#127]
Slack, HipChat, Skype, WhatsApp... all have this feature.
# Value

IN ORDER TO be able to fix all typos in the last message that has already been sent by a participant (one-to-one and MUC)
AS A normal (advanced) chat user
I WANT to have an interface that enables all participants to edit their last message text
# Behaviours
## **Basic** fixing of **my** typo

GIVEN I have just sent my last message with a typo to fix (one-to-one and MUC)
WHEN I type and send a "s/old/new/" notation
THEN Movim sends the plain "s/old/new/" notation as a body
AND Movim sends a stanza that respects XEP-0308 (same stanza?)
AND Movim changes my last sent message accordingly in my interface
## **Advanced** fixing of **my** typo

GIVEN I have just sent my last message with a typo to fix (one-to-one and MUC)
WHEN I right-click or long-tap on my last message in the conversation
THEN I can edit the whole message in the normal text/message input field

GIVEN I have just edited my last message
WHEN I send it
THEN Movim sends a stanza that respects XEP-0308
AND changes my last sent message accordingly in my interface
## Other participant fixing **his/her** typo

GIVEN I have a participant's last message with a typo to fix
WHEN I receive a "s/old/new/" notation OR a XEP-0308 stanza
THEN Movim changes this message accordingly in **my** interface
# Specifications

[XEP-0308: Last Message Correction](https://xmpp.org/extensions/xep-0308.html)
# Notes
1. Keep in mind that [XEP-0308: Last Message Correction](https://xmpp.org/extensions/xep-0308.html) should be compatible with [XEP-0313: Message Archive Management](https://xmpp.org/extensions/xep-0313.html): https://github.com/xsf/xeps/issues/146
2. Must stay compatible with MIX later

**Comment by edhelas** [comment]
Same as #37

**Comment by eyome** [comment]
This feature should be enabled only if the message box is empty. 
If not, up arrow should be used to move the cursor.

**Comment by eyome** [comment]
Down arrow erases the message if the message box is not empty
