### ISSUE TITLE
peertube support

### ISSUE THREAD

**Issue by rkarpuzov** [movim/movim#1270]
Hello,

Framasoft's Peertube is very similar as Youtube and will be good if Movim makes integrated video player inside of posts.

https://joinpeertube.org/ 
My instance and example video: https://peertube.teftera.com/w/3HSTcLwJxdLqzb8rQ7QhoH

Best regards,
Rossen Karpuzov

**Comment by edhelas** [comment]
This is not planned in the mid-long term, sorry
