### ISSUE TITLE
Unable to accept audio calls when logged in with account on Snikket server

### ISSUE THREAD

**Issue by mpanhans** [movim/movim#1271]
I have an xmpp account run through a Snikket server. When I use that account logged in to the Movim web application, I am unable to accept any audio calls. I am able to send and receive text messages, and I am able to successfully place audio calls.

I have noticed the following specific behaviors:

1. When calls are incoming from an xmpp account on the movim.eu server, upon clicking to accept the call, my Snikket account is suddenly logged out of Movim. I am able to consistently reproduce this behavior.

2. When calls are incoming through cheogram.com, I receive an incoming call notification pop-up through Movim, but am unable to successfully answer the call in any way.

Everything works fine with my Snikket account on other clients, as well as using other xmpp accounts on Movim. So there seems to be an issue that is specific to a Snikket account logged in to Movim. I've also tested this on a number of different web browsers and on a number of different desktop operating systems.

**Comment by edhelas** [comment]
> my Snikket account is suddenly logged out of Movim. I am able to consistently reproduce this behavior.

This looks like a crash, on which instance did you experienced that ?

**Comment by mpanhans** [comment]
Turns out that today I am no longer able to reproduce the crash. Incoming calls are able to be answered successfully. I'm still having issue 2, but now that seems like it might be a cheogram.com specific issue, so I will close this issue here. 
Thanks!
