### ISSUE TITLE
Sync of calendar from server to laptop and mobilephones not working 

### ISSUE THREAD

**Issue by cpcorvers** [movim/movim#1272]
Thank you for the great service and work Disroot is offering! I use Nextcloud via Disroot as much as possible. Calendar, Tasks and Deck I would like to use on a daily base but I run into some issues the last months.

I use these apps on the iPhone SE 2020, the iPhone 11, the iPad Pro 11inch and with Thunderbird on my laptop. All updated frequently to the latest version.

When adding an event in the calendar on device 'X' it will show on that device 'X' and in the Disroot cloud but it will not be 'pushed' to the calendars on the other devices. That is... at random some events will be visible on other devices mostly after a longer time. It looks like the synchronization from the server to the different devices/apps is not working as intended. The result is that I cannot trust my agenda overview on my devices and have to check my agenda via a browser on the Disroot cloud.

I already try to change settings like synchronization of only the last month, deleting and adding my account to the device and switching of all but one calendar.

What is going on? What can I check to reduce the problem to a concrete issue?

**Comment by ltguillaume** [comment]
This has nothing to do with Movim. Movim is a web client for XMPP/Jabber (the chat part that Disroot provides), but it's got nothing to do with Disroot or Nextcloud. Here are the ways to contact the Disroot team: https://disroot.org/en/contact

**Comment by cpcorvers** [comment]
My apologies. 
I'll mail the support via the contact information of Disroot.org.
