### ISSUE TITLE
Movim Connectivity Issue

### ISSUE THREAD

**Issue by harender28** [movim/movim#1278]
I want to set-up Movim for my private entity network. While connecting it is asking for a jabber id. I have created a Jabber id on movim.eu and tried to connect to our network but it is not working. On the Internet i have searched regarding the same, but i did not get anything from the internet. So I need help to  set-up  Movim on my local network.

**Comment by edhelas** [comment]
It seems that your local Movim instance cannot resolve movim.eu DNS ?

**Comment by harender28** [comment]
Yes, I need to install the movim on my local system

**Comment by edhelas** [comment]
Found the issue ?

**Comment by harender28** [comment]
trying to setup the movim on local server

**Comment by edhelas** [comment]
Closing the issue as no more feedback
