### ISSUE TITLE
Connection seems unstable

### ISSUE THREAD

**Issue by Nyco** [movim/movim#128]
I am using latest Mac OS X, and Firefox, Chrome, Safari latest.

What I can observe, **sometimes**:
- MAM is inconsistent with Conversations
- I don't receive my carboned messages
- I don't receive my contacts' messages
- I can't re-join a MUC

I am not sure about the conditions:
- sometimes it happens after I re-open my laptop
- sometimes it happens after a period of inactivity

I would suggest:
- XMPP ping, in order to maintain connection and have feedback on connectivity
- whitespace keepalives, in order to maintain connection

I am sorry for the lack of precision, please ask questions and challenge this, in order to better identify the conditions and results.

**Comment by Nyco** [comment]
Steps to reproduce:
- close my laptop (and go to lunch, or whatever... long enough)
- re-open laptop
- try to send message, by typing in the input field, <Enter>
  Result:
- message not in input field anymore
- message not displayed in conversation
- message not in another client that has carbon enabled

Wait...
- Redirected to the login page
- Log in
- Go back to the conversation
- Previous message is still not displayed in conversation, means it has not been archived in MAM
- Type and send messages, displayed twice in the conversation
- Receive messages, displayed twice in the conversation

Edhelas searched, two connections on the XMPP server are active:

**Comment by edhelas** [comment]
Same issue as #92
