### ISSUE TITLE
Font icon issue on login page

### ISSUE THREAD

**Issue by poVoq** [movim/movim#1293]
On Fedora 39 I see this:

![image](https://github.com/movim/movim/assets/940360/96a3f5e1-b94b-48ba-8fe6-ad1b76025ee4)

It seems to show on Android though, which makes me assume it is some sort of font issue.

Since all it is, is a `*`, why not use a normal `*` instead of some odd icon that not all devices render?

Thanks!

**Comment by edhelas** [comment]
Cannot reproduce, looks like your browser is blocking some fonts loading

**Comment by poVoq** [comment]
Double checked that, definitely not a browser blocking fonts issue. Although it is odd that the issue happens on Firefox, but not Chromium on the same system.

**Comment by edhelas** [comment]
I tried on Firefox on 4 devices, cannot reproduce, you you'll have to provide more info :)
