### ISSUE TITLE
Support for XEP-0393 preformatted text

### ISSUE THREAD

**Issue by poVoq** [movim/movim#1295]
It would be nice if Movim would support preformatted text as by [XEP-0393](https://xmpp.org/extensions/xep-0393.html) with the three back ticks.

Gajim for example supports this and you see this being used relatively often in developer discussions.

I think this could be styled similar to the /code command that is already available, see: https://github.com/movim/movim/issues/408 

Thanks!

**Comment by edhelas** [comment]
This ticket can easily be done by a contributor :)

**Comment by toastal** [comment]
I would be interested in this feature. I prefer reStructuredText & Asciidoc (& even Djot) to Markdown due to all of its limitations & lack of features & this would mean I could provide my own HTML.

**Comment by poVoq** [comment]
That's not really the purpose of XEP-0393 though. It is rather for Markdown like code-blocks.

What you want is the (deprechiated) [XEP-0071](https://xmpp.org/extensions/xep-0071.html) I think, and there are several people who would like this to be revived.

**Comment by edhelas** [comment]
XEP-0071: XHTML-IM is not happening

I'm ok to complete the XEP-0393 support. 
I added the "easy-first-ticket" tag for those that would like to do it, it should be pretty simple

**Comment by poVoq** [comment]
Done it seems: https://github.com/movim/movim/commit/2ace5889c3ef901c6088d60d1ba983bed122e5ac
