### ISSUE TITLE
Multiple entrée dans le fil d'actu pour le groupe Ouest France

### ISSUE THREAD

**Issue by ghost** [movim/movim#13]
# Question J’utilise #Movim et je suis abonnée au groupe Ouest France (actu locales et régionales). J’ai plein de doublons dans les articles, voire ils s’affichent 3, 4, 5 fois d’affilés !!! Déjà que l’OF diffuse beaucoup, là ça pourri carrément mon fil d’actualité ! Est-ce que vous avez constaté la même chose ? Est-ce que ce #bug peut provenir de Movim ? Ou de #ouestfrance ?

POD : https://pod.movim.eu/
GROUPE : news.movim.eu / Ouest-France - Actualité 

Désolé si la forme de la remonté de bug n'est pas extra, c'est la première fois que j'en fais.

**Comment by edhelas** [comment]
Pour faire simple, non ça n'est pas lié à Movim mais à l'outil que j'ai déployé qui parse le flux RSS et le publie sur Pubsub. J'ai l'impression que OuestFrance corrige ses articles faisant systématiquement remonter ceux-ci dans le flux et vu que je me base sur la date de publication… il y a doublon. 

Je vais retirer les publications OuestFrance pour le moment.
Si tu veux jeter un oeil au projet en question https://github.com/edhelas/atomtopubsub .

Je ferme le bug ;)

**Comment by ghost** [comment]
Ok, merci pour les explications.
Donc si je comprends bien, ce n'est pas OF qui publie volontairement, mais ton script qui parse le flux atom pour diffuser les articles dans pubsub.

Est-ce que ça marche aussi avec les autres format de flux RSS ?

Question perso, est-ce que l'ajout du flux émanent du Courrier Internationnal est possible ? ;-)
