### ISSUE TITLE
OMEMO Encryption error in chatrooms

### ISSUE THREAD

**Issue by Coehill** [movim/movim#1304]
I am able to use OMEMO encryption in direct messages, however if I enable it in a chatroom and attempt to send a message, I am presented with the attached error message.

![2a744c6c-97c6-420a-afd2-e0ce580c3c3e](https://github.com/movim/movim/assets/13023025/73047d2c-6aa5-4020-8f1b-6840580a7f4e)

**Comment by Arne19** [comment]
Hi, did you exchange presence and keys with these participants? You could also join the monocles support room to get more help: xmpp:support@conference.monocles.eu?join

**Comment by poVoq** [comment]
I think the problem here is that Movim has OMEMO disabled by default (due to various bugs) and those users probably only use Movim and therefore do not have created the necessary keys.

**Comment by edhelas** [comment]
Regarding the current OMEMO state and the fact that Movim relies on a now long deprecated library for that (https://github.com/signalapp/libsignal-protocol-javascript) I'm not doing support of that feature anymore until a proper replacement is found.

**Comment by edhelas** [comment]
This is not a bug but a flow misusage indeed.
