### ISSUE TITLE
Talking to myself...

### ISSUE THREAD

**Issue by Nyco** [movim/movim#131]
I confess I have an ego, but...

This "et bonjour, pardon", belongs to a conversation with edhelas...

![screen shot 2016-02-09 at 10 12 35](https://cloud.githubusercontent.com/assets/25348/12912633/2278bbc4-cf1a-11e5-8297-708df0519241.png)

This conversation with myself is empty.

**Comment by edhelas** [comment]
Does this still occurs ?

**Comment by edhelas** [comment]
I'm closing this ticket, I didn't experienced it myself since it was opened
