### ISSUE TITLE
OMEMO encrypted images in chats not shown inline, presented as downloadable files instead

### ISSUE THREAD

**Issue by Yetangitu** [movim/movim#1313]
Preamble: Running Movim v0.24 on Debian stable behind nginx (1.22.1), connecting to a Prosody server (0.12.3) on Debian stable.

In the above installation I notice that images in _OMEMO_ encrypted chats are not visible inline, instead they are presented as downloadable files using `blob:https://movim.example.org//01234567-1234-1234-1234-0123456789ab` links, eg:

![image](https://github.com/movim/movim/assets/2754838/32f61e10-d08b-4f65-bd8d-c211cd0d6592)

The same message shows the image as intended in other clients, e.g. gajim:

![image](https://github.com/movim/movim/assets/2754838/28972579-a2bd-4df4-be0d-510727241e2c)

In unencrypted chats images _are_ visible inline:

![image](https://github.com/movim/movim/assets/2754838/8288229b-1dce-4311-af23-7d16fde059a0)

Is this intended behaviour, is it the result of some (known) misconfiguration or is it a bug or something which has not yet been implemented? I know that _Movim_ does not (yet) support _sending_ OMEMO-encrypted images but it does seem to support _receiving_ them (the downloadable blobs do actually contain the correct images) but won't show them inline.

**Comment by poVoq** [comment]
It's probably done to avoid triggering the server-side image proxy that converts all images to .webp for display.

**Comment by edhelas** [comment]
Exactly, and this would require to cache the decrypted image browser side which is not planned for now.

**Comment by Yetangitu** [comment]
It would be good to document this behaviour in some way.

Would you be interested in a browser-side fix which implements inline encrypted image display with browser-side image caching (i.e. never touching the _webp_ proxy) or would that be perceived as too much of a privacy risk wrt. shared browsers?

OMEMO is what makes XMPP competitive vs. Signal/Telegram and is - at least here - used by everyone and his dog but the way it is currently handled in Movim makes it a less appealing alternative especially for those who speak in `<img>` instead of _words_ and want to see...

![image](https://github.com/movim/movim/assets/2754838/4ec4f22f-a618-46eb-a646-03b1d97d8c01)

instead of...

![image](https://github.com/movim/movim/assets/2754838/3e1cc4d3-0983-4c33-9ae7-21c2e57def63)

**Comment by CustardFlan** [comment]
I'm interested too in showing the encrypted images, maybe as an optative function, explaining the privacy risks to the user before enabling it?
