### ISSUE TITLE
Migrations failing on fresh install in fresh db in mariaDB Almalinux 9

### ISSUE THREAD

**Issue by CarlSinclair** [movim/movim#1315]
```
PDOException: SQLSTATE[HY000]: General error: 1833 Cannot change column 'id': used in a foreign key constraint 'movim/caches_user_id_foreign' of table 'movim/caches' in /var/www/html/movim/vendor/illuminate/database/Connection.php:587
Stack trace:
#0 /var/www/html/movim/vendor/illuminate/database/Connection.php(587): PDOStatement->execute()
#1 /var/www/html/movim/vendor/illuminate/database/Connection.php(816): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /var/www/html/movim/vendor/illuminate/database/Connection.php(783): Illuminate\Database\Connection->runQueryCallback()
#3 /var/www/html/movim/vendor/illuminate/database/Connection.php(576): Illuminate\Database\Connection->run()
#4 /var/www/html/movim/vendor/illuminate/database/Schema/Blueprint.php(110): Illuminate\Database\Connection->statement()
#5 /var/www/html/movim/vendor/illuminate/database/Schema/Builder.php(602): Illuminate\Database\Schema\Blueprint->build()
#6 /var/www/html/movim/vendor/illuminate/database/Schema/Builder.php(444): Illuminate\Database\Schema\Builder->build()
#7 /var/www/html/movim/database/migrations/20180510141439_change_length_contacts_id.php(30): Illuminate\Database\Schema\Builder->table()
#8 /var/www/html/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(111): ChangeLengthContactsId->up()
#9 /var/www/html/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(388): Phinx\Migration\Manager\Environment->executeMigration()
#10 /var/www/html/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration()
#11 /var/www/html/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate()
#12 /var/www/html/movim/vendor/symfony/console/Command/Command.php(326): Phinx\Console\Command\Migrate->execute()
#13 /var/www/html/movim/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#14 /var/www/html/movim/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#15 /var/www/html/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun()
#16 /var/www/html/movim/vendor/symfony/console/Application.php(175): Phinx\Console\PhinxApplication->doRun()
#17 /var/www/html/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#18 /var/www/html/movim/vendor/bin/phinx(119): include('...')
#19 {main}
```

```
Next Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1833 Cannot change column 'id': used in a foreign key constraint 'movim/caches_user_id_foreign' of table 'movim/caches' (Connection: default, SQL: ALTER TABLE users CHANGE id id VARCHAR(256) NOT NULL) in /var/www/html/movim/vendor/illuminate/database/Connection.php:829
Stack trace:
#0 /var/www/html/movim/vendor/illuminate/database/Connection.php(783): Illuminate\Database\Connection->runQueryCallback()
#1 /var/www/html/movim/vendor/illuminate/database/Connection.php(576): Illuminate\Database\Connection->run()
#2 /var/www/html/movim/vendor/illuminate/database/Schema/Blueprint.php(110): Illuminate\Database\Connection->statement()
#3 /var/www/html/movim/vendor/illuminate/database/Schema/Builder.php(602): Illuminate\Database\Schema\Blueprint->build()
#4 /var/www/html/movim/vendor/illuminate/database/Schema/Builder.php(444): Illuminate\Database\Schema\Builder->build()
#5 /var/www/html/movim/database/migrations/20180510141439_change_length_contacts_id.php(30): Illuminate\Database\Schema\Builder->table()
#6 /var/www/html/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(111): ChangeLengthContactsId->up()
#7 /var/www/html/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(388): Phinx\Migration\Manager\Environment->executeMigration()
#8 /var/www/html/movim/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration()
#9 /var/www/html/movim/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate()
#10 /var/www/html/movim/vendor/symfony/console/Command/Command.php(326): Phinx\Console\Command\Migrate->execute()
#11 /var/www/html/movim/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run()
#12 /var/www/html/movim/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand()
#13 /var/www/html/movim/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun()
#14 /var/www/html/movim/vendor/symfony/console/Application.php(175): Phinx\Console\PhinxApplication->doRun()
#15 /var/www/html/movim/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#16 /var/www/html/movim/vendor/bin/phinx(119): include('...')
#17 {main}
Script vendor/bin/phinx migrate --ansi handling the movim:migrate event returned with error code 1
```

**Comment by edhelas** [comment]
What is you MariaDB version. Also there is a lot of chances that your distro is enforcing some behavior, I cannot test them against the multiple MySQL/MariaDB flags that exists, do check your error on Stackoverflow and see if there's a specific config on your side to change in your database config.

**Comment by CarlSinclair** [comment]
Ver 15.1 Distrib 10.11.7-MariaDB, for Linux (x86_64) using  EditLine wrapper

Pretty weird that this happened on a fresh install though, following the instructions.

**Comment by edhelas** [comment]
Hello, got any news regarding that issue ?

**Comment by CarlSinclair** [comment]
What info do you need? I provided the MariaDB version.

**Comment by edhelas** [comment]
As I was saying above, I'm not planning to test Movim on the myriad of MySQL/MariaDB flavors, but I'm open to integrate fixes that you may find along the way.

**Comment by CarlSinclair** [comment]
I tried setting it up using Postgres but ran into other problems probably due to the fact that I'm on RHEL, so I'm just going to give up on it for now until I set up a Debian-based machine.

**Comment by pann** [comment]
I am seeing the same issue, on a fresh Debian 12 installation, MariaDB info:
Server version: 10.11.6-MariaDB-0+deb12u1 Debian 12
Movim is the only database that was created, and no modifications to any MariaDB configs.

**Comment by pann** [comment]
> I am seeing the same issue, on a fresh Debian 12 installation, MariaDB info: Server version: 10.11.6-MariaDB-0+deb12u1 Debian 12 Movim is the only database that was created, and no modifications to any MariaDB configs.

Perhaps this is related:
https://jira.mariadb.org/browse/MDEV-31987?jql=text%20~%20%22set_foreign_key_Check%22

**Comment by edhelas** [comment]
Did you find the cause of the issue ?

**Comment by pann** [comment]
There was an update to mariaDB regarding the handling of foreign keys. I managed to install MariaDB 10.3 using this:
https://olvy.net/blog/olvy-ported-mariadb103-to-debian12-and-ubuntu2204/

If I understood correctly, the update was first released as a patch, but I did not figure out when it was pulled into the normal releases.

**Comment by ghost** [comment]
OpenBSD 7.5 amd64
MariaDB version 10.9.8 is broken with Movim, but I have it working with MariaDB version 10.9.6

The problem is that disabling foreign key checks doesn't work with new versions of MariaDB.
This could be fixed by modifying the 'database/migrations/20180510141439_change_length_contacts_id.php' file to manually remove constraints, alter columns, and then re-add constraints unless there is some better way to do this with Phinx.

See: https://jira.mariadb.org/browse/MDEV-31987

I don't find this manual alterations to be the best solution so I have just opted to use an older version of MariaDB.
Not sure if MySQL is affected by this or not.

**Comment by CarlSinclair** [comment]
> I have it working with MariaDB version 10.9.6

Running 2 major versions behind doesn't sound very secure. Hopefully this gets addressed soon.

**Comment by edhelas** [comment]
> OpenBSD 7.5 amd64 MariaDB version 10.9.8 is broken with Movim, but I have it working with MariaDB version 10.9.6
> 
> The problem is that disabling foreign key checks doesn't work with new versions of MariaDB. This could be fixed by modifying the 'database/migrations/20180510141439_change_length_contacts_id.php' file to manually remove constraints, alter columns, and then re-add constraints unless there is some better way to do this with Phinx.
> 
> See: https://jira.mariadb.org/browse/MDEV-31987
> 
> I don't find this manual alterations to be the best solution so I have just opted to use an older version of MariaDB. Not sure if MySQL is affected by this or not.

The Movim/Migration object has `enableForeignKeyCheck()` and `disableForeignKeyCheck()` method, is this what you're looking for ? If yes can you please try them on the faulty migrations and propose a PR ?

**Comment by ghost** [comment]
> The Movim/Migration object has `enableForeignKeyCheck()` and `disableForeignKeyCheck()` method, is this what you're looking for ?

'database/migrations/20180510141439_change_length_contacts_id.php' is already utilizing those functions.
The problem is that MariaDB 10.9.8 will execute those functions as if it succeeded, but will still fail regardless.


In addition I ran into some problems when upgrading from 0.25.1 to 0.26 where some things would be broken; such as all banners becoming missing and registration page being broken. Dropped database and started from scratch and things were working fine again.

Except for stickers which throws this error:
```shell
$ php-8.2 daemon.php compileStickers
PHP Warning:  PHP Startup: Unable to load dynamic library 'mbstring' (tried: /usr/local/lib/php-8.2/modules/mbstring (File not found), /usr/local/lib/php-8.2/modules/mbstring.so (File not found)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'xml' (tried: /usr/local/lib/php-8.2/modules/xml (File not found), /usr/local/lib/php-8.2/modules/xml.so (File not found)) in Unknown on line 0


In Connection.php line 829:

  SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a t
  able referenced in a foreign key constraint (`movim`.`stickers`, CONSTRAINT
   `stickers_pack_foreign` FOREIGN KEY (`pack`) REFERENCES `movim`.`stickers_
  packs` (`name`)) (Connection: default, SQL: truncate table `stickers_packs`
  )


In Connection.php line 587:

  SQLSTATE[42000]: Syntax error or access violation: 1701 Cannot truncate a t
  able referenced in a foreign key constraint (`movim`.`stickers`, CONSTRAINT
   `stickers_pack_foreign` FOREIGN KEY (`pack`) REFERENCES `movim`.`stickers_
  packs` (`name`))


compileStickers

``` 


So it seems the foreign keys in MariaDB (even on 10.9.6) are causing a bit of trouble for Movim that go beyond the migration scripts as well.


> and propose a PR ?

I don't know PHP and decided to not continue with Movim to use something that is fully clientside.

**Comment by edhelas** [comment]
Closing the ticket as no clear solution of this problem was found.

**Comment by CarlSinclair** [comment]
> Closing the ticket as no clear solution of this problem was found.

... and that means the issue was completed? What? We can't fix it so let's just pretend it doesn't exist?

**Comment by edhelas** [comment]
Ugly fix, but at least it works ¯\_(ツ)_/¯

**Comment by CarlSinclair** [comment]
As @edshot99 explained, the problem goes beyond the migration scripts. The foreign key errors affect operation as well.

This issue should remain open because it still exists and has not been fixed. If closed, it will never be fixed.

**Comment by edhelas** [comment]
The initial issue was fixed as well as the other one (that should have been another ticket) mentioned by @edshot99 .
