### ISSUE TITLE
GUI of the option dialog of a chatroom is missleading

### ISSUE THREAD

**Issue by dtmf7133** [movim/movim#1316]
The scrollbars of the dialog are not immediately visible (Firefox) and the dialog seems to contain just the few options available on the top most part of the form.

Two possible solutions are.. a vintage overflow for the container div or an indication (like a button) fixed on the bottom on the dialog to push the scroll to the bottom.. both can give the necessary feedback to the user.

**Comment by edhelas** [comment]
Can I have a screenshot of the GUI issue ?
Some browsers such as Firefox are hidding automatically the scrollbar, it is not something that I can handle in CSS.

**Comment by dtmf7133** [comment]
Hello, I got the message now from the spam folder.
We are talking both about Firefox so I do not think the screenshot add more relevances, howevwer I can go to produce it for you.
The solutions could be variousas said, css: did you try using a container div with the overflow-y set to "yes" instead of the default ("auto") ?

**Comment by dtmf7133** [comment]
I'm not even sure what method you use to produce the dialog, maybe you get a simple way to act over the scrollbars display from there?

One more (dispandius) solution could be to architeft the form in tabs to simplify the interaction, the form in question is undubtly very rich of options.

Let me finish to trace my daugher sleeping and I could be in front of my station to help you further..

**Comment by dtmf7133** [comment]
Here: 
![administration](https://github.com/movim/movim/assets/22861380/1371668e-683c-4d67-9ebc-28924ecaf523)

given a resolution of 1920x1080px  only the topomost part of the form is visible as you can see.

**Comment by dtmf7133** [comment]
Tips:

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scrollbars_styling

for webkit browsers you should have this kind of stuff:

  .custom-scrolls::-webkit-scrollbar {
    width: 30px;
    background-color: lightgray;
  }
  .custom-scrolls::-webkit-scrollbar-thumb {
    background: #aaa;
  }

**Comment by edhelas** [comment]
![image](https://github.com/movim/movim/assets/3726886/03bd88a0-4e54-42ae-920b-0f8c2eb60110)

Already the case on Webkit based browsers.
This is a Firefox issue and I don't have a CSS to fix it.

**Comment by edhelas** [comment]
Movim is already customozing the scrollbar colors and shapes there https://github.com/movim/movim/blob/master/public/theme/css/scrollbar.css 

Your issue cannot be fixed with CSS as we discussed in the support chatroom. Sorry.
