### ISSUE TITLE
Private chats not showing any messages between @movim.eu contacts 

### ISSUE THREAD

**Issue by abergmot** [movim/movim#1317]
Private chats in https://mov.im is broken for @movim.eu users. We are a few people who used to communicate through https://mov.im website using private 1:1 chats, and all of our messages are never going through in both ways. We all have @movim.eu accounts. This has been happening for a few weeks. None of us use the same devices, we're mostly on Firefox (different versions which are up to date or not far from latest versions), and I tried to disable all extensions. Also, no OMEMO is enabled.

### Here's how you can replicate the problem :

- Go to mov.im subscription page and create two different @movim.eu accounts (one by one). 
- Then log in on the mov.im webpage with one account, and find your other contact with the search tool. Add them and send them a private message.
- log out, clear cache and cookies, close browser.
- Log into other accounts. You might get a notification, but no messages will show in chat in the window of your new account. If you didn't get a notification, add the other contact manually, and try to write a messag to them.
- Log out, close browser, and log in the first account again. nothing shows in private chat.

I tried this a lot of times between three new accounts, to be sure, in addition to testing with my friends. My Firefox extensions were all disabled the whole time, and I did close firefox between each login and clear cache + cookies.

**Comment by edhelas** [comment]
Note that by default the movim.eu server is only keeping history for messages coming from Contacts only. If you receive a message from a random stranger it will not be kept. This setting can be changed in the configuration page.

**Comment by abergmot** [comment]
> If you receive a message from a random stranger it will not be kept

The issue has been occurring all of a sudden with my previous contacts, not strangers. We used to communicate on https://mov.im for years, and now we can't see each others new messages in private 1:1 chats. I don't know why you closed this issue... Did you try to replicate this ?

**Comment by edhelas** [comment]
I've replicated this and it was caused by a MAM issue, messages were not handled properly on reconnect.

**Comment by abergmot** [comment]
> messages were not handled properly on reconnect

Yes, it seems to work, I'll confirm with all my contacts later. Thanks for solving this.  
I must say the process for giving feedback has not been ideal. How are non tech savvy users supposed to give you feedback on such a critical issue, if the only thing that's attracting attention from the devs is Github ? The official movim public chatroom should already have triggered an action to solve the problem, as I posted multiple times there about it, including a way to replicate the problem. Seeing that you have responded to other comments in the chat-room but not to this critical issue is really confusing, to say the least. A few weeks without service is a good way to lose users. If it wasn't for me, my friends would have ditch Movim already.

**Comment by edhelas** [comment]
I think you did what need to be done. I was in holidays and was not able to answer all the requests accordingly.

Creating an issue with a way to replace it on Github is indeed the best way to have the issue taken care of. However there's no guarantee that it will be solved in a specific time delay as I'm working on Movim on my free time and based on my current motivation.

In any ways, thanks for your support, hoping that this fix fixes your issue !
