### ISSUE TITLE
Emoji reactions are send unencrypted in 1:1 chats that have OMEMO enabled 

### ISSUE THREAD

**Issue by poVoq** [movim/movim#1332]
When sending an emoji reaction in an OMEMO encrypted 1:1 chat, the reaction itself is not encrypted.

This is invisible in Movim itself, but on clients like Cheogram that show a fallback for these reactions it shows them very clearly as unencrypted.

The same is actually happening with such reactions send from Gajim.

Edit: looks like an issue with OLDMEMO. Probably best to prohibit sending emoji reactions when OMEMO is enabled then.

**Comment by edhelas** [comment]
TODO: disable reactions when OMEMO is enabled

**Comment by edhelas** [comment]
Should be fixed in https://github.com/movim/movim/commit/6b18e3bb069a387ebb1844045c43eb7e2cbad494
