### ISSUE TITLE
`exec php` fails when multiple php versions are installed

### ISSUE THREAD

**Issue by Salamandar** [movim/movim#1334]
tl;dr : https://github.com/movim/movim/blob/47d12543228533dfd7f8d685dd4eed7bc4b71d36/src/Movim/Daemon/Session.php#L148

You shouldn't just call `php` as it might not be the right version.

**Comment by edhelas** [comment]
You should configure your OS to have a default php version.

 ```
$ update-alternatives --config php
$ php -v
PHP 8.2.21 (cli) (built: Jul  4 2024 15:15:46) (NTS)
```

**Comment by Salamandar** [comment]
That works when Movim is the only php software on the server. That's rarely the case. We have multiple services with different php version requirements...
You might want to use PHP_BINARY : https://www.php.net/manual/en/reserved.constants.php#constant.php-binary
