### ISSUE TITLE
composer install warns about abandoned packages

### ISSUE THREAD

**Issue by wiligl** [movim/movim#1336]
Hi, when installing movim on Debian 12 executing "composer install" gave warning:

Package web-token/jwt-key-mgmt is abandoned, you should avoid using it. Use web-token/jwt-library instead.
Package web-token/jwt-signature is abandoned, you should avoid using it. Use web-token/jwt-library instead.
Package web-token/jwt-signature-algorithm-ecdsa is abandoned, you should avoid using it. Use web-token/jwt-library instead.
Package web-token/jwt-util-ecc is abandoned, you should avoid using it. Use web-token/jwt-library instead.

Otherwise install was successful. Please update.

Kr, W

**Comment by edhelas** [comment]
I'm aware of that one but for now can't do much, we have to wait for one of my dependency to bump their own dependency.
