### ISSUE TITLE
Atom "rel" link indicates text/html instead of image/png

### ISSUE THREAD

**Issue by sjehuda** [movim/movim#1337]
An Atom "rel" link indicates that a PNG image is an HTML.

Subject file: [HowToExtract7zipMultipleFiles.png](https://upload.movim.eu/files/72545d95562ce01c8d7e25cb0e413a679c22c9f2/atqyWAdEChOEnAB0hHqrFFg6StSNwsXm0gc9dgRE/HowToExtract7zipMultipleFiles.png)

| *      | *                                    |
|---     |---                                   |
| pubsub | news.movim.eu                        |
|   node | fake-news                            |
|   item | fdef84f5-e3e1-41ea-9b68-af4bb9130f77 |
|  title | #14October2023EpochEclipse           |
|   date | Fri, 15 Jan 2021 20:24:46            |

These are the links that I have retrieved from Movim:
```
<link href="xmpp:news.movim.eu?;node=fake-news;item=fdef84f5-e3e1-41ea-9b68-af4bb9130f77" rel="alternate" type="" /
<link href="xmpp:comments.movim.eu?;node=urn:xmpp:microblog:0:comments/fdef84f5-e3e1-41ea-9b68-af4bb9130f77" rel="replies" type="" />
<link href="https://nl.movim.eu/?node/news.movim.eu/fake-news/fdef84f5-e3e1-41ea-9b68-af4bb9130f77" rel="alternate" type="text/html" />
<link href="https://upload.movim.eu/files/72545d95562ce01c8d7e25cb0e413a679c22c9f2/atqyWAdEChOEnAB0hHqrFFg6StSNwsXm0gc9dgRE/HowToExtract7zipMultipleFiles.png" rel="related" type="text/html" />
<link href="https://upload.movim.eu/files/72545d95562ce01c8d7e25cb0e413a679c22c9f2/atqyWAdEChOEnAB0hHqrFFg6StSNwsXm0gc9dgRE/HowToExtract7zipMultipleFiles.png" rel="enclosure" type="image/png" />
```

**Comment by sjehuda** [comment]
There is an issue which makes my post empty upon attempt to edit, so I post a new comment.

Here are other instances which a PNG image is determined only as an HTML document.:
```
pubsub: news.movim.eu
node: deltachat
items:
a3c8e447-8901-40fe-84ba-8da424c9cd53
6d822a77-c66f-4b5d-b57a-f9c089b5f0ed
4b5e0a74-b4bd-405c-961c-b23d185e78cb
```

**Comment by edhelas** [comment]
I just tested, Movim is properly setting the mimetype of the picture in the type.

This Atom doesn't seems to be generated by Movim. Movim handle it as it is received from the server.

**Comment by sjehuda** [comment]
> This Atom doesn't seems to be generated by Movim. Movim handle it as
> it is received from the server.
> 

This Atom is generated by Rivista.

Rivista retrieves all information from Movim.

I have a reason to assume that it correctly retrieves information as
delivered by Movim Atom, yet I could be wrong.

Please, try it for yourself.

Instance:
https://xpta.woodpeckersnest.space/

Code:
https://git.xmpp-it.net/sch/Rivista
