### ISSUE TITLE
[Suggestion] `x-scheme-handler/xmpp` as type

### ISSUE THREAD

**Issue by sjehuda** [movim/movim#1338]
Good day!

Shall `x-scheme-handler/xmpp` be added as "`type"?

I have chose `x-scheme-handler/xmpp` because of [the XDG system](https://wiki.xmpp.org/web/XMPP_URIs#Linux).

```
<link href="xmpp:news.movim.eu?;node=fake-news;item=fdef84f5-e3e1-41ea-9b68-af4bb9130f77" rel="alternate" type="x-scheme-handler/xmpp" />
<link href="xmpp:comments.movim.eu?;node=urn:xmpp:microblog:0:comments/fdef84f5-e3e1-41ea-9b68-af4bb9130f77" rel="replies" type="x-scheme-handler/xmpp" />
```

**Comment by edhelas** [comment]
From what I discussed with my pairs, this is not useful for Movim nor really "the way to do it".

**Comment by sjehuda** [comment]
Thank you for the respond.

I am interested any other solution to classify XMPP URIs, instead of
using processing power to analyze a given XMPP URI.
