### ISSUE TITLE
php not found

### ISSUE THREAD

**Issue by ghost** [movim/movim#1342]
If /usr/bin/php does not exist, the daemon.php file will complain about this and fail with linker killed.
Although this can be easily fixed with a symbolic link it would be nice to not have to do this.

Someone did fix this for themselves in #568, but that was with Linux and systemd.

**Comment by edhelas** [comment]
Maybe related to #1334 . Did you tried with the latest master ?

**Comment by ghost** [comment]
Seems to be related and is fixed with version 0.26
Thanks.
