### ISSUE TITLE
Movim Docker container needs a status acknowledgement

### ISSUE THREAD

**Issue by Waethorn** [movim/movim#1348]
What is the status on the Docker container images for Movim?  Is kawaii still working for Movim?  There's an issue published on the movim/movim-docker Github repo where kawaii was not being able to update the repo since Sept. 2023.  The last update to the stable branch on Dockerhub is a year old, and only the master branch is getting updates, though it still only references Movim version 0.22 from approximately the same time (Aug-Sept last year).  What is going on?  Some clarity would be appreciated.

**Comment by edhelas** [comment]
movim_docker has been officially archived as unmaintained, if someone is looking to maintain it again ping me 

https://github.com/movim/movim_docker
