### ISSUE TITLE
Sign Up should accept username and JID (username@domain)

### ISSUE THREAD

**Issue by wiligl** [movim/movim#1349]
Error: I tried to signup "roomservice@dhub.im" at my instance dhub.im, pressed validate, but got error "Not acceptable". 

Reason: "Sign up" asks for username (without domain), but I entered JID, which PROSODY accepted, but MOVIM complained about.

Solution: Accept username or username@domain (JID) to signup. Give more informative error message.

**Comment by edhelas** [comment]
I don't get what you did, which form are you talking about ?

**Comment by edhelas** [comment]
Ping

**Comment by edhelas** [comment]
The main form supports login using any XMPP JID

![image](https://github.com/user-attachments/assets/98a7c6e0-a56a-41c8-a0d3-c58c9f661762)
