### ISSUE TITLE
Add a reshare action on all posts

### ISSUE THREAD

**Issue by marevalo** [movim/movim#135]
As a final user I would like to reshare quickly on my feed any post in Movim, ideally with one click. Implementation propositions include:
- One reshare button that will open the "new post" UI (ideally on a dialog to not break the reading process) preloaded with the oiriginal post info (same title, URL, picture or attachment and a summary of the original post on the content) and the option to top comment on it.
- Two buttons: one "direct reshare" button that will repost directly the original post on my feed with only a popover and changing the color of the reshare icon; and another "reshare with note" button that implements the complete "repost" UI from the first proposition.

I propose to use the same icon for sharing from the material set with another dot at the beginning (to imply sharing on the same medium) making a -<. For the second proposition that would be the "direct reshare" button and the "reshare with note" button based on it adding a text balloon. A good place for the buttons could be right of the tags zone.

**Comment by edhelas** [comment]
There is now a share button on all the Movim posts.
