### ISSUE TITLE
Missing send button

### ISSUE THREAD

**Issue by tyler-hh** [movim/movim#1350]
Over the last few versions, I've had issues being unable to send messages as the button to send the text is gone.  

Running the latest movim .26.1 with latest ejabberd on ubuntu.  I've had the issue previously on brave and now firefox on android mobile.  

![Screenshot_20240810-083855_Firefox](https://github.com/user-attachments/assets/bf987f03-43d4-4e18-abd1-76d0b99ba758)

Usually the issue correct ts itself, but it's annoying for the time.

**Comment by edhelas** [comment]
As I never encounter this issue for the moment I'd need a way to properly replicate it.

**Comment by edhelas** [comment]
Bumping on that one. Please provide me with a way to reproduce this issue: which browser, which flow ?
