### ISSUE TITLE
[Feature Request] Ignore Unknown Contacts

### ISSUE THREAD

**Issue by maskedwitch** [movim/movim#1351]
Gajim has a feature called "Ignore Unknown Contacts" which helps cut down a lot on unwanted attention, especially for those among marginalized demographics. Would we be able to get a similar feature in Movim?

**Comment by edhelas** [comment]
I don't get what the feature is about ?

**Comment by maskedwitch** [comment]
The option to ignore, drop, or block incoming messages from JIDs not in
your roster. Enabling that would be a lot easier than blocking every
single JID when getting harassed by multiple often

**Comment by edhelas** [comment]
This is not something planned and should be done on the XMPP side directly through a spam filtering system.
Also blocking such messages will not prevent the people to send you contact request as well.

**Comment by maskedwitch** [comment]
There could be a second option for ignoring subscription requests as
well. A server side solution like a spam filter is great if the person
is running their own server, but doesn't help other users all that much
unless they happen to join a server using a filter that fits their
needs, unless a new XEP can be created to allow users to set their own
personal filters.
