### ISSUE TITLE
Buttons (links) that should be present on almost every page

### ISSUE THREAD

**Issue by sjehuda** [movim/movim#1352]
### Request

Here are links that would be useful on almost every page.

- Main (a link to root page `/`)
- Connect
- Profile
- Register
- Settings

### Reason

Suppose I ask a friend to open an (XMPP) account on the Movim system which I have linked to https://mov.im/node/pubsub.movim.eu/jazz-music

If the above links be present on most of the pages, then the friend will seek the registration link and would proceed; otherwise, I would have to send a link to https://mov.im/account or https://join.movim.eu/register

### Of note

It is important to mention that maybe these links should be present when a visitor is not connected to Movim.

The interface of Movim is lean, smooth and clean, so it already goves naything that is needed for graceful browsing of the site,

**Comment by sjehuda** [comment]
Pardon.

It is important to mention that these links should be present when a visitor is not connected to Movim.

**Comment by sjehuda** [comment]
The interface of Movim is lean, smooth and clean, so it already goves naything that is needed for graceful browsing of the site,

**Comment by sjehuda** [comment]
Thank you.

This change, has added an additional row.

I think that the single row was better.

Perhaps it would be better to place all buttons at a single row
which would be extended above both elements aside and div:
body > main > aside
body > main > div

Before:

Node  Title                    Subscribe  Atom
Icon  Subscribers and Summary  Button     Button

After:

Movim  Node  Title                    Subscribe  Atom    Login   Register
Icon   Icon  Subscribers and Summary  Button     Button  Button  Button

Notice that I have omitted the new Movim text:

Movim
mov.im

I recommend to incorporate buttons Login and Register, albeit
I do not know how exactly.

Also, instead of the additional Movim Icon, it might be good
to add a hyperlink to pathname /main to the Node Icon, and
upon "hovering" on the Node Icon, it can be switched to
Movim icon.

I will write a Userscript which does some of the design
suggestions, so it would be easier to realize.

**Comment by sjehuda** [comment]
I am posting this again for the sake of formatting.

Before:
```
Node  Title                    Subscribe  Atom
Icon  Subscribers and Summary  Button     Button
```
After:
```
Movim  Node  Title                    Subscribe  Atom    Login   Register
Icon   Icon  Subscribers and Summary  Button     Button  Button  Button
```

**Comment by edhelas** [comment]
I'm not planning to do further changes on this topic.
