### ISSUE TITLE
minimize posts on public blog pages (show previews instead)

### ISSUE THREAD

**Issue by ghost** [movim/movim#1354]
currently when you visit a public blog page, all of the articles there are shown at their full length, instead of a preview.

this makes for a very long scrolling session on such page, possibly passing through entire full length posts you may not be interested in.

this is a problem for when you're viewing the public blog, but not when you're viewing the contact/post author profile.

i propose that articles are to be minimized and have a "read more" button, just like everywhere else. (public blogs are inconsistent with news page and contact page)

**Comment by edhelas** [comment]
This is not planned, the blog view is having a standard blog view, so full articles paginated bellow eachothers.
