### ISSUE TITLE
migrating docker config from `movim_docker` to this repository

### ISSUE THREAD

**Issue by kskarthik** [movim/movim#1358]
I just observed that the `movim_docker` repo was archived.

I propose that the code can be moved to this repository under a directory `docker/`

Assuming there is still interest in providing docker images.

I can help with the task

**Comment by edhelas** [comment]
I prefer to keep things separated, if you want to upgrade `movim_docker` please fork it and contact me (preferably through the XMPP support channel) if you want to propose a PR to the archived one :)

**Comment by kskarthik** [comment]
@edhelas why was it archived ?

**Comment by stingbyte** [comment]
Only wanted to note that I am using the docker image and it is up to date if you use movim/movim:master as it downloads and uses latest github release. Updates worked fine too (I move old mounted volume, before updating).

**Comment by edhelas** [comment]
> @edhelas why was it archived ?

Because the original maintainer stopped working on it, I had a few people that told me that they had issues with it and its out of my scope regarding the work I can do on the project. But if you're interested to handle that no problem to unarchive it :)

**Comment by edhelas** [comment]
> Only wanted to note that I am using the docker image and it is up to date if you use movim/movim:master as it downloads and uses latest github release. Updates worked fine too (I move old mounted volume, before updating).

Ah yes indeed Docker is used in the small pipeline to run a few tests indeed, but it's very basic.

**Comment by Eirikr70** [comment]
> Only wanted to note that I am using the docker image and it is up to date if you use movim/movim:master as it downloads and uses latest github release. Updates worked fine too (I move old mounted volume, before updating).

Hello, do you have a working `docker-compose.yml` file ? I have tried tinkering and when I get out of the 426 error, I get a 400 error :(
Thanks !

**Comment by edhelas** [comment]
@Eirikr70 https://github.com/movim/movim/blob/master/podman-compose.yml

But its only for local setup

**Comment by Eirikr70** [comment]
> [@Eirikr70](https://github.com/Eirikr70) https://github.com/movim/movim/blob/master/podman-compose.yml
> 
> But its only for local setup

Thanks a lot !
