### ISSUE TITLE
message_files db table can't hold URLs longer than 255 characters

### ISSUE THREAD

**Issue by dos1** [movim/movim#1361]
> movim.ERROR: Illuminate\Database\QueryException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'url' at row 1 (Connection: default, SQL: insert into `message_files` (`name`, `type`, `size`, `url`, `message_mid`, `updated_at`, `created_at`) values (458781286_536704835586539_2418807086019789081_n.jpg, image/jpeg, 59368, https://scontent-waw2-2.xx.fbcdn.net/v/t39.30808-6/458781286_536704835586539_2418807086019789081_n.jpg?_nc_cat=102&ccb=1-7&_nc_sid=127cfc&_nc_ohc=7Ut2GNOVixIQ7kNvgFn-834&_nc_ht=scontent-waw2-2.xx&oh=00_AYB2qfYSqDO96K0klgaT6eWGg0a7WxPxQiH4BnHnt8vtCQ&oe=66E4CD3D, 106257, 2024-09-09 18:56:23, 2024-09-09 18:56:23))

Looking at the migration defined in `database/migrations/20240605155217_create_message_files_table.php`, the `url` field has a wrong type - it's `string` rather than `text`:

```
$table->string('url');
```

**Comment by edhelas** [comment]
Should be good now :+1:
