### ISSUE TITLE
Unable to start daemon.php

### ISSUE THREAD

**Issue by memiks** [movim/movim#139]
Hello,

When I try to execute daemon.php I receive this issue:

> PHP Fatal error:  Call to a member function execute() on a non-object in /srv/movim/vendor/movim/modl/src/Modl/SQL.php on line 133

But I configure my config/db.inc.php correctly...

```
<?php
# This is the database configuration of Movim
# You need to copy an rename this file to 'db.inc.php' and complete the values
$conf = array(
    # The type can be 'pgsql' or 'mysql'
    'type'        => 'mysql',
    # The database username
    'username'    => 'YYYYYY',
    # The password
    'password'    => 'XXXXXXXX',
    # Where can we find the database ?
    'host'        => '127.0.0.1',
    # The port number, 3306 for MySQL and 5432 for PostGreSQL
    'port'        => 3306,
    # The database name
    'database'    => 'movim'
);
```

Could you please help me ?

**Comment by gcsecsey** [comment]
I'm having the exact same problem on Ubuntu 14.04.1

**Comment by edhelas** [comment]
I'm sorry but I don't have enough information to find the issue for now. Are you sure that your database is up to date. What SQL database are you using ? MySQL or PostGreSQL ?

**Comment by src386** [comment]
I am able to reproduce this with the movim_ynh package.
Seems to be related to php composer, mud.php is unable to work (NSA errors).
But sometimes it works, I dont understand how.

**Comment by ghost** [comment]
Same here:

```
10:22 > php daemon.php                                                                                                                                      

        <div style="font-family: Arial; text-align: center;">
            <h2>Oops... something went wrong.</h2>
            <p>But don't panic. The NSA is on the case.</p>
        </div>
```

Everything was fine on the installation process, and the logs tell me that:

```
[07-Mar-2016 10:15:16 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /srv/htdocs/movim.unixcorn.org/movim/vendor/movim/modl/src/Modl/Modl.php:127
Stack trace:
#0 /srv/htdocs/movim.unixcorn.org/movim/vendor/movim/modl/src/Modl/Modl.php(127): PDO->__construct('mysql:host=loca...', 'XXXXXXX', 'XXXXXXXX...', Array)
#1 /srv/htdocs/movim.unixcorn.org/movim/bootstrap.php(328): Modl\Modl->connect()
#2 /srv/htdocs/movim.unixcorn.org/movim/bootstrap.php(64): Bootstrap->loadModl()
#3 /srv/htdocs/movim.unixcorn.org/movim/daemon.php(17): Bootstrap->boot()
#4 {main}
thrown in /srv/htdocs/movim.unixcorn.org/movim/vendor/movim/modl/src/Modl/Modl.php on line 127
```

**Comment by memiks** [comment]
Hello, after update dependencies :

```
rm -rf vendor
rm composer.lock
php ../composer.phar install
```

I am able to start daemon.php

thanks :+1:

**Comment by ghost** [comment]
Hello,

How « update dependencies » ?
Thanks in advance.

**Comment by memiks** [comment]
Hello,

Just go to movim folder

and do this:

```
rm -rf vendor
rm composer.lock
php composer.phar install
```

Bye.

**Comment by ghost** [comment]
Hello,

Thanks for answering but doesn't change anything to me. :-1:

**Comment by edhelas** [comment]
@memiks you should not remove composer.lock, it's a file that is delivered with the Movim sourcecode and enforce the version of the tested dependencies ;)

**Comment by memiks** [comment]
@edhelas : Ok sorry for the mistake about composer.lock.

So the good way to update is :

```
git pull
rm -rf vendor
php composer.phar install
```

I forgot the git pull to update movim dependencies.

@matunixe could you please test this ?

Thanks.

**Comment by ghost** [comment]
It works great.
Many thanks sir.

**Comment by singh1114** [comment]
I am facing similar issues, When I want to run the command php daemon.php. It says:

Failed opening required '/var/www/html/movim/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/movim/daemon.php on line 4

**Comment by Semperverus** [comment]
Alright, re-installed movim from the ground up and everything works now. Thank you guys, the dependencies seemed to have been the issue.

I'm assuming that there was a dep that for some reason didn't handle multiplexing properly.

**Comment by p0liper** [comment]
> I am facing similar issues, When I want to run the command php daemon.php. It says:

> Failed opening required '/var/www/html/movim/vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/movim/daemon.php on line 4

Do you execute memik's commands?
Two ways:
1) You aren't successfully downloaded all movim sources from git (Re-install movim in web root folder)
2)  You aren't execute these commands:
```bash
git pull
rm -rf vendor
php composer.phar install
```
