### ISSUE TITLE
Strange sorting on Contact Explore

### ISSUE THREAD

**Issue by christine-ho-dev** [movim/movim#14]
Go to the contact tab 
Click on a profile on page 3 for instance
Now go back to the list of profiles
You're back on page 1 (1) and the profile you clicked is on page 1 (2)

Owait..(2) only happens sometimes. Viewing is not related to changing the sorting of these profiles but it changes by itself sometimes :/

**Comment by edhelas** [comment]
I've already fixed the sorting but still need to fix the paging thing… to go back to the correct page when you press "back"

**Comment by edhelas** [comment]
Ok I've kept the pagination during the navigation, it's only lost when the profile is updated.
I'm closing this bug for now.
