### ISSUE TITLE
No format enabled in post comments

### ISSUE THREAD

**Issue by eyome** [movim/movim#140]
We can't format comments in posts. 
It would be nice to have this feature like it is in posts themselves.

**Comment by edhelas** [comment]
I've just added the URL supports in the comment, is in enough ?

**Comment by eyome** [comment]
In fact, the ideal case would be to have the sames rules, the sames abilities between the posts editor than the comments editor... :p
It would give an homogeneous behaviour and it would be less disturbing for users.

**Comment by rasos** [comment]
I am not seeing any formatting option at all (on the demo server https://nl.movim.eu), how do I activate that?  I assume that when formatting is enabled, I can also upload and embed media (as described [here](https://nl.movim.eu/?node/pubsub.movim.eu/Movim)) according to  XEP-0363: HTTP File Upload.

**Comment by edhelas** [comment]
@eyome I'm not planning to add more than that, comments are not the place to do Markdown formating to me
@rasos There's only Markdown formating enabled for posts content, there's a help icon on the Publish panel
