### ISSUE TITLE
An easy way to see all of my actions (my posts and my comments)

### ISSUE THREAD

**Issue by eyome** [movim/movim#141]
Right now, I can only see easily my previous posts in "My publications".
It would be nice to see also my comments I made on others posts.

**Comment by edhelas** [comment]
This is actually not possible. The XMPP network is totally decentralized and keeping track of everything that your account made on it is impossible (it's like trying to list everything that you have published on the web from your browser). Also this means that this have to be synchronized between the different Movim instances which complicate even more the task.

**Comment by edhelas** [comment]
I'm closing this for now.
