### ISSUE TITLE
[Android] Messy GUI

### ISSUE THREAD

**Issue by MRZA-MRZA** [movim/movim#142]
Hello.
I installed Movim for Android and encountered strange behavior of the App.
In the main menu Configuration and Chats menu items are to close to each other and on the contacts page I see teared background.
Here is the screenshots: https://imgur.com/a/x1g27

**Comment by edhelas** [comment]
Hi, do you have the same issue if Movim is used vertically ?

**Comment by MRZA-MRZA** [comment]
In portrait mode it works much better. Menu displays correctly. But I do not use portrait mode. My smartphone is locked to landscape mode.
![2016-03-08 20 49 14](https://cloud.githubusercontent.com/assets/3092263/13616161/b2c021f6-e589-11e5-9601-a0e9b48757f8.png)

**Comment by edhelas** [comment]
Movim is designed to work on portrait mode. I'll try to enforce it on Android.
See https://github.com/edhelas/movim_android/issues/3.

**Comment by jkufner** [comment]
>  I'll try to enforce it on Android.

Please don't.

**Comment by edhelas** [comment]
Why it's buggy and unusable if I don't do it ?

**Comment by jkufner** [comment]
Landscape mode is important on tablets, TVs, and phones have small keyboards to write longer texts in portrait mode...

**Comment by MRZA-MRZA** [comment]
> Why it's buggy and unusable if I don't do it ?

Because it won't work for me. I use special app which locks _any_ application to work in landscape mode.
My device is phablet and I use it as an ordinary tablet in landscape mode. I turns into portrait mode only during calls.

**Comment by edhelas** [comment]
I'm closing this ticket because I'm not planning to do a landscape mode for Movim for now.
