### ISSUE TITLE
ejabberd groups "Configuration" issue - Does't affect Metronome

### ISSUE THREAD

**Issue by ghost** [movim/movim#145]
Since switching to ejabberd, I've come across a cosmetic issue, that stops you from editing the dropdown.

When you create a group, then try to configure it, the "Publisher Model" drop down is stuck as seen in the picture : http://i.imgur.com/GBjjMi0.png

This does not happen with a Metronome server, only ejabberd.  It may happen on other server types as well, I have not tested others.

In the image, the drop down is not clickable, and cannot be changed.

**Comment by edhelas** [comment]
For the moment I've disabled the buggy item. I'll work on it later.

**Comment by edhelas** [comment]
This has been fixed for the 0.12 release.
