### ISSUE TITLE
[bug] Logout when receiving a special link

### ISSUE THREAD

**Issue by zamentur** [movim/movim#147]
Hi,

My coworkers are disconnected when I sent them this link by chat:
https://www.youtube.com/watch?v=5toHdWU7EgU&feature=youtu.be

They use the official "pod.movim.eu" with their own XMPP account.

After several trials, it seems that each link with a "&" can disconnect the other account.

Thanks for all,
ljf

**Comment by edhelas** [comment]
![capture d ecran_2016-03-08_21-34-09](https://cloud.githubusercontent.com/assets/3726886/13615407/86f82974-e575-11e5-94bf-d35d7bbb5018.png)

Everything seems fine for me.

**Comment by zamentur** [comment]
May be it's a problem with metronome XMPP server and movim ?
I will try again tomorrow, this issue has been tried on 2 accounts ...

If needed, I could give you a temporary account if I don't find out the
reason.

**Comment by edhelas** [comment]
No it's not a Metronome issue, the message is just forwarded by the XMPP servers, if there is a crash it must be on Movim side. Tell me if you can reproduce it.

**Comment by edhelas** [comment]
Do you experienced the issue again ? If not I can close the ticket.

**Comment by zamentur** [comment]
Hi,
We tried again, and we can reproduce it every time.
The attacker send "http://&" via pidgin and the other person is disconnected from movim.
We tried with attacker on a jappix system and in this case the problem doesn't exist beacause jappix convert the & into & amp; .
Sorry for the delay but I am very busy.
Thanks,

**Comment by zamentur** [comment]
The movim ynh package is not impacted. It seems it is only movim.eu
