### ISSUE TITLE
configuration settings are not saved

### ISSUE THREAD

**Issue by michel-briand** [movim/movim#153]
When I make changes in the "Configuration" panel, and I hit the save button, it seems they are saved.
I change the interface language and it works.

But when I disconnect and connect again, those settings are lost.

Although previous configuration settings are ok.

**Comment by edhelas** [comment]
Hi, what XMPP server do you have ? What Movim version and pod do you use ?

**Comment by michel-briand** [comment]
ejabberd (debian stable 14.07-4+deb8u3), movim (git master)

**Comment by edhelas** [comment]
Is PEP configured correctly ? Movim saves the configuration on the XMPP server.

**Comment by michel-briand** [comment]
I've enabled PEP like this:

>   mod_pubsub: 
>     access_createnode: pubsub_createnode
>     ## reduces resource comsumption, but XEP incompliant
>     ignore_pep_from_offline: true
>     ## XEP compliant, but increases resource comsumption
>     ## ignore_pep_from_offline: false
>     last_item_cache: false
>     plugins: 
>       - "flat"
>       - "hometree"
>       - "pep" # pep requires mod_caps

**Comment by edhelas** [comment]
Hi, I've put a little documentation on our Wiki for ejabberd :) Please have a look https://github.com/movim/movim/wiki/Configure%20ejabberd.

**Comment by michel-briand** [comment]
ejabberd configuration updated.
I've tried to delete old entries in Movim db.
But /h (/home) group is still showing up in the list. No way to delete it via Movim interface. Widget hangs...
Configuration is still not saved.

**Comment by weiss** [comment]
The PEP support in ejabberd 14.07 was buggy.  I'd try the [backport](https://packages.debian.org/jessie-backports/ejabberd).

**Comment by michel-briand** [comment]
Ok, it works now.
