### ISSUE TITLE
Better support for Transparency in User Avatar 

### ISSUE THREAD

**Issue by inkhey** [movim/movim#154]
Using Avatar with transparency (.png for example) doesn't look very nice in movim :
![image](https://cloud.githubusercontent.com/assets/7851652/13728151/ee6e32b4-e90e-11e5-805f-848b5cd5d20c.jpg)

They is probably a way to automatically add a background during the conversion to jpeg  .

**Comment by edhelas** [comment]
Don't apply it when saving PNG files
