### ISSUE TITLE
Registration should default to local server

### ISSUE THREAD

**Issue by Dragnucs** [movim/movim#162]
Whenever I invite someone to join the XMPP network via Movim, the first question is "_I click on the register button, now what?_" and I must reply "just pick one. movim.eu is a good choice".

A good behavior is to default to registering new users on the local server and hint them that they still can register on distant ones.

A better approach is to allow the pod administrator choose how he wants his pod to behave:
1. Disallow remore registration
2. Allow remote registration and default to local
3. Allow remote registration and default to remote
4. Disallow local registration

**Comment by edhelas** [comment]
Merged with #116
