### ISSUE TITLE
No more connexion to Movim

### ISSUE THREAD

**Issue by galuel** [movim/movim#163]
When trying to connect to Movim thru https://pod.movim.eu/?login After clicking my name, enter password, then "Come in", it appears "Connecting" nothing happens... I click then on "Connecting" and it goes back to https://pod.movim.eu/?login

Ubuntu 14.04 Firefox 45, and same issue trying with Chromium 49.0.2623.108

So impossible to connect thru Movim... (was working weeks ago)...

**Comment by edhelas** [comment]
What XMPP server are you using ? Did you tried on another Movim pod like https://nl.movim.eu/ ?

**Comment by galuel** [comment]
It works at https://nl.movim.eu/

**Comment by edhelas** [comment]
Ok it seems that I can reproduce the bug

**Comment by galuel** [comment]
The user i am in contact finally chosen https://www.xabber.com/ to dialogue, then I will not be able to reproduce bugs... It seems that Xabber has all necessary features for him, including audio and visual alerts when receiving message. It can be used to study the needed features !?
