### ISSUE TITLE
Double entry in "what's new" right part

### ISSUE THREAD

**Issue by Cypouz** [movim/movim#164]
The two last entries in the "what's new" right part are the same ones; the first without picture, the second with. If I delete one of them, the other disappears too.

![capture d ecran de 2016-04-06 16 03 42](https://cloud.githubusercontent.com/assets/4980075/14319914/588501ca-fc13-11e5-9196-9a2337ecde3b.png)

**Comment by edhelas** [comment]
I'm trying to reproduce this…

**Comment by edhelas** [comment]
I was not able to reproduce since then.
