### ISSUE TITLE
Can't start server "Ooops ...something went wrong"

### ISSUE THREAD

**Issue by davodego** [movim/movim#165]
When I try to start the server with 
`php daemon.php https://sub.domain.tld/movim/ port`
I got this error message.
Log shows:

`PHP Fatal error:  Class 'React\Http\Server' not found in /var/www/movim/src/Movim/Daemon/Api.php on line 15`

**Comment by edhelas** [comment]
Did you ran composer like said in the Wiki ? https://github.com/movim/movim/wiki/Install-Movim#dependency-installation

**Comment by davodego** [comment]
I done a git pull. Must i run the composer after a git pull?

**Comment by edhelas** [comment]
Always, and a database update as well using `php mud.php db set` ;)

**Comment by davodego** [comment]
Ok, solved. But the DNS error is still there :(
