### ISSUE TITLE
Websocket issues and notifications on the Android App

### ISSUE THREAD

**Issue by galuel** [movim/movim#167]
Using movim with the smartphone App leads to using problems : 
- many "websocket" disconnections...
- no audio or visual alert, and the end user need those alerts he uses to have with other applications (skype, mail...). usefull to know if the correspondant answered him or not ! A cloud appear, but only if the user reconnect ! (see first point : many disconnections)

**Comment by edhelas** [comment]
I've updated the Android app to improve the Movim notifications.
There is no plans to try to keep the Movim app running in the background, it will be too battery consuming. The Android app is just a "port" of  the webapp inside an Android WebView and this doesn't fit well with "background" apps.

I recommend you to use Conversations for this type of usage and just launch Movim to consult your news or for some occasional exchanges.
