### ISSUE TITLE
Unable to init/update the database

### ISSUE THREAD

**Issue by alexAubin** [movim/movim#175]
After attempting to update/reinstall movim, I encountered the message : 

```
Apr 24 04:43:16 serverHostname movim[8830]: To update the database run
Apr 24 04:43:16 serverHostname movim[8830]: php mud.php db --set
```

Running the command gave me 

```
 > php mud.php db --set
Oops... something went wrong.
But don't panic. The NSA is on the case.
```

After tweaking around, I got something more helpful :) : 

```
Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2002] No such file or directory' in /var/www/movim/vendor/movim/modl/src/Modl/Modl.php:127
Stack trace:
#0 /var/www/movim/vendor/movim/modl/src/Modl/Modl.php(127): PDO->__construct('mysql:host=loca...', 'movim', 'superSecurePassword', Array)
#1 /var/www/movim/src/Movim/Bootstrap.php(294): Modl\Modl->connect()
#2 /var/www/movim/src/Movim/Bootstrap.php(27): Movim\Bootstrap->loadModl()
#3 /var/www/movim/mud.php(13): Movim\Bootstrap->boot()
#4 {main}
```

Following [this thread](http://stackoverflow.com/questions/1435445/error-on-creating-connection-to-pdo-in-php), replacing localhost by 127.0.0.1 seems to have fixed the issue, though I have no idea what I am doing exactly...

Some more info : 

```
 > lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 8.0 (jessie)
Release:    8.0
Codename:   jessie

 > php --version
PHP 5.6.13 (cli) (built: Mar 22 2016 20:56:37) 
```

**Comment by edhelas** [comment]
Well looks like you DB is not reachable. Did you installed properly the MySQL module of PHP ?

**Comment by alexAubin** [comment]
Turns out this was probably related to the fact that I had a custom / manual install of PHP, which I thought I overwrote by reinstalling the debian package but it didn't.

So I'm closing the issue ;)
