### ISSUE TITLE
Pressing enter in the searchbox redirects to 404

### ISSUE THREAD

**Issue by olivierlemoal** [movim/movim#176]
In the searchbox (^M), pressing [enter] redirects to 
https://nl.movim.eu/?keyword=mysearch

**Comment by alexandrelb** [comment]
in the create pubsub node form too :
https://nl.movim.eu/?name=mynode
I take this opportunity to warn you about the form to join a gateway displays clear passwords

**Comment by alexandrelb** [comment]
another fields: 
When subscribe to a group, in the form for the name give to the subscription, and in the form send by prosody (ad-hoc command & sing up)
