### ISSUE TITLE
Rigth Issue on Ubuntu

### ISSUE THREAD

**Issue by Bluebeeep** [movim/movim#177]
Stopped at installation when using the install guide:

root@linux:/var/www# sudo -s -u www-data
bash: /root/.bashrc: Permission denied

Documentation needs an update? How do we get past this? Google takes you to all kinds of sticky bits and other topics. Would be great to have documentation that outlines what to do for this. 

Probably useful :)

Server: Ubuntu 14.0.4

**Comment by edhelas** [comment]
Well this is a standard Ubuntu permission error. Doesn't seems related to Movim ?
