### ISSUE TITLE
Communicaton

### ISSUE THREAD

**Issue by Bluebeeep** [movim/movim#178]
Where does a user go if they are having trouble installing? This doesn't seem like the place for these conversations. Is there a mailing list? Is there a forum? IRC? XMPP room thing?

**Comment by edhelas** [comment]
I've added a link to the XMPP chatroom on the homepage

**Comment by dkebler** [comment]
where on the homepage would that be? No place obvious.

Better yet how about a gitter room and/or a real forum app like discourse.  

More specifically does movim have an office docker file/repo?  

Lack of good places for community and/or developer support specifically for install and maintenance is a non starter for me.  The fact I have to use a github issue for this communication demonstrates my point.
