### ISSUE TITLE
Avatar doesn't change if changed in another xmpp client

### ISSUE THREAD

**Issue by MRZA-MRZA** [movim/movim#182]
Steps to reproduce:
Launch any xmpp client
Edit your vcard and change avatar
Login to your account with Movim client
You'll see your old avatar.

**Comment by edhelas** [comment]
"Any XMPP client" doesn't help me because there is several implementation in each of them.
To help please tell me with which client you have this issue.
Also there is some cache in the browser, so try to clear your cache to refresh the pictures of Movim.

**Comment by MRZA-MRZA** [comment]
I don't know why, but now it works. Previously it never worked.
