### ISSUE TITLE
DNS connection issue on xmpp.erlang-solutions.com

### ISSUE THREAD

**Issue by ludwikbukowski** [movim/movim#184]
Movim can't connect to our public xmpp server `erlang-solutions.com` and there is no logs in _log_ directory and either on the server side. I guess it might be related to wrong _DNS_ lookup. How can I get more information what's the problem? 
`dig` outputs:

```
root@db3b89e1e3c4:/var/www/movim# dig +short -t SRV _xmpp-server._tcp.erlang-solutions.com.
10 0 5269 xmpp.erlang-solutions.com.
```

**[EDIT]**
I figured out what was the reason. The host where the movim was running couldn't connect with XMPP server resolved by _DNS_ lookup.
How can configure movim and specify the xmpp host manually without _DNS_ lookup?

**[EDIT 2]**
Looks like _DNS_ lookup isn't configurable and it's hardcoded here:
https://github.com/movim/movim/blob/9a5175b263762bcf99209597a4985c84f42b0eb0/linker.php#L90
correct me if I'm wrong

**Comment by edhelas** [comment]
Can you please provide me a test account than I can verify on my side ?

**Comment by ludwikbukowski** [comment]
Sure
Username: `test.esl.user@erlang-solutions.com`
Password: `test.esl.user`

However, as I wrote before, I think I figured out what was the problem.
_DNS lookup_ returns domain where not xmpp server is hosted but the load balancer address. This host isn't reachable by the movim directly (because of the firewall or smth similar). I solved the issue by specyfing manually destination host, where the xmpp server is so it omits the load balancer (and it's reachable by movim host). In case to make the trick, I had to edit `linker.php` file

It would be great if it could be possible to disable _DNS lookup_ and specify the host manually in some config file :)

**Comment by edhelas** [comment]
With the current trunk, and no hack at all I was able to login on your test account.
Does the XMPP server and the Movim server are hosted on the same machine ?

**Comment by ludwikbukowski** [comment]
XMPP server and Movim are hosted on the same machine (in docker containers)
I'm able to connect Movim to our public server from other machines but not when Movim is running on that particular host. 
**[EDIT]**
I'm not sure I was clear enough. The problem was in our internal network configuration, not on the movim side

**Comment by edhelas** [comment]
So is it fine now ?

**Comment by ludwikbukowski** [comment]
Yes, its fine. However, this issue was intended to be a polite request for _XMPP_ destination host configuration. For now, movim connects to _jabber_ servers which are reachable by DNS lookup only. What if I'd like to have my server deployed locally with no _SRV_ records? 
I mean I could just type in a config file the destination IP address of my own server. 
 Almost every xmpp client provides such a functionality, so why not movim? :)

**Comment by edhelas** [comment]
Well if I remember correctly my own configuration. The config file that you're talking about can be `/etc/hosts`?

**Comment by edhelas** [comment]
Hi, I've checked the sourcecode. Movim do fallback to the default host if there's no SRV records so the issue seems to be elsewhere https://github.com/movim/moxl/blob/master/src/Moxl/Utils.php#L86 .
If you still experience this issue, do not hesitate to tell me here. If not, I'll close the ticket in a couple of days ;)

**Comment by smoebody** [comment]
i experienced this issue as well and i could boil it down to https://github.com/movim/movim/blob/master/linker.php#L98
`\Moxl\Utils::resolveIp($msg->host);` returns an object, so `gethostbyname()` in Line 99 is not called. But there is no `address`-property in the object (which is of type `Net_DNS2_RR_CNAME` in my case) and therefore the '$ip' variable becomes empty. also i receive a PHP_NOTICE

```
PHP Notice:  Undefined property: Net_DNS2_RR_CNAME::$address in /var/www/html/linker.php on line 99
```

i think line 99 would look better like this:

```
$ip = (!$ip->address) ? gethostbyname($msg->host) : $ip->address;
```

**Comment by edhelas** [comment]
Is this issue fixed ?

**Comment by smoebody** [comment]
i haven't had a chance to test it. i will report back soon. sorry for the delay

**Comment by edhelas** [comment]
Ping

**Comment by smoebody** [comment]
the fix is working. issue can be closed

**Comment by edhelas** [comment]
Thanks ;)
