### ISSUE TITLE
External and anonymous authentication

### ISSUE THREAD

**Issue by ffPjrZUGXfcxuAj** [movim/movim#186]
Is it possible to add external and anonymous authentication to Movim ?

The anonymous URL works like this: http://{JAPPIX_URL}/?r={ROOM}&n={NICK}

**Comment by edhelas** [comment]
Movim is not planning to support anonymous authentication for now. The architecture doesn't support this kind of feature and it brings a lot of issues (spam, load…).

**Comment by Ppjet6** [comment]
I was asked by a user of my instance today if movim supported this.

It would be cool to revive it, as I understand it's still in the codebase not in the UI. It could be enabled via a flag in the admin part, so you can deactivate it on movim.eu if you want.
