### ISSUE TITLE
Enternal form login

### ISSUE THREAD

**Issue by ffPjrZUGXfcxuAj** [movim/movim#187]
it's possible to implement external login form in post like this https://github.com/jappix/jappix/wiki/ExternalLogin

**Comment by edhelas** [comment]
Movim already support this external method to authenticate http://php.net/manual/en/features.http-auth.php . There is several examples on the page to create a form that will work with this system.

The implementation is done here https://github.com/movim/movim/blob/master/app/widgets/Login/Login.php#L96 .
