### ISSUE TITLE
Allow to invite users to a MUC [$100]

### ISSUE THREAD

**Issue by rasos** [movim/movim#188]
Adding a chatroom needs to follow two steps:
1. Add new chat room (available in movim). The "Chat Room ID" field should offer a drop-down list of servers (or at least suggest roomname@conference.myserver.tld , whereas myserver.tld is derived from my JID or the hostname).
2. We need to be able to add users (not yet available in movim) 
   Here we should get http://xmpp.org/extensions/xep-0045.html and http://xmpp.org/extensions/xep-0249.html implemented (the latter seems not yet available for ejabberd).

Finally, a room administrator also needs to be able to ban or remove users, which is described in XEP-0045.

**Comment by singpolyma** [comment]
XEP-0249 will never "be available for ejabberd" because it is a client-side feature that works on any server :)

**Comment by edhelas** [comment]
@rasos I've implemented 2 ways of inviting a user in a chatroom
* Using direct invitation https://xmpp.org/extensions/xep-0045.html#invite
* By a unique generated URL
What do you think?

**Comment by rasos** [comment]
Great that inviting users to rooms is now available with movim.
I tested it on https://nl.movim.eu/ and I would like to suggest, that you add an icon to add a user in the list of users of a chat room. I think this is the place users will search for it, rather than in the menu.

**Comment by edhelas** [comment]
3 different methods have been implemented in Movim to allow sending and receiving invitations in MUC. I now consider this feature request completed.
