### ISSUE TITLE
Support XEP-0084: User Avatar

### ISSUE THREAD

**Issue by ghost** [movim/movim#190]
Conversations uses XEP-0084 avatars, which are based on PEP (XEP-0163) instead the older vcard (XEP-0153) or IQ based versions (XEP-0060). When adding a contact with such a profile picture set, this should be used instead of the colored circle/letter.

Edit: Seems like this is actually supported, however it doesnt work -- neither does my movim avatar gets shown on the contacts xmpp client (conversations), nor does my contacts profile picture show up in movim.

**Comment by edhelas** [comment]
Please check if your Avatar is in WebP format, Movim doesn't support this picture format (yet). I'll try to reproduce the issue on my side.

**Comment by ghost** [comment]
No, it's not. It was magically "fixed" by logging in to nl.movim.eu instead of it.movim.eu... or by waiting some time (as in hours). Sorry for the noise.
