### ISSUE TITLE
Desktop application

### ISSUE THREAD

**Issue by Nyco** [movim/movim#194]
A web app is cool(tm), but a desktop app is a better solution for a large crowd we should not underestimate.

It would be nice to deliver Movim as a desktop app for Linux, Mac and Windows, as it is delivered on Android ([Play Store](https://play.google.com/store/apps/details?id=com.movim.movim), [F-Droid](https://f-droid.org/repository/browse/?fdfilter=movim&fdid=com.movim.movim)) and [Firefox OS](https://marketplace.firefox.com/app/movim-1/) (even on Ubuntu).

It could be done with [Electron](http://electron.atom.io/), or [NW.js](http://nwjs.io/) (formerly known as node-webkit) I guess.

**Comment by edhelas** [comment]
There is already an Electron package here https://github.com/movim/movim_electron. Contributions are welcome to package it for the other platforms.
