### ISSUE TITLE
Change time zone to get correct time in Chat

### ISSUE THREAD

**Issue by LudovicRousseau** [movim/movim#195]
I am in France with CEST – Central European Summer Time (Daylight Saving Time) time zone.
But the time displayed in the Chat section is using UTC and not UTC+2h as I would like.

Could it be possible to change the time zone in the preferences?
Or use the local setting of the browser if possible?

**Comment by linkmauve** [comment]
The timezone used should indeed always be the client time, and not the server time.

**Comment by edhelas** [comment]
That has been implemented recently. I'm closing the ticket, please tell me if you encounter issues.
