### ISSUE TITLE
Clear personal data when account is deleted

### ISSUE THREAD

**Issue by ghost** [movim/movim#196]
If you sign up for an account (on movim.eu), log in, do stuff (change profile, add contacts, chat, ...) and then delete the account from the settings, you are  able to sign up for this account again. However (even when used a completely new password), chats and contacts etc. are available to the re-created account as well. That should not happen. Either make sure all associated data are really gone (I don't know if this is possible for the client) or disable re-registration for some time (making this an issue with the used xmpp server).

**Comment by edhelas** [comment]
That's a tricky issue.

First, Movim is actually clearing some data when you quit the session (presences, roster and some minor info). When you delete an account, Movim is clearing data of the pod where the deletion is happening (but not the other ones !) : messages and personal posts (https://github.com/movim/movim/blob/master/app/widgets/Account/Account.php#L27).

So here there is two issues. 
First how can we clear the cache on all the Movim instances ? (that are servers that I don't control, and that's a good thing).
Secondly is there still some data that I can clear ?

**Comment by ghost** [comment]
Well, the issue is indeed far more complex than I thought. I dont know much about movim, but why does a pod cache things at all? Performance? Imho information should either be stored on the actual jabber server or on the users device (html5 local storage?). And whatever is cached in a session should be nullified when logged out or the account is deleted.

**Comment by edhelas** [comment]
Like a webmail, Movim is indeed doing caching for performance issues (the webmail is not re-downloading stuff from the IMAP servers each time). Also theses data are processed on the server to deliver a light experience client-side.

As I said, some of theses informations are destroyed when the user logout.

**Comment by edhelas** [comment]
I'm closing this ticket, as a wontfix.
