### ISSUE TITLE
Sync translation strings, please!

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#2]
The translations need to be re-uploaded in Transiflex

**Comment by edhelas** [comment]
Similar with this issue https://github.com/edhelas/movim/issues/3 so I close this one.
Please put a content in your issue next time.

**Comment by edhelas** [comment]
Reopening the issue

**Comment by edhelas** [comment]
I've updated the translations on Transiflex, closing the issue

**Comment by RobWJ** [comment]
please update the transiflex translations. looks like there are some changes since last update. or do you update it on a regular basis?
i see some few changes in the german translation
thx
