### ISSUE TITLE
Notifications needed for friends invitation proposals

### ISSUE THREAD

**Issue by ghost** [movim/movim#20]
I've received friend requests since I'm on Movim and I didn't notced because there were no warning displayed on the interface. I think there should be a red badge indicationg the number of friend requests over the _Contacts_ button on the right interface.

**Comment by Dragnucs** [comment]
Add to that notifications for comments.

**Comment by edhelas** [comment]
I've made some preliminar changes to handle more properly the invitations in the backend. I'll try to do a nice notification from this base.

Regarding the comments, there's no clear way today to get theses notifications from XMPP so I can't implement them in the current state.

**Comment by Dragnucs** [comment]
@edhelas You can use cookies and/or the database to store them.
