### ISSUE TITLE
relogin error

### ISSUE THREAD

**Issue by ludwikbukowski** [movim/movim#202]
When I log in in movim and then log out:

![movim logout](https://cloud.githubusercontent.com/assets/6969609/16046374/8a44dd06-324c-11e6-8537-6f3b24d95d65.png)

Then I can't log in again with an error  saying that the session is already established. Besides, the communicate is shown for a short amount of time, what seems to be strange behaviour....

_server: mongooseim
login: test.esl.user@erlang-solutions.com
password: test.esl.user
movim instance: http://31.172.186.62_

**Comment by edhelas** [comment]
That is actually a weird error. Did you actually use `http://31.172.186.62` as the URL parameter to launch the daemon ?

**Comment by ludwikbukowski** [comment]
Nope, I did use another IP since movim is run in our internal network and addresss http://31.172.186.62 is an external one. By our datacenter it's mapped to other internal IP which I use when launching the daemon. Using http://31.172.186.62 when launching the app should fix the issue?

**Comment by edhelas** [comment]
Yes you must as is it explained in the Installation Tutorial https://github.com/movim/movim/wiki/Install-Movim#3-start-the-daemon :)

**Comment by ludwikbukowski** [comment]
Thanks, it worked
