### ISSUE TITLE
No way to jump to right-sided pages from a sidebar in a mobile version of Movim

### ISSUE THREAD

**Issue by MMurzik** [movim/movim#205]
As in #204 there's no way to jump to public groups at Group page, and to jump to public contacts at Contacts page
![screenshot_20160620-003014](https://cloud.githubusercontent.com/assets/20031317/16180017/09343c4c-3680-11e6-9f1a-7553480045f1.png)
![screenshot_20160620-003005](https://cloud.githubusercontent.com/assets/20031317/16180018/09575f60-3680-11e6-9aa7-17811ddf3b8c.png)

**Comment by edhelas** [comment]
Similar as #204 
I can reopen the other ticket, no need to create a new one next time ;)
