### ISSUE TITLE
Unable to post images

### ISSUE THREAD

**Issue by pann** [movim/movim#206]
I am unable to add images to my posts, the option to add them is not visible, see screenshot.

The system is running with prosody 0.10. File upload path is served as:
https://proxy.example.com:5281/upload

Movim was cloned Jun 21st.

![selection_011](https://cloud.githubusercontent.com/assets/5699848/16262813/97e93e5e-3871-11e6-8b37-49a9e8ae4065.png)

The option shown in the blog post below is not available. Can this be due to me using Movim in english?
https://nl.movim.eu/?node/pubsub.movim.eu/Movim

**Comment by edhelas** [comment]
To enable the feature in Movim you need to declare the XMPP upload service in your discovery items. Here is an example for the `upload.movim.eu` service.

```
<iq id='step_01' to='movim.eu' type='get'>
    <query xmlns='http://jabber.org/protocol/disco#items'/>
</iq>
<iq id='step_01' type='result' to='test@movim.eu/1e360f00-a8bd-486b-ba34-c6453fd78ad5' from='movim.eu'>
    <query xmlns='http://jabber.org/protocol/disco#items'>
        <item jid='upload.movim.eu'/>
        <item jid='news.movim.eu' name='News feeds'/>
        <item jid='pubsub.movim.eu'/>
        <item jid='conference.movim.eu'/>
        <item jid='vjud.movim.eu'/>
        <item jid='sport.movim.eu' name='Sport feeds'/>
        <item jid='comics.movim.eu' name='Comics feeds'/>
        <item jid='blabla.movim.eu' name='Blabla'/>
        <item jid='jabber.movim.eu'/>
    </query>
</iq>
<iq id='step_01' to='upload.movim.eu' type='get'>
        <query xmlns='http://jabber.org/protocol/disco#info'/>
</iq>
<iq id='step_01' type='result' to='test@movim.eu/1e360f00-a8bd-486b-ba34-c6453fd78ad5' from='upload.movim.eu'>
        <query xmlns='http://jabber.org/protocol/disco#info'>
        <feature var='urn:xmpp:http:upload'/>
        <identity type='file' name='HTTP File Upload' category='store'/>
    </query>
</iq>
```

**Comment by pann** [comment]
This is the response I get from the server:

```
<iq id="purple535ece11" type="result" to="test@example.org/dator" from="upload.example.org">
   <query xmlns="http://jabber.org/protocol/disco#info">
      <feature var="urn:xmpp:http:upload" />
      <feature var="http://jabber.org/protocol/disco#info" />
      <feature var="http://jabber.org/protocol/disco#items" />
      <x xmlns="jabber:x:data" type="result">
         <field type="hidden" var="FORM_TYPE">
            <value>urn:xmpp:http:upload</value>
         </field>
         <field type="text-single" var="max-file-size">
            <value>1048576</value>
         </field>
      </x>
   </query>
</iq>
```

Compared to the response in edhelas post it is missing the "identity" field, which is also present in http://xmpp.org/extensions/xep-0363.html#disco

**Comment by pann** [comment]
With the following applied:
https://hg.prosody.im/prosody-modules/rev/131075a3bf0d

I get the possibility to upload files, but I get a 404 back from the server as below.
The URL seems correct, other clients can upload to the 'upload'-dir and folder can be created by other clients there:

```
Request URL:https://upload.example.org:5281/upload/6373ca7f-b37b-42cf-9a62-d9c8070b1c3e/Selection_001.png
Request Method:OPTIONS
Status Code:404 Not Found
Remote Address:10.0.0.1:5281
Response Headers
view source
Connection:Keep-Alive
Content-Length:366
Date:Mon, 04 Jul 2016 10:38:14 GMT
Request Headers
view source
Accept:*/*
Accept-Encoding:gzip, deflate, sdch, br
Accept-Language:en-US,en;q=0.8,sv;q=0.6
Access-Control-Request-Headers:content-type
Access-Control-Request-Method:PUT
Connection:keep-alive
Host:upload.example.org:5281
Origin:https://example.org
Referer:https://example.org/movim/?news/43323695-bd32-47a0-b380-7095b3d86861
User-Agent:Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
```

Response from server is now:

```
<iq id="purple9c36474f" type="result" to="test@example.org/hemma" from="upload.example.org">
   <query xmlns="http://jabber.org/protocol/disco#info">
      <identity type="file" name="HTTP File Upload" category="store" />
      <feature var="urn:xmpp:http:upload" />
      <feature var="http://jabber.org/protocol/disco#info" />
      <feature var="http://jabber.org/protocol/disco#items" />
      <x xmlns="jabber:x:data" type="result">
         <field type="hidden" var="FORM_TYPE">
            <value>urn:xmpp:http:upload</value>
         </field>
         <field type="text-single" var="max-file-size">
            <value>1048576</value>
         </field>
      </x>
   </query>
</iq>
```

**Comment by pann** [comment]
A bit of a hassle to get prosody and nginx to work with proxying upload requests but with the upload sections proxied over 443 and the fix to prosody mentioned above got things working.
Recomment to have prosody serve everything on the same domain with the http_upload explicity declared in the "disco_items" if it is not running as a seperate component.

**Comment by dnut** [comment]
I patched mod_http_upload.lua as described in your link. I added this to prosody.cfg.lua:

``` lua
disco_items = {
    { "upload.example.com", "HTTP File Upload" };
}
```

I'm getting the same server response as the last one you mentioned when you said "Response from server is now." The problem is when I attempt an upload in Movim I get NaN% and "Upload Failed." If the file is too large though, it doesn't do that, it just says "File too large," so some aspect of this is working. It's strange because http_upload has worked perfectly fine with other clients such as Gajim and Conversations without requiring any modification to the server.

I get nothing in prosody.log from upload attempts in Movim. xmpp.log looks like this when I attempt an upload:

```
[2016-11-13 21:34:08] moxl.DEBUG: Handler : Memory instance found for UP44Ye [] []
[2016-11-13 21:34:08] moxl.DEBUG: Package : Event "upload_request_handle [] []
```

@pann What exactly did you have to proxy?

**Comment by pann** [comment]
I do not know if it matters but I have another string in the disco items
This is what I have in my config file:

```
modules_enabled = {
        "http";  -- Needed for mod_http_upload
        "http_upload";
        "proxy65";
        }

http_upload_file_size_limit = 10485760

http_external_url = "https://example.org/"

plugin_paths = { "/usr/lib/prosody/plugins" }

disco_items = {
        { "example.org/upload//", "http_upload" };
    }
```

**Comment by dnut** [comment]
Thanks for the reply. I modified mine to be more like yours. Now instead of NaN% it climbs up to 100%, but unfortunately the end result is still "Upload failed."

**Comment by pann** [comment]
Can you post your prosody config and I will try to see what is different from mine?

**Comment by dnut** [comment]
https://gist.github.com/dnut/498f4ecc65a923b819b6e2298300fd55

I noticed that this line is the one that made the difference between going straight to NaN% versus climbing gradually to 100%:

``` lua
http_external_url = "https://example.com/"
```

It also prevents other clients from successfully using http_upload. As soon as I comment that out, it goes back to NaN% and other clients start uploading successfully again.

A few of the things on the bottom commented out are left over from me trying a bunch of different things to get this working.

**Comment by pann** [comment]
Not sure here, but one thing that differs is that I do not have the protocol in the disco_items i only have

```
disco_items = {
        { "example.org/upload//", "http_upload" };
    }

```

In the file you posted you have also the "https" part.
And I am using my config with other clients as well, such as conversations, so it should be possible to make it work.
