### ISSUE TITLE
Unable to launch daemon ('Movim\Exception' not found in Bootstrap.php)

### ISSUE THREAD

**Issue by Biniou180** [movim/movim#207]
Hello!

I need some help on this case: I'm not able to launch the daemon anymore (it worked before, but i suspect an update has broken the daemon).

When trying to do `php daemon.php https://chat.mydomain.tld 8080`, i got the warning :

```
`PHP Warning:  Version warning: Imagick was compiled against Image Magick version 1683 but version 1684 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0`
Oops... something went wrong.
But don't panic. The NSA is on the case.
```

...and the trace in the logs (`log/php.log`) are the following:

```
[27-Jun-2016 15:55:50 Europe/Paris] PHP Fatal error:  Uncaught Error: Class 'Movim\Exception' not found in /srv/http/movim/src/Movim/Bootstrap.php:290
Stack trace:
#0 /srv/http/movim/src/Movim/Bootstrap.php(27): Movim\Bootstrap->loadModl()
#1 /srv/http/movim/daemon.php(20): Movim\Bootstrap->boot()
#2 {main}
  thrown in /srv/http/movim/src/Movim/Bootstrap.php on line 290
```

To be sure, i restarted from a fresh github clone, and everything up-to date. My config:
Archlinux on a Rpi2, Php 7.0.8, Composer 1.1.2.

Could you maybe help me to solve this?
Thanks!

**Comment by edhelas** [comment]
Thanks, I've spotted a little mistake. The issue is now fixed in the trunk ;) Try again and you should have a proper Error.

**Comment by Biniou180** [comment]
Ok this time the error helps!
Thanks for the fix :-)

The correct error said that my socket for the database was inaccessible.
In fact my database seemed to be corrupted (I think it comes from an hard reboot I made several days ago because of other issues), it won't restart and i didn't see it. After wiping mysql and reconfiguring my database, it works well.

Thanks a lot!
