### ISSUE TITLE
Registration issue on ejabberd

### ISSUE THREAD

**Issue by p0liper** [movim/movim#209]
Hello, and excuse for troubling!
while create user on the Movim server, I get "Please, wait..." and... No actions. 
As a jabber server, I  select ejabberd. 
Config file contains here: https://ghostbin.com/paste/73o5n
Help me, plz :D
Thanks.

**Comment by ghost** [comment]
Try to flush config file of ejabberd and Movim, then restart server.
If issue still appears, you can re-open this issue.

Also, check is your server addr configured properly in config file.
Have fun!

**Comment by yanislavb** [comment]
mihip, Are you a Movim moderator?

**Comment by Mihip** [comment]
I'm afraid not. How can I be moderator of this project, judge for yourself?

**Comment by yanislavb** [comment]
This project is not adapted for Russian users. You can ask Ivan E.

Yan Media LLC
http://yanmedia.tk
+7 922 782 8725

**Comment by yanislavb** [comment]
comment has been changed because private data was shown.

**Comment by edhelas** [comment]
I made some cleanup in the comments of the ticket.
What is your exact issue ? I don't have enough information to understand it for now sorry.
