### ISSUE TITLE
Have clear "Accept"/"Refuse" buttons in invitations

### ISSUE THREAD

**Issue by Jehan** [movim/movim#210]
This remark will probably apply to a lot other parts of the UI but for now I had the experience in the invitation UI.
- Send an invitation from any software;
- You get a notification in contact list;
  And here problems start! I try to click the contact's name, and I get its infos.
  Then I tried to click the "+" icon below, but it proposes me to search for contacts. It took me several minutes to try and click the wheel button to get access/refuse buttons!

I propose:
- Drop menus! We should see the accept/refuse options directly under the invitation.
- Drop icons! Use text instead! It's just 2 words, it won't be very long, whatever the language, and it will be clear.
  Thanks! :-)

**Comment by edhelas** [comment]
![capture d ecran_2016-06-27_22-23-22](https://cloud.githubusercontent.com/assets/3726886/16394495/d4d2f678-3cb5-11e6-9565-2e9249503cca.png)

**Comment by Jehan** [comment]
Yes, maybe something like this. It looks better though I can't say for sure anymore since I've already experienced the problem and now know the solution. So now I am spoiled as a tester.

In any case, text is always the ultimate UI: you can't go wrong (well… nearly. Or let's say it's more difficult to go wrong), it is clearer and understandable. By the way, in your screenshot UI, the end of the sentence is replaced with ellipsis. This may be a problem as well, I'd say.

**Comment by edhelas** [comment]
The changes seems enough for now I think :)
