### ISSUE TITLE
Daemon reloading issue 

### ISSUE THREAD

**Issue by tuxh1** [movim/movim#211]
Hi
Movim is installed but there is a problem:

When run daemon : php daemon.php https://m.secaas.mx/movim/ 8080
I have this error on terminal : 

wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : 178 connected
wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : linker killed 
wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : 178 deconnected
wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : 225 connected
wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : linker killed 
wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : 225 deconnected
wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : 240 connected
wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : linker killed 
wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : 240 deconnected
wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : 249 connected
wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : linker killed 
wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : 249 deconnected
wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : 264 connected
wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : linker killed 
wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : 264 deconnected
wkVSjR5i7dCHBqMz1wPSLkmLnW7NLnWJ : 273 connected

And the page LOGIN reload and reload and reload.

Have you any idea why does this?

Thannks

**Comment by tuxh1** [comment]
And the log on Apache:

201.141.14.100 - - [28/Jun/2016:11:39:44 -0400] "GET /movim/?login HTTP/1.1" 200 10379
201.141.14.100 - - [28/Jun/2016:11:39:46 -0400] "GET /ws/ HTTP/1.1" 502 -
201.141.14.100 - - [28/Jun/2016:11:39:46 -0400] "GET /movim/?disconnect HTTP/1.1" 302 5636
201.141.128.100 - - [28/Jun/2016:11:39:46 -0400] "GET /movim/?login HTTP/1.1" 200 10379
201.141.128.100 - - [28/Jun/2016:11:39:48 -0400] "GET /ws/ HTTP/1.1" 502 -
201.141.128.100 - - [28/Jun/2016:11:39:48 -0400] "GET /movim/?disconnect HTTP/1.1" 302 5636
201.141.128.100 - - [28/Jun/2016:11:39:48 -0400] "GET /movim/?login HTTP/1.1" 200 10379
201.141.128.100 - - [28/Jun/2016:11:39:50 -0400] "GET /ws/ HTTP/1.1" 502 -
201.141.128.100 - - [28/Jun/2016:11:39:50 -0400] "GET /movim/?disconnect HTTP/1.1" 302 5636
201.141.14.100 - - [28/Jun/2016:11:39:50 -0400] "GET /movim/?login HTTP/1.1" 200 10379
201.141.14.100 - - [28/Jun/2016:11:39:51 -0400] "GET /ws/ HTTP/1.1" 502 -
201.141.14.100 - - [28/Jun/2016:11:39:52 -0400] "GET /movim/?disconnect HTTP/1.1" 302 5636
201.141.128.100 - - [28/Jun/2016:11:39:52 -0400] "GET /movim/?login HTTP/1.1" 200 10379
201.141.128.100 - - [28/Jun/2016:11:39:53 -0400] "GET /ws/ HTTP/1.1" 502 -
201.141.128.100 - - [28/Jun/2016:11:39:53 -0400] "GET /movim/?disconnect HTTP/1.1" 302 5636
201.141.14.100 - - [28/Jun/2016:11:39:54 -0400] "GET /movim/?login HTTP/1.1" 200 10379
201.141.14.100 - - [28/Jun/2016:11:39:55 -0400] "GET /ws/ HTTP/1.1" 502 -
201.141.14.100 - - [28/Jun/2016:11:39:56 -0400] "GET /ws/ HTTP/1.1" 502 -
201.141.14.100 - - [28/Jun/2016:11:39:57 -0400] "GET /movim/?disconnect HTTP/1.1" 302 5636
201.141.14.100 - - [28/Jun/2016:11:39:57 -0400] "GET /movim/?login HTTP/1.1" 200 10379
201.141.14.100 - - [28/Jun/2016:11:39:58 -0400] "GET /ws/ HTTP/1.1" 502

**Comment by edhelas** [comment]
Ok can you check if you have something interesting in `log/php.log` seems that you have a Fatal Error in the daemon

**Comment by tuxh1** [comment]
Hi @edhelas 

I in php.log not error but in error.log i have this

[Thu Jun 30 19:10:34.058270 2016] [proxy:error] [pid 20184](111)Conexión rehusada: AH00957: WS: attempt to connect to 127.0.0.1:8080 (localhost) failed
[Thu Jun 30 19:10:34.058352 2016] [proxy:error] [pid 20184] AH00959: ap_proxy_connect_backend disabling worker for (localhost) for 60s
[Thu Jun 30 19:10:34.058368 2016] [proxy_wstunnel:error] [pid 20184] [client 189.217.195.116:42159] AH02452: failed to make connection to backend: localhost
[Thu Jun 30 19:10:35.816847 2016] [proxy:error] [pid 19984](111)Conexión rehusada: AH00957: WS: attempt to connect to 127.0.0.1:8080 (localhost) failed
[Thu Jun 30 19:10:35.816966 2016] [proxy:error] [pid 19984] AH00959: ap_proxy_connect_backend disabling worker for (localhost) for 60s
[Thu Jun 30 19:10:35.816990 2016] [proxy_wstunnel:error] [pid 19984] [client 189.217.195.116:2533] AH02452: failed to make connection to backend: localhost
[Thu Jun 30 19:10:45.916803 2016] [proxy:error] [pid 19754] AH00940: WS: disabled connection for (localhost)
[Thu Jun 30 19:10:48.060574 2016] [proxy:error] [pid 19832] AH00940: WS: disabled connection for (localhost)
[Thu Jun 30 19:10:51.114993 2016] [proxy:error] [pid 20184] AH00940: WS: disabled connection for (localhost)
[Thu Jun 30 19:11:00.130239 2016] [proxy:error] [pid 19705](111)Conexión rehusada: AH00957: WS: attempt to connect to 127.0.0.1:8080 (localhost) failed
[Thu Jun 30 19:11:00.130316 2016] [proxy:error] [pid 19705] AH00959: ap_proxy_connect_backend disabling worker for (localhost) for 60s
[Thu Jun 30 19:11:00.130332 2016] [proxy_wstunnel:error] [pid 19705] [client 189.217.195.116:32038] AH02452: failed to make connection to backend: localhost
[Thu Jun 30 19:11:01.418754 2016] [proxy:error] [pid 20184] AH00940: WS: disabled connection for (localhost)

Thank for your help

**Comment by edhelas** [comment]
I'm sorry I don't have enough information to help you on this ticket. This can be caused by many different causes. I invite you to join our support XMPP channel on movim@conference.movim.eu.
