### ISSUE TITLE
Problem using Movim after installation

### ISSUE THREAD

**Issue by Catskan-zz** [movim/movim#212]
Hi,

I want using movim with my openfire server but I have a problem for access.

I followed the Wiki for my installation, and when I start " php daemon.php http://courstream.unice/ 8080", last line is "Unencrypted".
After, in firefox http://courstream.unice.fr:8080 
I have "Firefox can not establish a connection to http://courstream.unice.fr:8080

How can I solve this problem ? 

Thanks you in advance

**Comment by edhelas** [comment]
I think that you messed up when reading the documentation.

You should put **The public URL of Movim** which is, in your case `http://courstream.unice.fr/movim/`
After that you put in your webserver configuration the output generated by the daemon. And everything should be fine.

The port number is only used internally between the daemon and your webserver. Firefox will just load the default Movim pages.

**Comment by Catskan-zz** [comment]
yes, I have put 

> ProxyPass /ws/ ws://localhost:8080/' in /etc/apache2/sites-enabled/default-ssl.conf

 and reboot apache but when I try to connect on 'http://courstream.unice.fr/movim', botton of the index page have a message : 

> Movim can't communicate with the server. Try again

**Comment by edhelas** [comment]
The daemon is launched without any error ? And still running when you try to access the page ?

**Comment by Catskan-zz** [comment]
When I start the daemon I have : 

> Movim daemon launched
> Base URI : courstream.unice.fr/
> 
> --- Server Configuration - Apache ---
> Enable the Secure WebSocket to WebSocket tunneling
> '#' a2enmod proxy_wstunnel
> Add this in your configuration file (default-ssl.conf)
> ProxyPass /ws/ ws://localhost:8080/
> 
> --- Server Configuration - nginx ---
> Add this in your configuration file
> location /ws/ {
>     proxy_pass http://localhost:8080/;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection "Upgrade";
>     proxy_set_header Host $host;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header X-Forwarded-Proto https;
>     proxy_read_timeout 86400s;
>     proxy_send_timeout 86400s;
>     proxy_redirect off;
> }
> 
> Unencrypted

This is the daemon, right ? ( php daemon.php http://courstream.unice.fr 8080 )

**Comment by Ppjet6** [comment]
> This is the daemon, right ? ( php daemon.php http://courstream.unice.fr 8080 )

You forgot the `/movim/` part of the url.

**Comment by Catskan-zz** [comment]
Hi,

I restart the daemon with `php daemon.php http://courstream.unice.fr/movim/ 8080` and I always have the error `Movim can't communicate with the server. Try again`

**Comment by edhelas** [comment]
Hi, do you have some new information regarding this ticket ?

**Comment by edhelas** [comment]
Closing this ticket.

**Comment by heat** [comment]
I'm trying up the daemon and get same error.

**Comment by sigmap** [comment]
Running into a similar wall with xampp on windows.

**Comment by p0liper** [comment]
If there's actially,
```bash
ProxyPass /ws/ ws://localhost:8080/' in /etc/apache2/sites-enabled/default-ssl.conf
```
```bash
default-ssl.conf
```
You should specify ProxyPass inside **default-ssl.conf** and **000-default.conf**, not in a sngle file.
About xampp
```
Running into a similar wall with xampp on windows.
```
@sigmap, **WINDOWS IS NOT SUPPORTED ON A MOVIM!!**

**Comment by p0liper** [comment]
@edhelas Can you specify in a readme about windows? (for except offtop questions)?
