### ISSUE TITLE
'caps' table not correctly updated

### ISSUE THREAD

**Issue by pann** [movim/movim#213]
When changing the upload URL in of the http upload service from "upload.example.org" to "example.org/upload", the caps table in the sql database still kept the "upload.example.org".

This resulted in that movim tried to do uploads to "upload.example.org" instead of the new URL.

XMPP server used was prosody 0.10 and a movim git clone from July 5th.

**Comment by edhelas** [comment]
Closing this ticket as the Caps handling flow has been entirely rewritten since then.
