### ISSUE TITLE
Undefined constant breaks pages

### ISSUE THREAD

**Issue by bremensaki** [movim/movim#215]
My Group view was failing to render after an update, rendering as a blank white page. Logs contained:

`[11-Jul-2016 12:16:48 Australia/Melbourne] PHP Fatal error:  Undefined class constant 'ALPHACHANNEL_REMOVE' in /var/www/movim/system/Picture.php on line 184`

Commentary on the Imagick::flattenImage function page seems relevant: http://php.net/manual/en/imagick.flattenimages.php

The constant ALPHACHANNEL_REMOVE is only present in php-imagick > 3.2.0b2 and Ubuntu 14.04 ships with 3.1.2, Debian 7 has 3.1.0. 

I had some errors briefly after that, but I cannot recreate them now. Possibly depended on specific content being present on the Group page that's no longer in circulation. Will keep an eye on it.

The issue only seems to be that the constant isn't defined, not that the functionality isn't present.

**Comment by edhelas** [comment]
Do you still have the issue, on your side?

**Comment by bremensaki** [comment]
No, haven't seen it since.

There was another error that seemed related on mine after I implemented this same fix, but I can't reproduce it. I'm now back in sync with your builds and it's working fine.

**Comment by davodego** [comment]
I have also the `[18-Jul-2016 18:09:48 Europe/Berlin] PHP Fatal error:  Undefined class constant 'ALPHACHANNEL_REMOVE' in /var/www/movim/system/Picture.php on line 148` in my php.log

Movim is killed randomly. Sometimes when I want to login, sometimes when I work with movim.

**Comment by edhelas** [comment]
Oh sorry I forgot that part ! Thanks for pointing it out :)

**Comment by davodego** [comment]
Sorry it's not gone.
I con login but after few seconds movim kick me out and return to login page. Now it connects and disconnects on and on and the login page reloads every second.

php.log:

```
#1 /var/www/movim/src/Movim/Bootstrap.php(294): Modl\Modl->connect()
#2 /var/www/movim/src/Movim/Bootstrap.php(27): Movim\Bootstrap->loadModl()
#3 /var/www/movim/linker.php(12): Movim\Bootstrap->boot()
#4 {main}
  thrown in /var/www/movim/vendor/movim/modl/src/Modl/Modl.php on line 127
[23-Jul-2016 17:14:07 Europe/Berlin] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[08004] [1040] Too many connections' in /var/www/movim/vendor/movim/modl/src/Modl/Modl.php:127
Stack trace:
#0 /var/www/movim/vendor/movim/modl/src/Modl/Modl.php(127): PDO->__construct('mysql:host=loca...', 'NAME', 'PWD', Array)`
```

**Comment by edhelas** [comment]
Not related to this bug

> SQLSTATE[08004] [1040] Too many connections

Check your database configuration, it doesn't seems to be a Movim issue

**Comment by davodego** [comment]
Sorry, I have no luck. Everytime I start Movim I have the:  connects and disconnects on and on and the login page reloads every second. I made at git pull composer.phar install and update db. Start movim and no change.
I look to all the logs and till found something. Now its php.log:

```
[24-Jul-2016 11:45:46 Europe/Berlin] PHP Fatal error:  Uncaught exception 'ImagickException' with message 'Unable to set image alpha channel' in /var/www/movim/system/Picture.php:185
Stack trace:
#0 /var/www/movim/system/Picture.php(185): Imagick->setimagealphachannel(11)
#1 /var/www/movim/system/Picture.php(82): Picture->createThumbnail(50, false)
#2 /var/www/movim/app/models/contact/Contact.php(232): Picture->get('daniel@jabber.s...', 50, false)
#3 /var/www/movim/cache/_login_sessions.8eb3c4509677e4bd4b913d9eacaa89cb.rtpl.php(8): modl\Contact->getPhoto('s')
#4 /var/www/movim/vendor/rain/raintpl/library/Rain/Tpl.php(63): require('/var/www/movim/...')
#5 /var/www/movim/app/widgets/Login/Login.php(237): Rain\Tpl->draw('_login_sessions', true)
#6 [internal function]: Login->ajaxGetRememberedSession('["daniel@jabber...')
#7 /var/www/movim/src/Movim/Widget/Wrapper.php(138): call_user_func_array(Array, Array)
#8 /var/www/movim/system/RPC.php(86): Movim\Widget\Wrapper->runWidget('Login', 'ajaxGetRemember...', Array)
#9 /var/www/movim/linker.php(122): RPC->handle_json(O in /var/www/movim/system/Picture.php on line 185 
```

**Comment by edhelas** [comment]
Having a fatal error in Movim will break the connection, that's a fact, so no need to repeat it each time.
For the moment I've put a big try catch around the buggy lines to prevent the issue to propagate. Please pull and try again.

Also when you're pasting some log lines, please add ``` and a carriage return before and after the logs to make them readable :)

**Comment by Neunerlei** [comment]
I dug down a little bit deeper into the depth's of imagick and it's php implementation. 

I don't know when the "ALPHACHANNEL_REMOVE" constant should have been implemented or if it ever was. But on PHP.net's constants page of the topic: http://php.net/manual/en/imagick.constants.php#imagick.constants.alphachannel There is no such constant defined, but there is a: imagick::ALPHACHANNEL_DEACTIVATE which does what: http://php.net/manual/en/imagick.flattenimages.php#116956 said "11" would do. 

In addition to that, $im->getImageAlphaChannel() will throw an exception if the current picture has no alpha channel, so you have to check for: "$im->getImageAlphaChannel()" first. In some other forum I read, that $im->setImageBackgroundColor('#ffffff'); has to be defined before $im->setImageAlphaChannel(imagick::ALPHACHANNEL_DEACTIVATE); is called. 

So if I apply said knowledge and adjust /system/Picture.php from: 

```
             if($format == 'jpeg') {
                        $im->setImageCompression(Imagick::COMPRESSION_JPEG);
                        $im->setImageAlphaChannel(11);
                        // Put 11 as a value for now, see http://php.net/manual/en/imagick.flattenimages.php#116956
                        //$im->setImageAlphaChannel(Imagick::ALPHACHANNEL_REMOVE);
                        $im->setImageBackgroundColor('#ffffff');
                        $im = $im->mergeImageLayers(Imagick::LAYERMETHOD_FLATTEN);
                    }
```

to: 

```
            if($format == 'jpeg') {
                $im->setImageCompression(Imagick::COMPRESSION_JPEG);
                $im->setImageBackgroundColor('#ffffff');
                if($im->getImageAlphaChannel()){
                    $im->setImageAlphaChannel(imagick::ALPHACHANNEL_DEACTIVATE);
                }
                $im = $im->mergeImageLayers(Imagick::LAYERMETHOD_FLATTEN);
            }
```

It works for me 👍 

Hope this helps anyone!

**Comment by Neunerlei** [comment]
Just out of curiosity. Will said solution be implemented into your code? Updated to the latest version today which killed Imagick again :P
