### ISSUE TITLE
URL and image previews in chat

### ISSUE THREAD

**Issue by MRZA-MRZA** [movim/movim#218]
It would be good to add URL and image preview in chat, i. e. if someone drops a link to chat, Movim displays a brief content and if it is link to an image then Movim displays image preview. Then the user clicks on image preview bigger image pops up with an option to see an original image (i. e. opens new window with the image). Previews should be displayed after original message in the same chat bubble. Like it is implemented in other messengers.

**Comment by edhelas** [comment]
Seems to be done for small pictures ;)

**Comment by singpolyma** [comment]
Did this feature get removed later?  It doesn't seem to work for me...

**Comment by panigrc** [comment]
Neither for me

**Comment by edhelas** [comment]
This is only working for some specific pictures links, don't expect anything like Skype, Discord or other similar IM solutions are doing as this is really heavy on the server.

**Comment by panigrc** [comment]
Ok thanx for clarifying this
