### ISSUE TITLE
Uploads are no longer working

### ISSUE THREAD

**Issue by pann** [movim/movim#219]
Probably while fixing this:
https://github.com/movim/movim/issues/214
the uploads stopped working for me.

I am using FF 47.0 on ubuntu, with prosody 0.10 xmpp server. Uploads worked before in the same setup.
The file seems to upload (indicated by the progress counting to 100%), but once the "Close" button is clicked there is no sign of the upload.

**Comment by edhelas** [comment]
Did you update the dependencies ?

**Comment by pann** [comment]
Yes, it also required a database update which also was performed.

**Comment by edhelas** [comment]
Your server doesn't accept CORS requests, it's not related to Movim. Please have a look at for more information http://enable-cors.org/index.html .
