### ISSUE TITLE
Run in Background

### ISSUE THREAD

**Issue by davodego** [movim/movim#220]
Can I run movim in Background?
I tried a & after the movim command but this don't work. When I come back to commandline move is also gone. 
On what way can I run movim on startup. Here is the same problem. I placed the movim command in rc.local to run on boot. But then movim connects and disconnects randomly.

**Comment by edhelas** [comment]
This is not related to Movim itself but how you configure your system to keep the daemon on.
There is a systemd and init.d script here if it can helps you https://github.com/movim/movim_ynh/tree/master/conf.

**Comment by davodego** [comment]
Thanks, haven't found this. It worked.
