### ISSUE TITLE
Dropped from room to first single contact

### ISSUE THREAD

**Issue by ajira86** [movim/movim#224]
When I'm typing or waiting on a conversation room, I'm sometimes drop on a single contact chat. Even if I'm typing something which is not really nice.

**Comment by edhelas** [comment]
This is a known issue that is related to micro-deconnections of the websocket. When the websocket is reconnected Movim tries to reload parts of the UI which can cause some issues.

**Comment by edhelas** [comment]
This has been fixed for a while already. Closing the ticket.
