### ISSUE TITLE
Everything considered "public" should be accessible without login

### ISSUE THREAD

**Issue by Jehan** [movim/movim#225]
I am mostly thinking about the "news" but this may apply to other parts of Movim.

Basically we should be able to access the "news" of a Movim instance (i.e. https://it.movim.eu/?news) without having to log in. Of course we could imagine that as a subscriber to other's news, you get a customized view. But that should not prevent a non-specific view for a random person.

Even more important, we should be able to make links which are visible to everyone, once again even without a login (as long as the news was marked "public"). Right now Movim is completely "isolated" from the rest of the web, and every links it produces is "broken" by design. So you can't just copy-paste a link to a public news from Movim onto another website.

This is something I hate in some proprietary social networks trying to jail you in their system by forcing you to have a login just to read something which was supposed to be public. Let's not make the same thing with Movim and let's open the public parts to everyone. :-)

**Comment by edhelas** [comment]
That is actually the case, when you make a post public Movim generates a link that goes to a static HTML public page.

For example https://mov.adorsaz.ch/?blog/adrien@adorsaz.ch/da963b7f-9b20-4941-b734-ce036e3391eb .

Movim also generates a public page for all the public posts of someone like https://nl.movim.eu/?blog/edhelas@movim.eu but also a valid Atom feed that can be parsed by everyone (even people that are not connected to the network), exemple : https://nl.movim.eu/?feed/edhelas@movim.eu .

This also applies to Groups https://nl.movim.eu/?node/pubsub.movim.eu/Movim and their feeds https://nl.movim.eu/?feed/pubsub.movim.eu/Movim .

**Comment by Jehan** [comment]
Well, when I am in the Movim feed. Let's say that I opened my last post re-published there. I expect to be able to copy the URL and be able to give it to someone. For instance here: https://it.movim.eu/?news/urn:uuid:c74c0103-be86-5f0f-a9a9-50e294a1f1f8

But then if I try to open it in a private window (to ensure I am not logged in), I get a login page. There may be another URL which is actually public generated for it, but where do we get it? In any case, it should be the URL in my address bar, for obvious usability reasons.

**Comment by edhelas** [comment]
Yeah I can understand that it's a bit disturbing but I'm planning to redirect the URL to the public one if you're not logged in.

For all the public articles Movim will display this box that will actually have a link to the public URL.
![capture du 2016-08-03 22-58-04](https://cloud.githubusercontent.com/assets/3726886/17381792/0ce29804-59ce-11e6-9451-3e2504cb587f.png)

**Comment by Jehan** [comment]
Yeah I saw this link to the actual upstream URL. That's good.

Yet it remains good practice that the URL which is shown in the address bar of the browser be also working as well (unless that were meant to be a private section, of course, which is not what we are talking about here).

Redirecting the URL to the public one when one is not connected will be an acceptable solution as fix for this bug report. :-)
