### ISSUE TITLE
Improve the navigation using tabs on mobile

### ISSUE THREAD

**Issue by SyrupThinker** [movim/movim#227]
See title, tested on Galaxy S6 Edge on Android 6.0.1 in Firefox 48.

**Comment by edhelas** [comment]
Hi, you can delete your account in the Configuration panel, Account tab. :)

**Comment by SyrupThinker** [comment]
Thanks, in that case I have a real bug to report, which resulted on in me not finding this. 
In the Configuration menu you can only access the first three tabs on a mobile device. Swiping does not show the other two options. 
This can be fixed by tapping any entry of the available ones.
Tested with a Galaxy S6 Edge on Android  6.0.1 in the Browser version of Movim in Firefox.
(Yes this really resulted in me not finding it)

**Comment by edhelas** [comment]
Ok, thanks for your feedback, I'll rename the ticket and turn it into a bug :)

**Comment by edhelas** [comment]
I've made some small improvements in the tab CSS, it seems to fix the issue for me. I'm closing the ticket.
