### ISSUE TITLE
Probleme d'installation

### ISSUE THREAD

**Issue by alteirac** [movim/movim#228]
Bonjour, j'essaie d'installer movim sur Firefox os (version 1.3.0.0) sur un ZTE Open C et j'obtiens l'erreur "INVALID_MANIFEST". Merci de votre aide.

**Comment by xeperippamm** [comment]
Même chose sur firefox os 2.5 sur ZTE Open C.
En testant le manifeste sur le app validator de mozilla, il me donne l'erreur suivante :
`Manifests must be served with the HTTP header "Content-Type: application/x-web-app-manifest+json". See https://developer.mozilla.org/docs/Web/Apps/Manifest#Serving_manifests for more information.`
Je pense qu'il faudrait modifier la config du serveur https://nl.movim.eu pour qu'il serve le manifeste avec le bon Content-Type.

Manifeste utilisé : `https://pod.movim.eu/manifest.webapp`
Validator : `https://marketplace.firefox.com/developers/validator`

**Comment by edhelas** [comment]
It seems to work now https://marketplace.firefox.com/developers/upload/d9b27c4543234bfaaf3f9d35375d4d02 for nl.movim.eu

**Comment by xeperippamm** [comment]
Cela fonctionne maintenant merci !
It works now, thanks a lot !
