### ISSUE TITLE
Impossible to leave MUC after remote server disconnects

### ISSUE THREAD

**Issue by bremensaki** [movim/movim#229]
If a user is connected to a non-local MUC, and the remote MUC becomes unavailable for any reason, there is no way to leave/rejoin the MUC without completely logging out of Movim and restarting all chats.

Example:
1. mike@chinwag.im joins conference jabberzac@conference.jabberzac.org via Movim.
2. Remote server hosting jabberzac.org is restarted
3. mike@chinwag.im sees MUC forever frozen in last state before restart, and "close chat" X button in menu is non-functional.

At minimum, the "close chat" button should function whether communication of leaving chat to remote server succeeds or not, allowing a restart of the session by the user.

**Comment by ajira86** [comment]
Have the same problem with a conference room.
FYI: no error report in Javacript console (Firebug)

**Comment by edhelas** [comment]
There is now a configuration menu to edit the chatrooms, does this helps you with this ticket ?
