### ISSUE TITLE
"An error occured: Error"

### ISSUE THREAD

**Issue by gllmhyt** [movim/movim#23]
When I'm connecting to my pod (pod.postblue.info) or to pod.movim.eu, I get the following notification:

![capture d ecran de 2015-08-03 17-09-13](https://cloud.githubusercontent.com/assets/696539/9040448/84620f46-3a02-11e5-82bf-f540886e1504.png)

How can I debug it? The error message is not very prolix.

**Comment by Dragnucs** [comment]
This affects me as well.

**Comment by gllmhyt** [comment]
Another error message not very well understandable, this one in the admin:

![capture d ecran de 2015-08-03 17-14-43](https://cloud.githubusercontent.com/assets/696539/9040559/49fe598a-3a03-11e5-858d-c27133a31e1b.png)

The question is: what catches Movim to say that there's an issue? Where can I find if I can fix it or not?

**Comment by edhelas** [comment]
This issue was moved to movim/movim#11
