### ISSUE TITLE
Websocket connection issue if accessed behind apache proxy

### ISSUE THREAD

**Issue by clement-analogue** [movim/movim#230]
Movim is not working if attempt to access behind an apache proxy. Its displays "Movim cannot talk with the server, please try again later (Websocket connection error)" with no errors in apache2.4 with debug set to "warn".

**Comment by edhelas** [comment]
Hi, there was nothing interesting in `movim.log` so I removed it :)
Did you followed the tutorial here https://github.com/movim/movim/wiki/Install-Movim#for-apache ?

**Comment by clement-analogue** [comment]
Yes. To explain a bit more because I wasn't clear apparently. I have two VMs with Xen. One with Movim, which works fine on local network, the other one is acting as a proxy for all my web servers in order to give them access from outside local network.

Here apache virtual host on the proxy server.

```
# cat /etc/apache2/sites-available/movim.conf
<VirtualHost 192.168.1.10:443>
    ServerAdmin <bob@alice>
    ServerName movim.forumanalogue.fr
    ErrorLog /var/log/apache2/movim-error.log
    LogLevel warn
    CustomLog /var/log/apache2/movim-access.log combined
    SSLEngine On
    SSLCertificateFile <foo>
    SSLCertificateKeyFile <bar>
    SSLCertificateChainFile <foobar>
    <IfModule mod_rewrite.c>
    RewriteEngine on
    RewriteCond %{REQUEST_METHOD} ^(TRACE|TRACK)
    RewriteRule .* - [F]
    </IfModule>
    <IfModule mod_rewrite.c>
    <IfModule mod_proxy.c>
    SSLProxyEngine On
    SSLProxyCheckPeerExpire On
    SSLProxyVerifyDepth 10
    ProxyRequests Off
    ProxyPreserveHost On
    ProxyPass / https://movim.forumanalogue.fr:443/ keepalive=On retry=5
    ProxyPassReverse / https://movim.forumanalogue.fr:443/
    RewriteRule ^/(.*) https://movim.forumanalogue.fr/$1 [P,L]
    </IfModule>
    </IfModule>
    <Location />
    Order deny,allow
    Allow from all
    </Location>
</VirtualHost>
<VirtualHost 192.168.1.10:80>
    ServerName movim.forumanalogue.fr
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301]
    Redirect permanent / https://movim.forumanalogue.fr/
</VirtualHost>
```

**Comment by edhelas** [comment]
Do you still have the issue ?

**Comment by clement-analogue** [comment]
Yes. I didn't find a workaround.

**Comment by edhelas** [comment]
You seems to have a very specific issue related to your architecture. I'm quite sure that this is not related to the Movim architecture but because of your configuration. Also it seems that you didn't proxify the /ws link.

**Comment by edhelas** [comment]
It seems that this documentation explains quite clearly how to setup Movim behind a proxy : https://www.cypouz.com/article/151109/installation-plate-forme-sociale-movim (in french). 

I'm leaving this ticket open to add a parameter to the daemon to allow him to listen on another IP than localhost.

**Comment by clement-analogue** [comment]
Thanks Edhelas. By changing the IP from local loop to the IP of the virtual server in the daemon and by changing properly the vhost in the proxy apache, it is working from outside local network. However, Movim doesn't connect to the websocket anymore if attempt to access on the local network.

**Comment by Cypouz** [comment]
Le dernier point évoqué par @clement-analogue a été résolu en configurant convenablement le reverse proxy du serveur Movim afin de servir directement le réseau local ; en plus du reverse proxy du serveur frontal.

@edhelas, tu suggères de laisser ce ticket ouvert afin de proposer à l'avenir un paramètre pour le démon, mais j'ai ouvert un ticket spécifique pour cela : https://github.com/movim/movim/issues/313

Je suggère donc de fermer celui-ci ;)

**Comment by p0liper** [comment]
I recommend to use 'nginx' instead of Apache
