### ISSUE TITLE
Unexpected exit while editing a blog entry

### ISSUE THREAD

**Issue by SebastienGrand** [movim/movim#231]
While editing a blog post, movim unexpectedly refresh the page and goes back to the "news" view, losing all current modifications.
It does happen after 1 minute or so.
It does not happen while creating a blog entry, only when editing an existing one.

I am using nl.movim.eu pod. With Firefox 48 or chromium, under android and linux.

**Comment by edhelas** [comment]
Duplicate with #224 (same common connection mistake)
