### ISSUE TITLE
Big blog post has no associated header image.

### ISSUE THREAD

**Issue by SebastienGrand** [movim/movim#232]
I am still unsure of the root cause, but it seems to be related with the number of images in the blog post.
I have 2 "big" blog posts with 5 or more images in it.

These two posts do not display an image in the blog post header.
These two posts are not listed in the "Gallery" page while looking to my profile with another account.
Yet these two blog posts appear in the news page of all my contacts, and can be viewed properly, with all images embedded.

**Comment by edhelas** [comment]
Are theses images larges ? (> 300ko) If yes Movim have now a size limit to prevent large pictures to be loaded in the UI without actually going on the post itself.

**Comment by SebastienGrand** [comment]
Ok, I got you.
Images are resized on the fly while uploading to fit the blog post limitations. But this resize operation is sometimes not enough to fit the "title background" limitation of 300KB.
Original images I used are far larger than 300KB. Once uploaded, some are larger than 300KB, some are smaller. I can only use one smaller than 300KB as blog title background.
Right ?

Adding mention of this limitation after the "link" text field would help, for example: "link (image file <300KB)" (or whatever size limit set by the server). And even better, a warning while posting/editing a post with such a too large image.

Well, not a bug. Only an improvement suggestion.

Merci beaucoup.

**Comment by edhelas** [comment]
The banners are mostly cosmetic and the rules to display them (or not) is a bit more complex than that (needs to be available by a server reachable by the Movim backend that server the pictures using a correct MIME type and with a size < 300k). So I can't tell you in advance if it will be 100% sure. I'm putting this as a wontfix.
