### ISSUE TITLE
Adding a picture to a blog post removes web link.

### ISSUE THREAD

**Issue by MRZA-MRZA** [movim/movim#233]
If I make a blog post with a link, then edit it to add a picture it removes the link.
Steps to reproduce:
Make a blog post with a title, a link and some text.
Then edit it, add a picture, save.
You'll see the picture you added, title and text, but no link.
Tested on nl.movim.eu

**Comment by edhelas** [comment]
I'm sorry where did you add the picture, in the text content or you replace the link ?

**Comment by MRZA-MRZA** [comment]
I press "Add a file or a picture to your post". I suppose that this function should just attach picture/file to a blog post and leave the rest of the content intact.

**Comment by edhelas** [comment]
No actually this feature just replace the link. That is currently designed like this. For the moment I'm not planning to change this sorry.

**Comment by MRZA-MRZA** [comment]
But this is confusing. If picture is added as a link, it's better to add additional link. So user can post multiple links.

**Comment by edhelas** [comment]
I'm sorry but this feature is not planned for now.
