### ISSUE TITLE
Use Movim like a Planet

### ISSUE THREAD

**Issue by Keuronde** [movim/movim#234]
I would like too use Movim like a "planet". And it seems that nearly everithing is in place to do so :
- We can subscribe to a group
- We can publish article
- We can produce a atom feed from the articles

What is missing is the ability to a group to automatically republish what another group has published: 
- Is it a fonctionnallity coming soon?
- Is there another way to aggregate publications and republish them?

**Comment by edhelas** [comment]
Hi, it's planned to allow users to republish a post in another Group or on their Blog in the next version (0.11). It will not be automatic ;)

**Comment by edhelas** [comment]
The feature has been implemented in trunk and will be available in the next release (0.11)
