### ISSUE TITLE
links with no domain

### ISSUE THREAD

**Issue by vaucanson** [movim/movim#241]
Hello.
I'm trying to test Movim on my local machine. http://localhost/?login gives me the login screen, but I can't sign in with an existing xmpp account, it leads me direct to the deconnexion screen. Also, the links "about" and "administration" point respectively to "http:///?about" and "http:///?admin", while I think I should have "http://localhost/?about".
Maybe could it come from my nginx config (I'm new to this) :

```
server {
    listen 80 ;
    server_name localhost;

    location / {
      root /var/www/movim/;
      index index.php index.xhtml index.html;

      location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php5-fpm.sock;
        include /etc/nginx/fastcgi_params;
        fastcgi_param HTTP_MOD_REWRITE 1;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
      }
    }

    location /ws/ {
        proxy_pass http://localhost:8083/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_redirect off;
    }
}
```

Is there something I missed ?

**Comment by edhelas** [comment]
Wow did you launched the daemon ?

**Comment by vaucanson** [comment]
As user www-data, I typed : 
`$ php daemon.php localhost 8083`

**Comment by src386** [comment]
Hello @vaucanson ,
Please try this : 

```
php daemon.php https://localhost 8083
```

**Comment by vaucanson** [comment]
OK, it works. The daemon asked the base URI to be https://localhost, so I changed the nginx config for https, and now all work.
Many thanks !
