### ISSUE TITLE
No counter for new messages in active chat in inactive browser tab

### ISSUE THREAD

**Issue by MRZA-MRZA** [movim/movim#242]
When I switch to conference chat then switch to another browser tab OR press '←' in the upper left corner of the chat view counter for new messages doesn't count new messages in that chat and there is no counter for new messages in a conference list.

Steps to reproduce:
1. Switch to any conference in Movim.
2. Hit left arrow in the left upper corner. It will display "Chat" page.
3. Wait for new messages to appear in that chat room. (You can write test messages using another client)
4. When new message arrive you won't see counter for new messages to the right of the conference name and counter in tab caption won't count new messages in that chat.

OR

2.Just switch to another browser tab.

It will lead to the same result.

**Comment by edhelas** [comment]
You have good eyes, thanks !
