### ISSUE TITLE
Old messages can be stored more than once

### ISSUE THREAD

**Issue by quent1-fr** [movim/movim#244]
I noticed that messages loaded from XMPP server history might be loaded more than once into the table message if you try to get them fast enough (i.e. by clicking on #id-user every 200ms). This behaviour makes messages to be shown more than a single time into the chat.

How to reproduce (on Firefox) : 
1. Truncate the message table
2. Go to http://movim/?chat/
3. Get a user id with previous conversations (i.e. #id-quentin-quent1-fr-chat-item)
4. Try to execute this : 

> function click_simulator(){ $('#id-quentin-quent1-fr-chat-item').click(); }
> setInterval(click_simulator, 200);

Then messages should be loaded more than once.

**Comment by edhelas** [comment]
Same as #174. Thanks for the report.
