### ISSUE TITLE
No warning when clicking on nickname in a MUC if participant left the chat.

### ISSUE THREAD

**Issue by MRZA-MRZA** [movim/movim#248]
If someone is not in a chatroom and you click their nickname there is no warning that the person is not in the chat anymore.

Possible solutions: 
1. Make inactive participants' nicknames not clickable
2. Display a warning that the participant is not in the chat anymore.

Ability to call someone without knowing whether they are online or not usually confuses. You need manually track their presence in a MUC.

**Comment by edhelas** [comment]
What is the default behavior on the other chat clients ? This issue could be fixed when #151 will be fixed.

**Comment by MRZA-MRZA** [comment]
If someone left the chat:

In Gajim nickname is not clickable

Conversations tells that participant not in the chat anymore if you tap on their nick.

**Comment by edhelas** [comment]
Related to #151

**Comment by edhelas** [comment]
#151 is closed, I'm not planning to implement this feature on top of it.
