### ISSUE TITLE
Can't connect to a XMPP server reachable through non-standard ports

### ISSUE THREAD

**Issue by dragondaddy** [movim/movim#25]
Hi there,

I have a XMPP server that can be reached through port 5422 (c2s) and 5469 (s2s). I can use it with clients like Pidgin or Gajim, but was not able to connect to it using the main pod (https://pod.movim.eu).

SRV records seem to be OK for the domain name I use.

I see nothing in prosody's logs (I can't see any connection attempt), and also nothing in my iptables logs.

Is Movim only able to use XMPP standard ports for the moment?

**Comment by edhelas** [comment]
As far as I see yes it's hardcoded https://github.com/edhelas/movim/blob/master/linker.php#L55 for the moment. Can you give me your server name then I can fix this issue ?

**Comment by dragondaddy** [comment]
The server is ok42.pw (woohoo, a 0,99 € domain name!). 
Right now a prosody server is running there.

**Comment by edhelas** [comment]
I'm now taking the DNS record port, please tell me if it's fine for you :)

**Comment by dragondaddy** [comment]
Works perfectly!
