### ISSUE TITLE
News appears 6 times

### ISSUE THREAD

**Issue by vogloblinsky** [movim/movim#250]
I just published a news for test and it appears 6 times : 

![image](https://cloud.githubusercontent.com/assets/2841805/18550972/c31ae21c-7b56-11e6-9b09-9dcaece7e125.png)

Using version on master branch.

Any idea ?

**Comment by edhelas** [comment]
Is it saved 6 times in the database ? If you refresh the page, are they 6 times here again ?
What browser do you use ?

**Comment by vogloblinsky** [comment]
In which table is it saved ?
If i refresh the page, it is already here.
I think it is related to my xmpp server. It is an enterprise installation, i will check his config with the IT department.

Another question : 
Which server configuration is required for correct usage ? RAM, etc

Thanks
