### ISSUE TITLE
Non consistent process flow of GUI when using Groups

### ISSUE THREAD

**Issue by yo-k** [movim/movim#252]
## What I expect

(The examples assume that you subscribed to "Movim Blog The Official Movim Blog". Anyhow there is not difference with other blogs.)
1. click in the left column on "Groups". In the left column "Groups" is selected. The middle column shows groups you subscribed to (_Groups My Subscriptions_). The right column shows Groups servers.
2. click in the middle column on "Movim Blog". In the left column "Groups" is selected. The middle column shows "Groups". The right column shows blog entries of "Movim Blog" 
3. click in the right column on any blog entry. In the left column "Groups" is selected. The middle column shows "Groups". The right column shows the selected blog entry.
4. click in the right column on the back arrow. In the left column "Groups" is selected. The middle column shows "Groups". The right column shows blog entries of "Movim Blog", again.
## How it works at the moment
1. click in the left column on "Groups". In the left column "Groups" is selected. The middle column shows groups you subscribed to (_Groups My Subscriptions_). The right column shows Groups servers.
2. click in the middle column on "Movim Blog". In the left column "Groups" is selected. The middle column shows groups. The right column shows blog entries of "Movim Blog" 
3. click in the right column on any blog entry. **IMHO here begins strange behavior.** In the left column "News" is selected, now. The middle column shows "News" instead of "Groups", now.
4. click in the right column on the back arrow. **Second strange behavior. A consequence of the first?** Right column shows "What's Hot - Public posts from users". Still the "News" are selected in the first column and shown in the middle column.

**Comment by yo-k** [comment]
which info do you need?

**Comment by yo-k** [comment]
How may I help you?

**Comment by edhelas** [comment]
The Groups UI has been totally redesigned for the 0.11 release, these inconsistencies are now fixed.
