### ISSUE TITLE
Embedding youtube video

### ISSUE THREAD

**Issue by vogloblinsky** [movim/movim#255]
I have found some specific code for this : 
https://github.com/movim/movim/blob/1dda46fe3ee44957fd490930ff29d4e3ec51c392/app/widgets/Post/_post.tpl#L189

I have found that is related to the main link provided with the post.

but is it in the road map extending this code for embedding a video in a blog post ?

thanks

**Comment by edhelas** [comment]
No sorry there is no plan like that.
