### ISSUE TITLE
No permission to load avatar picture

### ISSUE THREAD

**Issue by yuggmatt** [movim/movim#257]
The picture that movim tries to load as my avatar is stored in the cache directory, where a very aggressive .htaccess has been set up ("Deny from all").
Consequence: my avatar cannot be displayed.

Sample log from apache:
[Fri Sep 23 23:09:57.523077 2016] [access_compat:error] [pid aaaaa] [client xx.xx.xx.xx:yy] AH01797: client denied by server configuration: /var/www/cache/666540550e4861a6bd2226a611118954_50.jpg, referer: https://movim.mysite.com/?login

**Comment by edhelas** [comment]
Well, the cache folder should be accessible. Why do you want to have such restrictions ?

**Comment by yuggmatt** [comment]
I do not want to have such restrictions at all. It seems to me that composer is creating this file. And in fact, a git pull/composer install has just created such a file in my movim root dir.

**Comment by yuggmatt** [comment]
Making progresses on the matter:
1. The .htaccess files are created by the createConfig function from Factory.php in composer
2. Setting the COMPOSER_HOME global var. to the Movim directory triggers the problem:
COMPOSER_HOME=/var/movim_install_dir php composer.phar install

Setting this variables was the solution I found to prevent these messages from composer:
Cannot create cache directory /var/www/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /var/www/.composer/cache/files/, or directory is not writable. Proceeding without cache

I installed composer in the movim dir.

**Comment by edhelas** [comment]
Composer doesn't create .htaccess files, also the .htaccess that Movim have at its root directory doesn't say anything related to file access restriction (except folder listing content).

```
Options -Indexes
AddType application/x-web-app-manifest+json .webapp
```

As explained in the Wiki tutorial, the Movim root should be accessible in writing by the web-server, Movim will automatically create everything needed to work automatically after that.

**Comment by edhelas** [comment]
Closing this ticket
