### ISSUE TITLE
moxl and movim default log level is debug

### ISSUE THREAD

**Issue by yuggmatt** [movim/movim#258]
moxl and movim are generating an awful lot of logs in syslog by default. The log level seems to be "Debug", e.g (pasting just one line of each):

```
Sep 23 23:28:59 hostname movim[25009]: movim.DEBUG: Locale: Translation key "Submitting" not found [] []
Sep 23 23:30:55 hostname moxl[25009]: moxl.DEBUG: Handler : This event is not listed [] []
```

There does not seem to be a way to reduce this verbosity.

**Comment by yuggmatt** [comment]
modl also have this problem. In 28 hours, when having issue #259, modl has produced 63891 lines of syslog, all at the INFO level.
These lines contain SQL request:

```
Sep 24 11:13:23 hostname modl[32574]: modl.INFO: s:554:"insert into item                 (server,                 creator,                 node,                 jid,                 name,                 created,                 updated,                 description,                 logo                 )                 values(                     :server,                     :creator,                     :node,                     :jid,                     :name,                     :created,                     :updated,                     :description,                     :logo                     )"; [] []
```

or more cryptic lines:

```
Sep 24 11:13:23 hostname modl[32574]: modl.INFO: i:1062; [] []
```

In both case, they do not seem to provide much information for the sysadmin. Perhaps more to the application dev ? In any case a debug log level seems more appropriate and it should be possible to configure the application for not having them.

**Comment by edhelas** [comment]
By default the LOG_LEVEL value should be at 0 (it should only log the fatal errors in `log/php.log`)
