### ISSUE TITLE
Windows Phone 8.1 + IE

### ISSUE THREAD

**Issue by src386** [movim/movim#26]
Hi,

Movim doesn't work on Windows phone + IE :

http://pix.toile-libre.org/?img=1438933472.png

It's the same with Opera Mini : "Votre navigateur est trop vieux pour prendre en charge Movim".

**Comment by edhelas** [comment]
Can you tell me what IE version do you have on your phone? Is it IE11 ?

**Comment by src386** [comment]
```
Trident/7.0; Touch; rv:11.0; IEMobile/11.0
```

**Comment by edhelas** [comment]
Thanks, I'll try to find a IE11 and reproduce the issue :)

**Comment by Trim** [comment]
You can get any IE version officially from Microsoft on their [modern.ie](http://dev.modern.ie/tools/vms) website.

**Comment by edhelas** [comment]
I'll work on a IE11 debug soon, let's put Microsoft in the party now.
![](http://images-cdn.9gag.com/photo/192332_700b.jpg)
