### ISSUE TITLE
Cannot see posts from my contacts

### ISSUE THREAD

**Issue by yuggmatt** [movim/movim#261]
When clicking on a post from the News column, nothing happens. It's exactly the same from the posts lists on a contact's profile. I get the following message in syslog:

```
Sep 25 11:42:57 hostname movim[15940]: movim.ERROR: PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens [] []
Sep 25 11:42:57 hotsname modl[15940]: modl.INFO: s:339:"select postn.*, contact.*, postn.aid from postn             left outer join contact on postn.aid = contact.jid             left outer join item                 on postn.origin = item.server                 and postn.node = item.node             where postn.origin = :origin                 and postn.node = :node and postn.nodeid = :nodeid"; [] []
Sep 25 11:42:57 hostname modl[15940]: modl.INFO: N; [] []
Sep 25 11:42:57 hostname" modl[15940]: modl.INFO: N; [] []
```

**Comment by RobWJ** [comment]
i get a similar error on actual code from github.
also on groups post, same behavior.

but when i login to it.movim.eu with my xmpp user from my ejabberd 16.09.9 server, it works as expected.
looks like not a server xmpp problem.

movim php.log output:

```
PHP Warning:  PDOStatement::execute(): SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens in .../movim/vendor/movim/modl/src/Modl/SQL.php on line 133
```

i run it on ubuntu and debian, same problem.

workaround for me, i switched my database from mysql to postgres, works :)

now i get some other error, but i can click and see the posts:

```
PHP Warning:  PDOStatement::bindValue(): SQLSTATE[HY093]: Invalid parameter number: :jid in .../movim/vendor/movim/modl/src/Modl/SQL.php on line 117

```

**Comment by yuggmatt** [comment]
Same for me:
- I am using movim from the master branch on github
- when connecting to it.movim.eu with my xmpp user from my account, everything works as expected.
- I did not try with postgres.

**Comment by edhelas** [comment]
I made a small fix, is it ok for you ?

**Comment by RobWJ** [comment]
works for me, mysql and postgres.
thx
