### ISSUE TITLE
Static URLs for MUCs

### ISSUE THREAD

**Issue by bremensaki** [movim/movim#263]
Alongside #188, how feasible would it be to provide a shareable static URL for a conference to non-XMPP users? Say for example:

https://chat.chinwag.im/?chat&join=lobby%40rooms.chinwag.im

The ideal result when clicking this:

1) if the user is logged in and has an open Movim instance, change to/join that channel via normal methods immediately
2) if the user is not logged in, present login window and redirect to channel on success
3) if the user has no account, allow registration, then redirect to channel on success

As a total bonus, wrapping the generated URL into a shortening/encoding wrapper would be huge. Movim presents (optionally) something like: https://join.chinwag.im/sjjs32DsA 

Short URL could probably be provided by API call to another service.

Conference URLs should be accessible to users from the top menu in a room, possibly alongside the ability to invite a regular XMPP contact.

**Comment by edhelas** [comment]
It's related to that feature. Movim now support xmpp links, it's actually working in Firefox (see https://developer.mozilla.org/en-US/docs/Web-based_protocol_handlers). If you click on a chatroom link xmpp:movim@conference.movim.eu?join for example, it will be automatically open in Movim with the behaviour that you described.

Is it fine for you?

**Comment by bremensaki** [comment]
I have a much different use-case in mind. xmpp: links are only of use if someone already has an XMPP account. I need a way to say to a regular person who may or may not have used any XMPP service before "here is a link to our chatroom, please come and discuss things with us".

This is about engaging and attracting new users more than anything.

**Comment by edhelas** [comment]
Movim now support invitation (to JID or via an URL) to a chatroom :)
