### ISSUE TITLE
A movim session is already opened from another device

### ISSUE THREAD

**Issue by Insoleet** [movim/movim#266]
When connecting to movim with multiple devices, often I canno't connect using the device I'm currently using.

I think Movim behaviour should not refuse the connection if the user is already connected. It should be, either : 
- Let the user connects and disconnect the other session
- Support multiple devices connections

**Comment by edhelas** [comment]
Movim can actually handle several devices at the same time on the same session. But I'm wondering why it doesn't work for you. Can you easily reproduce the issue ?

**Comment by edhelas** [comment]
Ping

**Comment by Insoleet** [comment]
I can only reproduce this under really specific conditions : 
- Connecting to movim behind proxy
- Cut brutally the connection of the computer by putting it in stand by mode or by unplugging the network
- Reload the computer again

Maybe it's the websocket behaviour behind the forward proxy which is doing this bug ?

**Comment by edhelas** [comment]
This will be difficult to reproduce on my side for now. Sorry.

**Comment by edhelas** [comment]
I'm closing the ticket.
