### ISSUE TITLE
XF86Back and XF86Forward proper support

### ISSUE THREAD

**Issue by Jehan** [movim/movim#271]
Steps:
- I see the main page in https://nl.movim.eu/?news
- I click a news (any news). The URI in the browser address field changes.
- I hit a key which outputs XF86Back.

Expected result: I should be back to the news main page.
Actual result: the content of the address bar displays "https://nl.movim.eu/?news" as expected, but the browser still displays whatever news I was showing.

Of course, once this is fixed, I expect the opposite: hitting XF86Forward should bring me back to the news.
Note: this behavior is expected both on the web UI and the electron desktop container.

For more background, some keyboards have keys for forward/backward navigation (my Lenovo X220 has these) and I make extensive usage of these in both web and desktop applications.
Also I know it can work on web UIs even without any UI reload like in Movim, since it works as expected in gmail.

**Comment by edhelas** [comment]
With the communities and the new UI for the posts this seems to work properly. However I see that it's still not working on the chat page. I'm not planning to fix it for now. Please provide a PR and I'll review it :)

**Comment by edhelas** [comment]
Closing this ticket.
