### ISSUE TITLE
Chatrooms won't work properly with CAPS in ID

### ISSUE THREAD

**Issue by BoltonFR** [movim/movim#275]
Creating a chatroom like ThisIsMyChatroom@conference.movim.eu will result as an empty and buggy chatroom.

**Comment by edhelas** [comment]
Need to add stringprep support in Movim for the JIDs

**Comment by edhelas** [comment]
Movim is converting Chatrooms in lowercase for now, I didn't found a proper PHP library to do stringprep. If you have one, please comment and I'll reopen the ticket.

**Comment by p0liper** [comment]
How libraries are you using for XMPP contacting as well?
