### ISSUE TITLE
Connection host different from username host

### ISSUE THREAD

**Issue by ghost** [movim/movim#276]
I have a XMPP account that uses one of many different domain aliases available when registering at https://cock.li (`firemail.cc`, in my case). When logging in https://nl.movim.eu, I think Movim tries to connect to the host `firemail.cc` (which is part of the username) when the right connection host is `cock.li` (which should also be used for IMAP and SMPT), so it fails.

Other clients such as conversejs or IM+ can automatically resolve to the right host and even jwchat offers an extra field to specify the connection host, independently from the username.

**Comment by edhelas** [comment]
Is it possible to have a test account on your server, then I can reproduce properly the issue?

**Comment by ghost** [comment]
That's the problem, I'm not self hosting Movim so no server. You can try to register a test account at https://cock.li or maybe easier, I can change my password to a temporary one and privately send you the login credentials through xmpp, so you can test it in both https://nl.movim.eu and https://conversejs.org (for example).

xmpp://dmz76@firemail.cc
xmpp://dmz76@teknik.io

**Comment by ghost** [comment]
Or I can email you the credentials. Let me know through one of the emails above.

**Comment by p0liper** [comment]
Hm.. In a both domains, A record was
```bash
Name:    cock.li
Addresses:  2a06:1700:0:b::c0cc
          185.100.85.212
=======================
Name:    firemail.cc
Addresses:  2a06:1700:0:b::c0cc
          185.100.85.212
```
Can you tell me, is XMPP server running at this IP?

UPD:
I can connect to this XMPP server, using this IP. 

![image](https://cloud.githubusercontent.com/assets/9640308/23092226/f57ba05a-f5e7-11e6-90be-aa472a191fcf.png)

Also, I detect AAAA records. May be, Movim doesn't supports IPv6?

**Comment by ghost** [comment]
> Can you tell me, is XMPP server running at this IP?

It's a third party service so I can't be sure but that IP matches the record on Cock.li's [Server Info](https://cock.li/server) (there's another IP for VPS).
Also, for reference, Cock.li's [XMPP Settings](https://cock.li/xmpp) on Pidgin.

By the way, when trying to login in Movim, it just fails with no error message. The user/pass fields are just reset.

**Comment by p0liper** [comment]
> By the way, when trying to login in Movim, it just fails with no error message. The user/pass fields are just reset.


That's a movim bug.
@edhelas Can you check?

**Comment by p0liper** [comment]
@megadr01d Can you set IP address, instead of domain name? Or can you connect from other sites? (such as any XMPP online clients)?
I don't except Anti DDoS module from cock.li's XMPP server.

**Comment by ghost** [comment]
@yanislavb Thanks for the follow-up.

> Can you set IP address, instead of domain name?

All the clients I tried need the `username@domain.tld` format.

> Or can you connect from other sites? (such as any XMPP online clients)?

Yes. [Conversejs](https://conversejs.org/), [IM+](https://plus.im/), [JWChat](https://jwchat.org/) (online clients) and Messages (local client for Mac) all connect well. JWChat and Messages have an additional field for host (or IP), independently from the username, but they can be left blank since they're correctly resolved.

**Comment by p0liper** [comment]
@megadr01d Please, instead of domain name, try to connect using IP address
For ex.: megadr01d@185.100.85.212

**Comment by p0liper** [comment]
Hm... I can connect to cock.li using NL pod.
Can you give server access.log and error.log?

**Comment by p0liper** [comment]
![image](https://cloud.githubusercontent.com/assets/9640308/23329769/bd6cdfac-fb60-11e6-9cf3-569b688f4e62.png)
As proof :D

**Comment by ghost** [comment]
> Please, instead of domain name, try to connect using IP address

I tried that yesterday, didn't work. It warned about the correct format to use, stated in the placeholder `username@server.com`. Today Movim has a "We are currently experiencing authentication issues, sorry for the inconvenience" warning, so I'll try again later.

> I can connect to cock.li using NL pod. Can you give server access.log and error.log?

If you read the whole discussion you see that I don't have access to either server. I'm just a client of both Cock.li's and Movim's services. Also, as the discussion title says, my username is different from the hostname. You provided a proof with `cock.li` as part of your username which is also the connection host so Movim should have no problem connecting. While I chose `firemail.cc` in the dropdown menu in Cock.li's [Register](https://cock.li/auth/register) page.

**Comment by edhelas** [comment]
Just a precision, Movim doesn't resolve IPv6 addresses by default. There's a specific configuration on the nl.movim.eu pod to do it.

Please uncomment the two lines 80-81 in the following file to enable IPv6 DNS resolution on Movim

> vendor/movim/moxl/src/Moxl/Utils.php

I didn't found a way to detect easily in PHP if there's a IPv6 connectivity to the outside. If someone know how to do it, do not hesitate to propose a PR on https://github.com/movim/moxl

**Comment by ghost** [comment]
@edhelas OK, thanks for the info. Since it's not a bug I'll close the issue. For reference, if anyone should pursue it, don't know if `FILTER_FLAG_IPV6` helps: http://stackoverflow.com/a/15675444.
Thanks again guys, for the help.

**Comment by edhelas** [comment]
The problem is not to know if the IP is a valid IPv6 or not, the problem is to know if your server can reach this IP using IPv6 :D

**Comment by p0liper** [comment]
@edhelas Hm... I don't understand, but how movim can connect to unreachable address?

**Comment by p0liper** [comment]
if ipv6 wasn't active by default, but movim connects to it.

**Comment by edhelas** [comment]
If you don't uncomment those lines, Movim will only resolve IPv4 addresses and connect to those ones using IPv4, that's all.
