### ISSUE TITLE
Improve the loading time of the “New post” page

### ISSUE THREAD

**Issue by linkmauve** [movim/movim#282]
When clicking on the pen icon in the news, getting the form can take a long time currently, you should either add a spinner or preload the form.

**Comment by edhelas** [comment]
Under which circumstances did you had a delay. Even on a slow mobile connection this action should not take more than half a second.

**Comment by linkmauve** [comment]
It was on pep.’s slow mobile connexion.  Aside from the initial load, the rest felt normally slow, or at least gave immediate feedback about it.

**Comment by edhelas** [comment]
Since the UI refactoring, the post publication form is actually on another page, your browser should tell you about the loading process.
