### ISSUE TITLE
Don’t autocomplete the JID with @movim.eu

### ISSUE THREAD

**Issue by linkmauve** [movim/movim#290]
This is bad and **definitely** shouldn’t be the default.

**Comment by edhelas** [comment]
movim.eu is the default value if nothing is set on the admin panel, if you set your default domain here it will be automatically replaced.

https://github.com/movim/movim/blob/master/app/widgets/Login/login.tpl#L5
https://github.com/movim/movim/blob/master/app/widgets/Login/login.js#L183

**Comment by linkmauve** [comment]
We don’t have a default domain, we have 71 different domains, including three main ones, so it would at least need to let the user select which one to use.
