### ISSUE TITLE
Movim never answers to a disco#items to retrieve its list of commands

### ISSUE THREAD

**Issue by linkmauve** [movim/movim#295]
This is a violation of RFC6120, it should at least return an error if it doesn’t support ad-hoc commands or if the entity isn’t allowed to query them, or an empty set if none are available.

**Comment by singpolyma** [comment]
Indeed. `iq` should have a catch-all handler, that replies with `feature-not-implemented` error

**Comment by linkmauve** [comment]
This is definitely not an enhancement request, this is a bug report due to a protocol violation.
