### ISSUE TITLE
Allow the use of the back button

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#298]
Right now the only way to "go back" anywhere in Movim is to press the left arrow at the top which is not intuitive on mobile for example. Please ask for an example if it's not clear.
I would also like to be able to use swipe on mobile for the exact same behavior.

**Comment by edhelas** [comment]
The back button on Android is now linked to the "previous page" behavior on Movim. The recent refactoring of the Communities also bring a more natural navigation.
