### ISSUE TITLE
Post API?

### ISSUE THREAD

**Issue by MarcelWaldvogel** [movim/movim#302]
We are happy to see the progress Movim is making lately.

Originally, we were looking to interact with Buddycloud to have automated processes store and retrieve information that can also be created, modified, and queried by users. However, Buddycloud does have some critical bugs and development seems to have essentially stopped.

We are therefore looking to switch to Movim for our integrat with other workflows, e.g.

* creating a post when a particular event has been triggered, and
* showing posts from particular users and/or with particular tags inside a web page.

It should use the same infrastructure as Movim, but without going through the Movim frontend.

Are there code examples on how to do this or do we need to reinvent the wheel by implementing an XEP-0277 client from scratch? Does the Movim server have a (caching) API for this?

**Comment by edhelas** [comment]
Hi :)
Short answer, our API is XMPP. We don't want to create another abstraction layer on top of XMPP and end up with something like https://xkcd.com/927/.
Actually it's quite easy to publish something on a XMPP Pubsub node in any languages. Using a Python library like Slixmpp it can be done in a couple of lines.

Also if you publish something on a XMPP node using another client, the post will be synchronized automatically in real-time with Movim.
