### ISSUE TITLE
Show a loading icon while a message is being sent

### ISSUE THREAD

**Issue by Dragnucs** [movim/movim#312]
Expected behaviour:
When sending a message takes a long time, something like three dots or a small message should indicate that the message is being sent.

Current behaviour:
The message is *cleared* from the text box and does not appear in the chat screen.

**Comment by kawaii** [comment]
WhatsApp handles this quite nicely. It shows one tick for sent, two for delivered and then those ticks become blue when the message is read. Currently Movim does one tick for delivered and two for read but I feel this would be quite a nice change.

**Comment by edhelas** [comment]
Movim now doesn't clear the textbox until the message has been processed by the server.
