### ISSUE TITLE
Support selecting more precisely who can see posts

### ISSUE THREAD

**Issue by tikank** [movim/movim#316]
Movin seems to now support two modes for a post. Posts are either public (everyone can see the post) or non-public (only all contacts of the user can see the post).

The visibility of posts should be possible to restrict more precisely, because a user might have a rather large contact list and not every post is meaningful or even desirable for every contact. 

Apparently this is not purely Movim issue but also XMPP protocol issue, as mentioned in a comment of the post https://nl.movim.eu/?blog/tsk%40movim.eu/2642d165-09df-43a4-a831-46fdd90fa0ae . Maybe somebody still sometime invents a good solution for this.

**Comment by edhelas** [comment]
The main issue with XMPP is that you can mostly configure the "who can see" thing per node only, and not per posts.

**Comment by edhelas** [comment]
This will be a wontfix for now in Movim and should be see as a request for the XMPP protocol itself.
