### ISSUE TITLE
SQL datetime formats invalid in MySQL >5.6

### ISSUE THREAD

**Issue by bremensaki** [movim/movim#318]
Movim uses an ISO8601 datestamp format in many records. This is not a valid format for MySQL datetime columns, but versions up to 5.5 "guessed" the correct value and performed the insert without error. On 5.6 and above this is no longer the default behavior.

Relevant reference: http://dba.stackexchange.com/questions/48704/mysql-5-6-datetime-incorrect-datetime-value-2013-08-25t1700000000-with-er

Log excerpt here including a triggering insert statement:

```
Dec  7 02:34:03 cripes modl[23272]: modl.INFO: s:89:"1292 : Incorrect datetime value: '2016-12-07T07:34:03+0000' for column 'created' at row 1"; [] []
Dec  7 02:34:03 cripes modl[23272]: modl.INFO: insert into presence (id, session, jid, resource, value, priority, status, node, ver, delay, last, publickey, muc, mucjid, mucaffiliation, mucrole, created, updated) values( :id, :session, :jid, :resource, :value, :priority, :status, :node, :ver, :delay, :last, :publickey, :muc, :mucjid, :mucaffiliation, :mucrole, :created, :updated) {"id":"248a58a192624c7f740ff1ce1ecf56bc66504e7c","session":"mike@bremensaki.com","jid":"mike@bremensaki.com","resource":"d4d369ab-78c3-4d11-b283-ea8689462310","value":2,"priority":null,"status":"","node":"http://swift.im","ver":"3ScHZH4hKmksks0e7RG8B4cjaT8=","delay":null,"last":null,"publickey":null,"muc":null,"mucjid":null,"mucaffiliation":null,"mucrole":null,"created":"2016-12-07T07:34:03+0000","updated":"2016-12-07T07:34:03+0000"} []
```

On a fresh install of Ubuntu 16.04 with default settings, Movim is pretty much non-functional due to a vast amount of SQL inserts failing. 

The workaround from the linked Stackexchange post solves this issue for now - removing STRICT_TRANS_TABLES from the sql_mode setting results in Movim running normally.

**Comment by QuentinC** [comment]
Hello @edhelas !

I think that this could be the problem I had a few months ago ! (If you don't remember, I didn't succeed to run Movim using a MySQL server on Windows Server, but it was working with a local MySQL on debian !)

When I've seen this, I have checked, on debian I have MySQL 5.5 and 5.7 on Windows !

I will check later if I have the same date issues !

Thanks,

Quentin
