### ISSUE TITLE
XEP-0198: Stream Management

### ISSUE THREAD

**Issue by jkufner** [movim/movim#32]
At http://wiki.movim.eu/en:dev:protocol_implementations there is no mention of [XEP-0198: Stream Management](http://xmpp.org/extensions/xep-0198.html). Therefore there are two possible bugs:
1. Documentation is incomplete and should be updated.
2. Movim is loosing messages and other users' data when connection to server is broken. Which is very bad.

As you know, TCP connection is not reliable if it is not properly closed. When connection is lost in middle of communication, sender does not know how much data receiver actually received. So if XMPP server is  far away from Movim pod and connection is even slightly unstable, data will be lost. This is one of the biggest problems of XMPP, so XEP-0198 is must have.

**Comment by edhelas** [comment]
XEP-0198 is not planned for 0.9. I will see if I add it in the roadmap for the next version.

**Comment by edhelas** [comment]
Actually, if you have a look at the Movim architecture I don't think that this XEP is a "must-have", the XMPP connection is here managed by the Movim server that should have a reliable Internet connection.

**Comment by sezuan** [comment]
Stream Management could be used to automatically resume the sessions after a server('s process) restart. One might argue that this is not desired :)
