### ISSUE TITLE
Debian package for movim pod

### ISSUE THREAD

**Issue by guillaume-uH57J9** [movim/movim#320]
Hi,

It would be great to have Debian packages for the movim pod software for an easier installation and maintenance.  

[Current installation instructions](https://github.com/movim/movim/wiki/Install-Movim) involve doing a git clone to grab a development version, and use Composer (a PHP dependency manager) to install PHP dependencies. 

Git is great for development, but packages are more appropriates for deployment, and update. 
I have no particular opinion about Composer, but am avoiding language-specific package/dependency management systems as a general rule. 

I have to handle update through my system's package manager, as most people. This needs regular attention in order to stay current with software updates (security patches et al). 
To keep things manageable and ensure maintenance doesn't get more time consuming, I am avoiding additional language-specific managers. Many languages have their own managers (python, perl, js, php, ...), some languages even have multiple ones, and I'd rather not install a new manager for every 2 software I install.

**Comment by edhelas** [comment]
I totally agree with you and I'm ok to help with the packaging process. However I don't have the knowledge and the time to create and maintain the Debian package of Movim.
If someone here is OK to help, do not hesitate to drop a comment here.

**Comment by guillaume-uH57J9** [comment]
I also can help with testing and small tasks. My time is also limited thus I can only assist in small ways, not  take the lead on packaging. If someone to take the leads but need resources, I'll do a contribution on bugbounty.

**Comment by Ppjet6** [comment]
That's also my aim for the packages on Archlinux, but there are too many dependencies not packaged, and that means more packages to maintain with time that I don't have.

**Comment by guillaume-uH57J9** [comment]
As @Ppjet6 pointed out, a big part of this involves working on dependency packaging. 

Ideally each dependency would have its own package. This is a condition for inclusion in the official Debian repository. 
An easier way is bundling them in the movim-pod package, and distribute it only on Movim's own repository. This might be more realistic for start, and could be cleaned up later if there's need for inclusion in Debian's repo. 

I've had look at composer.json which lists the required dependencies + version, and made a [wiki page to summarize what's available in Debian jessie](/movim/movim/wiki/PackagingDependency).
This is a wiki page so you can correct mistakes, add information about other distributions, ...

**Comment by Natureshadow** [comment]
I am willing to create and maintain the movim package in Debian. I will look into the dependencies and create ITPs/RFPs as necessary the next days.

For the 0.12 release, please already make sure that some basic things are given: A complete and correct copyright/licence file, a complete source tarball and ideally a  GPG signature on it.

**Comment by guillaume-uH57J9** [comment]
Yay @Natureshadow thanks for volunteering on this. 

I updated the [Packaging-Dependency wiki page](/movim/movim/wiki/Packaging-Dependency) with current depedencies, and updated debian links from jessie to stretch.

**Comment by Natureshadow** [comment]
I just filed ITP bugs for all missing dependencies, updated the wiki page and started coordinating the work with the Debian PHP Packaging team.

**Comment by guillaume-uH57J9** [comment]
movim made some changes since this was last touched : 
* Added dependency on react/zmq
* Bumped required versions for multiple dependencies

I updated the [Packaging-Dependency wiki page](/movim/movim/wiki/Packaging-Dependency) accordingly.

**Comment by Natureshadow** [comment]
>movim made some changes since this was last touched : 
>* Added dependency for react/zmq
>* Bumped required versions for multiple dependencies
>
>I updated the [Packaging-Dependency wiki
>page](/movim/movim/wiki/Packaging-Dependency) accordingly. 

Thank you. Teckids is currently building a task force to get this done until April.

**Comment by Natureshadow** [comment]
Status update:

All dependencies are uploaded to Debian, Movim package is prepared and waiting for a legal issue in a dependency being resolved.

ETA less than a month until it hits buster.

**Comment by edhelas** [comment]
![](https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.d3zKmeJz4mFUnco7oirmawHaEJ%26pid%3D15.1&f=1)

**Comment by Natureshadow** [comment]
And sorry for the long delay. Nothing turns out as it was supposed to, you know ;)

**Comment by Natureshadow** [comment]
```
binary:movim is NEW.
binary:movim is NEW.
source:movim is NEW.

Your package has been put into the NEW queue, which requires manual action
from the ftpteam to process. The upload was otherwise valid (it had a good
OpenPGP signature and file hashes are valid), so please be patient.

Packages are routinely processed through to the archive, and do feel
free to browse the NEW queue[1].

If there is an issue with the upload, you will receive an email from a
member of the ftpteam.

If you have any questions, you may reply to this email.

[1]: https://ftp-master.debian.org/new.html
     or https://ftp-master.debian.org/backports-new.html for *-backports
```

https://ftp-master.debian.org/new/movim_0.14~rc-1.html

**Comment by Natureshadow** [comment]
```
Date: Sun, 02 Dec 2018 17:00:10 +0000
From: Debian FTP Masters <ftpmaster@ftp-master.debian.org>
To: Dominik George <natureshadow@debian.org>, Debian XMPP Maintainers
        <pkg-xmpp-devel@lists.alioth.debian.org>
Subject: movim_0.14-1_amd64.changes ACCEPTED into unstable, unstable
```

Time to close this issue, and happy `apt install`ing ;)!

**Comment by edhelas** [comment]
![](https://www.muvee.com/wp-content/uploads/2012/09/66796734.jpg)
Took me 10 years to make Movim, and now it's in Debian. Achievement unlocked.

**Comment by edhelas** [comment]
I'd like to thank personally @Natureshadow and @mirabilos for the awesome work done!
Thanks guy, much appreciated :tada:

**Comment by Natureshadow** [comment]
Quick note for those who are looking for it:

Debian buster will release with Movim 0.14.1
Debian testing/sid will stay with Movim 0.14.1 until buster is released.
Debian experimental always has the most recent release, also release candidates.

The 0.14.1 version is not the vanilla 0.14.1 release, but the 0.14.1 with all bugfixes backported. So, it's 0.14.1 minus the bugs, or 0.14.2 minus the features :P.
