### ISSUE TITLE
Missing execute bit in rpm package

### ISSUE THREAD

**Issue by ValdikSS** [movim/movim#321]
There's no execute (x) bit set to the `/opt/movim/movim/movim` binary after rpm installation, therefore movim cannot be started without running `sudo chmod +x /opt/movim/movim/movim`

**Comment by Ppjet6** [comment]
I am not sure Movim contains any binary file, can you be a bit more explicit? Are you sure you are trying to install the correct project?

**Comment by ValdikSS** [comment]
Yes it does, `/opt/movim/movim/movim` is an ELF executable but it doesn't have executable bit set.

Also, there's another issue that .desktop file contains:
```
Exec=/usr/bin/movim %U
```

but `/usr/bin/movim` is a symlink to a directory:

```
$ ls -la /usr/bin/movim
lrwxrwxrwx. 1 root root 16 Dec 18 18:13 /usr/bin/movim -> /opt/movim/movim
```

So, to fix these issues you need to `chmod +x /opt/movim/movim/movim` and make proper symlink. I can assume, judging by double `movim/movim` path and `Exec=` in .desktop file that there's just another additional `movim` directory that shouldn't be there, that's probably why your package script fails to `chmod +x` proper `movim` executable. I think it should be installed to `/opt/movim`, not to `/opt/movim/movim`.

**Comment by pztrn** [comment]
Are you trying to install desktop client? If so, this issue should be created here: https://github.com/movim/movim_electron

**Comment by ValdikSS** [comment]
@pztrn you're right, created issue there.
