### ISSUE TITLE
Login page: password can't be autofilled by firefox browser

### ISSUE THREAD

**Issue by lazyadmin111** [movim/movim#323]
Hey Folks,

I use movim daily and there is one thing which causes some annoyance, and that's that I have to type each type my password when logging in. Usually the firefox browser autofills my passwords fields at my mail provider and so on, and when I check the firefox settings, it seems to have saved also the password, but unfortunately the movim login webpage is done in a way, so that the password is not filled out.

Thus, the user like me has to fill out the password each time, thus that you either choose a very simple password, or you get mad :)

greets,

**Comment by edhelas** [comment]
It seems to work on my side when using the tab key (filling or selecting the JID, press tab key and then the password is autofilled). What specific behavior did you expected exactly ?

**Comment by lazyadmin111** [comment]
Dear Edhelas,

first, thank you for your reply and the hint, that the tab key can be used to autocomplete the password.

Well, it's great to know about this tab key trick, but nevertheless, this is not the behavior that most will expect I guess, or at least me and my freinds. Usually if I go to my webmail account at GMX or whereever, I just go to the site, and firefox automatically filled out the forms there, there is my ID in the user form, and the password field also shows only by going to the site some "********" stars, such that I know that it also filled in the password for me. 

The only thing then I have to do at other service sites, as every form has been filled out already, is to move my mouse to the "login" button, and that's it. At the movim page, this is not the case.

greets.

**Comment by jsonoctopus** [comment]
I also came across this issue, which might be just an issue about how Firefox handles stored passwords.
When Firefox has more than one username/password per domain saved, this behavior happens.
I noticed that I have both a username/password stored for movim.eu and api.movim.eu stored.
If I right click on the password field, Firefox offers me to autofill in two passwords.
Perhaps that is the case for you as well ?
You could choose to delete the saved username/password for api.movim.eu after which the expected auto-login behavior might work for you.

**Comment by lazyadmin111** [comment]
I think the whole approach to let movim offer a sort of "account" management, to offer a "another account" button and so on, is no good idea. This should be done by the browser's autofill form functions.

**Comment by edhelas** [comment]
I'm currently asking the community about it, actually going back to the "default behavior" will be less code to maintain for me as well :) Thanks for the feedback, much appreciated!
