### ISSUE TITLE
Simplify login page UX

### ISSUE THREAD

**Issue by lazyadmin111** [movim/movim#326]
Furthermore, the login page is also made too complicated in my experience: There is some "account" button, some "come in" button, and some "create one" button, a help button, and an administrator button. For the new users, I think it would be helpful to have one button to "login", and one to register. And all other buttons should be somewhere else on the webpage, maybe at the bottom or at the top of the page. The usual user is no administrator.

They are too many buttons which confuse the new user, and are also confusing: "Create One" Button is made more visually impressive than the "Come in" button. And instead of giving the buttons unusualy names, it would make things easier, if they are just as the new users knows them already from other services: There is no webmail provider who calls his login button "come in".

greets

**Comment by edhelas** [comment]
I made some small improvements, tell me what you think :)

**Comment by lazyadmin111** [comment]
Hey Edhelas,

Thank you!
I updated it, and still too many buttons at one place, but now see a "login" Button! ;-))

happy near year to you! :)

**Comment by edhelas** [comment]
I'm closing this ticket, I'm not planning to do further updates for now.
