### ISSUE TITLE
Unread message mark after I wrote to myself and ignored notification

### ISSUE THREAD

**Issue by unclechu** [movim/movim#327]
I can't get rid of this unread message mark until I write to myself again and open chat by clicking on notification.

I've recorded [screencast that demonstrates this](https://www.youtube.com/watch?v=9kI8geqtu5g).

**Comment by edhelas** [comment]
Hi, thanks for the screencast! I was able to reproduce the issue. Movim will not notify you if you are sending a message to yourself on another client now :) Fixed in https://github.com/movim/movim/commit/8f1ee58bb6095315f8cbcf439ccf9961018ee0f5 .
