### ISSUE TITLE
XEP-0313: Message Archive Management [$100]

### ISSUE THREAD

**Issue by jkufner** [movim/movim#33]
According to http://wiki.movim.eu/en:dev:protocol_implementations Movim does not support MAM. How Movim can know about messages sent when the pod is offline?

MAM is supported by Conversations, Gajim, eJabberd and few others. It works nicely.

**Comment by edhelas** [comment]
Movim already have a light implementation of MAM, I need to complete the Wiki page.

**Comment by edhelas** [comment]
This issue was moved to movim/movim#12

**Comment by stevenroose** [comment]
What is meant with a "light" implementation?

**Comment by sezuan** [comment]
Any plans to fix MAM? It appears that with the latest mod_mam in ejabberd it doesn't work any more.

The current behaviour without mam (caching and storing messages as long as the php process is not restarted) is highly confusing and leads to a very inconsistent history.

**Comment by rasos** [comment]
+1 to have MAM working again, as many people are not always online. When chatting using a mobile device they loose messages meanwhile.

**Comment by edhelas** [comment]
Some informations, I've fixed the XML mam:0 request in Moxl. Movim only support MAM up to mam:0 (which is not the latest revision) for now. This was tested with ejabberd, Metronome and Prosody and seems to work perfectly.

To request the history, open or load a discussion with the contact you want to talk with.
