### ISSUE TITLE
How does movim know "this is the blog for this user"?

### ISSUE THREAD

**Issue by singpolyma** [movim/movim#331]
Is there a wiki page or docs or similar (or is it a single XEP) on the "blog" tab movim has for each contact?  I know it's going to be PubSub, but how does it discover what node is the blog for that user?

**Comment by edhelas** [comment]
Movim implements this XMPP extension XEP-0277: Microblogging over XMPP http://xmpp.org/extensions/xep-0277.html

**Comment by singpolyma** [comment]
Ok, so, all my server needs is PEP? Is there something else I need on my XMPP server to make a button for creating the blog node show up on a Movim node when logged in with my self-hosted XMPP?
