### ISSUE TITLE
Movim as comment (and sharing) system for (outside) blogs

### ISSUE THREAD

**Issue by silverhook** [movim/movim#332]
I propose to make it easy to embed and use Movim as the commenting section of a (e.g. static) blog.

# Reasoning

A blog’s main content can easily be done in static HTML as once it’s written and published, it doesn’t change much. Its comment section, on the other hand, is by definition much more lively and is intended for many more people to write.

This way you can make it the best of both worlds – the easy to archive static blog and enable discussions for already existing blogs on in an unprecedented way when it comes to speed and convenience – commentators can use their own Movim/XMPP account to follow all comment threads they participated in instead of refreshing dozens of websites.

# Suggestion / use case

Here is how I imagine this could work, using [Pelican][pelican] and Movim.eu as a use case, but ideally this should be done on an API level agnostic of the blogging solution.

1. User publishes a blog post on their Pelican instance.
2. Pelican (via a plugin of its own to talk to Movim) on generation sends the new blog post to Movim to be published on Movim as a Movim blog post as well – this bit should be easy, as Pelican uses Markdown as well.
3. Movim sends back to Pelican the URL to the comment thread of the new Movim blog.
4. Pelican embeds that thread (e.g. as iframe) under its own blog post as a comment section.
5. Every one with an XMPP account can now publish and follow comments as well as like the (Movim copy) of the blog etc.

# Further challenges

- how to handle updates of the blog post
- how to make it possible to comment already on the static blog page, through the iframe
- comment (or follow comments) directly through an XMPP client – potentially very useful for the blog author to answer comments in a matter of minutes (instead of the usual days), especially for older blog entries

[pelican]: https://blog.getpelican.com/

**Comment by silverhook** [comment]
The above _use case_ is intended merely as a discussion starter. If this can be done on a XMPP or PubSub etc. level, it would be even better and there would be no need for an additional API, of course.

**Comment by edhelas** [comment]
This is something that can be totally outside Movim by any client that implements the XEP-0277 (http://xmpp.org/extensions/xep-0277.html), Movim will then be totally compatible with it.

**Comment by silverhook** [comment]
Ah, thanks. I’ll look into it :)
