### ISSUE TITLE
Submit comment (maybe also blog post) with Ctrl+Enter

### ISSUE THREAD

**Issue by silverhook** [movim/movim#333]
Using Ctrl+Enter to send a comment or message is a very common shortcut. I’m surprised that it doesn’t seem to work on Movim (at least on http://it.movim.eu) for comments and blogs.

I suggest that Ctrl+Enter is used (at least as an option) to submit messages and comments in Movim. Ideally also blog posts.

**Comment by edhelas** [comment]
That's not something I'm planning to work on. Please provide a proper PR if you want to add that feature in Movim.

**Comment by edhelas** [comment]
Closing this
