### ISSUE TITLE
Implement the Cat Avatar Generator (as a Gravatar replacement)

### ISSUE THREAD

**Issue by silverhook** [movim/movim#334]
In #291 Gravatar was removed, but now there is a MIT (and CC-By-4.0) licensed cute alternative: [Cat Avatar Generator][cat] ([git repo][git]) :smile_cat: 

I suggest to implement it to auto-generate the avatars.

[cat]: http://www.peppercarrot.com/extras/html/2016_cat-generator/index.php?seed=
[git]: https://framagit.org/Deevad/cat-avatar-generator/tree/master

**Comment by edhelas** [comment]
This is out of the project boundaries, sorry.

**Comment by silverhook** [comment]
Fair ’nuff :crying_cat_face:
