### ISSUE TITLE
Movim cannot talk to server, try again later

### ISSUE THREAD

**Issue by vitalyster** [movim/movim#337]
This pops up every time when I tap "back" under Safari Mobile. Both with back safari button at bottom bar and movim back button at top left of page. Didn't see it on the desktop

**Comment by edhelas** [comment]
Movim is currently not supported officially on iOS. Any contribution is welcome.

**Comment by ScootRay** [comment]
I can report the same issue happening on Safari on the Mac..  The page freezes up and I can't scroll.

Ray
