### ISSUE TITLE
Movim + Tigase compatibility issues

### ISSUE THREAD

**Issue by nwrkbiz** [movim/movim#339]
Hi,

I am just playing a little bit round with movin + tigase. I recognized, that the "news" module is not working with Tigase XMPP server. I guess that is because tigase does not implement pep-microblogging? I should also mention, that movim does not work with the normal Tigase PEP implementation, movim automatically logs me off after about 10 - 15 seconds. I had to switch to pep-simple to overcome this problem. Subscribing to PubSub channels does not work either (there is no subscribe button).

Seems like either movim or tigase is not 100% standarts compilant.

**Comment by edhelas** [comment]
Hey, I don't have a Tigase server available to debug. Can you provide me with credentials on a up-to-date Tigase server, then I can debug things :) ?

**Comment by nwrkbiz** [comment]
I just updated my server to 7.1.0, I think tigase does not implement xep-0223....
Is there any way I can send you the login credentials? I do not want to post them publicly ;)

I would really like to help, but php skills are very low....

**Comment by edhelas** [comment]
Hi, you can send them on my email address or my JID (you will find it easily).

**Comment by edhelas** [comment]
Hi, any news regarding this ticket?

**Comment by edhelas** [comment]
Closing this ticket as I didn't had feedback since February.
