### ISSUE TITLE
Toolbar button labels and sidebar on large screen

### ISSUE THREAD

**Issue by jkufner** [movim/movim#34]
Please add labels to toolbar buttons (in the blue top row of the screen) when screen si large enough to show them. Function of some buttons is not that obvious, so it will help a lot.

Also the sidebar does not have to hide on large screens (desktop size). Look at GitLab's sidebar for example (it also has a hide button for situations when more space is required).

**Comment by edhelas** [comment]
I've added a bit of CSS in this commit to display the nav-bar all the time on HD screens https://github.com/edhelas/movim/commit/1a9af1951c41c99460bcf52a87d1e1bd81e57269

**Comment by edhelas** [comment]
I've not planned to add labels in the toolbar for the large screens, I'm closing this issue.
