### ISSUE TITLE
Problem starting the deamon

### ISSUE THREAD

**Issue by mariobrussi** [movim/movim#340]
when i execute "php daemon.php start --url={public url of your pod} --port={port used by the daemon} "

it gives me that error

Oops... something went wrong.
But don't panic. The NSA is on the case.

what can be wrong?

**Comment by edhelas** [comment]
Can you check the content of `log/php.log`, there's maybe a PHP error there that could help you to debug :)

**Comment by mariobrussi** [comment]
yes some problem with database, now it works, thanks!

**Comment by edhelas** [comment]
Yay!
