### ISSUE TITLE
Movim doesn't display image in the right position (portrait/landscape)

### ISSUE THREAD

**Issue by Trim** [movim/movim#342]
Hello,

I'm using Movim 0.11alpha1 on mov.adorsaz.ch and I've found this little issue:

When Movim displays image from https://cloud.adorsaz.ch/index.php/s/U2MwOgcH9zUDjzW , there an issue with image rotation. As you can see with this link, my NextCloud server is able to display it with right rotation while Movim displays it 90 degrees rotated:

![Movim and Nextcloud display difference](https://cloud.adorsaz.ch/index.php/s/Ue2zwtFDJFrIjbz/download)

Best regards

**Comment by edhelas** [comment]
Movim doesn't do any transformation on the images, the orientation should be then adjusted by the browser itself when the JPEG headers are parsed.
