### ISSUE TITLE
Daemon.php cannot launch React\ ChildProcess\ Process in Windows (WAMP/XAMP) environment

### ISSUE THREAD

**Issue by Shaunzer** [movim/movim#343]
I have an issue with repeated daemon linker disconnections when running Movim on a Windows server machine (with WAMP/XAMP).

## Desired outcome
Daemon should launch and connect linker, does not disconnects and user can log-on to chat page and use the system as per normal.

## Current outcome/Problem
Daemon when executed, keeps getting linker disconnections. User cannot logon as the login page keep alternating between linker disconnections. Error message _'exec' is not a recognized as an internal or external command..._ is shown repeated as a daemon error between linker connections and disconnections.

![12-2-2017 9-47-13 pm](https://cloud.githubusercontent.com/assets/25722622/22862608/681d48b8-f16d-11e6-9f6d-d3430c59e9d8.jpg)

## Background
I've installed Movim on my local Windows machine. I had got all my dependencies setup and all running fine, however when I invoke the daemon.php either on cygwin or cmd, I keep getting Linker disconnections with the 'exec' error.

I am able to run the 'exec' command on windows cygwin bash and have my windows environment variables setup, including PHP (otherwise the daemon would not had been able to run).

I had been scratching my head on the problem, I had narrowed down the issue to two possibilities:
1) Incompatible call using linux 'exec' to run a php file in windows, launched from the daemon as a child process. I had narrowed down the code in src/movim/daemon/sessions.php. Could this code be potentially be updated to run on windows?

![12-2-2017 9-51-58 pm](https://cloud.githubusercontent.com/assets/25722622/22862656/0341afbe-f16e-11e6-8985-5ca60e4ec347.jpg)

2) Daemon.php not having Permission/Different rights in running linker.php

I had tried giving the daemon and linker administrator rights to execute code, and running the console as an administrator, but to no avail too.

What do you think?  I am unable to install movim on a Linux Distro or virtualise one. Will appreciate if ya folks can fill me in on my issue or potential bug.

Thanks,

**Comment by p0liper** [comment]
Movim is not supported on Windows-like systems.
But, if you want, you can check of use 
```bat
C:\php\php.exe linker.php
```
instead of 
```bash
exec php linker.php
```

**Comment by edhelas** [comment]
Yes, there is actually no support of Windows OS for Movim, a PR is welcome.

**Comment by edhelas** [comment]
Closing the ticket as no one took care of the ticket recently.
