### ISSUE TITLE
Movim doesn't share SQL access

### ISSUE THREAD

**Issue by Semperverus** [movim/movim#344]
Running Ejabberd 16.09 with SQL database enabled, I launch the Movim daemon.

Most of my other SQL processes share port 3306 just fine, but not Movim.

Movim wants 3306 to itself. Ejabberd continually crashes over and over as a result with "SQL database unavailable" and "timed out" errors.

Once Movim's daemon is killed, all is well again.

**Comment by Dragnucs** [comment]
Do not start the daemon with port 3306 but better on 8080 or 8000. Then set up your web server to this new value.

```bash
php daemon.php start --url=movim.domain.name --port=8080
```

**Comment by Semperverus** [comment]
I have the frontend port running off of 8080 like that, but SQL needs to be on a single port if you're running on MariaDB/MySQL I believe. I'll give tossing it up on a different port a shot though.

That is to say, the websocket port is different than the SQL port.

**Comment by Semperverus** [comment]
That is to say, the websocket port is different than the SQL port.

**Comment by Semperverus** [comment]
Alright, tested it on a separate port and the SQL daemon doesn't freely accept access from other ports. It has to be configured with mysqld_multi (basically running two instances at the same time). Not ideal, and proving to be fairly frustrating to configure.

**Comment by Dragnucs** [comment]
@Semperverus a port can be listened on only by one process. You cannot have both Movim and MySQL running on 3306.

You can have phpMyAdmin listening on 8080 or a subfolder, web server on 80 and Movim's daemon on 8000.

**Comment by edhelas** [comment]
I'm a bit lost here, I can run Movim with MySQL and other apps without issues. Maybe you have some specific configuration ?

**Comment by Semperverus** [comment]
You guys are missing the point. I'm launching movim on port 8080 for the daemon, but in the daemon configuration file where you tell it where to connect to (as in the SQL database, username, and port), you have to tell it 3306 for MySQL or the 5000 range port for Postgre. The daemon itself is listening for the movim webpage on 8080 but connecting to SQL on 3306.

There are two ports involved.

And edhelas, try connecting eJabberD to an SQL database instead of mnesia, then connect movim to an SQL database as well. Movim gobbles up all the access and doesn't take turns like literally everything else does.

I have no special configurations. Just apache2, mariaDB (mySQL), and php7 on Debian Testing.

**Comment by edhelas** [comment]
Ok, sorry for the misunderstanding, I'll try to reproduce it tomorrow.

**Comment by oappiah** [comment]
@Semperverus a default mysql-server on debian allows 151 connections.
Do a "SHOW PROCESSLIST" or ( SHOW PROCESSLIST\G for more info). 

When this happens and see how many belong to movim , to ejabberd , and other things you might have running.

You might have to tweak your settings... Unless the output shows unreasonable amount of connections for movim

**Comment by Semperverus** [comment]
Sorry, i should have marked this as fixed. It's not an issue anymore, the maintainer fixed it.
