### ISSUE TITLE
Messages sync between platforms

### ISSUE THREAD

**Issue by Metal-Mighty** [movim/movim#345]
Hi,

First and foremost: I am not familiar with XMPP, therefore I don't know whether the solution given here would work with that protocol!

Currently, messages sent in chat on one device/app doesn't seem to show up in other apps if they are not open at the same time. It can be quite a bummer whenever you want to switch from one device to another (smartphone to pc for example) since you won't get the whole history or messages.

As an example: I received a message on my phone app today and my PC was turned off. When I got back home I started Movim's Windows app and the message wouldn't show up.

Even though a centralized messaging system may not fit with Movim's philosophy, a decentralized system such as the P2P one used by Skype before being acquired by Microsoft (= messages were synced whenever both contacts were online) would sound great to me.

**Comment by edhelas** [comment]
Hello, can you please tell me what other app you are using (Pidgin, Gajim?…) and what is your current XMPP server?

**Comment by Metal-Mighty** [comment]
I am using the Windows app, Conversations on Android, and I'm using the nl.movim.eu pod

**Comment by p0liper** [comment]
edhelas, can you tell me, does movim supports web sockets? (ws, or wss)?

**Comment by ivucica** [comment]
@Metal-Mighty This is supposed to be supported by MAM -- which is [XEP-0313](https://xmpp.org/extensions/xep-0313.html). (For online connections, message carbons are used, which works fine.)

Gajim and Conversations work perfectly fine for this purpose.

@edhelas Movim does not seem to be fetching XEP-0313 from my own Prosody server.

The relevant MAM module comes from https://hg.prosody.im/prosody-modules/ commit 28d99ffa3c061f8476c225c7064729b870eac874. (Almost a year old, but eh.) [mod_mam](https://hg.prosody.im/prosody-modules/file/28d99ffa3c061f8476c225c7064729b870eac874/mod_mam), [mod_mam_muc](https://hg.prosody.im/prosody-modules/file/28d99ffa3c061f8476c225c7064729b870eac874/mod_mam_muc). This still uses the `urn:xmpp:mam:0` namespace, seemingly supported by Movim's master. (If I were to switch to latest, `mod_mam` seems to support `urn:xmpp:mam:0`, `:1` and `:2`, while `mod_mam_muc` seems to support only `urn:xmpp:mam:2`.)

Is MAM supposed to work correctly with Movim? Why wouldn't Movim be fetching history aside from its own database?

If you would like an account on my server to experiment, please reach out to me off-bug and I'll provision you with an account.
