### ISSUE TITLE
Movim produce invalid microblog posts (XEP-0277) when there is no title

### ISSUE THREAD

**Issue by goffi-contrib** [movim/movim#348]
According to [XEP-0277](https://xmpp.org/extensions/xep-0277.html) which follow Atom [RFC 4287](https://tools.ietf.org/html/rfc4287), `<title>` element is mandatory in microblog items.
However, Movim doesn't produce it when a post has no title (only a content), and this is not standard (resulting in the post being rejected by Salut à Toi).

The correct behaviour in this case is to put the message in `<title>`, and to not produce `<content>`.

**Comment by edhelas** [comment]
Can you please tell me on which article did you saw that. It seems that this issue has been fixed a couple of months ago.

**Comment by goffi-contrib** [comment]
Sure, you can see it on comments of this post: https://nl.movim.eu/?blog/edhelas%40movim.eu/a8736ad3-2d20-4bdb-b898-fc6297bca44f

The main post itself is alright, but comments have no <title> and from December 2016 or January 2017

**Comment by edhelas** [comment]
Ah on the comments.
