### ISSUE TITLE
Typo in the French translation

### ISSUE THREAD

**Issue by k3ck3c** [movim/movim#349]
replace, when logging the message

Profil publique

by

Profil public

**Comment by p0liper** [comment]
You can help by translate Movim on:
https://www.transifex.com/projects/p/movim/

**Comment by p0liper** [comment]
What language are you want to fix?

**Comment by k3ck3c** [comment]
I think the french translation is completed, but there is a typo, this is a common mistake, use 
publique
instead of
public

**Comment by p0liper** [comment]
okay, i'll fix it.

**Comment by edhelas** [comment]
Please update the translation on Transifex. I'll import the fixed translation.
