### ISSUE TITLE
Notifications multiply on unstable connection.

### ISSUE THREAD

**Issue by MRZA-MRZA** [movim/movim#352]
If my connection is unstable and slow sometimes Movim says that it can't connect to server. If it happens several times notifications begin multiply from one opened Movim tab. If i have too many disconnects Movim literally spams me with notifications.

**Comment by edhelas** [comment]
What kind of browser do you use? I can't reproduce this issue for the moment.

**Comment by MRZA-MRZA** [comment]
Well, I must admit that it's hard to represent. It happened in Firefox. I'll try to observe it for a couple of weeks and report.

**Comment by MRZA-MRZA** [comment]
It's too hard to reproduce. Because it happens under very specific circumstances. So I'm closing it.
