### ISSUE TITLE
Provide a way to send pictures in chats

### ISSUE THREAD

**Issue by singpolyma** [movim/movim#353]
I prefer Jingle FT (since it's what my other clients use), but SI FT, HTTP Upload, upload to a movim server and send a link, really any of these might be ok.

Unless it's already there and I just can't find the button?

**Comment by edhelas** [comment]
Movim relies on HTTP Upload to share pictures in chat. The XMPP caps should be setup properly to make this works.

**Comment by singpolyma** [comment]
Found it, thanks :)
