### ISSUE TITLE
Registration on a own server

### ISSUE THREAD

**Issue by p0liper** [movim/movim#355]
Hello!
Does Movim compitable with CloudFlare? And, except 'pod' port, what ports are needed to be open?

**Comment by p0liper** [comment]
Hm. That's compitable, but another question:
How do I allow the registration on a my server? 
I see this, and.. That's all. 
![image](https://cloud.githubusercontent.com/assets/9640308/23593768/0f28bcfa-0235-11e7-97f3-3e723c5a8ff5.png)
Can you help with it?

**Comment by edhelas** [comment]
Movim was never tried with Cloudflare and I don't see why it should work. Cloudflare is making cache of static HTTP pages afaik, Movim relies heavily on real-time, websocket and personalized generated content.

**Comment by yanislavb** [comment]
Are you read newest message?
I have trouble with make a new registration into own server.
