### ISSUE TITLE
Allow starting a chat with someone without adding them to my contact list first

### ISSUE THREAD

**Issue by singpolyma** [movim/movim#357]

**Comment by PeskyFactoids** [comment]
Before implementing this [annoying to me] feature please offer either xep0016 ui, or subscription buttons to allow/disallow this behavior.

**Comment by singpolyma** [comment]
@PeskyFactoids the UI this ticket asks for is unrelated to you being able to receive messages from people you have not approved. Any federated XMPP user can message a movim user, and even from in movim you can add a user to your contacts and then message them right away even if they do not subscribe to you :)

**Comment by edhelas** [comment]
How does this works with a client like Conversations?

**Comment by singpolyma** [comment]
Conversations happily receives messages from people not in Roster: I get such messages all the time :)

**Comment by edhelas** [comment]
That's also the case with Movim, but here we're talking about sending, not receiving no?

**Comment by singpolyma** [comment]
Conversations does require adding a contact before starting a conversation with them (in the UI) right now. Most other clients have some way to do without that, though.

**Comment by edhelas** [comment]
Ok, just to say, it's possible in Movim by calling the `?chat/jid@server.com` URL. But this feature is not planned for now.

**Comment by edhelas** [comment]
Closing this one as #482 has been closed.
