### ISSUE TITLE
Include XEP-0066 with image sending

### ISSUE THREAD

**Issue by singpolyma** [movim/movim#358]
The use of XEP-0372 to send images is pretty cool, but many older clients still support XEP-0066 and it's pretty easy to add :)

**Comment by edhelas** [comment]
Movim already implement SIMS https://xmpp.org/extensions/xep-0385.html

**Comment by singpolyma** [comment]
I know, and that's cool, but 0066 is just one extra tag and has the benefit of being around longer and not marked experimental :)
