### ISSUE TITLE
xep interrogation

### ISSUE THREAD

**Issue by PeskyFactoids** [movim/movim#359]
Will there be a movim variant of 

https://gultsch.de/compliance_ranked.html

😀

To make jabber texting server selection less painful  (pep persistence, for example)

**Comment by edhelas** [comment]
https://nl.movim.eu/?about#caps_widget

**Comment by queegipus** [comment]
The first link is for servers whereas the second link is for clients. :confused:

**Comment by queegipus** [comment]
how does one pick optimal providers?
