### ISSUE TITLE
MAM sync

### ISSUE THREAD

**Issue by PeskyFactoids** [movim/movim#360]
different than https://github.com/movim/movim/issues/345 ?

Should MAM histories be visible when switching between

it.movim.eu
and
nl.movim.eu

for servers topping 
https://gultsch.de/compliance_ranked.html

login IT.  chat a while.  close- or logout.  login NL.   Either no MAM, or only my side in history.

**Comment by edhelas** [comment]
Same as https://github.com/movim/movim/issues/345
