### ISSUE TITLE
How can I allow registration on a own server?

### ISSUE THREAD

**Issue by p0liper** [movim/movim#362]
Hello!
How can I allow register on a my server?

**Comment by MRZA-MRZA** [comment]
What jabber server do you use? You can enable it in server config (in band registration). But I'm in doubt it's Movim related. I don't see such feature on admin page.

**Comment by p0liper** [comment]
I have ejabberd, and I allow registration on my server, but I'm in stuck with movim. :-1: 
Movim is a great social network, based on Jabber, but without registration feature :-1:

**Comment by MRZA-MRZA** [comment]
So, what's your problem? Movim allows to register accounts.

**Comment by p0liper** [comment]
But on a their own servers. I can't allow registration on a my server.

**Comment by MRZA-MRZA** [comment]
Please describe what you do, what you expect and what you get.

**Comment by p0liper** [comment]
I want to allow register other users IN MOVIM, NOT JABBER CLI\MySQL (underline the required)

**Comment by Dragnucs** [comment]
@yanislavb You just need to pay attention when registering your account on movim to chose/type-in your server instead of movim's or converseations' one. Same applies for all clients.

**Comment by edhelas** [comment]
Closing this for now

**Comment by p0liper** [comment]
I can't understand your reply, @Dragnucs.
Can you re-phrase for me?
