### ISSUE TITLE
Support for chat markers (XEP-0333)

### ISSUE THREAD

**Issue by fegul** [movim/movim#363]
One thing that most XMPP clients are lacking are read receipts (a.k.a chat markers) which are defined in XEP-0333.

Conversations.im currently supports them however there are no XMPP clients that can be used on the desktop which support this.

Are there any plans to include this in Movim in the near future?

**Comment by edhelas** [comment]
Movim should now notify the user if the sent messages are displayed. It's still a WIP.

**Comment by edhelas** [comment]
Done on trunk
