### ISSUE TITLE
Instructions for installing stable version are not clear

### ISSUE THREAD

**Issue by daftaupe** [movim/movim#365]
From the wiki page : https://github.com/movim/movim/wiki/Install-Movim#stable-version
> The Movim source code is not available in a packaged version for now, please follow the next paragraph. You simply have to clone it from git and put it on your web server. The package contains everything to make Movim run on your system.
The next part is only required for those who want to install the development version. If you took the Movim package from the repository please jump to the next chapter and go directly to the Deployment section.

This paragraph has several issues in my opinion :
- next paragraph is installation of development version not stable
- the source code is not available in a packaged version / the package contains everything to make Movim run on your system ? which sentence am I supposed to trust here ?
- The next part is only required for those who want to install the development version : okay but if you don't run the part about Composer nothing will work I guess, at least not straight from the repo clone.
- which Movim package ? and which Deployment section ?

I don't have a precise solution to discuss/offer but I guess this wiki page has to be refreshed otherwise a lot of people will abandon trying to setup movim :(

**Comment by edhelas** [comment]
I've removed the unclear parts as we don't have proper packages for now
