### ISSUE TITLE
PHP minimal version is not correct

### ISSUE THREAD

**Issue by daftaupe** [movim/movim#366]
When I follow https://github.com/movim/movim/wiki/Install-Movim in order to install, I can read that the minimal version of PHP required is 5.4.
I have Centos7 and then when I run composer.phar to install the dependencies I get the following error 

> Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Installation request for cocur/slugify v2.4 -> satisfiable by cocur/slugify[v2.4].
    - cocur/slugify v2.4 requires php >=5.5.9 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 2
    - Installation request for embed/embed dev-master -> satisfiable by embed/embed[dev-master].
    - embed/embed dev-master requires php ^5.5|^7.0 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 3
    - Installation request for symfony/console v3.2.6 -> satisfiable by symfony/console[v3.2.6].
    - symfony/console v3.2.6 requires php >=5.5.9 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 4
    - Installation request for symfony/debug v3.2.6 -> satisfiable by symfony/debug[v3.2.6].
    - symfony/debug v3.2.6 requires php >=5.5.9 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 5
    - Installation request for symfony/http-foundation v3.2.6 -> satisfiable by symfony/http-foundation[v3.2.6].
    - symfony/http-foundation v3.2.6 requires php >=5.5.9 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 6
    - Installation request for symfony/routing v3.2.6 -> satisfiable by symfony/routing[v3.2.6].
    - symfony/routing v3.2.6 requires php >=5.5.9 -> your PHP version (5.4.16) does not satisfy that requirement.
  Problem 7
    - symfony/http-foundation v3.2.6 requires php >=5.5.9 -> your PHP version (5.4.16) does not satisfy that requirement.
    - cboden/ratchet 0.4.x-dev requires symfony/http-foundation ^2.2|^3.0 -> satisfiable by symfony/http-foundation[v3.2.6].
    - Installation request for cboden/ratchet 0.4.x-dev -> satisfiable by cboden/ratchet[0.4.x-dev].

So either composer has changed its requirements and the install page should be updated in consequence, or there's something else to do, anyway a piece of info is missing somewhere.

**Comment by daftaupe** [comment]
The wiki page has been update accordingly to PHP >= 5.5

**Comment by p0liper** [comment]
Can you update PHP to 7 or greater?

**Comment by daftaupe** [comment]
Well I can, but the issue was about PHP 5.4 being advertised as the minimal version required, but not actually being able to install Movim project with it in reality.

**Comment by p0liper** [comment]
Hello. Not so long ago, @edhelas was correct the minimal PHP version in source code. 
So, one way to use movim is update PHP to 7.0 or greater version.

**Comment by daftaupe** [comment]
@yanislavb I understood, but as I told you I don't have a particular issue, I just wanted the documentation modified. I guess I can close this issue now.
Thanks for your help.
