### ISSUE TITLE
Contacts' blog view

### ISSUE THREAD

**Issue by baptistem** [movim/movim#369]
If I understand how it works, every contact can have a blog. but in order to view your contact blog, you have to select a contact, then check his blog. one by one.

I think it would be a very nice feature to display all your friends latest post / image publishing!

**Comment by edhelas** [comment]
This is actually available in the News page (if you have a compatible server) under the "Contacts" tab.

**Comment by baptistem** [comment]
I guess that my contact aren't very active and that the "degraded" mode doesn't help for this. :)

**Comment by edhelas** [comment]
Closing this ticket.
