### ISSUE TITLE
XEP-0308: Last Message Correction

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#37]
This is a feature request. It would be nice to support it.

**Comment by src386** [comment]
+1

**Comment by Dragnucs** [comment]
+1

On 27 August 2015 08:06:29 WEST, src386 notifications@github.com wrote:

> +1
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/edhelas/movim/issues/37#issuecomment-135316637

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Bretos** [comment]
+1

has any other client already implemented this?

**Comment by edhelas** [comment]
I'm also interested by this feature, but I'll have issues to support it on mobile (hard to ingrate it properly in the UI).
Also I definitely don't have time for this (yet) ;)

**Comment by edhelas** [comment]
This issue was moved to movim/movim#13

**Comment by edhelas** [comment]
Well the feature has been integrated in Movim and seems now stable. Have fun !
