### ISSUE TITLE
UX : responsive improvement for largest screen on community view

### ISSUE THREAD

**Issue by baptistem** [movim/movim#370]
In the community view, I'm quite annoyed by the "edit" or "new" button at the bottom right of the screen.
I'm browsing on a fullscreen 16:10 1080p screen, this button is at the exact oposite of every action you can do.
For example : 

you click on the upper left side of your screen for the community panel, then you need to select a communities server at the middle left of the screen. Once you are there your eyes and your mouse stay on the top left screen part. But if you want to add a community, or a post in a community you have to "travel" to the bottom right of the screen. (which is a long trip when you have a big screen :D ).

More over it is kinda inconsistent with a single post view, where the edit button is at his best place imo, just after the title.

This is so far the only issue I had with the responsive which is in fact really impressive! Thanks for that good work!

**Comment by edhelas** [comment]
I've moved the edit/new button at the bottom-right corner of the main corner. Thanks for the feedback.

**Comment by baptistem** [comment]
I can confirm it's better!
Thanks for the improvement and all the work done here :)
