### ISSUE TITLE
UX : my profile page

### ISSUE THREAD

**Issue by baptistem** [movim/movim#371]
I'm confused by the amount of action you have to follow / guess to access your own profile page.
today I do the following  : 
click on my name -> pop-up for status
click on the edit button -> settings page
click on the "go to my  profile page" -> contact page with the profile page

I'd have expect something more close to this : 
click on my name -> pop-up with status
click on the edit button -> profile page

as long as having "my profile page" in the contact view

I don't understand the logic behind going to the settings from the status popup to be honest.

**Comment by edhelas** [comment]
I've reorganized the Contact page removing some of those steps to access your profile page.
Now you can simply click on your avatar in the menu.
