### ISSUE TITLE
login with userid alone

### ISSUE THREAD

**Issue by lazyadmin111** [movim/movim#376]
Hey folks,

I have one suggestion: It would be nice, to be able to login only with the user-id, without the "@"-part. Why? -- Because I run for my friends on my server more than only this xmpp-service, and the users get confused, because some services want them to specify just the userid, some don't. So there should be some default host which is used, and the userid alone should suffice.

what you think about that suggestion?
any helpful comments welcome.

have a nice day.

**Comment by edhelas** [comment]
It's possible to define a default XMPP server on the admin panel, Movim will then autocomplete the server part.
Also the JID is not only to login but also will be used everywhere on the XMPP network.

**Comment by lazyadmin111** [comment]
With "autocomplete" you mean, that movim automatically shows visually the completion by "@server.com" or?

**Comment by edhelas** [comment]
Yes :)
