### ISSUE TITLE
presence table should not have NOT NULL constraint on resource column

### ISSUE THREAD

**Issue by singpolyma** [movim/movim#377]
For example, a server component way have presence sent directly from the "bare" JID and the table should not reject to store that.

https://mail.jabber.org/pipermail/standards/2017-April/032562.html

**Comment by edhelas** [comment]
What do you think about putting an empty string in a else case here https://github.com/movim/movim/blob/master/app/models/presence/Presence.php#L76 ?

**Comment by singpolyma** [comment]
If you prefer that it should work almost the same, so probably fine

**Comment by edhelas** [comment]
Fixed
