### ISSUE TITLE
pod.movim.eu claims movim.eu/urn:xmpp:microblog:0 group doesn't exist anymore on first login 

### ISSUE THREAD

**Issue by esijg** [movim/movim#38]
Just created a brand new account on pod.movim.eu and after I log in for the first time I get the following error dialog.
`It seems that this group doesn't exists anymore. Do you want to remove it from your subscriptions? myUsername@movim.eu/urn:xmpp:microblog:0`

**Comment by edhelas** [comment]
This issue was moved to movim/movim#14
