### ISSUE TITLE
Fix all undefined variables, indices, dereferenced null objects…

### ISSUE THREAD

**Issue by linkmauve** [movim/movim#382]
Here is a short excerpt of errors happening in the php.log when running Movim:
```
[13-Apr-2017 14:50:20 UTC] PHP Notice:  Undefined index: title in /usr/share/webapps/movim/app/models/postn/Postn.php on line 363
[13-Apr-2017 14:50:20 UTC] PHP Notice:  Undefined index: description in /usr/share/webapps/movim/app/models/postn/Postn.php on line 365
[13-Apr-2017 14:50:20 UTC] PHP Notice:  Undefined index: logo in /usr/share/webapps/movim/app/models/postn/Postn.php on line 366
[13-Apr-2017 14:50:20 UTC] PHP Notice:  Undefined variable: caps in /usr/share/webapps/movim/cache/_contact.d3ae090a36f5326bcabc0372395ca98c.rtpl.php on line 72
[13-Apr-2017 14:50:20 UTC] PHP Notice:  Trying to get property of non-object in /usr/share/webapps/movim/cache/_contact.d3ae090a36f5326bcabc0372395ca98c.rtpl.php on line 222
[13-Apr-2017 14:50:26 UTC] PHP Notice:  Trying to get property of non-object in /usr/share/webapps/movim/app/widgets/Contact/Contact.php on line 292
```

You really should find a tool to identify these bugs before they reach your users.  I don’t know of any such tool for PHP but look for tools doing type inference on your code, possibly helped by manual hints where they are wrong, and make sure to avoid any kind of operation on variables whose type is maybe something (and maybe null).

**Comment by p0liper** [comment]
You can disable these errors via htaccess (if apache) or nginx.conf (if nginx). These errors is not critical, and can allow users to work with Movim.

**Comment by linkmauve** [comment]
These errors **are** critical, I don’t care about seeing them myself, but I do know they are preventing my users from using their client properly, and that is a big issue.

Hiding issues is never going to be a good idea, they should be identified and fixed, and the addition of new ones should be prevented at any price.

**Comment by p0liper** [comment]
Please, show your phpinfo().
Because I checked these scripts now on my machine and, it works without any errors (but I don't disable error logs on my server).

**Comment by p0liper** [comment]
I think your error_reporting says about undefined variables, but in these scripts are detected pre-use check (if is this variable defined?)

**Comment by singpolyma** [comment]
Most PHP code throws these kinds of warnings if you turn error reporting up high enough. So long as the code can handle the value being null, accessing a non-existent index can be fine (even common) in PHP.

**Comment by Ppjet6** [comment]
Are you really fighting in favor of people writing PHP doing the wrong thing here? And because it's too common an issue nobody cares anymore?

Warnings are just the tip of the iceberg and should be treated as carefully as errors.

EDIT: It's not about the language

**Comment by singpolyma** [comment]
@Ppjet6 the point is that these "issues" are *not* causing issues for users. One can argue the merits of DBU in various programming languages, but this is at most a style fight and not a bug that affects functionality. You may argue that this coding style might result in a bug in the future, and you might be right, but it's hardly a critical situation since no user is directly affected by the non-DBU coding style (which style, as I have said, is popular in the language of this project)

**Comment by Ppjet6** [comment]
> No user is directly affected so it doesn't matter

Am I reading this correctly? If so, wtf?

**Comment by Ppjet6** [comment]
To be a bit more clear, (if it wasn't already), this issue is a call to start using tests, linters etc. There are tools available to help us identify problems before they even reach the user, and it would be a good idea to start using them, instead of ignoring/silencing the problem at hand.

**Comment by edhelas** [comment]
Closing this one as it will be tracked in #512.
