### ISSUE TITLE
Whitespaces in messages are not preserved

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#383]
Whitespace is not really the problem here, (well it is because of HTML,) it's about preserving messages content.

I believe this could be fixed using https://developer.mozilla.org/en-US/docs/Web/CSS/white-space
This would also allow to stop replacing newlines with `<br />`.

Please :)

**Comment by linkmauve** [comment]
This is a bug, you shouldn’t close valid bugs like that…

Anyway, the solution is to set the `white-space: pre-wrap` CSS property on all non-XHTML-IM messages.
