### ISSUE TITLE
History in chat not requestable until the scroll bar appears

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#384]
I am running 322a82ca.

When opening a chat window with a contact, chat history doesn't seem to be requestable until there is enough messages for the scroll bar to appear.

**Comment by edhelas** [comment]
So basically you have no messages at the beginning ?

**Comment by Ppjet6** [comment]
I have messages, it goes maybe to half the page, (not sure how many messages are loaded by default), but I can't load more from history at this point

**Comment by edhelas** [comment]
Is it better with 50 messages?

**Comment by Ppjet6** [comment]
No it doesn't. You can make it 100 messages, it won't fix the problem entirely

**Comment by edhelas** [comment]
Fixing this issue "the proper way" will complexity the current code. Appending 50 messages creates a height that is big enough to add a scrollbar on a FullHD screen (scale 1x) and trigger the event to request the history if the user is scrolling up.

I'm closing this ticket.
