### ISSUE TITLE
403 Forbidden after starting daemon

### ISSUE THREAD

**Issue by Oviked** [movim/movim#386]
Hi,

I'm having some troubles with Movim. I've followed the wiki page https://github.com/movim/movim/wiki/Install-Movim and started the daemon, but I get this : 

```
php daemon.php start --debug --url=https://xmpp.oviked.xyz --port=8080

Movim daemon launched
Base URL: https://xmpp.oviked.xyz/

--- Server Configuration - Apache ---
Enable the Secure WebSocket to WebSocket tunneling
# a2enmod proxy_wstunnel 
Add this in your configuration file (default-ssl.conf)
ProxyPass /ws/ ws://localhost:8080/

--- Server Configuration - nginx ---
Add this in your configuration file
location /ws/ {
    proxy_pass http://localhost:8080/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect off;
}

Encrypted 

```
Nginx "virtual host" config file : 

```
server {
    listen 80;
    listen [::]:80;
    server_name xmpp.oviked.xyz;
    # enforce https
    return 301 https://$server_name$request_uri;
}

server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name xmpp.oviked.xyz;

  ssl_certificate     /etc/letsencrypt/live/xmpp.oviked.xyz-0002/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/xmpp.oviked.xyz-0002/privkey.pem;
  ssl_protocols TLSv1.2;
  ssl_ciphers EECDH+AESGCM:EECDH+AES;
  ssl_ecdh_curve prime256v1;
  ssl_prefer_server_ciphers on;
  ssl_session_cache shared:SSL:10m;
  ssl_session_tickets off; # Requires nginx >= 1.5.9
  ssl_stapling on; # Requires nginx >= 1.3.7
  ssl_stapling_verify on; # Requires nginx => 1.3.7
  keepalive_timeout    70;
  sendfile             on;
  client_max_body_size 0;

  root /data/movim/;
	location / {
		try_files $uri $uri/ =404;
	}

  location /ws/ {
      proxy_pass http://localhost:8080/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
      proxy_redirect off;
  }
 

}
```
error_log sample :
`2017/04/19 22:12:21 [error] 30325#30325: *139569 directory index of "/data/movim/" is forbidden, client: 90.120.211.57, server: xmpp.oviked.xyz, request: "GET / HTTP/1.1", host: "xmpp.oviked.xyz"
`
Movim binaries are located in /data/movim with chown www-data and chmod u+rwx on it.

**Comment by p0liper** [comment]
Check the permissions to the "/data/movim" folder.
It should be the same of the provided in server configuration.

**Comment by p0liper** [comment]
For detailed response, please, attach the output from:
```bash
ls -ltrha /data/movim
```
and 
```bash
cat /etc/nginx/nginx.conf
```

If the output is very long, you can paste them on '[GhostBin](http://ghostbin.com)'

**Comment by Oviked** [comment]
Hi yanislavb,

Sure, here is the output :
https://ghostbin.com/paste/3p5h6

**Comment by p0liper** [comment]
execute these commands from root:
```bash
chown www-data:www-data /data/movim -R
nginx -s reload
```

**Comment by Oviked** [comment]
Same error : 403 Forbidden

`2017/04/20 21:45:21 [error] 10156#10156: *158005 directory index of "/data/movim/" is forbidden`

**Comment by p0liper** [comment]
>  10156#10156: *158005 directory index of "/data/movim/" is forbidden

Include inside virtual host (inside 'location' block):
```bash
index index.php;
```

**Comment by p0liper** [comment]
And restart nginx
```bash
nginx -s reload
```

**Comment by Oviked** [comment]
Same error again in error_log but it downloads index.php as a bin file.

**Comment by p0liper** [comment]
```bash
cat /etc/php/7.0/fpm/pool.d/www.conf
```
And output, please, upload to ghostbin.
Thanks.

I think you don't install php-fpm package.

**Comment by Oviked** [comment]
`cat /etc/php/7.0/fpm/pool.d/www.conf`

https://ghostbin.com/paste/g5zx6

**Comment by p0liper** [comment]
Write this inside 'virtual host' block (**not 'location' block**)
https://ghostbin.com/paste/68hrf

And, restart nginx

**Comment by p0liper** [comment]
Please, fix configuration file ('https' instead 'http')
Then contrib can close issue.

**Comment by Oviked** [comment]
"Please, fix configuration file ('https' instead 'http')"

Which configuration file are you talking about ?
EDITED : I figured out. 

And thanks for your help.

**Comment by c-93** [comment]
I am having a similar problem. Can someone please again upload his/her working nginx vhost? Thanks! :)
