### ISSUE TITLE
Creating a new account on pod.movim.eu displays two forms, top one being unusable

### ISSUE THREAD

**Issue by esijg** [movim/movim#39]
![screenshot from 2015-08-24 11 35 31](https://cloud.githubusercontent.com/assets/2924543/9439213/668b542a-4a54-11e5-98cd-afddb1b81fd1.png)

Like the screenshot shows, when creating a new account on pod.movim.eu the page shows two forms. One in a regular fashion, while the second one is overlaid on top. The overlay form's submit button does not do anything. Making it impossible to sign up unless you close the overlay and use the form below.

**Comment by edhelas** [comment]
The issue seems fixed now
