### ISSUE TITLE
Open "Read x remaining paragraphs" in new Tab

### ISSUE THREAD

**Issue by elouin** [movim/movim#391]
Its super annoying that its open those in the tab movim is opened.

**Comment by edhelas** [comment]
If you use Movim in a browser, you can use the middle click of your mouse to open the link in a new tab, like on any other link.

**Comment by elouin** [comment]
I know. But thats not expected behaviour. 
Links in Chats and such also open in new Tabs, so its not consistent design there.

**Comment by edhelas** [comment]
There's a difference between opening a link that goes on the same domaine/website and another that bring you outside the website. That's how Twitter, Facebook are working.

**Comment by elouin** [comment]
Yeah, but a link that opens an article outside of movim from the "readx remaining paragraphs" link and the same link in a chat are doing different things. thats not how facebook and twitter are working.

**Comment by edhelas** [comment]
Wait, what kind of articles are we talking about here, there's a "read more + " button, no "read x remaining paragraphs"

**Comment by elouin** [comment]
I have that ars technica group thing subscribed. When i hit read more, it opens as expected in the same tab movim with more info than in the preview. at the bottom of this preview(most of the time its about 3 paragraphs long) there is a link that says "read x remaining paragraphs", wich is a raw link to that specific article. That raw link is opening in the same tab as movim, but should be opened in a new.

**Comment by edhelas** [comment]
Ah, that's different, that "read x more paragraph" link is generated by ArsTechnica themselves ;) Movim doesn't control the content of those body links.

**Comment by elouin** [comment]
Ohh, i didnt knew that. 
Sorry for that trouble then.

**Comment by edhelas** [comment]
Hey, I've made a little fix to force all the links in articles to open in a new tab :)

**Comment by elouin** [comment]
Thanks, thats much better! :D
