### ISSUE TITLE
Unable to open a pubsub page, automaticly go back to home

### ISSUE THREAD

**Issue by dnorak** [movim/movim#396]
When i try to connect to a pubsub page (via https://server/?community/pubsub.server/anycommunity ) i come back quickly to login page then to Home.

I search in log files and in php.log I see :

PHP Fatal error:  Uncaught Error: Call to a member function isComment() on null in /srv/www/htdocs/movim/app/widgets/Menu/Menu.php:61

I looked in this file and i added change ligne 61 to :
if($post != null && $post->isComment() && !$post->isMine())

and it fixes it.

I think it was happened because I have some bug in some post : I can't comment them while others are OK. I don't know why ...
I edit these posts, I touch nothing, i save and then, i can comment them. 
After corrected them all, my patch wasn't necessary.

**Comment by edhelas** [comment]
I've made some commits, can you tell me if it's working?

**Comment by dnorak** [comment]
It's exactly what i will doing :D
It's Ok for me
