### ISSUE TITLE
registration page refreshes after 30s, too quick

### ISSUE THREAD

**Issue by ghost** [movim/movim#397]
When newcomer tries to register a new account, (s)he reaches the 'AccountNext' page.
(S)He is invited to fill in the form with login, password, (and optionally the captcha web page).
After **30s**, a timeout happens and reloads the page automatically. Thus the registration can't be achieved properly if it spends more than 30s.

By opening the webconsole, I can read :
> Connection established!
> [...] 30s later
> Connection closed by the server or session closed

and the page is reloaded and goes back to the 'Login' page.

How to handle this issue ? 
Disable or change the timeout delay for the registration might help.

**Comment by ghost** [comment]
thx

**Comment by edhelas** [comment]
This should be more stable now, the limitation has been removed, closing the ticket.
