### ISSUE TITLE
Posts - duplicated likes and comments

### ISSUE THREAD

**Issue by tbeitter** [movim/movim#398]
under my post likes and comments are shown twice.
![2017-06-14-093306_852x1105_scrot](https://user-images.githubusercontent.com/756334/27120708-ef7594ba-50e4-11e7-896d-0d5fc1ca5593.png)

**Comment by edhelas** [comment]
Are you using different XMPP clients? Did you changed your server configuration? Is it possible to get a dump of those comments from the DB? On which pod do you have this issue?

**Comment by edhelas** [comment]
This didn't happen recently, closing the ticket
