### ISSUE TITLE
Click on contact seems to fetch the N oldest entries from MAM archive.

### ISSUE THREAD

**Issue by sezuan** [movim/movim#40]
Click on contact seems to fetch the N oldest entries from MAM archive and erases the current chat history.

**Comment by edhelas** [comment]
As I see nothing is deleted when Movim do a MAM request so I don't see exactly your issue here.

**Comment by sezuan** [comment]
probably cause by https://github.com/edhelas/moxl/commit/910d9555ace24f9cf42e09213a3f74ff3f520522
seems that ejabberd doesn't support namespace prefixes.
