### ISSUE TITLE
Wrong message order

### ISSUE THREAD

**Issue by MRZA-MRZA** [movim/movim#400]
Sometimes two messages are received very quickly so Movim displays them in wrong order.
Example:
    [20:00:00] user: !command
    [20:00:00] bot: answer
As you can see bot answers immediately. Gajim displays it correctly but Movim can place bot's answer before user's command.

**Comment by edhelas** [comment]
Is it possible to find a way to reproduce this issue?

**Comment by MRZA-MRZA** [comment]
I can easily reproduce it by issuing a command to a bot in another xmpp client (like Gajim) and then entering to that MUC using Movim. I see bot's answer before command.
You need any bot to try it.

**Comment by edhelas** [comment]
Hi, is it still happening?

**Comment by MRZA-MRZA** [comment]
Unfortunately it still happens sometimes.

**Comment by edhelas** [comment]
This will require to be more precise on the way Movim handle timestamp of saved messages in the DB.

**Comment by edhelas** [comment]
I'm closing this ticket as this is requiring to move to a specific wait to order the messages in the DB which is something that I'm not planning to do.
It's "good enough for me".
![](https://media1.tenor.com/images/8856e3ad69679ed85e3239df270a24a6/tenor.gif?itemid=11860846)
