### ISSUE TITLE
Private posts not working

### ISSUE THREAD

**Issue by kvaps** [movim/movim#402]
Steps for reproduce:
- Go to communities
- Create new post (don't mark "Public" trigger)
- Try to access this post from another server or another account

**Comment by edhelas** [comment]
This feature is working, it seems to be a server configuration issue. Can you please be more precise with which server, domain, account it doesn't work and if possible provide me a test account, then I can reproduce the issue?

**Comment by kvaps** [comment]
Hi, I used kvaps@xmpp.ru accound, and I created post on pubsub.feder8.ru using movim.feder8.ru server.
This is the post:
https://movim.feder8.ru/?post/pubsub.feder8.ru/feder8/b98e98f5-38b7-40d1-a087-b9df962306b3#

After it, I tried to access this post via nl.movim.eu and kvaps@movim.eu acount:
https://nl.movim.eu/?post/pubsub.feder8.ru/feder8/b98e98f5-38b7-40d1-a087-b9df962306b3

And I was success

**Comment by edhelas** [comment]
Hi, is there some updates regarding this ticket?

**Comment by edhelas** [comment]
Closing this ticket.
