### ISSUE TITLE
Add option to restrict suggestion to a specific XMPP domain

### ISSUE THREAD

**Issue by kvaps** [movim/movim#403]
I am considering Movim for creating some security private portal, Jappix was very fine for it, but I have many questions how to implement it in Movim.

Is Movim supported to creating private portal?
- How I need to configure my jabber server for allow pubsub access only from my own movim instance?
- How I can prohibit my users to read and create posts on another jabber servers?
- Is it possible to disallow users to create public account?
- I found the whitelist server setting in admin panel, but it is applicable only for login step, isn't it?

Thanks!

**Comment by kawaii** [comment]
+1 for this. We use Movim at work and because I'm a member of some other MUC rooms that aren't work-related they keep showing up to my colleagues in the 'Communities' section. It would be nice if the administrator could set the pod into some kind of isolated mode so that it doesn't do this and can purely be used as a nice webclient. 😄

**Comment by Natureshadow** [comment]
If possible, please make this a two-step option:

1. Allow access to everything, but hide foreign stuff from the discovery as to not leak what others searched for to everyone (c.f. #491)
2. See above

**Comment by edhelas** [comment]
For this ticket I can add a checkbox in the admin panel to only show Communities and Muc "discovery" restricted to the same domain (and subdomains) as the logged in user.

**Comment by Natureshadow** [comment]
There still seems to be a bug with this. While the new option works when setting it, at some point it is automatically turned off again. It's not really reproducible, and when it first happened, I thought I maybe hadn't saved the setting, but now it happened again.
