### ISSUE TITLE
Oops... something went wrong.

### ISSUE THREAD

**Issue by frimdo** [movim/movim#405]
Every my attempt to install movim ends with
```
Oops... something went wrong.
But don't panic. The NSA is on the case.
```
This message is completely useless. Is there any way to get more information? Maybe edit the code so that the error says something useful? At least "error with database", "error with permissions",...

**Comment by edhelas** [comment]
Can you please have a look at php.log in the logs folder and report any fatal error here?

**Comment by linkmauve** [comment]
The issue isn’t about this particular case, it is about reporting the actual error to the user instead of this message.

**Comment by frimdo** [comment]
Thank you. This little commit helped a lot!
