### ISSUE TITLE
Prosody mod_pubsub Integration

### ISSUE THREAD

**Issue by kawaii** [movim/movim#407]
I noticed that Movim will run in degraded mode with Prosody backend even when that service has mod_pubsub enabled. Is it simply a matter that Prosody's implementation of pubsub is not advanced enough to support the Movim features? Perhaps since you last checked there may have been some improvements to mod_pubsub that may make this possible in the future? :slightly_smiling_face: 

https://prosody.im/doc/pubsub
https://prosody.im/doc/modules/mod_pubsub

**Comment by edhelas** [comment]
I'm currently talking about it with the developer of mod_pubsub :) Looks like some features are still missing.

**Comment by kawaii** [comment]
Thank you! Hopefully we might see some improvement in 0.13. I only discovered Movim last week and today I finally managed to get it working in my Docker stack with Prosody and PostgresSQL, already I'm very impressed with the range and quality of XEPs integrated. 😄

**Comment by pztrn** [comment]
> Hopefully we might see some improvement in 0.13

If this related to Prosody - maybe. This issue isn't related to Movim, because Prosody's mod_pubsub lack of ability to permanently store nodes on disk. This issue should be sent to Prosody's developers.

(This is also a reason why I switched to ejabberd, BTW)

**Comment by edhelas** [comment]
The was just a question, closing :)

**Comment by poVoq** [comment]
Would be still nice to have some sort of update thread here regarding the Prosody situation. 

Proper prosody support would really ease setup of a Movim pod and there are probably quite a lot of XMPP Prosody hosts that would like to add Movim but shy away from switching to another server.

Edit: Related topic on the Prosody issue tracker:
https://prosody.im/issues/issue/485

**Comment by pztrn** [comment]
Read my reply above. Nothing changed yet.

**Comment by kawaii** [comment]
Hello! Am I right in thinking this can be closed now? I believe Prosody has all the required pubsub features to make this work but has anyone actually tested it properly?
