### ISSUE TITLE
Code Syntax Highlighting

### ISSUE THREAD

**Issue by kawaii** [movim/movim#408]
Feature request: We are hoping to replace [Mattermost](https://about.mattermost.com/) in our workplace in favour of using XMPP (Prosody) backend with Movim frontend. One thing we often do is paste code snippets in chats and group rooms. Mattermost has nice code syntax highlights much like GitHub does, it would be nice to see this included in the same way for Movim. :)

**Comment by edhelas** [comment]
For the moment Movim doesn't support formatting in chat, especially for security purpose. But it's something that can be researched :)

**Comment by kawaii** [comment]
Thanks for the consideration. :)

This JS library would add some overhead in terms of page load time, but it looks like it would accomplish this enhancement quite nicely:

https://highlightjs.org/

It seems to be updated quite regularly. Unless you feel like writing your own parser. The nice thing about how Mattermost parses code is that you can specify the exact language by doing this on the opening tag:
```
```python
[code here]

**Comment by edhelas** [comment]
Hey, I've added the feature in chat chat discussions, the syntax is /code (similar to /me).
