### ISSUE TITLE
Support for XMPP URI scheme

### ISSUE THREAD

**Issue by MRZA-MRZA** [movim/movim#410]
I think it would be good if Movim could recognize Jabber URI Scheme (https://xmpp.org/extensions/xep-0032.html). Currently it doesn't highlight xmpp: links.

**Comment by edhelas** [comment]
Movim already support those schemes, but how do you want to use them? Do you mean that it should open Movim when you encounter such URI in your browser?

**Comment by MRZA-MRZA** [comment]
Tested on latest git version. URI like xmpp:somechat@conference.server.tld?join is not clickable.
I think that browser must have appropriate handler to open such links, but that is another topic.

**Comment by edhelas** [comment]
Those URI are now clickable accross the UI and will redirect you to Account pages or MUC conversations. I'm marking the ticket as resolved :)
