### ISSUE TITLE
No error given why trying to join members-only MUC

### ISSUE THREAD

**Issue by kawaii** [movim/movim#412]
If you are not authorized (no affiliation) to join a MUC room/channel there is no error given. It looks like you might have joined it only there are no other participants, you can't send messages and no MAM history is returned. The room will just sit there in your 'Chatrooms' list. Perhaps some error should be returned and the room not left displayed in the list? :)

**Comment by edhelas** [comment]
Can you please provide me a chatroom where this happens then I can debug and handle correctly this case?

**Comment by kawaii** [comment]
I'll need to get a test server deployed soon so that I can do this for you, since currently I just use the one at my workplace. I'll let you know the details when I do. 😄
