### ISSUE TITLE
Can't scroll sticker tabs on mobile

### ISSUE THREAD

**Issue by Altreus** [movim/movim#413]
If you're a sticker junkie and have many sticker sets, the icons for the sets becomes wider than the screen and can't be scrolled sideways.

**Comment by edhelas** [comment]
Hi, thanks for the report. Is it possible to have a bit more information about your OS/browser/app info then I can try to reproduce properly :) ?

**Comment by Altreus** [comment]
I'm using Chrome on Android (6.0 I think). In portrait mode the screen is too narrow for all of the sticker sets. Here's a picture.
![screenshot_20170705-100950](https://user-images.githubusercontent.com/74533/27875882-c0f14d18-61ac-11e7-9b97-2b6d247bc5a4.png)
