### ISSUE TITLE
Entire page covered by `<span id="AutoConvertInstalled">`

### ISSUE THREAD

**Issue by Altreus** [movim/movim#414]
This issue only happens on one system, and I can't reproduce it on any other. I don't know what triggers it, but movim appears to be confused as to whether I'm using a desktop or mobile.

There are no JS errors and it's not caused by my minimum font size.

It's possible that somewhere in movim is an attempt to use browser information instead of CSS to decide whether I'm on a mobile device or not, but this is merely conjecture.

If someone can suggest what information I can gather to help isolate this issue I will happily oblige.

**Comment by kawaii** [comment]
I've resolved this issue for @Altreus, he had a Chromium extension interfering with the DOM. 🙂 

This can be closed.

**Comment by Altreus** [comment]
hold on there boi

Although this was caused by a plugin, the plugin was doing nothing more egregious than adding a `span` to the body.

The problem here is that this rule is far too aggressive:

```
body > * {
    display: block;
    height: 100%;
    /* snip */
}
```

It's very common for extensions to add items to the DOM, so it seems fair if websites are a bit more conservative about their CSS. It would be good if this rule could be made more specific to the application so unexpected DOM elements don't cause big problems.

**Comment by edhelas** [comment]
"My extension is breaking websites, please fix the website" :D 
Not sure if this will go in wontfix or actually a bug.
