### ISSUE TITLE
Enhancement: Ability to select one's own status

### ISSUE THREAD

**Issue by Nick-OpusVL** [movim/movim#415]
I like to be able to set my status explicitly to "Away", "Extended Away", "Do Not Disturb" or "Invisible", but haven't found a way to do it in Movim.

It's also good to be able to set a status message to go with them with a reason why one is away/dnd, e.g. 'Out to lunch' or 'Working on project $x', like is possible in Pidgin.

**Comment by edhelas** [comment]
This feature was actually removed a couple of months ago for a lack of usage (~5% of the users).

**Comment by StuartJMackintosh** [comment]
I think this functionality is useful for users who are migrating from other clients that support this feature and expect it to be there. Not having it is a barrier to some of our users (we have migrated about 15 users from  Mattermost and another 15 from Gaim / Pigin on to Movim).

Is there a specific reason why this will cause an issue - does it break something or cause complicated code?

**Comment by kawaii** [comment]
+1 for this being implimented (perhaps you could release it as a patch or 'plugin' file?) again. In a business environment it's nice to be able to set your status to 'busy' or 'working on a project' so that your colleagues are aware you may be concentrating on something before they send you a message that might cause distraction. 🙂

**Comment by edhelas** [comment]
Here we are following the Conversations client that also choose to remove those features as well to keep the UI simple. It's an old feature that wasn't really used anymore and that requires to manually set it several time through the day (people also tend to forget that they were in XA, DND…).What I'd suggest is maybe to turn that into a "mute notification" feature (like on Slack). 

If you close the Movim client, it goes in "away" after 10sec like is it now but you can ask to mute the notifications with a simple checkbox button somewhere (maybe also for a period of time?).

**Comment by kawaii** [comment]
I would support a toggle on/off that sets you into 'busy' (DND) mode and suppresses all notifications until disabled if you'd be willing to consider that instead of the full XEP. 😁

**Comment by PaulGWebster** [comment]
Re bump for this feature
