### ISSUE TITLE
Messages not always sent but disappeared from the text box

### ISSUE THREAD

**Issue by kawaii** [movim/movim#416]
This is quite an odd issue and I can't always reproduce (because it's seemingly random).

Sometimes I will type a message and hit enter, the message will be removed from the textbox but not then appear in the chat. When checking the Prosody log I can't see that it recieved a stanza at all from Movim. Like I said this happens very randomly, maybe once a day but sometimes it can happen twice in a row which is quite annoying. I'm trying to find a way to reproduce but have not managed to do that yet.

**Edit:** Could this be browser related? It's only happened to people in my company that use Firefox so far. The other two people I asked use Chrome and it hasn't happened to them yet.

**Comment by edhelas** [comment]
Hi, thanks for the report! I'm keeping this open because I already experienced similar issues. I'll try to figure this out.

**Comment by edhelas** [comment]
Hey, I made some changes in the code, can you try again now :) ?

**Comment by kawaii** [comment]
Yeah, I'll have some time to test this maybe tomorrow. It's difficult to replicate but I'll try! :)

**Comment by kawaii** [comment]
This appears to have been resolved now, I haven't been able to replicate this after sending 200+ messages. Thanks. 🙂
