### ISSUE TITLE
ProfilePicture not changeable

### ISSUE THREAD

**Issue by ghost** [movim/movim#417]
If I create a new user, he can set a profile picture for himself.
But after that, it's not possible to change it, because Settings > ProfilePictures stucks at "Loading..."
There are no hints in my logs. Any idea I can provide more information?

**Comment by edhelas** [comment]
What server are you using ? Is it possible to get a test account where I can replicate the error ?

**Comment by ghost** [comment]
I'm using ejabberd. And i got a hint:
If i change the user-language back to english the preview-page appears again (instead of only loading...) but when i change the picture, after a while it notifies me "profile picture changed" but nothing happens with the avatar... :-( 
its social.oh-my-goodness.de - just create an testing account ;-)

**Comment by ghost** [comment]
If i change the user-language from german back to english, click on submit and go away to chat, the language changes. Back to configuration i can select another avatar (which not changes). And if i log off and on again, it's in german again(with the old avatar)...

**Comment by ghost** [comment]
okay, the avatar changes, but around 15 minutes after i made the changes... !?

**Comment by ghost** [comment]
the next time i tried it did not change :(

**Comment by edhelas** [comment]
I made some fixes to force the picture reload, can you please try again?

**Comment by ghost** [comment]
Yes, it works immediately now, but only if my user's language is in english.
If my profile is in german the content of the avatar-page is still not shown.
