### ISSUE TITLE
Admin Page doesn't work propperly

### ISSUE THREAD

**Issue by ghost** [movim/movim#418]
I got language "German" at the Admin-Interface. Changing it to English(default) doesn't change anything.
At Installation-Time it worked, thus it is German now.
And if I choose anything in system-logging nothing happens (in movim/logs ?)

**Comment by edhelas** [comment]
Did you restart the daemon ?

**Comment by ghost** [comment]
Yes, i guess i tried. But it's strange. Now (after a few hours) it is in English again, but changing to German and restart the daemon doesn't change the language. 
Is it possible that the changes are commited after a few hours?
Okay, and now there appeared some other logfiles, so it seems to work, but not immediately... !?

**Comment by edhelas** [comment]
Changing the language doesn't enforce it for all the users, Movim still try to detect the browser language of the user on top, maybe it explains the current behavior.

**Comment by ghost** [comment]
Hm, my browser is german, i changed my user's language to spanish, logged out, logged in at admin interface (it's still english, but i changed back to german half an hour ago), changed to french there, restarted the movim-daemon and it's still english.
If i truncate the tables, movim needs some time to get all the posts back to its database (eg. after update). Perhaps the configuration is read the same way?

**Comment by edhelas** [comment]
Hi, any news on this ticket?

**Comment by edhelas** [comment]
Closing the ticket.
