### ISSUE TITLE
Database structure causes issues when changing time zone

### ISSUE THREAD

**Issue by notnamed** [movim/movim#42]
Hello,

I've just installed movim on my server, and I was able to resolve an issue unrelated to the subject with WebSockets (CloudFlare's free account blocks websocket connections, so I turned off CloudFlare protection for the subdomain I'm testing movim on). However, I've run into another issue.

Now that I have WebSockets working, I was playing with the customization settings in the admin panel, and I set the time zone to Los_Angeles/America (which is reversed from the normal format, making it difficult to locate; another minor issue). Once this was done, however, the web interface crashed.

This appears to be because the timezone column on the config table in MySQL is a varchar(16) limit, which America/Los_Angeles (it's in the correct order in the database) exceeds. This causes the column to truncate to America/Los_Ange which the web interface can't handle and it flames out with "oops, an error [...]."

Manually modifying the column type in MySQL brings the WUI back up, but it won't let me modify any of the settings because the database needs to be "upgraded" to the varchar(16). 

The column config.timezone should be set to a more sane limit than varchar(16), or the admin panel should insert shortnames for time zones into the database to prevent truncating.

I hope this is not a duplicate issue; I searched, but I find it somewhat difficult to characterize or explain without many words. My apologies if this is already being addressed!

**Comment by edhelas** [comment]
Thanks for the feedback ! I'll look into this issue asap ;)
