### ISSUE TITLE
Login button not working in embedded browser?

### ISSUE THREAD

**Issue by poVoq** [movim/movim#425]
What determines if the login button is desaturated and doesn't work? From a normal browser (both Chrome & Firefox, also on android) it works fine for my Movim instance, but with an embedded browser (likely a chrome derivate) in an android app (Nextcloud) it does not allow me to log in.

**Comment by edhelas** [comment]
Can you please check the logs of your embedded browser and of the daemon server side.
Also, the Movim Android app is an embedded browser and everything works fine.

**Comment by edhelas** [comment]
Any news on this ticket?

**Comment by poVoq** [comment]
Seems like it was a missing feature in the nextcloud client and should work in a near future version. Lets see.

**Comment by ghost** [comment]
I'm having this problem on SailfishOS default browser.
