### ISSUE TITLE
Adding a publisher to my community group, now I as owner can't post

### ISSUE THREAD

**Issue by Perelandra0x309** [movim/movim#426]
I changed a role of one subscriber to be a publisher, and he successfully published.  But now when I click the pencil icon to write a new post it says "You cannot publish a post on this group". I tried some different Publisher Model settings in the COnfiguration but that didn't help.  I am listed as owner, and I can't seem to add myself again as a publisher as well.

https://nl.movim.eu/?community/pubsub.movim.eu/digital-life

**Comment by Perelandra0x309** [comment]
This seems to have resolved itself. I have been able to post recently.

**Comment by edhelas** [comment]
I'll keep this bug open because I was able to reproduce it one time.

**Comment by edhelas** [comment]
I didn't experienced this issue since then. Closing the ticket.
