### ISSUE TITLE
After klicking on my local pubsub server the system got into an endless loop

### ISSUE THREAD

**Issue by annando** [movim/movim#427]
Under ```/?community``` I simply clicked on my local pubsub server (with zero groups and maybe poorly configured). After this the system jumped to ```/?contact``` and keeps reloading it several times a second. My system is now unusable for me, because I cannot click on any other link, since the system always returns to ```/?contact``` and is keeping that reloaded.

Where is the problem? How can I stop it?

**Comment by edhelas** [comment]
Do you know how to reproduce it? Do you see something in the logs?

**Comment by annando** [comment]
Which loglevel would you recommend? Currently the log is empty.

I can reproduce it all the time by doing the steps I described above. I can imagine that it is some misconfiguration with my XMPP server that causes this.

**Comment by edhelas** [comment]
I'm really sorry by this bug :/
Can you please give me your local pubsub server address to start with? I'll see if I can reproduce this way.

**Comment by annando** [comment]
It is pubsub.pirati.ca

**Comment by edhelas** [comment]
Ok, I can't access it. Or I'll need an pirati.ca XMPP account to reproduce, or you'll have to configure your DNS server to make it available to the others XMPP servers. :)

**Comment by annando** [comment]
Do you know any documentation that could help? I'm having a wildcard entry for *pirati.ca, so the DNS shouldn't be a problem.

**Comment by edhelas** [comment]
Hey, does it still occur?

**Comment by annando** [comment]
I just updated from the git, did the database update, restarted the daemon. Then I clicked on an item and got a similar problem. Means: after I clicked on that single item, the system reload the page multiple times a second.

**Comment by edhelas** [comment]
Then I'll need a pirati.ca account to reproduce it.

**Comment by annando** [comment]
That's not that easy since the credentials are synchronized with my Friendica server - where registrations are closed. I have to check. But I must confess that this runs with very low priority at the moment.

**Comment by edhelas** [comment]
Closing for now. Please comment if you encounter the issue again.

**Comment by annando** [comment]
It is still not working here. Currently I'm avoiding clicking on that link.
