### ISSUE TITLE
problem with the websockets,anyone know ?

### ISSUE THREAD

**Issue by husen13** [movim/movim#430]
i've done all the steps and do it right,and every time,i got some error "movim cannot talk with the server",and when i go to admin page,it says "WebSocket connection error, check if the Movim Daemon is running and is reachable",i am stuck in websocket problem,i am using apache2,any help?

**Comment by BenoitPoulet** [comment]
Hello,

I just solved this issue . Simply put the URL in httpS when starting the daemon :
php daemon.php start --url=https://yoururl/ --port=8080

**Comment by edhelas** [comment]
I've updated the documentation to mention that :)
