### ISSUE TITLE
Cannot log in to Movim

### ISSUE THREAD

**Issue by ghost** [movim/movim#432]
Trying to log in it says I entered incorrect information.
Attempted:
--logging in over Android Movim Client using password saved in my password manager
--logging in over web browser using password saved in password manager
--logging in over Windows 10 Movim App with saved password from password manager
--logging in to movim@conference.movim.eu through Jitsi using stored password from password manager

Each attempt yields a message saying I entered incorrect information. I am sure I did not. Has the movim.eu jabber server been purged of accounts?

Error: Oops. Movim failed to authenticate. You entered incorrect data.

**Comment by edhelas** [comment]
There was a migration yesterday, normally all the accounts were migrated successfully.
Can you please send me an email with your JID and I'll reset your password.

**Comment by XanatosChimera** [comment]
affected jids are xanatos.chimera@movim.eu and irked.hyena@movim.eu.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by edhelas** [comment]
Can you please try again?

**Comment by galuel** [comment]
I have that problem too... doesn't work anymore... cannot connect with galuel@movim.eu, works fine with galuel@jabber.fr

**Comment by edhelas** [comment]
I've done a full reimport. Can I close the ticket?

**Comment by galuel** [comment]
It seems ok to me today...
