### ISSUE TITLE
Cannot connect to movim since yesterday

### ISSUE THREAD

**Issue by galuel** [movim/movim#433]
Since yesterday Movim doesn't accept galuel@movim.eu
Connecting with galuel@jabber.fr works on movim web interface, but cannot connect to either : 

movim@muc.movim.eu
movim@conferencemovim.eu
ffe@conference.movim.eu

Movim answer : 

![capture du 2017-08-14 19-17-59](https://user-images.githubusercontent.com/5245398/29283037-54565e1c-8125-11e7-951f-de7b44c3fd44.png)

**Comment by edhelas** [comment]
Should be fixed by now
