### ISSUE TITLE
Incorrect messages author in MUC

### ISSUE THREAD

**Issue by matlag** [movim/movim#438]
The following screenshots were taken today in the support room of Yunohost.

Sylvanair's posts are missing in Movim, and roger's posts get Sylvanair as author.

![2017-08-23 09_52_28- 265_0 discussions](https://user-images.githubusercontent.com/5243762/29623762-6d88141c-87f5-11e7-98e1-c6072bb64598.png)
![screenshot_20170823-095352](https://user-images.githubusercontent.com/5243762/29623763-6d9401a0-87f5-11e7-960c-76b17d16efc8.png)
![screenshot_20170823-095356](https://user-images.githubusercontent.com/5243762/29623764-6d94e264-87f5-11e7-9281-4ad4b423dbd9.png)

I'm using Yunohost's Movim package (version 0.11).
PHP 5.6.30

See also #437

**Comment by edhelas** [comment]
Merge with #437
