### ISSUE TITLE
Unable to connect via Slack XMPP gateway

### ISSUE THREAD

**Issue by notnamed** [movim/movim#44]
Hello,

I'm trying to hook up Movim to Slack, and I get the following errors (example from xdebug trace):

`[06-Sep-2015 02:19:01 PST8PDT] PHP  13. Evenement\EventEmitter->emit($event = 'data', $arguments = array (0 => 'error xmlns="http://etherx.jabber.org/streams"><connection-timeout xmlns="urn:ietf:params:xml:ns:xmpp-streams"/><text xmlns="urn:ietf:params:xml:ns:xmpp-streams" xml:lang="en">Expected bind and session</text></error>', 1 => class React\Stream\Stream { public $bufferSize = 32768; public $stream = resource(238) of type (stream); protected $readable = TRUE; protected $writable = TRUE; protected $closing = FALSE; protected $loop = class React\EventLoop\StreamSelectLoop { private $nextTickQueue = class React\EventLoop\Tick\NextTickQueue { private $eventLoop = ...; private $queue = class SplQueue { private ${SplDoublyLinkedList}:flags = 4; private ${SplDoublyLinkedList}:dllist = array (...) } }; private $futureTickQueue = class React\EventLoop\Tick\FutureTickQueue { private $eventLoop = ...; private $queue = class SplQueue { private ${SplDoublyLinkedList}:flags = 4; private ${SplDoublyLinkedList}:dllist = array (...) } }; private $timers = class React\EventLoop\Timer\Timers { private $time = 1441531141.6482; private $timers = class SplObjectStorage { private $storage = array (...) }; private $scheduler = class SplPriorityQueue { private $flags = 1; private $isCorrupted = FALSE; private $heap = array (...) } }; private $readStreams = array (1 => resource(1) of type (stream), 238 => resource(238) of type (stream)); private $readListeners = array (1 => array (0 => class React\Stream\Stream { ... }, 1 => 'handleData'), 238 => array (0 => ..., 1 => 'handleData')); private $writeStreams = array (238 => resource(238) of type (stream)); private $writeListeners = array (238 => array (0 => class React\Stream\Buffer { ... }, 1 => 'handleWrite')); private $running = TRUE }; protected $buffer = class React\Stream\Buffer { public $stream = resource(238) of type (stream); public $listening = TRUE; public $softLimit = 2048; private $writable = TRUE; private $loop = class React\EventLoop\StreamSelectLoop { private $nextTickQueue = class React\EventLoop\Tick\NextTickQueue { private $eventLoop = ...; private $queue = class SplQueue { ... } }; private $futureTickQueue = class React\EventLoop\Tick\FutureTickQueue { private $eventLoop = ...; private $queue = class SplQueue { ... } }; private $timers = class React\EventLoop\Timer\Timers { private $time = 1441531141.6482; private $timers = class SplObjectStorage { ... }; private $scheduler = class SplPriorityQueue { ... } }; private $readStreams = array (1 => resource(1) of type (stream), 238 => resource(238) of type (stream)); private $readListeners = array (1 => array (...), 238 => array (...)); private $writeStreams = array (238 => resource(238) of type (stream)); private $writeListeners = array (238 => array (...)); private $running = TRUE }; private $data = '<iq xmlns="jabber:client" type="set" id="1EqAS0" xml:lang=""><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind"><resource>moxlUhxbNl</resource></bind></iq>'; private $lastError = array ('number' => 0, 'message' => '', 'file' => '', 'line' => 0); protected $listeners = array ('error' => array (0 => class Closure { ... }), 'drain' => array (0 => class Closure { ... })) }; protected $listeners = array ('data' => array (0 => class Closure { public $static = array (...); public $parameter = array (...) }), 'error' => array (0 => class Closure { public $static = array (...); public $parameter = array (...) }), 'close' => array (0 => class Closure { public $static = array (...); public $parameter = array (...) })) })) /home/movim/public_html/vendor/react/stream/src/Stream.php:123`

Mozilla seems to have had a similar issue in the Thunderbird XMPP client:

https://bugzilla.mozilla.org/show_bug.cgi?id=1186463

A similar error message occurs in a Perl module, also related to the namespace, although this question is unanswered:

http://stackoverflow.com/questions/31692364/how-can-i-enable-anyeventxmpp-to-connect-to-a-server-using-namespace-prefixes

**Comment by edhelas** [comment]
I'm closing this issue, it seems to be a Slack issue more than a Movim issue
