### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by BenoitPoulet** [movim/movim#440]
Hello,
Is it possible to improve the documentation of the project please ?

I have a fully working Openfire 4 server for years, but :
- in Movim i can't search user to add them to my contact list, i have no button but a label «Cherche de nouveaux amis»
- conferences room are not working (ie : users can't join with their Spark client)
- i found no way to send file to other users 

Regards

**Comment by edhelas** [comment]
Hello, I never tried Movim with Openfire and I'm not planning to do it, sorry about that. But for your 3 questions.
* This is not related to Openfire, this item will have content when you'll start to have some users on your pod, it's purely based on currently connected users on the Movim instance.
* Is this related to Movim ? This seems to appears between your Openfire server and Spark.
* You need to add HTTP Upload support to your Openfire server to do it, see https://community.igniterealtime.org/thread/58280 , Movim relies on the XMPP server feature to handle file upload.

**Comment by BenoitPoulet** [comment]
Hello,

Too bad for the search, it would be nice to be able to use the XMPP search. (Sometime you need to search add add a user who is offline)

For the conferences, i tried with Jitsi, still the same (they got the invitation, but conference not found after trying to join, but i see it in the Openfire admin). Conferences between traditionals XMPP clients are working fine (pidgins, gaijim, ...)

Thanks for the tips pour HTTP upload. Could be a good info to but in the deploy doc :)

**Comment by BenoitPoulet** [comment]
Hello,

Too bad for the search, it would be nice to be able to use the XMPP search. (Sometime you need to search add add a user who is offline)

For the conferences, i tried with Jitsi, still the same (they got the invitation, but conference not found after trying to join, but i see it in the Openfire admin). Conferences between traditionals XMPP clients are working fine (pidgins, gaijim, ...)

Thanks for the tips pour HTTP upload. Could be a good info to but in the deploy doc :)
