### ISSUE TITLE
User email image isn’t created in the cache.

### ISSUE THREAD

**Issue by linkmauve** [movim/movim#441]
How to reproduce:
- Go to the Contacts tab.
- Add a new contact, for example `user@server`.
- See a missing image when clicking on them, pointing to `https://movim.jabberfr.org/cache/user@server_email.png`.
- No file named that way appeared in `/usr/share/webapps/movim/cache/`.

**Comment by linkmauve** [comment]
Also, what is the reason for creating an image and not displaying it as text?

**Comment by edhelas** [comment]
This is actually an old feature that remains, the email address used to be exposed publicly, but it's not the case anymore, I'll remove that.
