### ISSUE TITLE
Don’t store the admin password as a plain unsalted sha1

### ISSUE THREAD

**Issue by linkmauve** [movim/movim#445]
It’s extremely bad practice.

Also sha1 is broken, don’t use it anymore.

**Comment by edhelas** [comment]
PR welcome

**Comment by p0liper** [comment]
Hm... MD5 with salt? xD

**Comment by p0liper** [comment]
Article about it:
https://security.stackexchange.com/questions/211/how-to-securely-hash-passwords

**Comment by kawaii** [comment]
Consider Argon2.
https://wiki.php.net/rfc/argon2_password_hash

**Comment by MarcelWaldvogel** [comment]
Why not use the PHP built-in BCRYPT? See PR #469

**Comment by Ppjet6** [comment]
I would say use PHP **defaults**, as they explicitely say for `PASSWORD_DEFAULT`:
> Note that this constant is designed to change over time as new and stronger algorithms are added to PHP.

Your PR looks like what I had in mind.

**Comment by MarcelWaldvogel** [comment]
@Ppjet6 I had misread that part, thanks for pointing it out. Changed.

**Comment by edhelas** [comment]
PR merged :)
