### ISSUE TITLE
Support XEP-0249 (Direct MUC Invitations)

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#446]
MUC invitations sent by something like:

```
ejabberdctl send_direct_invitation foo conference.example.com none none bar@example.com
```

are not displayed anywhere. According to a chat with @edhelas, there might be an issue with invitations not being handled correctly when the sender is not a fully qualified JID, instead of it being shown in a server chat like motds, etc.

**Comment by Natureshadow** [comment]
The reason is that the following protocol seems to be missing in Movim: https://xmpp.org/extensions/xep-0249.html

**Comment by Natureshadow** [comment]
It seems #188 should have covered this…

**Comment by Natureshadow** [comment]
Sorry to report that, but the commit does a lot of things, except make direct invitations visible ;)… Instead, Movim now opens a single user chat for every entity sending <message> stanzas, except when receiving direct invitations ;).

**Comment by edhelas** [comment]
I made a fix to prevent those events

**Comment by Natureshadow** [comment]
OK!

Still, this does not help with direct invitations. The messages in direct invitations do not have a body or a subject.

I still do not see any of them…
