### ISSUE TITLE
UIs are completely synchronised/remote controlled

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#447]
In this installation here, I see the UIs of two clients connected to the same account being completely synchronised (UI actions done in one client are directly replicated in the other). Is that intended, or is it something wrong with my setup for WebSockets or the like?

My mobile phone, which runs the Android app and is configured to be in Norwegian, even managed to change my desktop client to Norwegian on the fly (language in my settings is still English).

**Comment by edhelas** [comment]
It's a feature, not a bug (actually it's an architectural decision, I can't go away from it without rewriting the all core).

**Comment by matlag** [comment]
You'll find it actually very useful if you jump from one device to another: you're always exactly where you left it, by design!

**Comment by Natureshadow** [comment]
>You'll find it actually very useful if you jump from one device to
>another: you're always exactly where you left it, by design!

Maybe.

Right now it really confuses me, because I do chat with different parties on different devices simultaneously :D.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
