### ISSUE TITLE
Support more than one roster group per contact

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#448]
Contacts can be in more than one roster group, a fact that some modern XMPP clients use for "tagging" contacts. Movim, however, only respects one of the groups (probably the first).

It would be great if Movim could display all groups a contact belongs to, and also turn the group input field in the contact edit view with a checkbox list.

**Comment by edhelas** [comment]
I'm not planning to support more than one group par contact for now.

**Comment by Natureshadow** [comment]
>I'm not planning to support more than one group par contact for now.

Why not, and would you accept someone else doing it?
