### ISSUE TITLE
Error when trying to get a blog entry

### ISSUE THREAD

**Issue by Letterus** [movim/movim#450]
Steps to reproduce on my instance: Click on a group post ("read more").

Error:

`
Sep  2 17:33:15 movim.ERROR: Uncaught Error: Call to undefined method Moxl\Xec\Action\Microblog\CommentsGet::setParentOrigin() in /home/webserver/www/movim/app/widgets/Post/Post.php:137 Stack trace: #0 /home/webserver/www/movim/app/widgets/Post/Post.php(227): Post->requestComments(Object(Modl\ContactPostn)) #1 /home/webserver/www/movim/app/widgets/Post/Post.php(89): Post->preparePost(Object(Modl\ContactPostn)) #2 [internal function]: Post->ajaxGetPost('pubsub.xxx', 'luki-e-v', 'c36421ca-3e6a-4...') #3 /home/webserver/www/movim/src/Movim/Widget/Wrapper.php(145): call_user_func_array(Array, Array) #4 /home/webserver/www/movim/src/Movim/RPC.php(89): Movim\Widget\Wrapper->runWidget('Post', 'ajaxGetPost', Array) #5 /home/webserver/www/movim/linker.php(168): Movim\RPC->handle_json(Object(stdClass)) #6 /home/webserver/www/movim/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(70): {closure}('{"func":"messag...', Object(React\Stream\Stream)) #7 /home/webserver/www/movim/vendor/react/stream/src/Stream.php(173): Evenement\Eve [] []
`

**Comment by edhelas** [comment]
Can you please update your dependencies and try again?

**Comment by Letterus** [comment]
Oh, darn. I should have recognized that myself. Thanks for the hint. It works now - you can close this issue. :-)
