### ISSUE TITLE
(Cosmetic) Long names in chat list overflow

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#452]
If the name of a contact is too long, it is abbreviated in the chat list. However, the icon next to the name (e.g. mobile, web, ...) is not taken into account and overflows into the neighbouring timestamp.

**Comment by edhelas** [comment]
This seems to be caused by a rendering issue on Chrome based browsers.

**Comment by Natureshadow** [comment]
Like, the official Movim client apps ;)?

**Comment by edhelas** [comment]
Yes exactly, the Android and desktop apps are relying on Chrome :)

**Comment by edhelas** [comment]
Closing this ticket.

**Comment by Natureshadow** [comment]
> Closing this ticket.

Umm, because…?
