### ISSUE TITLE
max_items set to 1 everywhere

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#457]
On ejabberd, all microblog pubsub nodes are set to max_items 1. This is the default. While the movim docs suggest changeing max_items_node in ejabberd, this only sets the maximum number clients can configure, but does not impose any default configuration on its own.

The configuration for that would be:

```
  default_node_config:
    max_items: 1000
```

However, XEP-0277 suggests that clients SHOULD set a high number when creating the node. ejabberd treating all nodes without a specification as singleton seems sad, but correct.

My idea would be to check the maximum number on connection and raise all microblog nodes to that number if possible.

**Comment by Natureshadow** [comment]
I updated the docs in the wiki accordingly for now.

**Comment by edhelas** [comment]
I made some changes in Moxl and Movim to enforce max_items to a larger number.

**Comment by Ppjet6** [comment]
I just stumbled upon the same issue. Prosody also defaults to `max_items = 1` for PEP things.

I am not sure what changes were made into Moxl/Movim but my microblog node didn't have any specific value (thus defaulting to 1).
