### ISSUE TITLE
Clarify AGPL status.

### ISSUE THREAD

**Issue by Jookia** [movim/movim#46]
The project says it's under the AGPL but all I can find is that it's under the AGPL, and a copy of the AGPLv3. It doesn't mention which version in the source code, meaning I could use whatever version (AGPLv2 if I wanted.) It'd be great if licensing information is clarified such as AGPL version in the source code itself and whether it's upgradable to a later version. There's also some nonfree files marked as 'All rights reserved' which I assume is a mistake, but means reading them is a bad idea.

**Comment by edhelas** [comment]
This issue was moved to movim/movim#16
