### ISSUE TITLE
PHP Warning:  fread(): Length parameter must be greater than 0

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#461]
`PHP Warning:  fread(): Length parameter must be greater than 0 in /usr/share/webapps/movim/vendor/rain/raintpl/library/Rain/Tpl/Parser.php on line 126`

Running e1bb12c9 (master), php 7.1.9

**Comment by edhelas** [comment]
This was caused when loading a RainTPL view that doesn't exists, I've checked and I cannot find such things. Closing the ticket.
