### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#462]
`PHP Warning:  Invalid argument supplied for foreach() in /usr/share/webapps/movim/app/widgets/CommunityPosts/CommunityPosts.php on line 171`

Running e1bb12c9 (master), php 7.1.9 and prosody b69b40a828fd (trunk)

**Comment by edhelas** [comment]
This has been fixed already.
https://github.com/movim/movim/commit/305c10ee532d0fc69707f5064bd895804f731959
