### ISSUE TITLE
Paperclip disappears in personal chat room

### ISSUE THREAD

**Issue by Perelandra0x309** [movim/movim#463]
When you enter an existing personal chat after being out of it, the paper clip appears at the bottom next to the text entry box.  But when you start typing it changes to the airplane, and the paper clip does not appear again unless you leave the chat and then return again.

**Comment by edhelas** [comment]
That's by design :) You can clear your message to make it appear again.

**Comment by Perelandra0x309** [comment]
Ah, you have to press Delete after sending a message to get the paper clip back.  Not intuitive.  Maybe better to have both icons always show?

**Comment by edhelas** [comment]
Oh indeed, that's a bug, once the file is sent it should go back to the other icon.

**Comment by edhelas** [comment]
No actually I was right :D The icon behavior is fine.

**Comment by Perelandra0x309** [comment]
Really?  Because this is what I am seeing:
Go into a chat and you see a paper clip.
Start typing a message and the paperclip change to a paper airplane?
Hit enter and message is sent.  Airplane icon remains
Hit delete to get the paperclip icon back (even though there is nothing in the text box to delete)

**Comment by Perelandra0x309** [comment]
Test- push comment to chat room
