### ISSUE TITLE
mud tries to connect to the db even when not asked

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#465]
Some nit pick. I am setting up movim on a different host, and haven't setup much yet.

I just ran `mud --help` and got a PDOException because pdo_pgsql wasn't enabled. This could probably be avoided until later in the script. It's not really needed for the help.

**Comment by edhelas** [comment]
Well mud actually relies on the same Bootstrap as the Daemon so use the same dependencies.
Putting this as a wontfix :)

**Comment by p0liper** [comment]
For 'help' command database is not required. So, 'mud' can just return output and no more. =)
