### ISSUE TITLE
Own messages appear on the left in MUCs

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#466]
The messages I send to chatrooms appear on the same side as everybody else, istr it was different in previous versions.

movim: 5ac5dd1f (master)
php: 7.1.9

**Comment by edhelas** [comment]
No it was not different, previously it was all text aligned to the left. It's just not consistent with single chats :p

**Comment by Ppjet6** [comment]
Right, I do not use chatrooms from movim often so I was a bit confused.

Could this be made consistent then? Is there a reason for it being the way it is?
