### ISSUE TITLE
Daemon won't start without set admin credentials

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#470]
```
php[4758]: Please set a username and password for the admin panel (https://<movim_instance>/?admin)
php[4758]: To set those credentials run
php[4758]: php mud.php config --username=USERNAME --password=PASSWORD
```

## Steps to reproduce

1. log into the db and `UPDATE config SET username = '', password = '';`
2. start the daemon

## What happens

Daemon doesn't start and give the above error

## What I expect

Daemon starts.

As far as I understand the daemon doesn't need these credentials to run, it'll compare them against whatever is in the db when the admin panel is accessed. This shouldn't block running it.
I am not sure if this was intended, maybe just give a warning at launch?

EDIT: I am not sure how I got into state 1. in the first place, still investigating, this error is weird nonetheless.

**Comment by poVoq** [comment]
Ah... is it possible that this was just introduced recently? Because since a few days my dev-system refuses to run properly after an Movim update and I did not have time to investigate it.
