### ISSUE TITLE
request {Add Wiki}

### ISSUE THREAD

**Issue by Madji** [movim/movim#471]
Need full manual for full installation and configuration from setup web movim xmpp server . for example for me the problem was to raise apache2 not work. nginx I don't know. I want to raise to feel to participate . take the example of wiki: slack / mattermost, and others. everything from ideology to advertising is registered.

**Comment by Ppjet6** [comment]
The wiki is available here: https://github.com/movim/movim/wiki

**Comment by Madji** [comment]
it's not wiki. this clippings configs. !

**Comment by Ppjet6** [comment]
I'm sorry I am not sure I understand what you are saying. It would be nice if you could try and detail what you think can be improved in the wiki.

You can also join the chatroom to discuss about it, join `movim@conference.movim.eu` with an XMPP client, (e.g., https://nl.movim.eu)
