### ISSUE TITLE
Cannot use Movim chatroom anymore

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#472]
I am trying to send messages to the Movim chatroom. All that happens ist my message is rendered with sender name "null", and 1:1 chat from movim@conference.movim.eu opens.

Other MUCs work flawlessly.

**Comment by Natureshadow** [comment]
I obvioulsy do not receive messages either (I do not receive anything concerning this issue from the bot…). Last time I received a message was 16:02 CEST today.

**Comment by edhelas** [comment]
What pod are you using ? If it's your, did you pulled the latest version, updated the dependencies and the database ?

**Comment by Natureshadow** [comment]
>What pod are you using ? If it's your, did you pulled the latest
>version, updated the dependencies and the database ?

Three days ago, yes.

Why would you expect the chatroom to break without updating? Isn't it a MUC just like any other?

**Comment by edhelas** [comment]
Is it possible to know which commit you actually have deployed on your server?

**Comment by Natureshadow** [comment]
2c92535557757bd778b4a196e737d630354b21d9

**Comment by Natureshadow** [comment]
Updated to 3cce0327cd32b454d80917cc635a5afb4f3c8971 now, updated the DB and restarted… either the update or the restart fixed it. I still have no idea why one MUC should fail and others not, though.

**Comment by edhelas** [comment]
Closing the ticket then :)
