### ISSUE TITLE
Add a sound theme to Movim 

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#473]
Nice to have, gives a bit more feedback that everything is running correctly, and I suppose that's also the usual behavior in most applications.

**Comment by poVoq** [comment]
Might include some usable stuff:
https://opengameart.org/content/doorbell-ring
https://opengameart.org/content/rotating-bicycle-bell
https://opengameart.org/content/sound-effects-sfx009

**Comment by edhelas** [comment]
As I'm not planning to work on that soon I'm closing this ticket.
I'd prefer to have a unify and distinctive sound theme from Movim if it's made one day.
