### ISSUE TITLE
Add call button to chat

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#475]
The Call button is really well hidden in the user profile view. It looks like really everyone seems to expect it in the chat window - I really have to explain everyone who wants to call me where to find it. The most natural flow seems to be that people chat and want to "upgrade" to video chat from there.

**Comment by edhelas** [comment]
This is because the Video-Conference is still in a beta state, I'm currently running tests to see if I can move it to a stable version and finish the integration in the UI.

**Comment by Natureshadow** [comment]
I can only say that it works pretty much all the time. Only issue is that Firefox seems to be very flaky in regards of opening and using popup windows, but that seems to be a Firefox issue. The video feature itself works really well, even under the most awkward of configurations.
