### ISSUE TITLE
Sidebar menu and profile for public feed (twitter like)?

### ISSUE THREAD

**Issue by poVoq** [movim/movim#478]
Is there an option for public feeds (such as: https://nl.movim.eu/?node/pubsub.movim.eu/Movim ) to have a side-bar with links and other suggested feeds on the server or something like that?

Some optional profile info/picture would be also nice.

Not asking to clone twitter directly, but something to make the public feeds a bit nicer and more micro-blogging like would be nice.

Alternatively, is there an external interface (like qvitter for gnu-social or something like that), that could be configured to read Movim's RSS feed?

**Comment by edhelas** [comment]
It's not something that I'm planning to put in the UI for now.
