### ISSUE TITLE
OTR support

### ISSUE THREAD

**Issue by marxistvegan** [movim/movim#48]
I see this in the source code for otr.js but not sure about the application, how is this activated?

**Comment by edhelas** [comment]
This is no planned in the short term view. There's a BoutySource ticket here : https://www.bountysource.com/issues/10091409-implement-otr-in-the-chat-page

Implementing OTR in Movim will require a lot of development to do it "properly", Movim is not only a XMPP JS client but need to keep in sync with the Web server, which is a bit tricky with OTR.

**Comment by edhelas** [comment]
I'm closing the ticket for now.
