### ISSUE TITLE
Lookup stun SRV record

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#480]
I have observed this behavior in gajim, it looks for a stun server on the xmpp domain.
It would be nice to prepend this server to the list of hard-coded public servers.

https://github.com/movim/movim/blob/21a39b59cd1e4e105fd8ec8930049df3618bc8da/app/widgets/Visio/visio.js#L141-L161

Documentation:
https://wiki.xmpp.org/web/SRV_Records#STUN_SRV_records

**Comment by Natureshadow** [comment]
+1, also for privacy reasons.

**Comment by Natureshadow** [comment]
Also, please discover TURN servers provided by the XMPP server while at it ☺

**Comment by Neustradamus** [comment]
@edhelas: Good job!
