### ISSUE TITLE
Reset notifications in MUCs when messages are from another resource

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#481]
## Steps to reproduce

- Use clientX to send messages to a MUC
- Login to movim with the same account, to the chat page

## What happens

I am being notified of a number of new messages in that MUC.

## What is expected

No notifications for these messages.

Ideally maybe reset the notification counter when messages from any resource are sent? This is also valid for normal 'chat' messages.
For MUC this happens both when movim is online and I use another client, _and_ also when it is not and messages are fetched via MAM.

**Comment by poVoq** [comment]
I had the same issue with JSXC MUC ( https://github.com/jsxc/jsxc/issues/577 ) and the developers replied that this is how MUCs work (e.g. no clear user/resource recognition?). It might be possible to work around that, but it seems like there is no standardized way?

**Comment by Ppjet6** [comment]
I just [commented in that thread](https://github.com/jsxc/jsxc/issues/577#issuecomment-333804669). It should be possible in semi-anonymous MUCs if a user sticks with the same nickname, otherwise it is not possible indeed. There should be no problem in non-anonymous MUCs though.

**Comment by edhelas** [comment]
Movim doesn't notify (anymore?) messages coming from another resource from the same JID in a MUC.
