### ISSUE TITLE
Allow sending messages to non-contacts

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#482]
At the moment it is not possible to send a message without adding the JID to the roster. The contact doesn't have to accept though and I can then go to chats and start talking.

Please make it so I don't have to add these junk entries in my roster.

My use case is for contacts behind gateways, like biboumi (IRC). If I want to talk to foo I have to add it in the roster as `foo%irc.server.org@biboumi.component`, and I know I will never get subscription presences from them, because it makes no sense due to the nature of the IRC protocol.

As for the UI, maybe allow people to enter JIDs in the search input when looking for contacts?

**Comment by edhelas** [comment]
@Ppjet6 please, be a bit more careful when opening tickets, it's not like this bugtracker have 500 pages of tickets open.
Closing because duplicate with #357
