### ISSUE TITLE
Messages get visually duplicated until websockets is reloaded

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#483]
## Steps to reproduce

- Send or receive a message, in chat or groupchat

## What happens

Message gets displayed multiple times.

## What is expected

Message gets displayed once.

## Version

Movim: `568e2d17`
Php: `7.1.9`

I have been using movim extensively this weekend due to being on a high latency / restricted connection with only 80/443 opened, and not always having a laptop opened. I have seen this happen in the past at home in normal conditions.

I am sorry I don't have much details, and I don't know how to reproduce. It did happen 3-4 times over the weekend.

When the above happens, the following messages also get duplicated. Reloading the page usually fixes the issue.

**Comment by MRZA-MRZA** [comment]
It happens if connection is unstable (e. g. on mobile network).

**Comment by edhelas** [comment]
Hello, did you experienced this bug recently? Some changes were made on the connection layer and messages handling in the project (released with the 0.12).

**Comment by MRZA-MRZA** [comment]
I still see message duplication when I'm on mobile connection.
