### ISSUE TITLE
Community articles gets updated to new ones from feed while reading them.

### ISSUE THREAD

**Issue by ThurahT** [movim/movim#486]
Reading an article is all fun and interesting until you get a new one in the feed and the one you're reading gets promptly updated to the new one. I am subscribed to twelve feeds/communities and sometimes the updates comes very rapidly.

Opening articles in a new tab solves it though. But only for one tab at a time though. If you try to open several tabs from different articles all new tabs will have the same content. The last opened tab. Maybe that is a separate bug or related to this one.

Browser: FF 52 ESR. 
uBlockO Standard lists + block third party scripts and frames. Youtube excluded.

**Comment by edhelas** [comment]
You should logout and login back again to make it work :)

**Comment by ThurahT** [comment]
This was a triumph. 
I'm making a note here: Huge Sucess.
