### ISSUE TITLE
Support vCard search (vjud)

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#489]
Title says it all ;).

**Comment by edhelas** [comment]
I'm not planning to implement XEP-0055 in Movim as it has a pretty bad search mechanism (no real-time completion, case handling…).

**Comment by Natureshadow** [comment]
>I'm not planning to implement XEP-0055 in Movim as it has a pretty bad
>search mechanism (no real-time completion, case handling…).

So, what else would you consider in order to find users?
