### ISSUE TITLE
Add mechanism to contact support / report abuse

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#490]
Probably one of XEPs 0161, 0236 and/or 0377.

Additionally, a link to a help website should be configurable and clearly visible in the main menu.

**Comment by Ppjet6** [comment]
Maybe also worth having a look at [0157 - Contact Addresses for XMPP Services](https://xmpp.org/extensions/xep-0157.html)

**Comment by Ppjet6** [comment]
Also one thing, I like the idea, but I fear the end-user will not be aware that the movim admin and the xmpp admin may not be the same person.

**Comment by edhelas** [comment]
I'm planning to implement XEP-0157 in Movim

**Comment by edhelas** [comment]
For this ticket I'm planning to get and store the Contact Addresses in the DB (if they are available, see XEP-0157).

For the Pubsub services (Communities Servers) the information will be displayed in the right column on the Community Server general page.

For the MUC and Chat they will be available trough the "menu" (to right corner).

For both:
- If the link is a JID, the user will be able to start a conversation (or join a MUC in case of a ?join)
- If it's a mail, a mailto link will be created
- If it's a link, open the link

For the root domain the information will also be available in the Help page in a new "Service Contact" section.
 
See https://docs.ejabberd.im/admin/configuration/#mod-disco for ejabberd configuration.

**Comment by Natureshadow** [comment]
The "report abuse" menu only works with xmpp: URLs. Other link types simply reload the page and do nothing.
