### ISSUE TITLE
Improve feedback when closing a call

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#493]
## Steps to reproduce

- Start a call, [..]
- Hang up

## What happens

Pop-up disappears.

## What do you expect

It would be nice to have a bit more feedback saying the call has been correctly terminated, visually and/or via audio. My first reaction seeing this was "what just happened? Where is the popup?".

**Comment by linkmauve** [comment]
It’s even worse when the other party hung first, the popup just disappears like that.
