### ISSUE TITLE
Make it more obvious that one has to click on the phone icon to start the call

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#494]
## Steps to reproduce

- Go to contact page
- Click on "call"

## What happens

Pop-up appears, and the phone icon at the bottom is still.

## What I would expect

One could expect the call to start directly like said in #474, but this is not happening so it would be nice to have a bit more indication as to what to do next.

Maybe make the green icon move? But that could confusing ("Is the call already started?")
Or have a sentence saying "Start the call by pressing the button [..]", with a fancy arrow pointing to the call button (if possible, should be a bit more explicit without)

**Comment by edhelas** [comment]
Merge with a similar ticket for the same person #474.

**Comment by Ppjet6** [comment]
This two tickets are not similar, this one is a consequence of the other, (see that I cited it even). I'm sorry but no it is not obvious that one has to click on that phone the first time. It would be great to have an answer to this.
