### ISSUE TITLE
Find a way to better integrate video calls with the chat

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#496]
## Steps to reproduce

- Click "call" on contact page

## What happens

Video chat happens in a pop-up separated from the Movim tab.

## What I expect

I am not sure if/how this can be done, but I would like to be able to have both chat _and_ video available at the same time. By default have the video in the same tab maybe? And be able to expand that into a popup still with chat _and_ video.

It would be nice to try and gather comments about this. Maybe people have ideas.

**Comment by edhelas** [comment]
No, impossible, Movim reload the page when navigating, the whole purpose of a popup is to prevent the call to be killed when doing that.
