### ISSUE TITLE
Implement jingle-ft

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#497]
Movim supports http-upload. This require among other things, some setup server-side that might not always be done, and prevents the user from being able to do any file transfer. This also require the use of http, and http-upload components do not always server on standard ports. I have seen more than once people using it on 5281. Jingle could also negociate http of course, but is not limited to it.

**Comment by edhelas** [comment]
For the moment I'm not planning to implement Jingle-File transfer no, if you want to add it, please submit a PR.
