### ISSUE TITLE
Private MUC messages not shown anywhere

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#499]
When someone who is not on the roster sends a message, Movim receives it (which can be seen because the unread messages counter is increased), but the conversation can be seen nowhere.

Adding the person to the roster immediately makes the messages visible.

It seems that there needs to be at least some hint on the contact's existence - a simple "from" or "to" subscription on the roster is enough for Movim to make the messages visible.

**Comment by edhelas** [comment]
Receiving messages from a freshly connected account works in Movim, are you sure that the JID was not special (from Biboumi for example ?)

**Comment by Natureshadow** [comment]
Yes, I also saw it working (as you know).

The contacts in question here are indeed Biboumi contacts, but I cannot imagine what difference this could make.

Maybe it's not specifically Biboumi, but something about the messages sent by Biboumi that is different.

**Comment by Natureshadow** [comment]
I think I found the bug, and it's something entirely different:

The real issue is that Movim has no way to show messages from MUC resources (private messages in MUCs). I jsut verified that in a real Jabber MUC - someone sent me a private message, and it did not show up anywhere. Clicking the speech bubble in the occupants list opened the conversation with the message.

Biboumi also sends priavte messages as a MUC resource from the first channel both users are in, iff they have a common channel. Whether this is a bug or a feature in Biboumi is not quite clear to me, but yeah, the real issue is that Movim does not show MUC private messages.

**Comment by Natureshadow** [comment]
Reading the code of the Message model, it seems that a mic#user message gets the JID of the room plus the user name as resource. So in turn, the message would be linked to the user room@muc.service, because messages in 1:1 conversations are grouped by the bare JID. This makes it somewhat difficult to open a separate conversation for such a case.

**Comment by Natureshadow** [comment]
Uh oh?

One of the two MUC private conversations I tried just popped up as a seperate conversation, but the second didn't.

Now I am entirely confused :)!

**Comment by edhelas** [comment]
Got any news regarding this issue ? I was not able to reproduce it recently.

**Comment by Natureshadow** [comment]
Issue seems to be gone.
