### ISSUE TITLE
Tab color not changing when talks happen in the chatroom

### ISSUE THREAD

**Issue by Insoleet** [movim/movim#50]
Hello,

On firefox, with Movim tab in pinned mode, when people are discussing in the chatroom, the tab is not changing color. It does on jappix or in gmail chatrooms.

**Comment by edhelas** [comment]
This will be a bit tricky to do with Movim as it should keep the state even if the page is reloaded. Jappix and Gmail doesn't have this issue.
I'll put this as a request for feature.

**Comment by edhelas** [comment]
This issue was moved to movim/movim#17

**Comment by edhelas** [comment]
I'm closing this issue because Movim now notify silently if there was some new messages in connected chatrooms.
