### ISSUE TITLE
Pending muc messages are not received when mam enabled in a room

### ISSUE THREAD

**Issue by srgcdev** [movim/movim#500]
Hello,

When  I join a muc on movim where mam is enabled, pending messages are not received, only I receive messages that are sent when I'm online.

Testing in:
- A room with mam enabled in conference.movim.eu using a movim.eu account on https://nl.movim.eu instance of movim
- A room with mam enabled on my own xmpp server that is using ejabberd 17.09 using https://nl.movim.eu/ instance of movim

In the logs I can see that the mam query is using mam:1 and I can see the results messages but the client doesn't show those messages.

Thanks in advance.

**Comment by edhelas** [comment]
![capture du 2017-10-12 08-33-31](https://user-images.githubusercontent.com/3726886/31482311-12a0436c-af28-11e7-9d0a-fad4836949d9.png)

This has been took 5min ago on the movim@conference.movim.eu channel using the current (trunk) version of Movim. The room is hosted on a ejabberd 17.09. This is from a blank account that never connected to the chatroom before and the database was clear of any previous messages.

In the console I received.

```xml
<message to="gnap@movim.eu/1260751124166575368740018" from="movim@conference.movim.eu">
    <result xmlns="urn:xmpp:mam:1" id="1507789473008638" queryid="pMV2wfSO0Ipp">
        <forwarded xmlns="urn:xmpp:forward:0">
            <message xmlns="jabber:client" xml:lang="en" from="movim@conference.movim.eu/Miho" type="groupchat">
                <archived xmlns="urn:xmpp:mam:tmp" by="movim@conference.movim.eu" id="1507789473008638" />
                <stanza-id xmlns="urn:xmpp:sid:0" by="movim@conference.movim.eu" id="1507789473008638" />
                <delay xmlns="urn:xmpp:delay" from="movim@conference.movim.eu" stamp="2017-10-12T06:24:33.008638Z" />
                <body>[movim] @srgcdev opened issue #500: Pending muc messages are not received when mam enabled in a room https://github.com/movim/movim/issues/500</body>
            </message>
            <delay xmlns="urn:xmpp:delay" from="conference.movim.eu" stamp="2017-10-12T06:24:33.008638Z" />
        </forwarded>
    </result>
</message>
```

**Comment by srgcdev** [comment]
@edhelas movim@conference.movim.eu room doesn't have mam enabled.
