### ISSUE TITLE
vendor/autoload.php file not found

### ISSUE THREAD

**Issue by godwiniheuwa** [movim/movim#508]
Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\movim-master\index.php on line 42

**Comment by pztrn** [comment]
Have you performed dependencies installation with Composer as per https://github.com/movim/movim/wiki/Install-Movim?

**Comment by edhelas** [comment]
This seems to be cause by that indeed. Closing.
