### ISSUE TITLE
Allow configuration, log, data, and user file/directory paths to be passed as configuration

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#509]
At the moment movim assumes there are folders in the same folder as the daemon or linker. It would help packaging if we were allowed to specify somehow where we want these files or folders to be.

In other words, be able to do `daemon.php --config /etc/movim/config` and then specify paths in the config file, or directly `daemon.php --config /etc/foo/bar --cache /var/cache/movim [..]`.

Folders or files that would be useful to have configurable are:
- `config/db.inc.php`
- `cache`
- `log`
- `users`

**Comment by edhelas** [comment]
Not a huge priority for the upcoming months, a PR is welcome.

**Comment by Natureshadow** [comment]
Hmm, for Debian, I will just go with some symlinks.

**Comment by edhelas** [comment]
Is it still a "must have" ? symlinks are not fine for those usages ? I'd prefer to not add unnecessary configurations/parameters if the thing can be "fixed" using a simple trick like symlinks.

**Comment by Natureshadow** [comment]
Having these directories in the document root is still a critical design flaw, in any case. Do with that whatever you want ☺.
