### ISSUE TITLE
Define a coding style and enforce it (for example with phpcs)

### ISSUE THREAD

**Issue by ghost** [movim/movim#512]
Hi.

It seems that there is no explicit coding style. It could be useful to explicitly define one and enforce it with a tool. For example, it can be done with [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) that is [available in Debian as "php-codesniffer"](https://packages.debian.org/stable/php-codesniffer).

Regards.

**Comment by edhelas** [comment]
Thanks for providing me the tool name! Will help to solve #382.

**Comment by edhelas** [comment]
Closing the ticket as this work is actually never fully done. I'm trying to keep the warnings low.
