### ISSUE TITLE
Add CSS animated emojis ☺

### ISSUE THREAD

**Issue by subpub** [movim/movim#514]
You know this would be cool ;)

**code:** https://github.com/robertsLando/animated-emojy

##### PREVIEW: http://htmlpreview.github.io/?https://github.com/robertsLando/animated-emojy/blob/master/index.html

![CSS animated emoji](https://camo.githubusercontent.com/372b529dc7b2f8d4aa9377154475bad3923e5330/68747470733a2f2f63646e2e6472696262626c652e636f6d2f75736572732f34333736322f73637265656e73686f74732f313932353730382f656d6f6a69732e676966)

**Comment by edhelas** [comment]
No sorry, this is not planned for now.
