### ISSUE TITLE
basedir problems because .dir-locals.el is a file and not a folder

### ISSUE THREAD

**Issue by annando** [movim/movim#515]
I'm constantly getting this error:
```
movim.ERROR: file_exists(): open_basedir restriction in effect. File(/path/to/movim/htdocs/app/widgets/.dir-locals.el/locales.ini) is not within the allowed path(s): (/usr/share/php/:/path/to/movim/htdocs/:/path/to/movim/tmp/:/path/to/movim/logs/:/tmp/:/path/to/movim/) [] []
```
This is caused, because ".dir-locals.el" is a file and not a folder:
https://github.com/movim/movim/tree/master/app/widgets

**Comment by edhelas** [comment]
When are you getting that, under which circumstances ?

**Comment by annando** [comment]
In the PHP error log file. And I'm getting this all the time, every few minutes. But I deactivated Movim now, since it opened up as many TCP connections that the Apache stopped serving pages.
