### ISSUE TITLE
Movim doesn't inform user about server restart/disconnection in a remote MUC.

### ISSUE THREAD

**Issue by MRZA-MRZA** [movim/movim#517]
If a user joins a remote MUC and remote server restarts or temporarily disconnects, chat stalls and Movim neither disconnects user from that MUC nor throw a warning about server restart/disconnection.
It's related to https://github.com/movim/movim/issues/229
It's possible to leave disconnected room and rejoin but Movim doesn't do it automatically leaving user unaware of stalled chats.

**Comment by edhelas** [comment]
@linkmauve is there something I can catch somehow to fire that?

**Comment by edhelas** [comment]
I've asked that in the XSF chatroom, except doing some weird tricks to detect that possible disconnection there's not much to do. I'm closing it as a wontfix.
