### ISSUE TITLE
Popup "public profil" at all connexion

### ISSUE THREAD

**Issue by Zatalyz** [movim/movim#519]
Hello,
When I'm connect to movim web interface ( https://fr.movim.eu ), I have always a pop-up to say me "do you want to make your profile public" and "you can receive notification". I said yes, again, at each connection ; I go in configuration too, but my preferences seems not saved. 

Probably a cookie (I drop cookies when I close my webbrowser) but if yes, why don't saved preference with account ? I want adjust this only one time...

====
French translate, because I speak  french better, and I know there are french dev here ;)

Lorsque je me connecte à movim via l'interface web ( https://fr.movim.eu ), j'ai à chaque fois la popup me demandant si je veux passer mon profil en public et si je veux recevoir les notifications. Je dis oui à chaque fois, j'ai aussi essayé via la configuration de sauver ça, mais j'ai tout de même la demande qui reviens sans cesse. Je ne sais pas comment l'information est stockée, si c'est un cookie ça viens de mes paramètres un peu parano mais... ce serait de toute façon plus agréable que ce genre de préférences soit stocké et enregistré via le compte de façon définitive.

**Comment by edhelas** [comment]
Are you using the anonymous mode of your browser to connect ? If yes that maybe explains why.
But I'm still planning to improve that in the upcoming release.
