### ISSUE TITLE
[Android] Bold font for cyrillic letters

### ISSUE THREAD

**Issue by MRZA-MRZA** [movim/movim#524]
In Android app Cyrillic symbols are bold in comparison with Latin symbols.
![screenshot_20171029-111128](https://user-images.githubusercontent.com/3092263/32142784-16444b96-bcaf-11e7-87e3-51e6b02887dd.png)

**Comment by edhelas** [comment]
I don't really know how this is happening, maybe you can help me to figure it out?

**Comment by MRZA-MRZA** [comment]
It also happens in mobile web interface. Which font is used for mobile interface?

**Comment by MRZA-MRZA** [comment]
Quick debugging showed that Clear Sans Medium is used for Cyrillic letters instead of Open Sans font.
