### ISSUE TITLE
MD5 used in model Privacy

### ISSUE THREAD

**Issue by ghost** [movim/movim#526]
Hi.

`app/models/privacy/Privacy.php` uses MD5. I do' not know what his exact purpose is, but MD5 and privacy are not friends anymore. If there is no problem in this case, it should be documented why.
https://en.wikipedia.org/wiki/MD5#Security
Moreover, using only 5 bytes seem strange.

Regards.

**Comment by ghost** [comment]
I do not understand how https://github.com/movim/movim/commit/2b560853c9181638f0f4d33add6e53224cf162fe is supposed to have fixed the issue.

**Comment by edhelas** [comment]
MD5 has been simply removed, we don't need it anymore.
