### ISSUE TITLE
"Chats" tab does not recognise open chats

### ISSUE THREAD

**Issue by tbeitter** [movim/movim#53]
If I do not have a open/existing multi user chat there is a message "No chats yet..." on the "Chats" tab. This message does not disappear even if I have open chats there.

![2015-10-11-134654_1915x971_scrot](https://cloud.githubusercontent.com/assets/756334/10416656/fae397b4-701e-11e5-99c3-65a3246e23cd.png)

**Comment by edhelas** [comment]
This is displayed when you don't have a one-to-one chat open.

**Comment by tbeitter** [comment]
you're right, my fault :)
