### ISSUE TITLE
Not working with X-Content-Type-Options "nosniff"

### ISSUE THREAD

**Issue by gllmhyt** [movim/movim#533]
If I enable the X-Content-Type-Options "nosniff" in my HTTP headers (a quite common security flag), it's not working anymore because there are some loaded scripts that are not JavaScript MIME types, e.g. `<script src="https://pod.domain.name/?system"></script>` I think.

```js
var BASE_HOST = 'pod.domain.name';
var ERROR_URI = 'https://pod.domain.name/?disconnect';
var SECURE_WEBSOCKET = true;
var SMALL_PICTURE_LIMIT = 320000;
```
Leading to this error:

```
ReferenceError: SECURE_WEBSOCKET is not defined
```

Is it a way to fix this and make it possible to add the header to my whole webserver stack?

**Comment by edhelas** [comment]
This has been solve in the trunk normally, it will come with the 0.12.1 that will be released soon.

**Comment by gllmhyt** [comment]
Can you tell me which commit solves it?
I'll wait for the release, thanks.

**Comment by edhelas** [comment]
0.12.1 has been released, should be fixed by now :)

**Comment by gllmhyt** [comment]
Amazing, thank you!
