### ISSUE TITLE
Messages counter incorrect in rooms when autojoin or manual join

### ISSUE THREAD

**Issue by srgcdev** [movim/movim#536]
Hello,

I noticed that when I start movim and I autojoin some rooms, the messages counter of each room are not correct. If I leave movim and I enter again, the messages counter are the same again despite I previously have read all the messages and there aren't any new messages on these rooms.

Thanks.

**Comment by Ppjet6** [comment]
I can also reproduce this on master.

**Comment by edhelas** [comment]
This is actually happening on MUC that doesn't handle MAM yet, Movim is then clearing and retreiving the chat history "the old way" (see https://xmpp.org/extensions/xep-0045.html#enter-managehistory) and there's no proper way to know if those received messages are new or were already read afaik.

A close issue was resolved with the commit mentioned just before.
