### ISSUE TITLE
MAM pagination for mucs

### ISSUE THREAD

**Issue by srgcdev** [movim/movim#537]
Hello,

Could you implement mam pagination for mucs? I have to leave the room and join it again a few times to get all the pending messages on the rooms.

Thanks in advance.

**Comment by edhelas** [comment]
That is indeed a bug.

**Comment by lovetox** [comment]
should not be that hard to fix if pagination works on 1:1 or?

**Comment by edhelas** [comment]
MAM was reworked since this ticket and pagination is working fine now. I'm closing this ticket.
Feel free to comment if you have further issues :)
