### ISSUE TITLE
Basic functionality still missing at 1024x768px

### ISSUE THREAD

**Issue by mirabilos** [movim/movim#538]
Followup for https://github.com/movim/movim/issues/520

The new expander works, but **there’s still no logout button** (basic functionality). I also think some settings are missing; can someone with a larger screen please compare the two views side-by-side?

**Comment by Natureshadow** [comment]
The logout button is actually there (on the right next to your avatar and name), but it is not clickable because it is covered by the link to the profile page.

**Comment by edhelas** [comment]
![menu](https://user-images.githubusercontent.com/3726886/32840377-be11a01a-ca17-11e7-90a9-4b2e424b67d9.png)

**Comment by edhelas** [comment]
@Natureshadow indeed the logout link is broken, thanks for noticing that, I'll try to fix it asap

**Comment by mirabilos** [comment]
Dominik George dixit:

>The logout button is actually there (on the right next to your avatar
>and name), but it is not clickable because it is covered by the link
>to the profile page.

Ah, so that *is* supposed to be a logout button. I’d almost have
guessed it (despite lacking any description) but as it went to the
profile page it could be interpreted as an icon for the profile
page too. (Icons/Emôji are just that ambiguous.)

**Comment by Natureshadow** [comment]
> >The logout button is actually there (on the right next to your avatar
> >and name), but it is not clickable because it is covered by the link
> >to the profile page.
> 
> Ah, so that *is* supposed to be a logout button. I’d almost have
> guessed it (despite lacking any description) but as it went to the
> profile page it could be interpreted as an icon for the profile
> page too. (Icons/Emôji are just that ambiguous.)

Well, it does have a description… but as another element overlays it,
you don't get to see it, currently ;).
