### ISSUE TITLE
Allow basic configuration of MAM

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#539]
Please support basic configuration (enabling/disabling) of MAM. It is an important privacy feature. Users must be able to decide whether they want their messages to be stored persistently server-side or not.

Please also add an indicator to the chat view showing whether the other party has MAM activated (as I recall, the MAM protocol defines how to do that).

**Comment by mitchellurgero** [comment]
Question: if you set MAM in Pidgin, wouldn't that carry over to Movim anyway? That could be one work around.

**Comment by Natureshadow** [comment]
> Question: if you set MAM in Pidgin, wouldn't that carry over to Movim
> anyway? That could be one work around.

Yes it would.

But I am not looking for a workaround, but helping create a chat
solution everyone can use. Free services will not come forward if I have
to tell users to install eight XMPP clients to get four features working
correctly ☺!

**Comment by mitchellurgero** [comment]
Not arguing with that logic lol ;)

Was merely suggesting a work around until a solution was put in place :D

**Comment by edhelas** [comment]
More info there as a note https://xmpp.org/extensions/xep-0313.html#config
