### ISSUE TITLE
chat overrides any other movim tab

### ISSUE THREAD

**Issue by ThurahT** [movim/movim#541]
When having several opened tabs in movim, like different news articles or contacts and you click on chat from the menu in one of them, every opened tab becomes the chat window. Expected behavior would be that only the tab where you click chat opens the chat and the others remain where they are.

**Comment by edhelas** [comment]
The architecture doesn't allow Movim to do that unfortunately. Sorry.

**Comment by ThurahT** [comment]
I see, no worries. I'll try to remember it in the future.
