### ISSUE TITLE
php 5.x support broken

### ISSUE THREAD

**Issue by lazyadmin111** [movim/movim#543]
I wanted to update on my debian jessie box. The git pull worked, but updating the dependencies broke everything. They require now php-7 even thought eh docs still say they are fine with php5. Seems no one tested this.

**Comment by edhelas** [comment]
Can you please paste here the error that you have?

**Comment by edhelas** [comment]
Is it possible to have updates on this ticket please?

**Comment by src386** [comment]
Installation request for evenement/evenement v3.0.1 -> satisfiable by evenement/evenement[v3.0.1].
    evenement/evenement v3.0.1 requires php >=7.0 -> your PHP version (5.6.30) does not satisfy that requirement.
