### ISSUE TITLE
AGPLv3-mandated download link missing

### ISSUE THREAD

**Issue by mirabilos** [movim/movim#544]
https://commu.teckids.org/movim/?help#about_tab mentions that Movim is under GNU AGPLv3(only, why not or-later?), but lacks the required download link for the complete(!) corresponding(!) source code.

“Corresponding” is defined by the GNU AGPLv3 to include the exact sources, recursively, that make up the exact version of the service running at any given time. “Complete” means it also includes the build system/scripts used, and (!) the complete, corresponding source code for all dependencies, even if those themselves are not published under the GNU AGPL.

**Comment by edhelas** [comment]
I bet that this can be fixed with a little PR to put the link of the Github repo :) ?

**Comment by mirabilos** [comment]
Of course it can’t, because it needs the sources of the **exact** version that’s running. Sysadmins may use locally patched versions with extra fixes, and whatnot.

Basically, you need to, at build time, create a tarball of the sources *as patched by the one compiling them*, and copy that into the installation directory. (The Debian package would require access to the source package, but it could also pick up the debian/ subdirectory during build.)

Additionally, you need to aggregate the equivalent source tarballs of *all* recursive dependencies, even those that don’t (need to) provide those because they’re not using the AGPL.

**Comment by mitchellurgero** [comment]
Why not change to a different license? why AGPLv3?

**Comment by mirabilos** [comment]
(At least) one of the dependencies uses AGPLv3(plus? only?) so Movim has to use it as well.

**Comment by mitchellurgero** [comment]
But that means AGPLv3 is only used for that dependency right? but movim can still be say as an example MIT?

**Comment by mirabilos** [comment]
No.

Well, long story: Yes, but Movim still would have to have the complete corresponding source of itself *and* all dependencies, recursively, on the webinterface.

**Comment by mitchellurgero** [comment]
So just having a link to the github wouldn't work in the case of someone modifying the source?

**Comment by mirabilos** [comment]
Exactly. The Movim project “probably” could say they can’t be bothered, but then *every* admin has to install that link.

If a security incident happens, you want to be able to patch *quickly*, without having to invent a major change to the build system first, so it’s best to have this prepared ahead of time and working.

Yes, licence compliance is hard, but it’s nevertheless necessary. (Thankfully I got my employer to change away from AGPL for one project, when I pointed this out to them. But another one, Apache 2-licenced, Java/Javascript with a handful of dependencies, still has a `LICENCE` plaintext(!) file of about 500K, plus the GNU LibreJS-compatible JS licencing information. It also ships its own source tarball, created at compilation time, now (linked from the licence overview page), even if none of the licences directly mandate it, because it makes overall compliance _simpler_.)

**Comment by mirabilos** [comment]
Hm, actually, linking to the github source wouldn’t be the **complete** corresponding source code. For example, the complete **corresponding** sources for everything listed in Movim’s `composer.json` are missing from that repository.

Also, for GPLv3 and AGPLv3, the build system is considered part of the “complete corresponding”, so you’d also need the sources for PHP-Composer “unless it’s a system library”, but it’s better to include it.

**Comment by mitchellurgero** [comment]
Then at this point I would say

- Movim master branch has a link to the original github

- Admins that modify the project in some way to suit their needs are then responsible for updating the link as required by the license.

**Comment by mitchellurgero** [comment]
>Hm, actually, linking to the github source wouldn’t be the complete corresponding source code. For example, the complete corresponding sources for everything listed in Movim’s composer.json are missing from that repository.

However the link still exists in composer to get the source for each composer project, so I'd say that is sufficient.

**Comment by mirabilos** [comment]
> However the link still exists in composer to get the source for each composer project, so I'd say that is sufficient.

It’s not: how does *Movim* _guarantee_ that, for at least three years after any given Movim release, that source will stay available? (This, again, is actually something Movim could get sued over.)

**Comment by mitchellurgero** [comment]
>(This, again, is actually something Movim could get sued over.)

But:

> to also make available the "Corresponding Source" of the work if you distribute object code of the modified or unmodified work

Which in this case we are NOT distributing but rather having to download via composer. So Movim should be in the clear.

**Comment by Natureshadow** [comment]
@mirabilos, Please read the paragraph in question, number 13 of the AGPL, correctly:

> Notwithstanding any other provision of this License, **if you modify the Program**, your modified version must prominently offer all users interacting with it remotely through a computer network (if your version supports such interaction) an opportunity to receive the Corresponding Source of your version by providing access to the Corresponding Source from a network server at no charge, through some standard or customary means of facilitating copying of software.

Thus, it is entirely up to the Movim project as licensor of the unmodified code if and how they provide the source code in the application. Anyone running an instance only needs to add a download possibility if they *modify* the code on their instance.

I actually discussed this with a FOSS lawyer concerning one of my own AGPL projects.

**Comment by Natureshadow** [comment]
It would, nonetheless, be kind of any upstream to reserve a place for such a link somewhere, so others can replace it with a link to their own version if they modify it. This would also help Debian or other distributions, that might patch hteir packaged version of Movim, and they could very easily replace the link with their own then.

But it is nice to have at best, not a licence issue for Movim.

**Comment by mitchellurgero** [comment]
I agree with you, I am just saying Movim does not need to link to it's dependencies' sources and code so long as that is unmodified, movim's license/source still needs to be given however.

**Comment by Natureshadow** [comment]
@mitchellurgero I was actually talking to @mirabilos ;)

**Comment by mirabilos** [comment]
@Natureshadow sure, you’re right… if Movim is developed by a single entity and never accepts any contributions, *or* if it uses a CLA, or the rights to the contributions are licenced under CC0.

**Comment by Natureshadow** [comment]
> @Natureshadow sure, you’re right… if Movim is developed by a single
> entity and never accepts any contributions, *or* if it uses a CLA, or
> the rights to the contributions are licenced under CC0.

It would be very helpful if you quoted the "corresponding source" (pun
intended), like I did, to support your claims - or even better, clarify the situation together with someone who knows the legal issues for sure, write someone up with supporting sources, and use that as a basis for discussion, instead of splitting the same lengthy discussion across any number of bug trackers on the internet ☺!

**Comment by edhelas** [comment]
Closing the ticket.
