### ISSUE TITLE
OpenID Support?

### ISSUE THREAD

**Issue by mitchellurgero** [movim/movim#552]
Just an idea that ran through my head to start getting Movim and GNUSocial federating together.
OpenID login for Movim.

This would require OpenID support for ejabberd/Prosody, however it would still need an interface in the client (hence movim would also need to support it.).
Have no idea how to implement this, but if this gets enough responses, I can begin work on getting ejabberd to work with OpenID logins.
The benefits to this would be that your GNUSocial/Yahoo/Other OpenID site logins would work in movim/xmpp. Allowing 1 login for multiple services. 
What do you all think?

**Comment by edhelas** [comment]
This is an idea, but I prefer to talk about it on the chatroom better than here. I prefer to keep here only tickets that are related to bugs or small (short-mid term) improvements.
