### ISSUE TITLE
Add multiple images to posts

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#554]
It would be very good if we could add several images to a post, not only one (oer an image *and* a link). I don't know for sure what XMPP microblogging defines protocol-wise, but if the protocol does not allow adding multiple images, an upload form that just uploads an image and adds it to the post body as Markdown would be great.

**Comment by edhelas** [comment]
Hey, you can indeed add several images in Markdown using the specific tag for that. For now I'm not planning to offer the support for it (as it complexity a bit the UI) but it's possible to do it in the protocol ;)

**Comment by Natureshadow** [comment]
> Hey, you can indeed add several images in Markdown using the specific tag for that.

I know. But I need an external hosting service for that.

**Comment by thundergreen** [comment]
I agree. Uploading the pics to httpserver to link them after is a bit complicated for normal users

**Comment by edhelas** [comment]
I'm closing this ticket as this is the kind of feature that I might add myself one day if I have the will to, but that is not planned for now.

**Comment by edhelas** [comment]
As said just above. I had some time to fully rewrite the Post publication widget and refresh the UI. The feature is now in master and will then be naturally shipped with the next release ;)
