### ISSUE TITLE
Additional group functionality based on data_forms and pubsub?

### ISSUE THREAD

**Issue by poVoq** [movim/movim#557]
The Salut à Toi project recently implemented an interesting issue tracker on top of XMPP with data_forms and pubsub, see:

https://www.goffi.org/blog/goffi/9555cc02-6a87-4b6b-af85-20f1c0736722

While I don't really think Movim also needs a XMPP based issue tracker, the overall idea is kind of intriguing for additional group features... maybe making appointments or having a small shared tasklist etc.

Any thoughts on this? I assume that most building blocks for this are already in place for Movim?

**Comment by edhelas** [comment]
Sorry, definitly not planned to implement that in the project for now.
