### ISSUE TITLE
Can't see browser suggestions for search input field

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#558]
## Steps to reproduce

- Open Search
- Manually click on the field to see suggestions offered by the browser (taken from history/other websites)

## What happens

The input field being positionned where it is (bottom of the viewport), I can barely see what appears.

## What's expected

Not sure. Movim doesn't POST here so the browser won't remember them, which means that feature of the browser is not so useful in the first place, maybe find a way to deactivate it.

A quick hack would be to change the input name from `keyword`, which is rather common, to something else. Maybe there's a way to tell the browser to not show these in the first place, (for this field).

**Comment by edhelas** [comment]
Is it possible to get a screenshot?

**Comment by Ppjet6** [comment]
![movim-input](https://user-images.githubusercontent.com/138302/34618484-cf3ab3bc-f236-11e7-8e87-f13cedc4f0da.png)
