### ISSUE TITLE
Search keybinding conflicts with Firefox tab mute binding

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#560]
## Steps to reproduce

- In Firefox Nightly (59.0a1), use ^M (Ctrl-M) to open the Search box

## What happens

Search box opens, and tab gets muted.

## What's expected

Search box opens, nothing else.

This could be particularly annoying when audio calls get announced.
I don't have a real solution to propose. Change the key binding, or stop using it?

**Comment by edhelas** [comment]
Here we'll have to find another shortcut, but which one ?

**Comment by edhelas** [comment]
For the moment I've kept the same shortcut but disabled it for muting the tab.

**Comment by edhelas** [comment]
Closing the issue
