### ISSUE TITLE
"Like" button uncertain status

### ISSUE THREAD

**Issue by matlag** [movim/movim#561]
Hi!

I tried to like the article about Movim 0.13 today.
Since nothing seemed to happen, I assumed something went wrong (mis-clicked or network issue), so I tried to press the button again.

Now I can see 2 likes from me.

Not that it doesn't deserve 2 likes, but I believe it would be a sane behavior not to allow anyone to spam the comments with hundreds or thousands of l"like".

Movim version 0.12 on Yunohost as of 2017-12-25

So, what i suggest:
-Change of icon appearance/small animation to indicate the "button pressed" even is taken in account" on the page side (ie: not requiring connection to happen).
-Top the number of "like" recorded to 1

**Comment by edhelas** [comment]
Unfortunately I cannot enforce that on the protocol level, so I've just disabled the button once it's pressed.

**Comment by matlag** [comment]
That will do as well!
