### ISSUE TITLE
Display pubsub server name before URI

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#564]
In `/?community#communities_servers_tab`, if available, it may be more intuitive for the user to read the pubsub serve name "Fancy Pubsub Server" (what's available in the identity), instead of the URI "pubsub.fancy.server".

**Comment by edhelas** [comment]
This will only be fixed when I'll be able to customize the name of the Pubsub services in ejabberd (already doable in Prosody/Metronome).

**Comment by edhelas** [comment]
Still not fixed in ejabberd, I might do directly vcard support for services one day. But not for now.
