### ISSUE TITLE
More RSS feed options

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#567]
A (hopefully relatively simple) feature request concerning the public web feeds / RSS feeds:

It would be great to have some more possibilities to get a set of posts as a website or RSS feed. What would be helpful is the following:

 * Website/feed for a hashtag
 * Website/feed for alls posts with a certain hash tag by a certain user

I would like to add my Movim microblog to some blog planets, some of which require to only add a subcategory of a blog that deals with the topic of the planet.

**Comment by poVoq** [comment]
There are some feed readers that allow filtering RSS feeds though.

But basically all this would need is enable RSS feeds for Tags no?

**Comment by Natureshadow** [comment]
Hi,

> But basically all this would need is enable RSS feeds for Tags no?

That, plus combining two criterions (user AND tag).

-nik

**Comment by edhelas** [comment]
This is not planed for the moment.

**Comment by edhelas** [comment]
Closing the ticket as no further work is planned for now on this ticket.
