### ISSUE TITLE
Stuck in a redirect loop

### ISSUE THREAD

**Issue by ghost** [movim/movim#568]
You can witness the issue at https://movim.thecrimsontint.com

**Comment by oappiah** [comment]
Check your webserver (nginx) configuration.
or do you have any warnings/errors in movim logs?

**Comment by ghost** [comment]
Obvious comment is obvious :)

Nginx error logs only complain about robots.txt 404'ing.

Nothing in php-fpm logs either.

Only thing in php.log from movim is:

```
[31-Dec-2017 03:03:36 UTC] PHP Notice:  Undefined property: React\ZMQ\SocketWrapper::$buffer in /data/movim/vendor/react/zmq/src/SocketWrapper.php on line 127
[31-Dec-2017 03:03:36 UTC] PHP Notice:  Undefined property: React\ZMQ\SocketWrapper::$buffer in /data/movim/vendor/react/zmq/src/SocketWrapper.php on line 127
```

My /etc/nginx/sites-available/movim.thecrimsontint.com.conf:

```
server {
  listen       *:443 ssl http2;

  server_name  movim.thecrimsontint.com www.movim.thecrimsontint.com;

  ssl on;

  ssl_certificate           /data/shared/letsencrypt/live/thecrimsontint.com/fullchain.pem;
  ssl_certificate_key       /data/shared/letsencrypt/live/thecrimsontint.com/privkey.pem;
  ssl_session_cache         shared:SSL:10m;
  ssl_session_timeout       5m;
  ssl_session_tickets       off;
  ssl_protocols             TLSv1.2;
  ssl_ciphers               EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH;
  ssl_prefer_server_ciphers on;
  ssl_stapling              on;

  resolver                   10.136.55.144 10.136.56.21;
  gzip_types text/css text/xml text/javascript application/javascript application/x-javascript application/json application/xml application/xml+rss application/xhtml+xml application/x-font-ttf application/x-font-opentype image/svg+xml image/x-icon;
  index  index.php index.html;

  access_log            /data/shared/nginx/log/movim_access_log combined;
  error_log             /data/shared/nginx/log/movim_error_log;
  root /data/movim;
  add_header              "Strict-Transport-Security" "max-age=63072000; includeSubDomains; preload";
  add_header              "X-Content-Type-Options" "nosniff";
  add_header              "X-Frame-Options" "DENY";

  location ~ \.php$ {
    root          /data/movim;
    include       /etc/nginx/fastcgi.conf;

    fastcgi_pass  127.0.0.1:9000;
    fastcgi_index index.php;
  }

  location ~ ^/ws/ {
    proxy_pass            http://10.136.43.113:8080;
    proxy_read_timeout    90s;
    proxy_connect_timeout 90s;
    proxy_redirect        off;
    proxy_http_version    1.1;
    proxy_set_header      Upgrade $http_upgrade;
    proxy_set_header      Connection "Upgrade";
    proxy_set_header      Host $host;
    proxy_set_header      X-Real-IP $remote_addr;
    proxy_set_header      X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header      X-Forwarded-Proto https;
  }
  real_ip_header X-Forwarded-For;
  real_ip_recursive on;
  resolver_timeout 5s;
  set_real_ip_from 0.0.0.0/0;
  ssl_ecdh_curve secp384r1;
  ssl_session_cache shared:SSL:10m;
}
```

My /etc/opt/rh/rh-php71/php-fpm.d/www.conf:

```
[www]

user = nginx
group = nginx

listen = 127.0.0.1:9000

listen.allowed_clients = 127.0.0.1

pm = dynamic

pm.max_children = 50

pm.start_servers = 5

pm.min_spare_servers = 5

pm.max_spare_servers = 35






slowlog = /var/opt/rh/rh-php71/log/php-fpm/www-slow.log

request_terminate_timeout = 86400


php_admin_value[error_log] = /var/opt/rh/rh-php71/log/php-fpm/www-error.log
php_admin_flag[log_errors] = on

php_value[session.save_handler] = memcached
php_value[session.save_path]    = 'app-01.mgmt.thecrimsontint.com:11211,app-02.mgmt.thecrimsontint.com:11211,app-03.mgmt.thecrimsontint.com:11211'
php_value[soap.wsdl_cache_dir]  = /var/opt/rh/rh-php71/lib/php/wsdlcache
php_value[memcached.sess_consistent_hash] = 1
php_value[memcached.sess_binary] = 1
php_value[memcached.sess_prefix] = 'session.'
php_value[memcached.sess_remove_failed] = 1
php_value[memcached.sess_number_of_replicas] = 2
```

**Comment by ghost** [comment]
Any ideas?  This is very annoying, and I don't see that I did anything wrong.

**Comment by edhelas** [comment]
I cannot reproduce the issue on my side. It seems to be a configuration mistake on your instance but I have no clue at the moment where it's coming.

**Comment by ghost** [comment]
[movim.tar.gz](https://github.com/movim/movim/files/1607487/movim.tar.gz)

I've attached a gzipped tarball of my entire nginx config, along with the following files:

```
/etc/default/movim
/etc/opt/rh/rh-php71/php.ini
/etc/opt/rh/rh-php71/php-fpm.conf
/etc/opt/rh/rh-php71/php-fpm.d/www.conf
/data/movim/config/db.inc.php
```

Here are my package versions on this CentOS 7.4 server.

```
[root@app-01 ~]# rpm -qa rh-php71-php-fpm
rh-php71-php-fpm-7.1.8-1.el7.x86_64
[root@app-01 ~]# rpm -qa nginx
nginx-1.13.8-1.el7_4.ngx.x86_64
[root@app-01 ~]# uname -a
Linux app-01.thecrimsontint.com 3.10.0-693.11.1.el7.x86_64 #1 SMP Mon Dec 4 23:52:40 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@app-01 ~]# cat /etc/*release
CentOS Linux release 7.4.1708 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.4.1708 (Core)
CentOS Linux release 7.4.1708 (Core)
[root@app-01 ~]#
```

 @edhelas is there any more you need?

**Comment by oappiah** [comment]
@jas612 I'm also unable to reproduce,
I'm suspecting your nginx configuration.

Look at this example https://github.com/movim/movim_docker/blob/master/nginx/config/default
Can you try this? (http , unsecure)
Define a root location and take the movim part out of php location....

I tried things with your approach but I couldn't get nginx to run then.

**Comment by ghost** [comment]
Your suspicion appears correct... but I'm not seeing which part of my nginx config is doing it.

**Comment by ghost** [comment]
(it works with that barebones http setup)

**Comment by edhelas** [comment]
So is it fixed :) ?

**Comment by ghost** [comment]
Not completely.

It works if I point it at one server, with this exact config.  However, I have a load-balanced set of servers on Digitalocean.  My vhost config is now nearly exactly the same as the docker config, except for IPs, and I reconfigured my Digitalocean load-balancer to terminate SSL at that load balancer and then forward requests via HTTP to servers, just so I could make the configs match.  Still no joy:

```
upstream ws {
  server 10.136.43.113:8080;
}

server {
  listen [::]:80;
  listen 80;
  server_name movim.thecrimsontint.com www.movim.thecrimsontint.com;

  index index.php;
  root /data/movim;

  charset utf-8;

  location = /favicon.ico { log_not_found off; access_log off; }
  location = /robots.txt  { log_not_found off; access_log off; }

  location ~ /.well-known {
      allow all;
  }

  location / {
      try_files $uri $uri/ /index.php$is_args$args;
  }

  location ~ [^/]\.php(/|$) {

      if ($request_uri ~ "\/\?infos") {
        return 403;
      }

      fastcgi_split_path_info ^(.+?\.php)(/.*)$;
      fastcgi_pass 127.0.0.1:9000;
      fastcgi_index index.php;
      fastcgi_intercept_errors on;
      fastcgi_request_buffering off;
      fastcgi_param REMOTE_USER $remote_user;
      fastcgi_param PATH_INFO $fastcgi_path_info;
      fastcgi_param SCRIPT_FILENAME /data/movim$fastcgi_script_name;
      include fastcgi_params;
  }

  location /ws/ {
      proxy_pass http://ws;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto http;
      proxy_redirect off;
      proxy_read_timeout 14400s;
      proxy_send_timeout 14400s;
  }

  location ~ /\.ht { deny all; }
  location ^~ /log/ { return 403; }
  location ^~ /config/ { return 403; }
  location ^~ /?infos { return 403; }
}
```

If I point at single servers, I don't redirect.  If I point at load-balancer, infinite redirect loop.  Instead of dwelling on nginx, could you perhaps account for what issues javascript redirects on the login page?  My guess is a header is not making it, in either the request or response, that your login process somehow needs.

This is the redirect loop my browser says is happening:

Status Code	URL	IP	Page Type	Redirect Type	Redirect URL
200	https://movim.thecrimsontint.com/?login	138.197.229.43	client_redirect	javascript	https://movim.thecrimsontint.com/?login
200	https://movim.thecrimsontint.com/?login	138.197.229.43	client_redirect	javascript	https://movim.thecrimsontint.com/?disconnect
302	https://movim.thecrimsontint.com/?disconnect	138.197.229.43	server_redirect	temporary	https://movim.thecrimsontint.com/?login
200	https://movim.thecrimsontint.com/?login	138.197.229.43	client_redirect	javascript	https://movim.thecrimsontint.com/?login
200	https://movim.thecrimsontint.com/?login	138.197.229.43	client_redirect	javascript	https://movim.thecrimsontint.com/?login
200	https://movim.thecrimsontint.com/?login	138.197.229.43	client_redirect	javascript	https://movim.thecrimsontint.com/?login
200	https://movim.thecrimsontint.com/?login	138.197.229.43	client_redirect	javascript	https://movim.thecrimsontint.com/?login
200	https://movim.thecrimsontint.com/?login	138.197.229.43	client_redirect	javascript	https://movim.thecrimsontint.com/?login
200	https://movim.thecrimsontint.com/?login	138.197.229.43	client_redirect	javascript	https://movim.thecrimsontint.com/?login
200	https://movim.thecrimsontint.com/?login	138.197.229.43	normal	none	none

It says javascript issued the redirect, not the webserver.

**Comment by oappiah** [comment]
Not sure if you can load balance movim in this way...

Can you provide some configuration details of this load balancer?

**Comment by ghost** [comment]
Managed offering from Digitalocean, L7 LB, SSL termination is at the load-balancer, and communicating back to my droplets on HTTP.  Also, to amend the last comment, it does in fact work through the load balancer.... if I just do HTTP.  The second I try to make the movim URL https is when it all goes to shit.... behind this load-balancer, or not.

**Comment by oappiah** [comment]
Even trying to reach your admin page redirects you back to the login page.
( https://movim.thecrimsontint.com/?admin )
It keeps going to disconnect

Can you enable more logs in movim using the cli
"php mud.php help config"

**Comment by ghost** [comment]
which level?

**Comment by ghost** [comment]
guessed 3, started getting this from journalctl -f -u movim

```
Jan 07 06:18:32 app-01.thecrimsontint.com bash[31546]: sh: line 0: exec: php: not found
Jan 07 06:18:32 app-01.thecrimsontint.com bash[31546]: 5e71q80krzpGx8GjGo3O6QRqOylUiSob : linker killed
Jan 07 06:18:32 app-01.thecrimsontint.com bash[31546]: 5e71q80krzpGx8GjGo3O6QRqOylUiSob : 492 deconnected
Jan 07 06:18:33 app-01.thecrimsontint.com bash[31546]: BoPG0wm3Mvb7HyrHfMgCJa7T2gkSqaO9 : 505 connected
```

**Comment by ghost** [comment]
Doing this solved the problem:

ln -s /opt/rh/rh-php71/root/usr/bin/php /usr/bin/php

Now, I find this odd because, when I started the movim systemd unit, I sourced the SCLo PHP 7.1 environment:

```
[root@app-01 ~]# systemctl cat movim
# /etc/systemd/system/movim.service
[Unit]
Description=Movim Daemon
After=network.target nginx.service rh-php71-php-fpm.service

[Service]
User=nginx
Group=nginx
WorkingDirectory=/data/movim
EnvironmentFile=/etc/default/movim
ExecStartPre=/bin/bash -c "source /etc/profile.d/rh-php71.sh; php mud.php db --set"
ExecStart=/bin/bash -c "source /etc/profile.d/rh-php71.sh; php daemon.php start --url=${MOVIM_URL} --port=${MOVIM_PORT} --interface=${MOVIM_INTERFACE} --verbose --debug"
Restart=always

[Install]
WantedBy=multi-user.target
[root@app-01 ~]
```

I'm guessing the daemon instantiates shell commands and doesn't source my environment after start?  If so, any way to tell it to do so, or where the alternate php path is, without an ugly symlink?

**Comment by oappiah** [comment]
OK. so the issue is not in Movim, (or nginx) ,but your PHP Environment(s).

Maybe you can handle those issues in the file you created : 
"EnvironmentFile=/etc/default/movim"

**Comment by ghost** [comment]
ah yeah I guess I could.... yeah, this is resolved, thanks folks.

**Comment by xtf0** [comment]
What are the contents of that environment file?
