### ISSUE TITLE
Public discover communities page?

### ISSUE THREAD

**Issue by poVoq** [movim/movim#569]
I really like how the discover communities page highlights the latest posts and would also like to enable it for outside visitors, similar to how the community feeds themselves are publicly available.

Is there somewhere an undocumented link that allows to do that which I could include in my main website?

**Comment by edhelas** [comment]
Theres the ?home page for that maybe?

**Comment by poVoq** [comment]
Ah, as I expected a hidden link :)

That one is doing for now, but if you would enable a optional card based view for it, similar to the discover comunities page (i.e. smaller previews in a grid view), that would be much apprechiated.

It would be also nice if the ?home page would make the different pubsub communities somehow a bit more visible. Maybe a color code or some more prominent link? 

Also, right now the pubsub link is displayed but you can't click it to reach a view of that particular group of communities.

Thanks a lot for looking into this!

**Comment by Letterus** [comment]
Hm, is there a way to remove posts shown there (?home)? When I unsubscribe a community on my pod (v0.13) it will be removed from my news feed but is still shown on the public ?home page.

**Comment by edhelas** [comment]
Did you understood the aim of that page? It doesn't reflect your subscriptions. This is a public home page.

**Comment by Letterus** [comment]
Yeah, of course. But how to remove posts or communities from there?

**Comment by edhelas** [comment]
You don't remove them directly. Those are cached articles, you have to remove the original ones and Movim will clear them from the cache.

**Comment by Letterus** [comment]
Ok, thank you. Can I trigger reloading of the cache? Or should I just empty the cache directory of movim?

**Comment by edhelas** [comment]
No you can't trigger reloading the cache. You have to be connected to do so and Movim will do it for you. Those articles are saved into the DB, it's not about the /cache directory.

**Comment by Letterus** [comment]
Ok, technically that's good. :) But it would be great if I somehow could manage which posts are shown there. Especially because I'm responsible for the public content beeing shown on that page regarding German law.

**Comment by edhelas** [comment]
I was expecting that, for now because I don't want to start a whole configuration panel I'll simply remove that feature.

**Comment by Letterus** [comment]
Hm, ok. ;)

**Comment by poVoq** [comment]
Hey, this is not how this should have worked out :( What about people not falling under German law like that? And besided, any kind of public posting would be effected not only the ?home page...
