### ISSUE TITLE
only one chatroom can be joined at once

### ISSUE THREAD

**Issue by sezuan** [movim/movim#57]
Steps to duplicate (tested with: https://github.com/edhelas/movim/commit/f2033b67aa97374c79d6ee17d24cc28efb7629d2):
1. Create two chatroom bookmarks.
2. Join first -> History appears. You can proberly write messages
3. Join seconds -> History doesn't appear. Messages you write seems to be written by the muc jid.
4. Close both chatrooms.
5. Join seconds -> History appears. You can proberly write messages
6. Join first -> History doesn't appear. Messages you write seems to be written by the muc jid.

**Comment by edhelas** [comment]
I can't reproduce this issue on my side.

**Comment by sezuan** [comment]
When I try to enter the secon MUC I get the following log entries:

```
[2015-10-25 19:37:39] moxl.DEBUG: Handler : Memory instance found for J38Mst [] []
[2015-10-25 19:37:39] moxl.DEBUG: Handler : J38Mst - errorServiceUnavailable [] []
```

"J38Mst" is changing with each click.

**Comment by edhelas** [comment]
Can you please provide the URI of a buggy chatroom ? :)

**Comment by sezuan** [comment]
Awesome. Some update (movim, ejabberd, whatever) fixed it.
