### ISSUE TITLE
Custom registration redirection link?

### ISSUE THREAD

**Issue by poVoq** [movim/movim#570]
Would it be possible configure the registration link in the settings? 
I have my ejabberd set up to only accept accounts from an external source (a website were users can register), and the movim internal registration link is a bit confusing because of that.

Thanks.

**Comment by poVoq** [comment]
Ejabberd supports getting user accounts out of an external database, or in my case from a Nextcloud installation. I have disabled registration via the internal system.

So registering an XMPP account through clients or Movim does not work.

I know this isn't really a general issue, but would be a small nice to have feature to allow redirecting to a custom URL for registration.

**Comment by Natureshadow** [comment]
Look at the redirect option of ejabberd's mod_register. Movim supports it.

(Available since ejabberd 17.09)

**Comment by poVoq** [comment]
ok thanks for the hint, this can be closed then I guess.

For reference: https://docs.ejabberd.im/admin/configuration/#mod-register
