### ISSUE TITLE
Can't get to persons profile from chatroom

### ISSUE THREAD

**Issue by KillyMXI** [movim/movim#571]
First, I think I've seen profile icons along with chat icons in users list:
https://i.imgur.com/SRPiign.png
That might be my memory playing on me. In any case it might be nice thing to have, instead of going to personal chat just to get to "See the profile" link.

Then, after clicking "See the profile" link in personal chat, I get either of those:
![](https://i.imgur.com/316H7N9.png)
![](https://i.imgur.com/4L90DEL.png)
Profile info in the right block might be loaded or not.
On the left it shows conference address (instead of persons nickname) and infinite spinner.

Seems like the separation between actual Jabber profile and conference profile is what makes this happen. In case of social network, this separation looks just weird.

**Comment by edhelas** [comment]
This is because you're trying to get profiles from anonymous chatrooms.

**Comment by KillyMXI** [comment]
The problem is, movim trying to show something, even though it's impossible
by design. Either there should be no profile link in this case, or it
should clearly state that this is an anonymous profile.

If there is a possibility for non-anonymous chat rooms - it would fit
better into the social network concept.

**Comment by edhelas** [comment]
So basically the idea would be to forbid the users to see the Contact page for anonymous MUC contacts, seems fair to me.

**Comment by KillyMXI** [comment]
Yep. As a first step, stop doing what's impossible.

But, thinking further, I don't ever want to hide my public profile when using movim. This kind of artificial walls is not good for UX. I don't see how anonymity by default any helpful - more of opposite.

When trying to create a room in movim, it looks like it can only create anonymous room.
Not sure how common non-anonymous rooms are and how many bugs may occur as the result of using them. Every piece of software is defaulted to anonymous, it seems. I don't ever know how non-anonymous rooms are created.

If there is any other way to let movim know that I wan't my movim profile to be visible - it would be nice to have.
Otherwise it would mean you can't create an integrated user experience and will have two completely separate systems under one roof, essentially.
