### ISSUE TITLE
Own posts in conference look no different from others

### ISSUE THREAD

**Issue by KillyMXI** [movim/movim#572]
![](https://i.imgur.com/rAlXKV7.png)
"killy" on screenshot is me.

This happens in any conference once I open it with other jabber client (Conversations for example.)
Before that my posts were aligned right and had my avatar.

**Comment by Natureshadow** [comment]
I only see this behaviour in biboumi conferences.

**Comment by edhelas** [comment]
What XMPP server, Movim pod are you using?

**Comment by KillyMXI** [comment]
movim.eu account and feder8.ru pod, if I got it right.

**Comment by MRZA-MRZA** [comment]
I have exactly the same issue. Sometimes I see my messages on the right even if I use another client and sometimes my messages appear on the left (and without avatar) if I send it using Movim.

**Comment by edhelas** [comment]
For this case I'd need more precision how to reproduce exactly the issue.

**Comment by KillyMXI** [comment]
- movim.eu account logged in in movim client and other client (Miranda-NG in this case. works the same for Conversations);
- chatroom is opened in movim client only;
- once I join the same chatroom in other client, this thing happens (have to switch somewhere and back to chatroom to observe effect);
- to get it back to initial state, I have to leave room from everything and reopen it from movim.

![](https://i.imgur.com/vKkHyia.gif)

**Comment by edhelas** [comment]
Is this still happening, there was a big refactoring done on how messages are handled in Movim.

**Comment by KillyMXI** [comment]
![movim_test](https://user-images.githubusercontent.com/13851064/41722260-96824c66-7570-11e8-9008-ac6d4f80ab92.png)
Still the same. After connecting from other client, this thing happens.
(movim account, nl.movim.eu web client, other client is Miranda-NG)

**Comment by edhelas** [comment]
I made changes regarding how presences are handled in Chatrooms. It seems to solve this issue. Can you please check again?

**Comment by Natureshadow** [comment]
Problem seems gone, my own messages in Biboumi MUCs are now rendered correctly.

**Comment by edhelas** [comment]
Great :)

**Comment by KillyMXI** [comment]
Hey! You're too fast, closing the issue before my answer.
I still can reproduce this issue. But on top of that I have some connection issues when switching between chat rooms.

**Comment by KillyMXI** [comment]
Another check.

If I'm connected to a MUC from a different client, nl.movim.eu just says "Connecting..." when I try to open it there too. Own posts can't be recognized before connection complete, can't post anything new - form is grayed out.

If I open a MUC in nl.movim.eu, and then open it from different client, new posts from different client and nl.movim.eu itself are shown as if from different person. After switching between conferences, previous posts are also shown the same.

![muc](https://user-images.githubusercontent.com/13851064/43226457-9eb389c2-9064-11e8-8a13-483f33c85972.png)
Here I did following:
- posted `test` from nl.movim.eu
- connected from Miranda-NG
- posted `test2` from Miranda-NG
- posted `test3` from nl.movim.eu
After switching to different conference and back, `test` was shown in the same way too, and it says "Connecting..."
