### ISSUE TITLE
Turn 1-to-1 chat into conference

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#574]
The MUC protocol defines how to invite contacts to a 1-to-1 chat, basically creating a temporary MUC from it. Conversations implements this quite nicely.

This would be good in Movim, and also can serve as a bsis to support the Jitsi Videobridge in the future.

**Comment by edhelas** [comment]
This is not planned for now, the conference creation flow will be redesigned in the future but I'm not planning to handle it the way it's explained in this ticket.
