### ISSUE TITLE
Returning from the "Read more" page back to feed throws you to top of the page

### ISSUE THREAD

**Issue by KillyMXI** [movim/movim#575]
Works the same for the back button on the page and in the browser.

That's really inconvenient.
Expected behaviour: you return to exactly the same scrolling position from where you left.

"+ Read more" button is also quite misleading in case there is no additional post content hidden. It implies there is actually something more, while its only purpose is to be a permalink.

For actually folded content it may have sense to let it unfold without switching page.

**Comment by edhelas** [comment]
That's not planned for now for the unfolding.
Going back to the scrolled position is something that can be done.

**Comment by edhelas** [comment]
Also this is only happening when you have paginated.

**Comment by maddanio** [comment]
the going back would be nice
