### ISSUE TITLE
New messages indication (dashed line) when the chat is opened but not in focus

### ISSUE THREAD

**Issue by KillyMXI** [movim/movim#579]
Typical scenarios when it's hard to catch up with new messages:
- opened a chatroom in movim tab in browser, switched to another tab;
- same, but switched to any other app.

New messages still considered as being read, and so no dashed line is drawn above them.

Current workaround is to make sure not to leave chatroom page open before switching to other tasks. That's not very convenient. Smarter detection of user not watching is required.

**Comment by KillyMXI** [comment]
Ok. I confused two things.
Notifications only when quoted - ok, good enough.
Being able to catch up with the discussion - that's still an issue.

Updated topic.

**Comment by MRZA-MRZA** [comment]
I suggest to stop auto-scrolling to the end of conversation when tab is not active.

**Comment by edhelas** [comment]
I'm not planning to implement a Discord-like system for now as it involve too much work to be done properly.
