### ISSUE TITLE
Unable to connect with XMPP.JP

### ISSUE THREAD

**Issue by GPhMorin** [movim/movim#58]
I tried with pod.movim.eu, it.movim.eu and nl.movim.eu. However, I get logged out automatically after a few seconds.

**Comment by edhelas** [comment]
The login is successful, however it seems that the server is dropping the connection when Movim is doing some pubsub requests. There was a known bug on old ejabberd versions about this. They should update their servers to fix this issue.

**Comment by GPhMorin** [comment]
@edhelas I see, I contacted the administrators for that.

**Comment by GPhMorin** [comment]
Finally, the answer I got is that they will not update "ejabberd" until December. I migrated to Movim.eu for now.
