### ISSUE TITLE
No access to some posts from own profile page

### ISSUE THREAD

**Issue by KillyMXI** [movim/movim#581]
I have two posts, both public:
both visible on the public page,
only newer one is accessible from my profile page.

![](https://i.imgur.com/DcgNuKQ.png)

**Comment by KillyMXI** [comment]
That's on the instance with version 0.13 installed.
When logged into the nl.movim.eu instance, I can see the same post two times, and still no previous one.

![](https://i.imgur.com/gK87Mbx.png)

**Comment by edhelas** [comment]
Just tried again, everything seems fine by now. Closing the ticket.

**Comment by KillyMXI** [comment]
Can't see the old test post. Have I deleted it or it get lost somewhere between instances?
"Get older posts" still shows me duplicates of existing posts.
I think at some point it was giving me different public urls - for nl.movim.eu and movim.feder8.ru but now I see no difference.
