### ISSUE TITLE
Invalid chat room stays forever

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#583]
A while ago, chat room control for disconnected chat rooms were disabled. While this was a good idea, it means that you cannot get rid of a disconnected chatroom anymore.

I jsut created a new room under the wrong domain, and now it sits in my bookmarks with all controls disabled and I cannot seem to remove it again ☹.

**Comment by edhelas** [comment]
You can use the little gear icon on top of the chatrooms list to remove them.

**Comment by Natureshadow** [comment]
> You can use the little gear icon on top of the chatrooms list to remove them.

Nope, I can't, because a disconnected room is the last entry in the
list, and the trash can icon is completely hidden by the + button ;).

**Comment by edhelas** [comment]
Not sure if I can fix that easily…

**Comment by Natureshadow** [comment]
Den 19. januar 2018 12.29.34 CET, skrev "Jaussoin Timothée" <notifications@github.com>:
>Not sure if I can fix that easily…

Well, for now maybe just raise the z-index of the controls or something. They already overlay the chat counters in an ugly way, so that'd not be much of a regression, but would restore functionality at least.

**Comment by pztrn** [comment]
Just a suggestion - lower z-index for plus button if gear icon was pressed.
