### ISSUE TITLE
Test tool for checking the XMPP capabilities?

### ISSUE THREAD

**Issue by annando** [movim/movim#588]
I'm trying to set up an XMPP server that is able to work with Movim. The current problem is that I cannot store XMPP group chat rooms. This is no problem with the local php daemon part, since I tested it with another Movim server as well (using the external Movim server to connect to my XMPP server).

So the problem clearly is my local ejabberd. I configured it according to your documentation and the XMPP test tool for "conversations".

Obviously something is still missing or badly configured at my server. It would be cool to have some (command line) test tool which you could provide the XMPP server credentials and the system could check if everything is supported.

P.S.: I checked all available log files in all different log levels but hadn't found the reason for the problem.

**Comment by edhelas** [comment]
Did you follow https://github.com/movim/movim/wiki/Configure%20ejabberd ?

I understand the need of such tool, it could be cool indeed to have a "Movim ready test" for XMPP servers. However it's not something directly linked to the work I'm putting in this project so I'm not planning to work on such "third-party" script for now, mostly for time reasons. 

If you are interested to do such work you can create one on a repository and it could be integrated in https://github.com/movim if it looks promising :)

**Comment by annando** [comment]
I did the configuration according to the documentation in the Wiki. Concerning the creating of a test tool: If I knew what is wrong, I could do something like this - but I don't know.

At least it would be great if there was some obvious error message what is wrong (means: why my settings aren't stored). But there doesn't seem anything in any logfile.

I'm core contributor of https://github.com/friendica/friendica - my longterm goal is to get to know how Movim works and to integrate the pubsub stuff into it, so that the systems could communicate natively - but to be able to do so, I have to set up a working server :-(
