### ISSUE TITLE
Add integration with Facebook

### ISSUE THREAD

**Issue by raphaeljolivet** [movim/movim#599]
I think Movim really has the potential of becomming a widespread alterantive to Facebook.
But for that purpose, we need a critical mass and enable smooth migration.
I think that the following features are required for this purpose : 
- **Find friends** on Movim (either by connecting to existing adress book, for application, or by connecting to facebook / searching by facebook Ids). We don't even need to make user email public for it : We can hash it, with a fixed seed, and search by meail hash
- **Invite friends** to Movim : by email or existing social network
- **Cross post** : post movim on Facebook and vice versa. The first one can be done by using public RSS + IFTTT action, but it should be integrated and easier to use

**Comment by Natureshadow** [comment]
Please don't get another "let's import address books" started (no, hashing does not help).

**Comment by raphaeljolivet** [comment]
"another" : 
Was it discussed here before ? 
I did not find a similar request.

**Comment by Natureshadow** [comment]
It is discussed for every mobile xmpp app under the sun.

**Comment by raphaeljolivet** [comment]
Ok do you have any pointers to one on those discussion or their outcome and the pro / cons ?
Thanks

**Comment by jmaris** [comment]
I agree that a mechanism to more easily find friends is vital

**Comment by edhelas** [comment]
Not in the scope of the project.
