### ISSUE TITLE
Self-signed certificate

### ISSUE THREAD

**Issue by chteufleur** [movim/movim#6]
Movim seems to not support self-signed certifiacte of the XMPP server.
The XMPP server certificate has been signed by CA that I created.

Movim php.log

> PHP Warning:  stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
> error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed in /var/www/html/movimdev/linker.php on line 109

Log of the XMPP server (Metronome)

> c2s2606e00      info    Client connected
> c2s2606e00      info    Client disconnected: tlsv1 alert unknown ca

**Comment by edhelas** [comment]
I've enabled self-signed certificates for the XMPP server in this commit https://github.com/edhelas/movim/commit/8df95ee4204bf8f20d10a0416ee4496c68a2102e please tell me if it's fine.

**Comment by chteufleur** [comment]
If this commit is running on nl.movim.eu, then it's not working with me.
I still can't connect on nl pod with accounts that are on my XMPP server.

**Comment by edhelas** [comment]
Ok :( Is it possible to get a test account on your server then I can debug properly ?

**Comment by chteufleur** [comment]
account: edhelas@kingpenguin.tk
password: edhelas

**Comment by edhelas** [comment]
Still get the message on my side

> stream_socket_enable_crypto(): SSL operation failed with code 1. OpenSSL Error messages:
> error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

I'm sorry but I can't disable certificates check on Movim so I have to deal with all theses edge-cases

**Comment by chteufleur** [comment]
No problem, I understand. This is quite difficult to handle in that case.

**Comment by edhelas** [comment]
It's not possible to enable self-signed certificate in Movim. But I recommend you to try https://letsencrypt.org/ and get a certificate from there :)
