### ISSUE TITLE
Suppport for XEP-0070: Verifying HTTP Requests via XMPP

### ISSUE THREAD

**Issue by jarobase** [movim/movim#600]
XEP-0070 allows a client to verify HTTP Requests via XMPP. It can be used in 2 factor authentication or as a remplacement of passwords.

See: 
https://xmpp.org/extensions/xep-0070.html
https://blog.agayon.be/xmpp_auth_django.html

There are some implementations on the server side:
 * A REST-like server: https://git.kingpenguin.tk/chteufleur/HTTPAuthentificationOverXMPP
 * As a Wordpress plugin: https://wordpress.org/plugins/xmpp-auth/
 
If the XEP-0070 is not supported, there is a  fall back method (just plain text) so the client doesn't necessarily has to have support for this. Unfortunately, this method is not practical to use.

In order to test several clients support, I made a small website:

https://demo.agayon.be/

You can use it to try the usability.
in the future, I aim to make a website for non-tech people based on this feature.

Unfortunately, it is not really convenient with Movim at the moment.
 * There is not notification (the component is not in the roster)
 * User must check new messages in discussion and copy paste the validation code.
 
People not familiarized with XMPP could not easily use the functionality with Movim.

Moreover, it seems not possible to add the component in the roster and therefore receive notifications. I don't know if it is a standard behavior.

**Comment by edhelas** [comment]
XEP-0070 has been implemented in the project, thanks for https://demo.agayon.be/.
However is seems that your library doesn't handle the "refuse" case yet :)

**Comment by jarobase** [comment]
Great ! 
With Gajim, when I refuse, I get the following message below the validation code on the web page.
"User jid@server.tld refused to authenticate."
Maybe a redirection on my website would be better in the future.

Can I try this functionality on a "trunk" pod? 

Thanks a lot for your reactivity and congratulations for your work.
