### ISSUE TITLE
Nicer URLs for personal blog

### ISSUE THREAD

**Issue by jogzug7** [movim/movim#601]
Posts in my personal blog have URLs like this:
https://xy.movim.eu/?blog/user%40movim.eu/01234567-89ab-cdef-0123-456789abcdef
I'ld very much prefer
https://xy.movim.eu/?blog/user%40movim.eu/nicer-urls-for-personal-blog
Either by automatical slug generation from title or by allowing the user to enter a slug.

In case of conflict (duplicate title), I suggest to always show the oldest post of the same title, because authors will immediately realise in the moment they post, that they get the wrong (older) post.

**Comment by edhelas** [comment]
Implemented, with some limitations:
* The title must be more than 32 characters
* The title is truncated after 80 characters (words are not cut)
* 6 random characters are added at the end to ensure uniqueness

**Comment by jogzug7** [comment]
Many thanks for this ultrafast reaction!
I see a problem with the last point, the six random chars:
The title is not predictable.
Maybe a user deletes a blog posts and regenerates it, then external links to the post would not match anymore.
How about adding a number to the slug in case of dupicates titles?

**Comment by edhelas** [comment]
If the user delete a blog post and publish another, then it's not the same blog post anymore.
And no I'm not gonna test that, it's not possible efficiently.
