### ISSUE TITLE
Status deletion when clicking on the "comments" button

### ISSUE THREAD

**Issue by Lomig** [movim/movim#603]
Hey!

I'm new to Movim and I had a very strange issue. 

The very first day, on the web version, after a few minutes, my first post has been deleted, I didn't understand how. 

Today, wanting to check the comments on one of my posts, I clicked on the "comment logo" behind the post. I had a little toaster saying my post was deleted, and that's it. 

Not sure I really clicked on this button, I stupidly clicked on the same button on my only other post which had comments too: the same causes caused the same results and I lost my other post without any warning as well. 

What happened? If it was something common, you would have had other reports way before mine! 

In any case, thanks for your consideration.

**Comment by edhelas** [comment]
Would it be possible to know which XMPP server you're using and your username on this server? You can also come talk with us on the official chatroom movim@conference.movim.eu.

**Comment by Lomig** [comment]
https://www.youtube.com/watch?v=XCDr2hsHTuo

I did it again (So, now, I don't have any post anymore :D)
It was easier to reproduce it on mobile, but the first occurence was on a laptop.

Instance: fr.movim.eu
My XMPP id: lomig@movim.eu

The first occurrence of the bug was on Safari (Last MacOS version)
One occurrence on Chrome 63.0.3239.132 (Windows 10)
The 4 others (including the video above) on a Samsung S8+ Android phone.

**Comment by edhelas** [comment]
Thanks for the feedback, I'll investigate that and come back to you ;)

**Comment by edhelas** [comment]
Hi, do you still have the issue at the moment?

**Comment by edhelas** [comment]
Closing the ticket.

**Comment by subpub** [comment]
It still is there on jp.mov.im using from jabber.fr on mobile Firefox 68
