### ISSUE TITLE
New post : web page resets itself.

### ISSUE THREAD

**Issue by ghost** [movim/movim#604]
Hello !

I'm new to Movim and I had a strange issue.

When I write the title of a new post, the web page resets itself. Same with the application for Ubuntu 16.04.
It is therefore impossible for me at the moment to add posts.

Thank you for your work to _Movim_.
Best regards

**Comment by edhelas** [comment]
Hi, thanks for this feedback, is it possible to know from which server/pod you tried to post articles? There was a similar bug that was fixed recently so I'd like to know that it was deployed on this server.

**Comment by ghost** [comment]
I try to post articles from server/pod : fr.movim.eu

**Comment by edhelas** [comment]
indeed the fix was not deployed there, now it is :)

**Comment by ghost** [comment]
Thank You.
But, currently the server is inaccessible. Is this normal ?

**Comment by ghost** [comment]
Server/pod OK, but no news, no discussions : Any texts deleted immediately (in a discussion).
Thank You.

**Comment by ghost** [comment]
Server OK. Discussions OK.
Articles :
Reading the first article since the second erases the first !
I am sorry !

**Comment by edhelas** [comment]
This is another problem, are you using another XMPP client with your XMPP account?

**Comment by ghost** [comment]
I use Ubuntu client and Android client.
The behavior is the same in WEB mode, Ubuntu client or Android client.

**Comment by edhelas** [comment]
The original issue has been resolved.
The other issue is related to XMPP itself and not Movim, it can be prevented when i'll deploy that piece of code on the server https://github.com/processone/ejabberd/commit/2785f1dfd2e1c15cc7ebfb909b8304f1e7a86414, closing the ticket.

**Comment by ghost** [comment]
I'll wait.
Thank You.
