### ISSUE TITLE
Contact publication

### ISSUE THREAD

**Issue by ghost** [movim/movim#605]
Sometimes when I post to Movim it says "Contact publication" and some times just my nick name. See the url's https://nl.movim.eu/?blog/arie@movim.eu/133f29da-7166-428f-8918-7d68738ea21c https://nl.movim.eu/?blog/arie@movim.eu/d4c67a41-98cc-4a6b-ac3c-6e85efbd1c95 Am I doing something wrong or is this a bug?

**Comment by edhelas** [comment]
Yes this is normal, those two articles have different layout, the first one is a "short" so basically the text can fit in the title, the other is having a long text so it is displayed bellow and Movim add "Contact publication as a title".
