### ISSUE TITLE
Only 2 posts to see

### ISSUE THREAD

**Issue by ghost** [movim/movim#606]
Yesterday I noticed I can only see my last posts. Other public post that were on my timeline I can't see neither. I'm logged in at nl.movim.eu

**Comment by edhelas** [comment]
What other XMPP client are you using with your account?

**Comment by ghost** [comment]
Website (Firefox, Chromium and Opera), Movim Linux app, Android app. Not at the same time ;)

**Comment by ghost** [comment]
And Conversations and Gajim for chat

**Comment by edhelas** [comment]
Is it still happening? If you're talking about your public blog it's maybe because those other posts where not published "publicly" ?

**Comment by ghost** [comment]
Yes, I can still only see my last 2 posts, all posts are public

Update : made a new post. At the moment I can see 3 posts. I'll check if or when the oldest will disappear

**Comment by ghost** [comment]
At the moment there is only 1 post left. Post from April 15 and 17 are gone.
Edit : It's getting weirder and weider. Old posts show suddenly up, to disappear after a few minutes.

**Comment by ghost** [comment]
Everything before May 14 is gone
https://nl.movim.eu/?blog/arie@movim.eu
I'm wondering if it's a Movim issue or a nl.movim issue

**Comment by edhelas** [comment]
This is not related to Movim but another issue, the Post cache is sometime cleared. So not related to your issue :)

**Comment by ghost** [comment]
Ok, considering leaving movim. If posts get deleted, what's the use of posting them?

**Comment by edhelas** [comment]
You posts are not deleted, it's a cache issue. They are actually available here https://nl.movim.eu/?blog/arie%40movim.eu .

**Comment by ghost** [comment]
Strange, 34 minutes ago they were gone, the same as in my post of May 1.

**Comment by edhelas** [comment]
Closing this ticket.
