### ISSUE TITLE
Metronome IM is not listed on the Wiki

### ISSUE THREAD

**Issue by Neustradamus** [movim/movim#607]
Metronome IM has not listed on the Wiki, it is possible to add?
https://github.com/movim/movim/wiki

Links:
- https://metronome.im/
- https://metronome.im/supported-xeps-list
- https://github.com/maranda/metronome

**Comment by edhelas** [comment]
I'm not planning to do specific documentation support for Metronome IM at the moment, also you could mention OpenFire, Tigase or the many other XMPP servers out there.
