### ISSUE TITLE
Movim doesn't show my bookmarks like other clients do

### ISSUE THREAD

**Issue by stevenroose** [movim/movim#608]
I've recently been testing Conversations, Profanity, Inverse.chat and Dino, and they all automatically connect to two MUCs that I have bookmarked, while on Movim I can't even find them. They don't show up in Chats or anywhere.

Does Movim support bookmarks?

**Comment by Natureshadow** [comment]
Hi,

> I've recently been testing Conversations, Profanity, Inverse.chat and Dino, and they all automatically connect to two MUCs that I have bookmarked, while on Movim I can't even find them. They don't show up in Chats or anywhere.
> 
> Does Movim support bookmarks?

Yes, but not the old standard implemented in the clients you listed.
Movim supports the current bookmark storing standard, which uses Pubsub
instead of private XML storage.

**Comment by edhelas** [comment]
Just to complete what @Natureshadow said, I'm not planning to use the old method. There's actually a new XEP that is coming that is based on the new method (with a few enhancements) https://xmpp.org/extensions/inbox/bookmarks2.html. There is still some work to do but it seems that several clients are planning to go to this new standard (including Movim :)).

**Comment by stevenroose** [comment]
Perfect!  Let's keep this issue open to track progress.

**Comment by ivucica** [comment]
Pubsub seems like it should be a better way to do it.

What is the migration and sync story?

Do you expect servers to implement sync? Do you expect *other* clients to read and sync both? (I can't imagine a safe way to do sync.)

Are users expected to manually re-create every single bookmark?

As a user: I should not care much about protocols. I currently have the same bookmarks in all clients I actively use: Conversations, Gajim, Psi, Jappix, Converse.js. Movim is the exception here. :-)

As a (hobbyist, but still) service provider: I am concerned about disparate UX, with no defined migration or sync story. :-)

> There's actually a new XEP that is coming that is based on the new method (with a few enhancements) https://xmpp.org/extensions/inbox/bookmarks2.html.

That link is broken. :-)

**Comment by edhelas** [comment]
There is now modules on the servers now to convert the new Bookmark standards to the old one (and vice-versa). Because I'm not planning to implement the old standard I'm closing this ticket :)

See the following XEP https://xmpp.org/extensions/xep-0411.html.
