### ISSUE TITLE
/usr/share/webapps/movim does not exist

### ISSUE THREAD

**Issue by buzanits** [movim/movim#609]
In the install documentation the systemd service file says:
`WorkingDirectory=/usr/share/webapps/movim`
but this directory is not created in the previous installation process.

Is this directory to create manually? Has it to be empty?

**Comment by oappiah** [comment]
I think you are supposed to edit the systemd service file according to your installation

**Comment by buzanits** [comment]
My installation followed exactly the installation page, so there should not be a difference...

**Comment by buzanits** [comment]
OK, ist seems that the informations on the install page are inconsistent. 

Above /var/www/movin is used as installation directory, in the systemd service file /usr/share/webapps/movin is used. I had to change this to /var/www/movin in order to make it work. I also had to remove the EnvironmentFile. This should be corrected as it can confuse other users too...

**Comment by thundergreen** [comment]
@buzanits can u please make pull request and maybe post your systemd here ? Had same issue. If I start movim with systemd it seems being started but it isn't somehow.

**Comment by buzanits** [comment]
It looks like wiki pages cannot be used in pull requests on Github. Here is my file:

```
[Unit]
Description=Movim Daemon
After=network.target

[Service]
User=www-data
WorkingDirectory=/var/www/movim
ExecStartPre=/usr/bin/php mud.php db --set
ExecStart=/usr/bin/php daemon.php start --url=http://movim.local --port=8080
Restart=always

[Install]
WantedBy=multi-user.target
```
where http://movim.local is the URL you must adjust to your needs. As they use apt-get in this tutorial to install git, the tutorial seems to be for Ubuntu/Debian. So it would be nice to also show which packages to also install in these distros as prerequisites:

`apt-get install phpmyadmin mariadb-server php-curl php-imagick php-zmq unzip`

I installed phpmyadmin for two reasons: It is an easy way to check, if the database tables have been installed and the package also installs apache, php etc... as dependencies.

**Comment by thundergreen** [comment]
Nice job! Will also add phpmyadmin later thanks so much for the systems.let me try ;)

**Comment by oappiah** [comment]
" Consider using systemd or init scripts to keep the daemon running in the foreground even after your disconnection. Below is a example of a systemd service file." ¨

Yeah it's an example , but sure the example could reflect above.
It's a wiki so I just made an edit 

https://github.com/movim/movim/wiki/Install-Movim/_compare/d0c151f75896161b0a82bb3ee2ea917f5ea65a14...6dd00c93154c95bddc836aa73e15bfc22e259048 :)

**Comment by thundergreen** [comment]
Got it running.nice work ;) thanks

**Comment by edhelas** [comment]
Closing the ticket
