### ISSUE TITLE
Certain URLs are partially recognized in Chat

### ISSUE THREAD

**Issue by GPhMorin** [movim/movim#61]
Here are examples:
https://en.wikipedia.org/wiki/Saguenay,_Quebec (the URL detection stops at the comma)
http://www.yr.no/sted/Sverige/Västernorrland/Sundsvall/ (the URL stops at the Swedish "ä")

**Comment by edhelas** [comment]
New buggy URL https://fr.wikipedia.org/wiki/Th%C3%A9or%C3%A8mes_d'incompl%C3%A9tude_de_G%C3%B6del#Les_conditions_d.27application_des_th.C3.A9or.C3.A8mes

**Comment by edhelas** [comment]
New buggy URL https://vice-images.vice.com/images/content-images/2015/05/20/jai-parle-avec-un-frotteur-du-metro-parisien-012-body-image-1432133440.png?resize=*:*&output-quality=75

**Comment by edhelas** [comment]
Fixed
