### ISSUE TITLE
emojis in messages disappear in cached messages

### ISSUE THREAD

**Issue by bastlwasti** [movim/movim#614]
I am running debian 9 + mysql (mariadb).

The problem is, that when I type messages with emojis, then they disappear after they have been typed. However the receivers receive them anyway.

My guess is, that the underlying database doesn#t use the correct character set, e.g. utf8mb4 instead of utf8.

**Comment by bastlwasti** [comment]
Ok, i think I found the problem:
"vendor/movim/modl/src/Modl/SmartDB.php:            $this->_sql .= ' CHARACTER SET utf8 [...]"

this line of code just overrides the database default character settings and thus causes the loss of characters.

I changed it to:

"vendor/movim/modl/src/Modl/SmartDB.php:            $this->_sql .= ' CHARACTER SET utf8mb4';"

and it now works fine. 

It seems to me that all servers using MYSQL/mariaDB should have this problem!

**Comment by edhelas** [comment]
Indeed the default utf8 encoding of MySQL doesn't handle "emojis" properly, utf8mb4 does.
The next version of Movim will have a different database library and will normally handle this encoding properly.
