### ISSUE TITLE
event management

### ISSUE THREAD

**Issue by subpub** [movim/movim#615]
#### Managing events:

- Create an event with name, date, time, place

- invite selected contacts/ public

- accept or deny invitations

- comments

**Comment by Natureshadow** [comment]
I don't know if there's a protocol for that, but a quick idea would be to support iCalendar attachments/URLs and render them nicely just like we do for images and videos.

**Comment by edhelas** [comment]
As this is not planned in the upcoming months/years I prefer to close this ticket. There's no plan to handle properly events in Movim for now.
