### ISSUE TITLE
Movim reacts indignant to MUC policy-violation

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#616]
I observed very bad behaviour in Movim when joining MUCs fails with a policy-violation, like when a component on the XMPP server that should host the MUC is not connected. Movim seems to endlessly retry joining, which makes Movim completely unresponsive once opening the Chat page for my ~40 IRC transported MUCs, and imposes such a high load on the database while doing so that it almost killed our database server. The bad behaviour went away once I started biboumi and the MUCs became available.

**Comment by edhelas** [comment]
Are you sure it's a policy violation ? Do you know a way to reproduce that issue properly ?

**Comment by edhelas** [comment]
I've completed the MUC errors handling https://github.com/movim/movim/commit/9ae001f13befceded30d97b9ec418ac90d67c58a

Movim should disconnect properly in those cases.
