### ISSUE TITLE
Emoji are not HighDPI

### ISSUE THREAD

**Issue by GPhMorin** [movim/movim#62]
Here is a screenshot taken on an iPad Air:

![image](https://github-cloud.s3.amazonaws.com/assets/6393838/10565532/a3ac44f0-75a0-11e5-8344-135e9a1c6329.png)

As you can see, the emojis are blurry.

**Comment by edhelas** [comment]
How are the native emojis on iOS ? 
I can't support easily high resolution for this kind of things.

**Comment by GPhMorin** [comment]
@edhelas [This is how they look.](http://emojipedia.org/apple/)

**Comment by valeriansaliou** [comment]
@edhelas why can't you? I'm using the same ones for a project of mine (EmojiOne if I recall - available as SVG). Resolution is not an issue.

Can help you with the 1x - 2x - 3x - 4x density inclusion system if you want. Have some SASS code for that under the hood.
