### ISSUE TITLE
Uncaught error on missing class loading pictures

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#620]
After the Eloquent update, the following happens for some users when loading chats:

`Apr 17 17:18:52 commu movim[8027]: movim.ERROR: Uncaught Error: Class 'App\Picture' not found in /var/www/movim/app/Message.php:157 Stack trace: #0 /var/www/movim/vendor/movim/moxl/src/Moxl/Xec/Payload/MAMResult.php(19): App\Message->set(Object(SimpleXMLElement), Object(SimpleXMLElement)) #1 /var/www/movim/vendor/movim/moxl/src/Moxl/Xec/Handler.php(223): Moxl\Xec\Payload\MAMResult->handle(Object(SimpleXMLElement), Object(SimpleXMLElement)) #2 /var/www/movim/vendor/movim/moxl/src/Moxl/Xec/Handler.php(151): Moxl\Xec\Handler::searchPayload('0e49eb65ba26605...', Object(SimpleXMLElement), Object(SimpleXMLElement)) #3 /var/www/movim/vendor/movim/moxl/src/Moxl/Xec/Handler.php(66): Moxl\Xec\Handler::handleNode(Object(SimpleXMLElement), Object(SimpleXMLElement)) #4 /var/www/movim/linker.php(26): Moxl\Xec\Handler::handle(Object(SimpleXMLElement)) #5 [internal function]: {closure}(Object(SimpleXMLElement)) #6 /var/www/movim/vendor/movim/moxl/src/Moxl/Parser.php(102): call_user_func_array(Object(Closure), Array) #7 [internal function]: Moxl\Parser->end(Resource id #28 [] []`

**Comment by edhelas** [comment]
I've just pushed a fix, can you please pull and tell me if it's fixed for you?

**Comment by Natureshadow** [comment]
@edhelas, well, maybe start by *logging* them properly formatted, then ☺! That paste without line breaks is a verbatim copy from the Movim logs ;)

But yes, it's fixed. Thanks!
