### ISSUE TITLE
Error 1215

### ISSUE THREAD

**Issue by scuba323** [movim/movim#621]
I just cloned fresh today, and was trying to run;   
  
`php vendor/bin/phinx migrate`  

step and I get  
  
<code>
 [Illuminate\Database\QueryException]
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `attachments` add constraint `attachments_post_id_foreign` foreign key (`post_id`) references `posts` (
  `id`) on delete cascade)

[PDOException]
  SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint
</code>

I am on 16.04 Xenial, using PHP7.0

**Comment by edhelas** [comment]
What database are you using ?

**Comment by scuba323** [comment]
MySQL

Edit: 
`mysql  Ver 14.14 Distrib 5.7.21, for Linux (i686) using  EditLine wrapper`
