### ISSUE TITLE
Images sometimes fail to display in news feed

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#624]
In some posts, images are not displayed inline in the news feed but only show as link. When opening the detailed post, the image appears.

Examples:

https://commu.teckids.org/movim/?post/tglaser%40mercurius.teckids.org/urn%3Axmpp%3Amicroblog%3A0/sakura-kirschbluetenzeit-in-bonn-2-2-jBMUie
https://commu.teckids.org/movim/?post/tglaser%40mercurius.teckids.org/urn%3Axmpp%3Amicroblog%3A0/sakura-kirschbluetenzeit-in-bonn-1-2-86Kkeq

**Comment by thundergreen** [comment]
@Natureshadow could you whitelist my server to be able to login and see what u mean ? Its emevth.no-ip.biz

**Comment by edhelas** [comment]
It's a limitation added during the refactor to prevent big pictures to be loaded in the news feed. It also need some adjustments. I've reduced the resolution of uploaded pictures a bit to prevent that for now.

**Comment by Natureshadow** [comment]
> It's a limitation added during the refactor to prevent big pictures to be
> loaded in the news feed.  It also need some adjustments.  I've reduced the
> resolution of uploaded pictures a bit to prevent that for now.

I can't confirm that.  I did just post a huge image and it shows in the news
feed like before, while some smaller ones don't.
