### ISSUE TITLE
movim loads images/favicons from third party sites directly

### ISSUE THREAD

**Issue by subpub** [movim/movim#627]
This is a privacy breach.
Eg., look at the third party requests on https://nl.movim.eu/?node/pubsub.movim.eu/Movim 

avatars2.githubusercontent.com
freedif.org
github.com
hasecke.eu
meetup.com
meetupstatic.com
secure.meetupstatic.com
process-one.net
blog.process-one.net
transifex.com
cdn.transifex.com
transifex.s3.amazonaws.com

**Comment by edhelas** [comment]
Yes because Movim can be considered as a feed aggregator, no thumbnail nor cache of the attachments are made on the server.

**Comment by Natureshadow** [comment]
On Thu, Apr 19, 2018 at 09:10:22PM +0000, Jaussoin Timothée wrote:
> Yes because Movim can be considered as a feed aggregator, no thumbnail nor
> cache of the attachments are made on the server.

Which is another reason for what I wanted to request for a long time:

Please allow posting links without a thumbnail.  One can already select a
picture from the website as post thumbnail, but please add an option to not
use a thumbnail.

-nik
