### ISSUE TITLE
Post editing quite broken

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#629]
I just tried to edit a post, containing a title, body and image attachment.

When editing, the image vanished (it was missing from the edit form already).

I removed the body, and then body and image were both gone.

Even more strange: When editing the post again, the body reappeared in the edit form (but not the image)!

**Comment by edhelas** [comment]
I fixed the attachment bug, there is no draft saved for now when editing a post. This is a feature that will require more work (and that was never implemented in Movim for now).
