### ISSUE TITLE
Broken images after Debian reboot

### ISSUE THREAD

**Issue by c-93** [movim/movim#631]
What I did:
I installed movim together with nginx and ejabberd. Tried mariadb and postgresql because I suspected a database issue (suscpicious mysql logging).
Maybe it is relevant that I installed movim on a subdomain like im.mydomain.de

Problem:
Movim works directly after installation, but not after reboot. After reboot images are broken and I can't upload new images.

Maybe relevant log:
movim.error.log (after reboot):
2018/04/25 08:26:15 [error] 688#688: *102 connect() failed (111: Connection refused) while connecting to upstream, client: 77.178.76.49, server: im.mydomain.de, request: "GET /ws/?path=&offset=-120 HTTP/1.1", upstream:  upstream: "http://[::1]:8080/?path=&offset=-120", host: "im.mydomain.de"

Ideas:
I also suspect some dns problem.

Update: Solution:
After reboot I have to findout movim process with "netstat -tulpn", kill it and start it again (even though it already was running). Maybe debian starts it to early?
I'm really glad having found some solution now. Movim is a great project.

**Comment by Natureshadow** [comment]
Yes, the systemd service is started too early. This also happens for biboumi.

Local fix:

```
mkdir /etc/systemd/system/movim.conf.d
cat >/etc/systemd/system/movim.conf.d/after-ejabberd.conf <<EOF
[Unit]
After=ejabberd.service
EOF
systemctl daemon-reload
```

The problem is that this will break if ejabberd is not on the same machine.

I am working on a solution for the official Debian package coming soon.

**Comment by c-93** [comment]
Cool. Thanks for the fix. Glad to hear this :) Looking forward for the package.

I thought about writing a detailed manual on how to install movim (with nginx, ejabberd and psotgresql) on debian, because it took me about 2 days to get everything working and find the causes of the (movim related and unrelated) problems I had. E.g. I tried to migrate from prosody to ejabberd, but did not find a good way to migrate users. Now my few users need to register again. On prosody movim only worked in degraded mode.

Btw.: I am running prosody on the same machine but prior got the problem with movim being started to early. Maybe it is because my machine is relatively slow.

**Comment by Natureshadow** [comment]
The fix is homeopathic, now that I was reminded that Movim is independent of the xmpp server 

It hides some other timing issue, though...

**Comment by Letterus** [comment]
Working fix for me was:

`After=mysql.service`
