### ISSUE TITLE
Feature: mute MUC rooms

### ISSUE THREAD

**Issue by kawaii** [movim/movim#632]
Hey, could we possibly get an option for MUC rooms to mute/unmute them so that their notifications don't add to the total notification counter in the tab title bar or appear next to the MUC itself? I think that mentions should still come through, but nothing else. I'm in 6 different XMPP-related MUC rooms and it does get a little annoying sometimes to just have all these unread messages.

Happy to sponsor/bounty this request, @edhelas knows where to find me. :slightly_smiling_face:

**Comment by dos1** [comment]
I'm willing to hop on this :)

**Comment by edhelas** [comment]
@kawaii there's a bounty on that ticket? 🤔

**Comment by poVoq** [comment]
@dos1 given the notification system was reworked, maybe time to have another look at this?

**Comment by edhelas** [comment]
This was implemented in 0.18 https://nl.movim.eu/?node/pubsub.movim.eu/Movim/11655111-e7ad-4e0c-975c-3c78755d22aa
