### ISSUE TITLE
how to run movim in ide

### ISSUE THREAD

**Issue by lich1011** [movim/movim#633]
After importing movim source code in netbeans, when I click run, the website shows cannot talk with the server. How can i fix it?

**Comment by oappiah** [comment]
What error are you getting and from where?

What PHP version are you using?
Do you have anything in your webserver logs?
Do you have anything in the movim log directory?

**Comment by lich1011** [comment]
My development environment
      Ubuntu 16.04
      Netbeans 8.2
      PHP 7.0
      Apache2 

When i run movim in netbeans, it shows following page
![error](https://user-images.githubusercontent.com/23086291/39469860-fe7194e8-4d6c-11e8-929c-7165cb461eda.PNG)
I have checekd log of movim, there is not update.
In the log of apache, it shows
![error2](https://user-images.githubusercontent.com/23086291/39469915-58bd2750-4d6d-11e8-90d3-d3d0bfbcee0e.PNG)

However, when I running movim via command line with 
        php daemon.php start --url=http://localhost/movim --port=8080
it works fine

**Comment by oappiah** [comment]
Then this is a netbean configuration issue rather then a movim issue...

Can you verify that netbeans launches daemon.php with the same settings as you are trying with on command line?

**Comment by edhelas** [comment]
This is a purely Netbean issue, Movim is not designed to be run in specific IDEs. I'm ok for you to discuss about possible solutions here but I'm closing the ticket as this is not related about the current project status and sourcecode.
