### ISSUE TITLE
Can't send URL from kibana

### ISSUE THREAD

**Issue by CraigBarnesOpusVL** [movim/movim#635]
When I try to send a URL from a kibana search in movim, it fails silently.

```https://elk.example.com/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now%2Fd,mode:quick,to:now%2Fd))&_a=(columns:!(_source),index:AWLinFXftquTVBoFqsgz,interval:auto,query:(query_string:(analyze_wildcard:!t,query:%27request:%22%2Fapartments%2Fwith-your-family%22%27)),sort:!(%27@timestamp%27,desc))```

**Comment by edhelas** [comment]
Oh sorry, indeed :) I'll have a look at it.

**Comment by edhelas** [comment]
Still don't have a clue how to handle this kind of URLs properly.
I think that this regex will have to be refactored https://github.com/movim/movim/blob/master/app/helpers/StringHelper.php#L9 .

**Comment by edhelas** [comment]
It's "kinda" fixed, the URL not disappearing anymore if Movim can't handle weird urls like this one
