### ISSUE TITLE
Add Progressive Web App metadata

### ISSUE THREAD

**Issue by maddanio** [movim/movim#639]
Hi all,

I would like to use movim on the iPhone. Since there is no app I would be fine just using the site, added as a separate icon on my home screen (ad per „add to home screen“ in mobile Safari). There are a few small issues making the experience less than ideal:
- the home screen entry has no nice icon (there is some special Tag the site can use to provide one, I can look it up if you want)
- scrolling is weird
- safari always shows navigation controls (ideally iOS would open it „like an app, I.e separate from safari and without navigation controls, not sure what the site has to do to achieve this, but I can do some research...)

**Comment by edhelas** [comment]
As I am not owning iOS and Apple devices I cannot work on that task, feel free to improve Safari support :)

**Comment by maddanio** [comment]
Hmm, i am really bad at this stuff...but ok, I will see what I can do :)

**Comment by maddanio** [comment]
Biggest problem will be getting a dev environment. Is it hard to set up?

**Comment by edhelas** [comment]
Well if you know how to install Movim you're good to go I think (have a look at the wiki)

**Comment by maddanio** [comment]
Yeah, started on that. Don’t find much time recently though :(. 

Gruß!

Daniel Oberhoff

**Comment by maddanio** [comment]
First halves of things to do is documented here: https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by edhelas** [comment]
Nothing happened there for a while :) Closing the ticket for now.

**Comment by edhelas** [comment]
The metadata were implemented recently. Scrolling on iOS was also fixed a few months ago.
Closing this ticket. There's still a PR with more features that is open.
