### ISSUE TITLE
SSO support for Yunohost

### ISSUE THREAD

**Issue by src386** [movim/movim#64]
That would be a good idea to support Yunohost SSO (ssowat).
SSO is a requirement for a package for Yunohost.

**Comment by edhelas** [comment]
Ok I made a little commit to support http://php.net/manual/en/features.http-auth.php tell me if it's ok.

**Comment by src386** [comment]
It's working if I replace PHP_AUTH_USER with HTTP_EMAIL .

**Comment by edhelas** [comment]
Thanks, I'll try to do the change ASAP.

**Comment by edhelas** [comment]
This pull request https://github.com/edhelas/movim/pull/67 should fix it. Please confirm :)

**Comment by src386** [comment]
It's working but I have this message for 1 second : 

```
Le format de l'identifiant n'est pas correct
```

**Comment by edhelas** [comment]
This issue was moved to movim/movim#19

**Comment by edhelas** [comment]
Linked with #86
