### ISSUE TITLE
Crash after recent upgrade

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#641]
After upgrading to current master, I get the following crash:

```
mai 10 00:23:31 commu movim[22869]: movim.ERROR: Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 7
ERROR:  value too long for type character varying(64) in /var/www/movim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:105
Stack trace:
#0 /var/www/movim/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(105): PDOStatement->execute(NULL) 
#1 /var/www/movim/vendor/illuminate/database/Connection.php(458): Doctrine\DBAL\Driver\PDOStatement->execute() 
#2 /var/www/movim/vendor/illuminate/database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into "co...', Array) 
#3 /var/www/movim/vendor/illuminate/database/Connection.php(624): Illuminate\Database\Connection->runQueryCallback('insert into "co...', Array, Object(Closure)) 
#4 /var/www/movim/vendor/illuminate/database/Connection.php(459): Illuminate\Database\Connection->run('insert into "co...', Array, Object(Closure)) 
#5 /var/www/movim/vendor/illuminate/database/Connection.php(411): Illuminate\Database\Connection->statement( [] []
```

I observed that after upgrading, migrating the database and restarting, Movim never got ready loading things. At first, I only saw my own posts but not those of contacts, then they showed up after approximately half an hour, but then they vanished again, and switching to chats either hangs indefinitely or causes the crash above.

**Comment by Natureshadow** [comment]
Right now, opening the chats view throws me into an endless loop of the login page realoaing.

**Comment by c-93** [comment]
After recent upgrade I am also having problems with dbal.

After:
`php vendor/bin/phinx migrate`

I get:
`[RuntimeException]                                                                   
  Changing columns for table "infos" requires Doctrine DBAL; install "doctrine/dbal". `

After successfull installation of (in debian):
`apt install php-doctrine-dbal`

I still get the same runtime exception during migration.

**Comment by edhelas** [comment]
It's a different issue but "doctrine/dbal": "^2.5" is actually in the Movim dependencies, by doing a simple composer install it will be installed.
