### ISSUE TITLE
Movim Account Creation fail : Unknow Error

### ISSUE THREAD

**Issue by ghost** [movim/movim#642]
Impossible to creat a Movim account no matter the server, no matter the pseudo, the device or the password. All time the same error : "Unknow Error" (no other infos).

![capture d ecran_2018-05-10_11-27-28](https://user-images.githubusercontent.com/8572474/39862968-894bff02-5445-11e8-935d-cad669c49171.png)

PS : the google captcha has some bug too. (some image dissipear when we click on it and replace by another. After some clic their is no result and the catcha fail)

**Comment by edhelas** [comment]
Indeed I've updated ejabberd yesterday, should be fixed by now, can you try again?

**Comment by ghost** [comment]
It's work now !
Thanks.

Edhelas, more reactive than superman 😎
