### ISSUE TITLE
Chats show up for wrong contact

### ISSUE THREAD

**Issue by stevenroose** [movim/movim#643]
![screenshot-2018-ym-11--13- m-03](https://user-images.githubusercontent.com/853468/39921846-b91aa90e-551c-11e8-8f73-08da1603207d.png)

As you can see there, messages from the "joris" chat appear on Movim in the chat with "david". They were not sent to/from david and obviously don't appear as such in other clients including Gajim and Conversations.

**Comment by edhelas** [comment]
I think that I experienced that bug as well, I'm trying to reproduce it :p

**Comment by edhelas** [comment]
This has been fixed in trunk, I'm working on a related MySQL migration error brought by this patch.

**Comment by edhelas** [comment]
MySQL migration fixed as well, closing.
