### ISSUE TITLE
Dependency review, again

### ISSUE THREAD

**Issue by mirabilos** [movim/movim#646]
Hi @edhelas,

we’ve started the packaging hackathon ;-) My notes are [here](https://wiki.teckids.org/wiki/MovimPaketierungsNotizen) in case you wish to review them (__please do!__).

Your [list](https://github.com/movim/movim/wiki/Packaging-Dependency) has a mismatch with your [composer.json file](https://github.com/movim/movim/blob/master/composer.json); for example, the Wiki lists `fabiang/sasl 1.0` but the composer file doesn’t. What is true now?

**Comment by mirabilos** [comment]
Never mind, sasl is from moxl…

**Comment by edhelas** [comment]
Good news, actually I was able to move to rain/raintpl v3.1.0 :) https://github.com/movim/movim/commit/519d57afb409ea488b9100ba88f439f4792c9930
