### ISSUE TITLE
Some Ad-Hoc Actions won't work

### ISSUE THREAD

**Issue by thundergreen** [movim/movim#65]
![movim_action_menu](https://cloud.githubusercontent.com/assets/13320319/10822035/8fad8bd6-7e55-11e5-8e2d-ddae0aa9c7e1.png) 

The menu for the admin is there but without any fucntion. no send buttons or save buttons. Only close in some menues.

**Comment by edhelas** [comment]
Thanks for the bug report it's related to some recent changes done on the XMPPtoForm library. I'll try to fix it ASAP.

**Comment by thundergreen** [comment]
Thanks dude ;) i highly appreciate your work ! ;)
Am 29.10.2015 18:18 schrieb "Jaussoin Timothée" notifications@github.com:
