### ISSUE TITLE
Maintenance page

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#659]
As an administrator, I would like to be able to run `php daemon.php maintenance-mode start` or similar, to get movim to display a static page (no php, no js, no db call), while I update. A simple "Movim is coming back soon" should be enough.

Once I am done I would run `php daemon.php maintenance-mode stop` to allow access to movim again.

I can already do this manually via the reverse-proxy, but I thought it might be better to have a webpage with movim colors, and having movim handle this itself would enable more admins to use the feature.

**Comment by edhelas** [comment]
As I prefer to keep the code simple and it's easy to do with a simple redirection or replacing a file I'm not planning to implement that feature in Movim. Also some users would like to personalize this page.
