### ISSUE TITLE
Provide a way to notify the daemon that logs have been rotated

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#660]
As an administrator I want to be able to rotate (archive or delete) every so often the log files movim produces. By default if I do this, the daemon will still keep links to the old files, even if unlink(2) is called by logrotate.

I would like to be able to tell the daemon it needs to reopen the logfiles, (by convention `SIGHUP`?), without having to restart it.

As a note, `SIGHUP` is also often used to reload configuration files.

**Comment by edhelas** [comment]
The logging system has been changed. Logs are only sent to syslog for Fatal Errors by now.
Movim is also writting logs in it's own directory if the feature is enabled (save to file) in the Admin panel but I'm not planning to rotate those logs as they are not enabled by default anymore.
