### ISSUE TITLE
Little bug when share a tor link (.onion)

### ISSUE THREAD

**Issue by ghost** [movim/movim#661]
When we share a tor link (.onion), while we don't submit the message it's don't stop loading. The load is propagate to movim on android.
Submit the message and the load dissipear.
![2018_06_08-movim-bug_with_tor_onion_link](https://user-images.githubusercontent.com/8572474/41153170-480bd836-6b16-11e8-89e8-f6780977c3a0.gif)

**Comment by edhelas** [comment]
Should be fixed now :)
