### ISSUE TITLE
Mixup of avatars and profile links in chatrooms

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#662]
I have a contact named ilian on my local XMPP domain, and I occupy a MUC where one user has the name ilian. They are not the same person.

Movim shows the ilian in the MUX with the avatar of my local contact named ilian, and also provides a link to their profile page.

**Comment by edhelas** [comment]
I made a fix regarding how the MUC presences are handled, can you please tell me if it fixes your problem?

**Comment by Natureshadow** [comment]
Yep, problem gone.
