### ISSUE TITLE
MUC messages disappear

### ISSUE THREAD

**Issue by Letterus** [movim/movim#664]
When I join a MUC afresh I can see all messages in a MUC. When I switch to another MUC and back certain messages are not shown anymore and won't come back unless I rejoin that MUC.

**Comment by edhelas** [comment]
It would be nice to specify which MUC. XMPP MUC implementation can be really inconsistent across the servers and versions so basically it's impossible to reproduce things easily without proper use cases.

**Comment by edhelas** [comment]
I'm closing this ticket. Not enough information to reproduce it.
