### ISSUE TITLE
Movim loops on the archive indefinitely.

### ISSUE THREAD

**Issue by maranda** [movim/movim#665]
If the server does return the wrong count of messages or possibly the approximate count of messages with RSM, Movim will start looping on the archive indefinitely this could be also used to DoS a Movim instance purposefully.

**Comment by edhelas** [comment]
What is aproximate for you? I know that it shouldn't behave like that but a client should a least trust the information delivered by his own server until a certain level.

**Comment by maranda** [comment]
Which is why you should break the loop somehow if you can't get to the end to the archive in a timely manner, be that using a execution time policy, loop iterations count, timer or whatever suits your boat.

**Comment by edhelas** [comment]
Should be fixed now no?

**Comment by maranda** [comment]
Yes
