### ISSUE TITLE
Should have 2 more configuration options

### ISSUE THREAD

**Issue by JiffB** [movim/movim#669]
Hi folks,

1- when using a home domain (ie: myhome1), movim is refusing to connect because of the strict php email check; this is ok for an external web site, not at home nor in an enterprise,

2- should have an option to allow self-signed certificates (same reason.)

**Comment by edhelas** [comment]
1- I'm not planning to support that for now, as for different tickets, I'll leave this one open for a while and close it in a couple of weeks/months if no one offered to fix it :)
2 - This is not planned, it's pretty easy to deliver valid certificates nowadays and I prefer to keep the config light in Movim. As Movim relies on PHP to check the certificates to can declare it valid directly there.
