### ISSUE TITLE
Date mark duplicated on edit

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#678]
When the last sent message was on anotehr day and the other party sent mesages on the days in between, and then the last sent message is edited, it is replaced at the correct point in history, but the date label of the day of the message is appended to the end of the log.

![screenshot_20180716_191927](https://user-images.githubusercontent.com/212972/42773317-2ebd1fea-892d-11e8-82d2-f60119f70306.png)

**Comment by edhelas** [comment]
I've pushed a fix related to that issue recently, can you please tell me if it fixes yours as well?

**Comment by edhelas** [comment]
Looks like its fixed. Closing the ticket.
