### ISSUE TITLE
Allow owners to manage community subscriptions

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#683]
With subscriber model (access model) set to `whitelist`, it is possible to get in a state where nobody is subscribed, and nobody (except owners, and maybe publishers?) can subscribe, or be added to the subscriptions.

It would be good to allow owners to manage subscriptions (add/remove) via the UI.

**Comment by edhelas** [comment]
Implemented a while ago

![image](https://user-images.githubusercontent.com/3726886/217379655-ff40638a-faa2-4479-be81-c4b9a0b04227.png)
