### ISSUE TITLE
Selection in chat list doesn't change when second Movim changes room

### ISSUE THREAD

**Issue by dos1** [movim/movim#689]
When using Movim from multiple devices, the UI state is synchronized between them - however, the highlight selection on the chat list doesn't change together with the room; it stays exactly as it was selected locally.

**Comment by dos1** [comment]
I'll take a look at it; basically wanted to dump my list of noticed issues so they won't get lost.

**Comment by edhelas** [comment]
I'll close this ticket soon as I'm not planning to fix it.
