### ISSUE TITLE
XEP-0106 JID support is very flaky

### ISSUE THREAD

**Issue by dos1** [movim/movim#691]
For starters, any MUC JID with '\' character can't be joined with Movim.

When such room already exists in bookmarks, Movim does strange things, like:
- not displaying room's name in the chat view
- not being able to click on the avatar circle to see the member list
- not being able to remove the bookmark

As far as I could see in the code, it seems related to `echapJS` and `filter_var($var, FILTER_VALIDATE_EMAIL)` function usage.

Related to #492

**Comment by dos1** [comment]
Also, I've seen some lines of code that seem like checking if JID is between 6 and 60 chars long. Given that a transport MUCs I used for testing, chosen randomly, was exactly 60 chars long, it seems that this should probably be changed to a greater values ;)

**Comment by Natureshadow** [comment]
> Related to #492 

Yeah well… actually a duplicate.

**Comment by dos1** [comment]
Not really - through the codebase there are two separate issues, one relating to validation, and second relating to sanitation. The first sentence from this report is covered by #492, but the rest is a separate thing. However, I must confess that I initially do missed that issue :P

**Comment by edhelas** [comment]
I'm closing this ticket in favor of #492. If any of you can find a proper way to validate a JID (also MUC JID in PHP please tell me).
