### ISSUE TITLE
Old sent messages pop up randomly during conversation

### ISSUE THREAD

**Issue by dos1** [movim/movim#692]
On fresh installation, when I started chatting, Movim kept appending seemingly random, old messages to the conversation.

Like this: I send a message "xyz" to contact A, and see "dos: xyz" appended to the message chat, and immediatelly after that, also "dos: qwertyuiop", which is some random old message I've sent to contact A ages ago.

FWIW, most of the history has been filled up with Psi, which sends message IDs that are unique only within a single session (which, AFAIK, is still correct according to the standard). Also, I think I may have noticed an message that I've sent long ago to someone else, so it's likely related to some ID, not a particular contact.

It appeared both times I set up a fresh installation - last time with v0.13, this time with master from git. Last time it kept appearing for some time and stopped by itself.

I've just disconnected Psi and seems like it stopped as well, so I suspect that it's somehow related to message receipts or something like that, but I'll keep an eye.

**Comment by edhelas** [comment]
Yup it's a Psi issue, I have that with another contact that uses Psi as well.
I still have to debug that but Psi is generating really small IDs for messages that are not unique enough, those IDs could replace some other messages creating this issue. However it's still a Movim issue as the Movim code should protect itself from such badly coded behaviors.

**Comment by dos1** [comment]
I'll probably fix this in Psi soon as well, but yeah, as you say, Movim should be prepared for stuff like that anyway.

**Comment by edhelas** [comment]
Should be fixed in https://github.com/movim/movim/commit/3c7595f9a0c01c7b1d1cf2cb9c6d0e330e125d29. Can you please confirm :) ?

**Comment by dos1** [comment]
I'll play around and scream if it happens again. Feel free to close it after a while of no screaming ;)

**Comment by dos1** [comment]
Haven't seen it yet, so let's close it for now. I'll sure holler if it happens again ;)
