### ISSUE TITLE
Status indicator on top of the chat view doesn't update

### ISSUE THREAD

**Issue by dos1** [movim/movim#699]
When contact changes its presence, the circular indicator in the header of the chat view does not refresh - the whole chat needs to be refreshed for it to notice a change.

The similar indicator in the chat list updates just fine.

**Comment by edhelas** [comment]
It's a known issue yes but that will involve some good filtering to prevent some useless code to be executed.

**Comment by edhelas** [comment]
I'm closing this ticket as I'm not planning to add this feature for now. It needs a really specific kind of filtering on the event to prevent spamming the browser with useless events.
