### ISSUE TITLE
su -u dans la documentation

### ISSUE THREAD

**Issue by Cypouz** [movim/movim#70]
Dans le tutoriel d'installation, sur le wiki, il est question à la fois de `su` et `sudo`.
1. Il faudrait faire un choix qui reste cohérent tout au long du tutoriel ;
2. L'option `-u` n'existe pas avec `su`.

Bref, il vaut mieux remplacer, dans le tuto, la commande `su -s -u www-data` par `sudo -s -u www-data`.

**Comment by edhelas** [comment]
Thanks, it's fixed now :)
