### ISSUE TITLE
Movim doesn't take in account the complete attribute on <fin /> on a MAM query.

### ISSUE THREAD

**Issue by maranda** [movim/movim#701]
Movim looping through the archive breaks only if it picks up an item-not-found (?) when querying which ultimately is *wrong* because in the case the server returns a complete attribute set as true on the fin tag it means there're no more remaining messages in the archive.

**Comment by dos1** [comment]
Fixed in #702

**Comment by edhelas** [comment]
Was merged. I'm closing the issue.
