### ISSUE TITLE
The login UI loops over and again: http://localhost/movim/?login

### ISSUE THREAD

**Issue by AdarshMaurya** [movim/movim#703]
I am new to php and xmpp. I was following the tutorial mentioned [here](https://github.com/movim/movim/wiki/Install-Movim) and seems like I was not able to set up the dependencies correctly :/.

for url http://localhost/movim/?login(url) UI was sending request over and again. I can see 101 status code. Kindly can you guide me how can I fix it?

Thanks

Seems like linked similar issue: https://github.com/movim/movim/issues/134#issuecomment-230144518
```
Movim daemon launched
Base URL: http://localhost/movim/

--- Server Configuration - Apache ---
Enable the Secure WebSocket to WebSocket tunneling
# a2enmod proxy_wstunnel 
Add this in your configuration file (default-ssl.conf)
ProxyPass /ws/ ws://localhost:8080/

--- Server Configuration - nginx ---
Add this in your configuration file
location /ws/ {
    proxy_pass http://localhost:8080/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect off;
}

Unencrypted 
e7lvNNPK3wRy7k338RWjXk3RYYg2O4vz : 345 connected
e7lvNNPK3wRy7k338RWjXk3RYYg2O4vz : linker killed 
e7lvNNPK3wRy7k338RWjXk3RYYg2O4vz : 345 deconnected
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : 385 connected
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : linker killed 
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : 385 deconnected
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : 394 connected
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : linker killed 
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : 394 deconnected
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : 403 connected
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : linker killed 
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : 403 deconnected
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : 412 connected
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : linker killed 
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : 412 deconnected
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : 421 connected
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : linker killed 
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : 421 deconnected
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : 430 connected
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : linker killed 
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : 430 deconnected
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : 439 connected
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : linker killed 
ZBMK24q9haD8PpnOqlj0Z9uj9G6914Ev : 439 deconnected

```

**Comment by dos1** [comment]
Enable all logs in http://localhost/movim/?admin and check them (`/log/` directory of your Movim installation)

`tail -f log/*` is your friend :)

**Comment by dos1** [comment]
Also, which version are you trying to run?

**Comment by AdarshMaurya** [comment]
@dos1 I took the latest pull - v.0.14alpha6 https://github.com/movim/movim/tree/v0.14alpha6 & also tried with your branch https://github.com/dos1/movim/

 There are no logs getting generated in `/log/`directory. 
 http://localhost/movim/?admin is redirecting back to login ui http://localhost/movim/?login

Please note that I did have my xmpp server up yet.

**Comment by dos1** [comment]
Don't use my repo, it's just for development and experimentation :)

Anyway - you could change that logging value directly in the database (table "configuration" IIRC, change it from value 0 to 2).

Alternatively, you could also add a `--debug` option to the daemon to display XMPP logs - maybe something goes wrong there.

**Comment by AdarshMaurya** [comment]
I made a new clone and did a fresh set up again as per the required dependencies for v.0.14alpha6. 
I have updated the loglevel in table "configuration"  from 0 to 2 :)
Also I am using --debug flag. 

--debug flag is not showing me any XMPP logs.

However I can see the initial login ui redirected over and again.

What I am not doing is setting up a xmpp server,locally? Is it is necessary to set up a xmpp server like ejabberd locally on my machine?


While setting up I received below errors:

`Adarshs-MacBook-Pro:movim adarshmaurya$ php daemon.php config --username=admin --password=password`

gives below error as /log &/cache did not have the required permissions. After granting the required permissions it seems to work as expected. However the path below has an extra '/' in bold?

```
PHP Fatal error:  Uncaught Exception: We're unable to write to file /Applications/XAMPP/xamppfiles/htdocs/movim**/log//logger.log: check rights**
<br />We're unable to write to file /Applications/XAMPP/xamppfiles/htdocs/movim/**log//php.log: check rights**
<br />We're unable to write to file /Applications/XAMPP/xamppfiles/htdocs/movim/**cache//test.tmp: check rights** in /Applications/XAMPP/xamppfiles/htdocs/movim/src/Movim**/Bootstrap.php:85**
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/movim/src/Movim/Bootstrap.php(33): Movim\Bootstrap->checkSystem()
#1 /Applications/XAMPP/xamppfiles/htdocs/movim/daemon.php(13): Movim\Bootstrap->boot(false)
#2 {main}
  thrown in /Applications/XAMPP/xamppfiles/htdocs/movim/src/Movim/Bootstrap.php on line 85
Oops... something went wrong.
Uncaught Exception: We're unable to write to file /Applications/XAMPP/xamppfiles/htdocs/movim/log//logger.log: check rights
<br />We're unable to write to file /Applications/XAMPP/xamppfiles/htdocs/movim/log//php.log: check rights
<br />We're unable to write to file /Applications/XAMPP/xamppfiles/htdocs/movim/cache//test.tmp: check rights in /Applications/XAMPP/xamppfiles/htdocs/movim/src/Movim/Bootstrap.php:85
Stack trace:
#0 /Applications/XAMPP/xamppfiles/htdocs/movim/src/Movim/Bootstrap.php(33): Movim\Bootstrap->checkSystem()
#1 /Applications/XAMPP/xamppfiles/htdocs/movim/daemon.php(13): Movim\Bootstrap->boot(false)
#2 {main}
  thrown
in /Applications/XAMPP/xamppfiles/htdocs/movim/src/Movim/Bootstrap.php (line 85)
```

After setting up the admin & password, I did launch the daemon:
daemon.php start --url=http://localhost/movim/ --port=8080 --debug

and opened http://localhost/movim/?admin

it showed up the Admin UI but after quickly it is being redirected to the login ui,  where it keep looping untill, it reaches to a limit, stops for a while and repeats again:

`[22-Aug-2018 00:30:35 UTC] PHP Warning:  proc_open(): unable to create pipe Too many open files in /Applications/XAMPP/xamppfiles/htdocs/movim/vendor/react/child-process/src/Process.php on line 102`

**Comment by dos1** [comment]
No, you don't need XMPP server.

The logs are clear: your permissions are wrong. Install guide tells you that user from which Movim and webserver are launched needs to be able to write into `cache` and `log` directory. You should fix that.

**Comment by AdarshMaurya** [comment]
These were the logs which I recieved before granting the  rwx permission to log & cache folders. I provided the permissions after those exception logs.

 php.log does logs exception but logger.log seems not to log anything. 

I would look in it again :) and would update this issue. Thank you so much.

**Comment by dos1** [comment]
Ah, okay, I misread :)

I've noticed the redirection to login as well once (like, once in about 30 seconds, right?), but that just went away on its own for me. I'll try to take a look.

**Comment by AdarshMaurya** [comment]
@edhelas : I have uploaded a video so you can have view here  [Login consistent loop issue](https://youtu.be/tQ_SGdZjBKI) - seems like session is being destroyed over and again, hence linker is being disconnected?
 
I did not find a reason even after cleanly following everything in the instruction, it's consistently looping over and again. There are no relevant logs in `log/logger.log` or `log/php.log` except
`[02-Sep-2018 22:46:32 UTC] PHP Warning:  proc_open(): unable to create pipe Too many open files in /Applications/XAMPP/xamppfiles/htdocs/movim/vendor/react/child-process/src/Process.php on line 102` in log/php.log
[php.log](https://github.com/movim/movim/files/2343830/php.log)

**Comment by Minikea** [comment]
@AdarshMaurya 
I have the axact same bug on my fresh install of Movim.
How did you resolve this?

**Comment by edhelas** [comment]
Some changes were made on master regarding how sub-processes are talking to the daemon. can you please try again and report any further information.

**Comment by JOduMonT** [comment]
might not the same issue
but I try to sign up than it loop back to the login page

![movim](https://user-images.githubusercontent.com/5204724/49282286-15520e80-f48f-11e8-9004-48a3ae96467a.gif)

**Comment by edhelas** [comment]
Not the same issue indeed, but still a serious issue. I'll look into it.
