### ISSUE TITLE
installation issues

### ISSUE THREAD

**Issue by OriginMayo** [movim/movim#707]
i have gone through what i believe to be correct installation but i cant get it working properly

www-data@gridux:~/movim$ php daemon.php start --url={gridux.se} --port={3306}
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php-mbstring' - /usr/lib/php/20151012/php-mbstring: cannot open shared object file: No such file or directory in Unknown on line 0

Invalid or missing url parameter

i am however able see the website running...
how do i connect movim to my own xmpp server aswell? or does it come with its own?

**Comment by OriginMayo** [comment]
i suppose maybe changing domain to my own would change where the login occurs?

var Login = {
    domain : '**@movim.eu',**
    submitted : false,
    fillExample : function(login, pass) {
        document.querySelector('input#username').value = login;
        document.querySelector('input#password').value = pass;

**Comment by edhelas** [comment]
Please install php-mstring on your host.
You don't connect Movim to your XMPP server, you can configure at default one in the admin.

**Comment by OriginMayo** [comment]
I already have mbstring for php7 up and running but it still returns me PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php-mbstring' - /usr/lib/php/20151012/php-mbstring: cannot open shared object file: No such file or directory in Unknown on line 0

Should i change where maybe mbstring is located?

**Comment by OriginMayo** [comment]
Oh i found the issue :) disregard it was old stuff from my php ini :)
