### ISSUE TITLE
Additional option: set posting in communities to private per default

### ISSUE THREAD

**Issue by ghost** [movim/movim#709]
Dear developers,

I would like to use communities also for private purposes. For example, I have a private community for my family. It is already possible to restrict the members (whitelist) and set roles - however I noticed, that all postings of members are public by default. 

I see the following problem: If someone (who has a role which is allowed to post), just posts something in my "private" community, this posting is public by default (unless he/she checks the icon which turns to a lock).

Hence, I would suggest an additional option in the community-settings which allows the creator to set the posting to "private" by default.

Best regards,
Tom

**Comment by edhelas** [comment]
All the publications are already private by default.
