### ISSUE TITLE
Printing Blogs - results just one page

### ISSUE THREAD

**Issue by ghost** [movim/movim#712]
Dear maintainer,

when printing a public or private post using the browsers print function, only one page is printed.

Example:
https://nl.movim.eu/?blog/edhelas@movim.eu/how-s-made-movim-part-i-the-architecture-CCA7If

Applies at least for chromium and firefox under linux as well as firefox under windows.

**Comment by edhelas** [comment]
Wow I never really worked on the printing part sorry :D 
Looks like doing a bit of CSS could help.

**Comment by ghost** [comment]
I didn't recognize by myself - However a senior user of my pod prefers printing ;-)

I found a quick fix for this issue, by appending the following lines at the bottom of article.css

```
@media print {
    div#hiddendiv, div#snackbar, div#drawer, div#preview, div#toast, header ul.middle, footer,  nav {
        display:none;
    }
    body {
        background-color:white;
    }
    article, body, main {
        overflow:auto; height:auto;
    }
    div#post_widget {
        max-width: none;
        width:initial;
    }
    main {
        display:block;
        position:relative;
    }
    section {
        padding:0;
    }
    p { 
       hyphens: auto; 
    }
}
```

When viewing the complete article, it is then possible to print the post. As you can see, navigation, comments etc. are hidden. Hyphens are not working at the moment, I guess the language is not set in the html document.
