### ISSUE TITLE
Clarification: Movim and Prosody

### ISSUE THREAD

**Issue by schiessle** [movim/movim#713]
Looking at he Wiki (https://github.com/movim/movim/wiki) I read:

> Prosody (0.10.x) currently doesn't implement the XEP-0060: Publish-Subscribe required to run Movim correctly. Movim will then run in "degraded mode". We recommend you to use another server like ejabberd or OpenFire for now.

But according to the Prosody documentation XEP-0060 is implemented since 0.9+, see https://prosody.im/doc/pubsub and https://prosody.im/doc/xeplist

Is the Movim wiki outdated or what's the exact issue with the XEP-0060 implementation of Prosody?

**Comment by Ppjet6** [comment]
The wiki should be edited to be more specific.

Movim requires the `#persist-items`, [among others](https://github.com/movim/movim/tree/master/lib/moxl#user-content-pubsub-support), feature of PubSub, that is only supported in Prosody Trunk.

**Comment by Ppjet6** [comment]
I [edited](https://github.com/movim/movim/wiki/Home/_compare/f88f703e0e1dac8b3c82a6174b3d0e1b737aa63a...4dfe82d3b19c744f426dd699e11694c657636246) the wiki a bit to reflect prosody's changes in trunk.

There are still *some* missing features, notably [RSM in PubSub](https://issues.prosody.im/1168), and [`pubsub#num_subscribers`](https://issues.prosody.im/1210). I have been using it for a while and I don't see any major issue for what it's worth.

**Comment by schiessle** [comment]
Thanks for clarification.
