### ISSUE TITLE
Can't change state of existing post from public -> private

### ISSUE THREAD

**Issue by ghost** [movim/movim#720]
Dear maintainer,

in order to reproduce the error:
- create a public post
- edit the post again and change the state to private (confirmation on state-change pops up)
- new state is displayed correctly in news-overview
- however, when clicking on the details of the post (which should now be private), it is still public. Other users (which are no contacts) still can read the post.

I don't understand the details and hence don't know if this is a "bug or a feature". If it is a "feature", perhaps it would be helpful to display a note, that the state of a post can't be changed afterwards.

**Comment by edhelas** [comment]
Hi, I made some changes regarding that behavior, going back to private should now work properly. Can you confirm?

**Comment by ghost** [comment]
Dear edhelas, thank you for the update! I pulled the latest git-version and did some tests:

- posts now seem to be private by default (which is a privacy-friendly setting)
- I can successfully change the state from private to public and back again

BUT: posts which are private (according to the settings in movim) **can be read by everyone** (having an account on the same xmpp-server), not only by contacts. In order to reproduce this:
- create two accounts (A and B) on the same xmpp server 
- login to movim and do a private post as user A
- login as B and search for A and show details of person A - > the private post is visible

My first idea was that my xmpp server might by misconfigured, however the error remains when using the official xmpp server from movim.eu

**Comment by edhelas** [comment]
Indeed, you were right! Now visiting a "non-contact" profile should only return public posts.

**Comment by ghost** [comment]
Thank you very much - public/private posting works like a charm now :-)
