### ISSUE TITLE
Movim uploads every attachment as "text/plain".

### ISSUE THREAD

**Issue by maranda** [movim/movim#727]
And of course getting rejected.
Also because it requests a download slow with the correct mime type, and the server will expect that to compute the hash to authorize the upload.

**Comment by maranda** [comment]
Not with Microsoft Edge or wrapped Windows app, tested on nl pod. But could be fixed in trunk perhaps?

**Comment by edhelas** [comment]
As I'm not planning to do further work on this ticket I'm closing it, feel free to comment if you found a way to fix it on Edge.
