### ISSUE TITLE
movim 0.13 seems incompatible with event-loop >=0.5

### ISSUE THREAD

**Issue by pitchum** [movim/movim#728]
I can't remember exactly how I've messed up with my recent install of movim but I ended up with movim daemon working only a few seconds and then crashing with the following trace:

```
Uncaught Error: Call to undefined method React\EventLoop\Timer\Timer::cancel() in /var/www/movim/movim-0.13/src/Movim/Daemon/Session.php:74
Stack trace:
#0 /var/www/movim/movim-0.13/vendor/react/event-loop/src/Timer/Timers.php(89): Movim\Daemon\Session->Movim\Daemon\{closure}(Object(React\EventLoop\Timer\Timer))
#1 /var/www/movim/movim-0.13/vendor/react/event-loop/src/StreamSelectLoop.php(177): React\EventLoop\Timer\Timers->tick()
#2 /var/www/movim/movim-0.13/vendor/cboden/ratchet/src/Ratchet/Server/IoServer.php(74): React\EventLoop\StreamSelectLoop->run()
#3 /var/www/movim/movim-0.13/src/Movim/Console/DaemonCommand.php(103): Ratchet\Server\IoServer->run()
#4 /var/www/movim/movim-0.13/vendor/symfony/console/Command/Command.php(255): Movim\Console\DaemonCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/movim/movim-0.13/vendor/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\C
in /var/www/movim/movim-0.13/src/Movim/Daemon/Session.php (line 74)
```

Indeed [method Timer::cancel() has been removed in 0.5.0](https://github.com/reactphp/event-loop/blob/master/CHANGELOG.md#user-content-050-2018-04-05 ):
> BC break: Documentation for timer API and clean up unneeded timer API. (#102 by @clue)
> 
> Remove TimerInterface::cancel(), use LoopInterface::cancelTimer() instead:
> 
>     // old (method invoked on timer instance)
>     $timer->cancel();
> 
>     // already supported before: invoke method on loop instance
>     $loop->cancelTimer($timer);

As a workaround I solved my problem by forcing the version of event-loop to stick to 0.4.* in *composer.json*:

    "react/event-loop": "^0.4",

And then:

    composer update
    composer install

**Comment by edhelas** [comment]
This has been fixed in master already.

**Comment by edhelas** [comment]
Closing the issue as it is related to 0.13 and 0.14 is released soon.
