### ISSUE TITLE
websocket issue

### ISSUE THREAD

**Issue by ellouze103** [movim/movim#729]
I followed the installation steps in wiki, I serve the daemon at `php daemon.php start --url=https://localhost --port=4481` and add this line `ProxyPass /ws/ ws://localhost:4481/` to apache config file (after `enabling the Secure WebSocket to WebSocket tunneling`).
I got this screen:
![movim](https://user-images.githubusercontent.com/35957548/47444121-1029e180-d7b6-11e8-8e41-6da87f62e012.png)

I serve the app with `php -S localhost:4488`, I got this message: `127.0.0.1:46274 Invalid request (Unsupported SSL request)`!
 
In the navigator I got this error:
![movim2](https://user-images.githubusercontent.com/35957548/47444686-56337500-d7b7-11e8-8fbe-90cfa8f81f40.png)

Any ideas to solve this issue?!

**Comment by edhelas** [comment]
Ok first if you follow the Wiki it actually says:
>  The **public** URL of Movim. For the official pod it is http://pod.movim.eu/, for a test on your own machine it could also be http://localhost/movim/. Don't forget to add the S of HTTPS in your URL if it is enabled on your side. 

Here public means that you put... the public URL, so `--url=https://movim.tn` in your case.
Also it's not weird to server a website on the port 4488?

**Comment by edhelas** [comment]
This looks like a configuration issue more than a bug.
Can you please join our official chatroom and ask for help there: movim@conference.movim.eu.
I'm closing this ticket.
