### ISSUE TITLE
Using multiple devices/tabs breaks commenting

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#734]
I know Movim shares state across devices/browser tabs, but I don't think this "symptom" is intended. It has the potential of having users share private information with users they did not intend to share them with.

1. Open news feed
2. Right click Read More on post X, open in mew tab.
3. Click Like on post Y.
4. Comment on post X in the other tab.

The comment will be added to post Y instead of post X.

**Comment by edhelas** [comment]
This is not actually publishing things on the other post. Simply the UI is refreshing the wrong part. If you reload the page things are going back to normal.

I'll try to add a filter to prevent that.
