### ISSUE TITLE
Better "back" placement

### ISSUE THREAD

**Issue by crosser** [movim/movim#739]
This is a minor thing, but I think it would improve usability: move the back-arrow button that is in the upper left corner to the left toolbar, so it does not get scrolled out, and you can instantly reach it even if you've scrolled many pages down.

**Comment by edhelas** [comment]
I'm not sure if I got exactly what you meant. Can you please provide a picture?

**Comment by crosser** [comment]
My suggestion is to place the backarrow in the left vertical toolbar that is not scrolling with the page
![screenshot from 2018-12-08 12-09-25](https://user-images.githubusercontent.com/1404921/49685375-c89bb280-fae2-11e8-88bb-c93e6d86d223.png)
![screenshot from 2018-12-08 12-10-27](https://user-images.githubusercontent.com/1404921/49685377-cd606680-fae2-11e8-9462-7eca0dbb9c63.png)

**Comment by edhelas** [comment]
It's an idea on desktop yes :) I'll see what I can do.

**Comment by edhelas** [comment]
After having a second though on that one I can't find an easy way to do it without introducing some complex JS to catch the scroll event and so… 
Sorry, but I prefer to keep things simple, also code wise.
