### ISSUE TITLE
Installation docs and code don't match, causing install headaches

### ISSUE THREAD

**Issue by realkinetix** [movim/movim#740]
Problem: On the Movim installation page (https://github.com/movim/movim/wiki/Install-Movim) it states: "Movim needs reading permissions on its root folder and recursively to be deployed properly. It will also try to create two folders:" and mentions cache and log as the folders.

When starting daemon.php, it creates the cache/ folder, but not the log/ folder.  It then complains about not being able to write to the logger.log file (separate issue).

I believe the issue is with the src/Movim/Bootstrap.php file, in "private function checkSystem()", it only checks for the cache folder, not the log folder, so the log folder never gets created as the installation page suggests it's going to.

In the same function, there is another bug in the foreach() loop where it tries to create log/logger.log, log/php.log and cache/test.tmp.  For some reason the touch($fileName) function isn't triggering or creating the files, leaving is_writable to fail.  I did get a php.log with the 'Unable to write to X' errors.  But, it was some interesting hunting this down to figure out why simple file creation wasn't happening.

**Comment by mitchellurgero** [comment]
I am also having this issue, has anyone else resolved this issue yet?

**Comment by realkinetix** [comment]
I think at the moment one has to make the log folder and touch the files it complains about not being able to write to.

I should mention that all the files that the foreach() loop mentioned in Bootstrap.php are not being created - I have validated this setup problem more than a handful of times in the past few days.

**Comment by mitchellurgero** [comment]
The bigger is issue is that because the cache folder cannot be written to properly as www-data, the login and registration loops. I've been able to replicate this issue more than a dozen times now.

**Comment by realkinetix** [comment]
mitchellurgero: Not the same issue as the issue with not creating files upon startup.  In my setup, which certainly has some issues, writing to the cache folder in general isn't an issue.  I'm running the daemon.php as the same user as the php-fpm setup that connects to it.

**Comment by mitchellurgero** [comment]
Docker image has the same issue. As for the folder creation, the issue is both with log/ and cache/ which is what I was trying to say as well. It is related, if not the "same issue" I believe.

**Comment by mitchellurgero** [comment]
Bumping @edhelas to see if he has a known work around.
