### ISSUE TITLE
errors on install starting at migrate

### ISSUE THREAD

**Issue by gstlouisgit** [movim/movim#743]
Hello 
I am trying to get this installed and after a few attempts it fails.  Here are the steps I have followed to get this installed.

I am using centos7
PHP 7.0.33 (cli) (built: Dec  5 2018 14:22:44) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

I walked through the installation guide to ensure dependencies here: https://github.com/movim/movim/wiki/Install-Movim#get-started](url)
notice later I get this error:

> PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/zmq.so' - libzmq.so.5: cannot open shared object file: No such file or directory in Unknown on line 0

However, prior I had installed it with yum install php-zmq

steps:
`git clone https://github.com/movim/movim`

`curl -sS https://getcomposer.org/installer | php`

` php composer.phar install`

` php composer.phar update`

`php vendor/bin/phinx migrate` - errors started

  [Illuminate\Database\QueryException]                                                                                                                                                                   
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `capabilities` add primary key `capabilities_node_primary`(`node`))  
                                                                                                     
  [Doctrine\DBAL\Driver\PDOException]                                                                              
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes  
                                                                       
  [PDOException]                                                                                                   
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes 

`php daemon.php start --url=movim --port=8080`

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/zmq.so' - libzmq.so.5: cannot open shared object file: No such file or directory in Unknown on line 0

An error occured, check syslog for more information
An error occured, check syslog for more information
The database needs to be migrated before running the daemon
To migrate the database run
php vendor/bin/phinx migrate ( which I have done and get those DB errors )

the user interface itself works great going to the url, but of course its looking for the msging server.

I use prosody ( I understand not all features will work and will look at ejabberd or openfire )

is it important to have the XMPP Server on the local machine or can I point it somewhere?

Thanks for the help,
Guy

**Comment by edhelas** [comment]
What MySQL version do you have ?

**Comment by gstlouisgit** [comment]
sorry
mysql  Ver 15.1 Distrib 5.5.60-MariaDB, for Linux (x86_64) using readline 5.1

**Comment by edhelas** [comment]
From https://github.com/movim/movim/wiki/Install-Movim#get-started

> MySQL 5.7 or higher with utf8mb encoding
> MariaDB 10.2 or higher with utf8mb encoding

For php-zmq you don't need it anymore since 0.14.1 (current master), I've just updated the documentation

**Comment by gstlouisgit** [comment]
thanks for that
I have upgraded to mysql  Ver 15.1 Distrib 10.3.11-MariaDB, for Linux (x86_64) using readline 5.1

I drop and create a new DB
ran `php vendor/bin/phinx migrate` and everything looked fine

I also ran this as well, not sure if good idea
`php vendor/bin/phinx seed:run -s FromModlToEloquent`
**output:**
Phinx by CakePHP - https://phinx.org. 0.9.2

using config file ./phinx.php
using config parser php
using migration paths 
 - /home/movim/public_html/movim/database/migrations
using seed paths 
 - /home/movim/public_html/movim/database/seeds
warning no environment specified, defaulting to: movim
using adapter mysql
using database movim

 == FromModlToEloquent: seeding

  [Illuminate\Database\QueryException]                                                                                          
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'movim.config' doesn't exist (SQL: select * from `config` limit 1) 

  [Doctrine\DBAL\Driver\PDOException]                                                     
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'movim.config' doesn't exist    
                                                                                      
  [PDOException]                                                                          
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'movim.config' doesn't exist

seed:run [-c|--configuration CONFIGURATION] [-p|--parser PARSER] [-e|--environment ENVIRONMENT] [-s|--seed SEED]

When I ran this 
`php daemon.php start --url=http://movim --port=8080`

I received this output:

An error occured, check syslog for more information
An error occured, check syslog for more information
Movim daemon launched
Base URL: http://movim/

--- Server Configuration - Apache ---
Enable the Secure WebSocket to WebSocket tunneling
a2enmod proxy_wstunnel 
Add this in your configuration file (default-ssl.conf)
ProxyPass /ws/ ws://localhost:8080/

--- Server Configuration - nginx ---
Add this in your configuration file
location /ws/ {
    proxy_pass http://localhost:8080/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect off;
}

Unencrypted 

log error from logs/php.log

[16-Dec-2018 19:37:51 UTC] PHP Notice:  Use of undefined constant CURLOPT_UNIX_SOCKET_PATH - assumed 'CURLOPT_UNIX_SOCKET_PATH' in /home/movim/public_html/movim/app/helpers/UtilsHelper.php on line 587

[16-Dec-2018 19:37:51 UTC] PHP Warning:  curl_setopt() expects parameter 2 to be integer, string given in /home/movim/public_html/movim/app/helpers/UtilsHelper.php on line 587


I have prosody on another local machine.  Is there a way to point to this machine that in the user interface under http://movim/movim/?account it will display my server to subscribe to it?

**Comment by edhelas** [comment]
Well if you started with a blank DB, you don't need to run FromModlToEloquent.

**Comment by edhelas** [comment]
If you need support for the deployment I strongly invite you to join the official Movim channel movim@conference.movim.eu as it seems that the things there are not related to Movim issues but more about how to configure it :)

**Comment by gstlouisgit** [comment]
well given that I am still getting 'An error occured, check syslog for more information' when I start
`php daemon.php start --url=http://movim --port=8080`
I assume I am not out of the woods yet!
**log/php.log output:**
PHP Notice:  Use of undefined constant CURLOPT_UNIX_SOCKET_PATH - assumed 'CURLOPT_UNIX_SOCKET_PATH' in /home/movim/public_html/app/helpers/UtilsHelper.php on line 587

PHP Warning:  curl_setopt() expects parameter 2 to be integer, string given in /home/movim/public_html/app/helpers/UtilsHelper.php on line 587

How do I subscribe to Movim channel?  Are you sure you can't share where the config is so I can point it to another machine hosting a xampp server?  Or if on a wiki somewhere I can read up would be nice.  So I can officially say I got this up and running would be a win for me :P

**Comment by gstlouisgit** [comment]
error: 
PHP Notice: Use of undefined constant CURLOPT_UNIX_SOCKET_PATH - assumed 'CURLOPT_UNIX_SOCKET_PATH' in /home/movim/public_html/app/helpers/UtilsHelper.php on line 587

Apparently this might be due to my version of php 
https://bugs.php.net/bug.php?id=72522&edit=1

I upgraded php to 7.3 and it did not fix the problem.
PHP 7.3.0 (cli) (built: Dec  4 2018 16:12:20) ( NTS )

**Comment by JKingweb** [comment]
The PHP bug suggested upgrading the cURL library, not PHP. If PHP is linking against a shared curl library older than 7.40, the constant will not be present.

**Comment by edhelas** [comment]
@JKingweb thanks :) So I don't think that it's related to Movim?

**Comment by JKingweb** [comment]
Probably not, but Movim perhaps should check the cURL version (`curl_version()['version']`) and bail with a more helpful error if it's too low.

**Comment by edhelas** [comment]
Well if I do that I have to start to check all the other dependencies versions as well.
It's something that was done in the past but was removed after a while.

So I'm closing this ticket :)

**Comment by gstlouisgit** [comment]
Thanks for clarifying that error to lead me to a fix @JKingweb 

I had curl -V was 7.29 and from what I read I needed 7.40+.  I found how to update curl [here](https://serverfault.com/questions/321321/upgrade-curl-to-latest-on-centos)

After update curl -V gives me curl 7.63.0

reboot httpd, load `php daemon.php start --url=http://movim --port=8080` and I still get the error in log

PHP Notice:  Use of undefined constant CURLOPT_UNIX_SOCKET_PATH - assumed 'CURLOPT_UNIX_SOCKET_PATH' in /home/movim/public_html/app/helpers/UtilsHelper.php on line 587
PHP Warning:  curl_setopt() expects parameter 2 to be integer, string given in /home/movim/public_html/app/helpers/UtilsHelper.php on line 587

I know @edhelas is eager to close this off ;) . But you guys got any other ideas why this would be happening? 
 
This should be my only problem.  I have Prosody up and running on the machine as well...

**Comment by JKingweb** [comment]
Is PHP actually using the updated library? What does the following output?

`php -r "echo curl_version()['version'];"`

**Comment by gstlouisgit** [comment]
I think so.
[root@stage ~]# php -r "echo curl_version()['version'];"
7.63.0[root@stage ~]#

**Comment by edhelas** [comment]
Again, please join the official chatroom for such deployment support : movim@conference.movim.eu.
If you need to find how to join that chatroom using XMPP, there's plenty of tutorials and clients online to do so.

Also, when you are pasting or writing messages I invite you to use formatting to make them more readable https://guides.github.com/features/mastering-markdown/ :)
