### ISSUE TITLE
TypeError: discussion is null

### ISSUE THREAD

**Issue by mirabilos** [movim/movim#745]
TypeError: discussion is null
	

    discussion.onscroll = function() {

chat.js...3771365 (line 273, row 9)

**Comment by edhelas** [comment]
Same here, all those tickets are linked by, I think a server issue.

**Comment by edhelas** [comment]
As I know you had server issues. This can generate faulty HTML, the JS is relying on the presence of this HTML, therefore this issue is caused by the backend issue that need to be solved and not a JS issue.
