### ISSUE TITLE
SecurityError: The operation is insecure.

### ISSUE THREAD

**Issue by mirabilos** [movim/movim#747]
window.history.pushState(null, '', url);

movim_utils.js...3771365 (line 100)

**Comment by edhelas** [comment]
What is the url, under which page where you, what were you doing ?
Seriously…

**Comment by edhelas** [comment]
From what I see from the first link on Stackoverflow while searching "SecurityError: The operation is insecure window push history" this looks like a misconfiguration server side.
https://stackoverflow.com/questions/13348766/securityerror-the-operation-is-insecure-window-history-pushstate

Not enough information. I'm closing this ticket.
