### ISSUE TITLE
No layout on chat page

### ISSUE THREAD

**Issue by jaydouble** [movim/movim#754]
I've just installed Movim, but there is one issue that make it useless... On the chat page, there is no base. It looks like the chat page is rendered RAW, without the base page.tpl.

![image](https://user-images.githubusercontent.com/3264300/50334001-3e524600-0507-11e9-9bac-672b856d28b1.png)

and the source of the page looks like:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/3264300/50334034-588c2400-0507-11e9-80f7-4800f4c6a8c3.png">

So the chat page (the reason why you should install something like this) is not rendered right.

How to fix this?

**Comment by edhelas** [comment]
Can you please check the PHP logs ?

**Comment by jaydouble** [comment]
There is nothing in it: (only those 2 lines)
```bash
cat /var/www/vhosts/movim/log/php.log 
[20-Dec-2018 15:33:51 UTC] PHP Warning:  unlink(/var/www/vhosts/movim/cache/socketapi.sock): No such file or directory in /var/www/vhosts/movim/src/Movim/Daemon/Core.php on line 207
[21-Dec-2018 07:17:51 UTC] PHP Notice:  Trying to get property of non-object in /var/www/vhosts/movim/lib/moxl/src/Moxl/Stanza/Presence.php on line 22
```

**Comment by edhelas** [comment]
Can you please pull master and tell me if this issue is still happening?

**Comment by jaydouble** [comment]
Hmm... strange...

I Could open the community tab. From there I could click on the search button, and there I started a chat, and now it is working fine....

Still no clue how this can happen....

**Comment by edhelas** [comment]
Closing the issue
