### ISSUE TITLE
Cannot join a MUC while online with another client (*different* nickname)

### ISSUE THREAD

**Issue by mirabilos** [movim/movim#757]
In the version installed on commu.teckids.org today (@Natureshadow would know which this is; I can’t find a version indicator in the web frontend… which, thinking of it, probably should show the Debian package version when installed using the packages) I (still) cannot join a MUC while online with mcabber, **even** if I select a different nick (`mirabilos|movim`) from the one used by mcabber.

**Comment by edhelas** [comment]
I'll have a look at that. The commit hash is on this page https://commu.teckids.org/movim/?infos ;)

**Comment by edhelas** [comment]
I can join a room on my side using the same account and even the same . I'll need a bit more information. What MUC did you tried to join? What does the XMPP logs are saying?

On my side for example I got:

```xml
>>> Sending the second presence
<presence xmlns="jabber:client" from="test@movim.eu/movimjWdrPw" id="gt6psc" to="chat@conference.movim.eu/test">
    <x xmlns="http://jabber.org/protocol/muc">
        <history maxchars="0"/>
    </x>
</presence>

<<< Receiving the ACK
<presence to='test@movim.eu/movimjWdrPw' from='chat@conference.movim.eu' id='16846851161609715786'>
    <c ver='EYnaKdYiiCNYuP5Mcdzm88kLIhw=' node='http://www.process-one.net/en/ejabberd/' hash='sha-1' xmlns='http://jabber.org/protocol/caps'/>
</presence>
<<< Receiving the first presence from pidgin
<presence xml:lang='en' to='test@movim.eu/movimjWdrPw' from='chat@conference.movim.eu/test'>
    <c xmlns='http://jabber.org/protocol/caps' node='http://pidgin.im/' hash='sha-1' ver='AcN1/PEN8nq7AHD+9jpxMV4U6YM=' ext='voice-v1 camera-v1 video-v1'/>
    <x xmlns='vcard-temp:x:update'><photo/></x>
    <x xmlns='http://jabber.org/protocol/muc#user'><item jid='test@movim.eu/1052123434454628095442946' role='moderator' affiliation='owner'/></x>
    <priority>1</priority>
</presence>
```

Movim is then merging the two presences in one.

**Comment by Natureshadow** [comment]
@mirabilos keeps reporting this to me over and over again, and I keep saying we need to debug it together, but he never followed up on it. There are also known compatibility issues with his version of mcabber, which he ignores and blames on Movim... That said, everyone and their dogs can join MUCs under the described circumstances without issues, on the same instance and the same XMPP server.

**Comment by edhelas** [comment]
¯\_(ツ)_/¯ looks like a weird edge case that will need "pair debugging" indeed.

**Comment by mirabilos** [comment]
Dominik George dixit:

>@mirabilos keeps reporting this to me over and over again, and I keep
>@saying we need to debug it together, but he never followed up on it.

Did you ever try to reproduce it?

>@There are also known compatibility issues with his version of
>@mcabber, which he ignores and blames on Movim... That said, everyone

Excuse me, if mcabber can join and Movim can’t, how is this
mcabber’s fault?

Besides, if there were a known bug, you’d surely have reported
this to Debian already and could cite BTS numbers.

>@and their dogs can join MUCs under the described circumstances
>@without issues, on the same instance and the same XMPP server.

Their dogs shouldn’t have the passwords ;)

**Comment by Natureshadow** [comment]
>Did you ever try to reproduce it?

No, because, as I said, you never followed up on that approach :D.

**Comment by mirabilos** [comment]
Dominik George dixit:

>>Did you ever try to reproduce it?
>
>No, because, as I said, you never followed up on that approach :D.

Eh, you don’t need me for an apt-get install mcabber…
but, sure, we can do that some day.

**Comment by Natureshadow** [comment]
> Nik said something about this being a general issue under Firefox,
> I can’t understand how joining a MUC in a webäpp can depend on
> the browser when everything else works though…

I did not say that. I said I have seen MUC joining issues on *old*
versions of Firefox (i.e. ≪ $esr).

**Comment by edhelas** [comment]
I'm closing the ticket. This seems to be a really specific edge case and I have other priorities.
