### ISSUE TITLE
Tags detected in inline code on blogposts

### ISSUE THREAD

**Issue by phoe** [movim/movim#760]
https://nl.movim.eu/?blog/phoe%40movim.eu/answers-from-2017-common-lisp-experts-introduction-and-table-of-contents-fMQOSd

![zrzut ekranu z 2018-12-23 12-44-36](https://user-images.githubusercontent.com/15045546/50383276-8496d900-06b0-11e9-8805-0cb51ecb1ca3.png)

The `#lisp` in inline code has been detected as a Movim tag - I do not think this is intended.

**Comment by edhelas** [comment]
This is also considered as a wontfix, starting to avoid hashtags detection regarding what is around is something (really) complex. Twitter is also detecting it the same way.

I prefer to use a simple Regex https://github.com/movim/movim/blob/master/app/helpers/StringHelper.php#L113.
