### ISSUE TITLE
Tags do not include commas

### ISSUE THREAD

**Issue by phoe** [movim/movim#761]
https://nl.movim.eu/?blog/phoe%40movim.eu/common-lisp-ultraspec-progresslessness-2niZfL

![zrzut ekranu z 2018-12-23 12-51-02](https://user-images.githubusercontent.com/15045546/50383318-70071080-06b1-11e9-9c24-0f8f1f8a23e0.png)

Using a tag like `#common-lisp` is impossible.

**Comment by edhelas** [comment]
This is not planned, the hashtag detection in Movim is using only word-characters (number, letters, underscore).
