### ISSUE TITLE
Min size limitation in Picture.display()

### ISSUE THREAD

**Issue by guillaume-u** [movim/movim#762]
Hello,

I don't understand why there is a min size limitation in "movim/app/widgets/Picture/Picture.php:17"

` && $headers["download_content_length"] > 2000`

It was created in this commit **bf185e3a365c138685567f6a8f5927cee9e432ac** and increased from 100 to 2000 in this commit : **91b877aec5c3a84a8eb5bcb7c20572c7b12307d2**.

For my usage, 2000 is too high, but maybe there is a reason to set this value.

Thanks.

Guillaume.

**Comment by guillaume-u** [comment]
Thanks @edhelas :)

This value (2000) does not permit to share an avatar / icon.  Do you remember why you increased it to this value ?

Is it a big issue to permit one pixel image ? (as it's downloaded on the server, it's not possible to make a web beacon — maybe I'm wrong.)

**Comment by edhelas** [comment]
It's 2000 bites afaik, if your avatar/icon falls under ~2kb I think it's small enough to not be processed by this part of the code.

**Comment by edhelas** [comment]
Closing this ticket as I'm not planning to change this behavior anytime soon.
