### ISSUE TITLE
WYSIWYG Markdown editor

### ISSUE THREAD

**Issue by crosser** [movim/movim#763]
Most of us are comfortable with Markdown, but in order to offer this service to wider audience it is essential to have more wysiwyg text editor for posting articles and comments. Something very basic like tumblr editor should be enough, though there is a big selection of javascript editors to chose from, e.g.: https://github.com/JefMari/awesome-wysiwyg

**Comment by edhelas** [comment]
After having a second though, and even if this feature is interesting I'm closing it as I'm not planning to work on it in the mid-long term.
