### ISSUE TITLE
Feature request: Automatic "enrichment" of media links

### ISSUE THREAD

**Issue by crosser** [movim/movim#764]
It is possible to automatically "enrich" links to some well-known media hosting services, like YouTube. E.g. if you have a link

https://www.youtube.com/watch?v=XZGMPD9rmQA

you can convert it into this Markdown:

```
[![](http://img.youtube.com/vi/XZGMPD9rmQA/0.jpg)](http://www.youtube.com/watch?v=XZGMPD9rmQA)
```
The result will be:

[![](http://img.youtube.com/vi/XZGMPD9rmQA/0.jpg)](http://www.youtube.com/watch?v=XZGMPD9rmQA)

Making "normal users" produce such Markdown by hand is too much to ask. Automating it would help mainstream adoption.

**Comment by crosser** [comment]
It could be a feature of the "Add link" dialogue. That would cover "simple" cases, which would be 99% of what "normal people" are doing. Those who put multiple links in a post will be able to do the job themselves.

And it is not necessary to resolve the links. Some sloppy regexp magic to convert links to a dozen most popular media hosting services should be sufficient.

Would you reconsider?

**Comment by edhelas** [comment]
The question is how to handle those info into the Atom standard attachment :) From what I know it's simply not possible to embed thumbnails and info in a wait to do a proper "preview box".

Movim is on the other side embeding Youtube videos this way https://github.com/movim/movim/blob/master/app/Post.php#L503 and https://github.com/movim/movim/blob/master/app/widgets/Post/_post_card.tpl#L93. Yes this can be extended, you're welcome to propose PR to improve this to other cases.

**Comment by crosser** [comment]
I agree that your existing approach is good enough.

I would still suggest that hosting-service-specific code is isolated in a "plugin", a separate file or a couple of files in a specific directory in the source tree. That would make contributing plugins for new services much easier.
