### ISSUE TITLE
Feature request: Embedded audio and video playback

### ISSUE THREAD

**Issue by crosser** [movim/movim#765]
Movim automatically embeds image attached via httpuload. It is possible to httpupload and attach video and audio files, but they are presented as http(s) links in the displayed message. Given that modern HTML allows easy embedding of a media player node, it would make sense to do it automatically when displaying a message with such links.

This would put Movim on par with Tumblr, feature-wise.

**Comment by edhelas** [comment]
Are we talking about Chat or Posts messages there. In both ways Movim is for now not made to handle the multimedia files correctly conversion, different formats/resolutions… 
I prefer to focus on pictures at the moment, such feature will require a lot of extra works to be done correctly. This is not planned in the middle long-term.

**Comment by Natureshadow** [comment]
> Are we talking about Chat or Posts messages there. In both ways Movim is for now not made to handle the multimedia files correctly conversion, different formats/resolutions… 
> I prefer to focus on pictures at the moment, such feature will require a lot of extra works to be done correctly. This is not planned in the middle long-term.

I see that a bit differently: Movim should keep its hands away from both
images and audio and video, but still render them wit htheir
corresponding HTML features. It's the job of the HTTP upload component
to provide a thumbnail, which Movim can use if it is provided, and it's
the browser's job to play adio and video or not.

**Comment by crosser** [comment]
I agree with @Natureshadow, movim should not bother about format conversion. Just present media-looking URLs as &lt;video&gt; and &lt;audio&gt; HTML elements, exactly the same way as it does with &lt;img&gt;.

**Comment by edhelas** [comment]
This is not planned on the mid-long term and would require lots of time to be done properly. I'm closing the ticket to keep the bug listed to the one that I want to work on and that I have time to do so.
