### ISSUE TITLE
Registration form refreshes in 30 sec (And linker also disconnected frequently)

### ISSUE THREAD

**Issue by sandeepbisht** [movim/movim#766]
In my environment Movim(0.14.1rc) and ejabbered(18.01) configured

Ejabbered registration module is enabled.And on selecting my local server in Movim sign-up section registration form is visible.

But I am facing two problem

1)Exact after 30 sec registration page refreshes and it is redirected to login section.

I do some changes in movim to print received messages and find that in-between this 30 sec ping request received and sending pong response.

after 30 sec Ejabber logs are as follows 
018-12-29 11:44:27.655 [debug] <0.588.0>@xmpp_socket:send:218 (tcp|<0.588.0>) Send XML on stream = <<"<stream:error><connection-timeout xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:error>">>

2)Linker behaviour is as follow
i)Linker once **disconnected** inbetween this 30 sec and if i write sometext in username/password;that text is removed but registration page is visible.
ii)linker killed after getting connection-timeout from ejabber
iii)In idle case(when there is no action) linker is disconnecting frequently.

**Comment by crosser** [comment]
It is especially annoying when admin page gets reloaded into the main page after half a minute of inactivity.

**Comment by edhelas** [comment]
I added a few exception to prevent the reload/redirect to login on some pages.

**Comment by edhelas** [comment]
As this has been refactored to prevent such behaviors, it should have been fixed a while ago.
