### ISSUE TITLE
"Comments disabled" on all posts without likes

### ISSUE THREAD

**Issue by crosser** [movim/movim#769]
On my two fresh pods, I observe this: all posts made on the pod (from local account) have "Comments disabled", *until* they are "liked". Once the post is "liked", it becomes possible to comment.

There have been several similar tickets, #149 #550 #625 that are closed. One [comment](//github.com/movim/movim/issues/149#issuecomment-366459109) on one of them describes exactly my problem, but it is not clear if it was addressed in any way.

If this is intentional behaviour, it should be made clear to wound-be-commenter that they must like the post before commenting. If it is unintentional, it would be nice to have it fixed.

**Comment by edhelas** [comment]
It is unintentional. Would it be possible to know what XMPP server are you using?

**Comment by crosser** [comment]
xmpp:average.org (but there is no registration on that instance, it uses PAM authentication. You can send me public ssh key and preferred username and I will create a user for you, then you set password that will be usable with jabber).

This https://www.average.org/movim/?community/pubsub.average.org/average-jabber is an example with two posts, one has a like and can be commented on, another has no likes and shows as "comments disabled".

Of course I followed the documentation!

**Comment by crosser** [comment]
@edhelas, you can reproduce it on xample.average.org. It runs stock ejabberd and nginx and freshly-pulled movim from master as of this comment.

**Comment by nullatmidnight** [comment]
I can also confirm that I too have the same issue, also running ejabberd.

**Comment by Trim** [comment]
On my side, last 2-3 posts I've made have too the "Comments disabled" message (see https://mov.adorsaz.ch and contact adrien@adorsaz.ch , for example [this post](https://mov.adorsaz.ch/?post/adrien%40adorsaz.ch/urn%3Axmpp%3Amicroblog%3A0/utilisation-de-gtktreemodel-gtktreeview-et-consorts-zjW9vs)).

Could we add a button to enable or disable comments on personal blogs for the author of the blog ?
I mean, on the `urn:xmpp:microblog:0` namespace of my account, I should be able to enable or disable comments on each post.

With such a button, the user can force to enable back comments and Movim will be able to say him "XMPP server wasn't able to do it" on error or "Comments enabled for anyone" on success.

This could even bee a nice feature as some authors like to disable comments on some posts which could be provoking.

Maybe, it could be good too to enable this feature for communities, but not sure right now, as communities can already be configured with advanced options.

Edit: I forgot to say I'm using ejabberd from Debian Stretch backports (18.12.1-2~bpo9+1) with Movim pulled from current master ( d75050c22 ).

**Comment by crosser** [comment]
> @edhelas, you can reproduce it on xample.average.org. It runs stock ejabberd and nginx and freshly-pulled movim from master as of this comment.

I am shutting down xample.average.org. (I kept it until now in the hope that, as a place where several issues can be easily reproduced, it could be a help for debugging.)

**Comment by edhelas** [comment]
Closing this ticket. Pubsub and Comment configuration can be done using the dedicated part on our Wiki https://github.com/movim/movim/wiki#2-configure-your-xmpp-server
