### ISSUE TITLE
Community: suggest community servers on first start

### ISSUE THREAD

**Issue by guillaume-uH57J9** [movim/movim#770]
Consider improving Movim by suggesting some Community and/or Community servers on first start, to provide new users with a nicer user experience. 

I recently started using a self-hosted Movim pod, and the Community page was a little empty. I suspect this occurs because I am self-hosted so there's no Community yet on that server, and only a handful of my contacts are using Movim/pubsub (but I'm working on that part).  
There should be ways to bootstrap new users, and make it easier for them to find content and Communities in Movim. 

Community and Community servers could come from a few places: 
* Enumerate pubsub servers by looking at the user's contact, or the contact's server. I don't know exactly how pubsub and XMPP interact, but there must be some to find which pubsub server a contact/JID is using. 
* Retrieve a directory of pubsub servers hosted either on movim.eu, or from a git page (allows modifying via pull requests), or through any native directory mechanism available in XMPP. 
* Distribute a hardcoded list of popular pubsub servers in the Movim software (pubsub.movim.eu et al)

**Comment by crosser** [comment]
I think that simply letting the administrator specify the list of suggested servers in the admin interface would fit the widest variety of use cases.
