### ISSUE TITLE
XMPP CAPTCHA is not shown on signup page

### ISSUE THREAD

**Issue by crosser** [movim/movim#771]
ejabberd with CAPTCHA-protected registration enables sends a form containing &lt;media&gt; element referring to the included &lt;data&gt; element with the PNG image. (It also contains a text field with type=url as a fallback.).

&lt;media&gt; element is not handled by movim (lib/XMPPtoForm.php), and there is no CAPTCHA image on the registration page.

attached is a (cut down) result of the query 'jabber:iq:register' sent by ejabberd.

[CAPTCHA.xml.txt](https://github.com/movim/movim/files/2716653/CAPTCHA.xml.txt)

**Comment by edhelas** [comment]
Would it be possible to know on which XMPP server you have such behavior (the domain), then I can try to reproduce?

**Comment by crosser** [comment]
@edhelas, I've spawned another server specially to let you play:
```
xample.average.org
```
(not a typo, without 'e').
You can have root access there if you wish, just send me your ssh public key.
