### ISSUE TITLE
Logout causes reload(?)/change protocol loop

### ISSUE THREAD

**Issue by realkinetix** [movim/movim#772]
Clicking the logout button in Movim, whether it's in Firefox on desktop or via the Android app, causes a  loop.  

Clearing the browser cache stops the issue, so I can only guess that it has to do with some element that isn't cleared properly at the end of the session?  

I've witnessed this behaviour in each movim version I've tried from v0.14, but can confirm I'm having the issue as of today's git pull.

My nginx logs look like this from when the logout button is clicked (in Firefox desktop anyway):

MyIP - - [02/Jan/2019:11:54:29 -0800] "GET /ws/?path=&offset=480 HTTP/1.1" 101 85608 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
MyIP - - [02/Jan/2019:11:54:29 -0800] "GET /themes/material/css/listn.css?t=1546453919 HTTP/2.0" 200 11166 "https://movim.isurf.ca/" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
MyIP - - [02/Jan/2019:11:54:29 -0800] "GET /ws/?path=&offset=480 HTTP/1.1" 101 24 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
MyIP - - [02/Jan/2019:11:54:30 -0800] "GET /ws/?path=&offset=480 HTTP/1.1" 101 4286 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
MyIP - - [02/Jan/2019:11:54:30 -0800] "GET /ws/?path=&offset=480 HTTP/1.1" 101 87429 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"
MyIP - - [02/Jan/2019:11:54:30 -0800] "GET /ws/?path=&offset=480 HTTP/1.1" 101 87429 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0"

My nginx configs are as specified by the movim daemon for the /ws/ location.

**Comment by crosser** [comment]
This happens to me too, but only on one installation and not the other. Both use recent master.

**Comment by edhelas** [comment]
This was a misconfiguration on the HTTP server, the server was forcing HTTP pages to be cached…

```
HTTP/2.0 200 OK server: nginx/1.14.1 
...
20:39:13 GMT; Max-Age=604800; path=/ 
access-control-allow-origin: * referrer-policy: strict-origin-when-cross-origin 
expires: Fri, 11 Jan 2019 20:39:13 GMT 
cache-control: max-age=604800
```

Before reporting any issues there, please ensure that you didn't added configuration on your server that are creating such hazardous behaviors.

**Comment by crosser** [comment]
To disable caching in Apache, include these directives in the section defining movim location (e.g. &lt;Directory&gt;). It relies on presence of `mod_headers`:
```
Header set Cache-Control "max-age=0, no-cache, no-store, must-revalidate"
Header set Expires "Wed, 11 Jan 1984 05:00:00 GMT"
```
Tested, works for me.
