### ISSUE TITLE
Whitelist doesn't remove default XMPP server

### ISSUE THREAD

**Issue by nullatmidnight** [movim/movim#773]
If you limit registration only to your own XMPP server via the allowed whitelist, the default movim.eu server is still displayed.

**Comment by edhelas** [comment]
Good find!

**Comment by crosser** [comment]
IMO when you specify *default* xmpp server (and have empty whitelist), movim.eu should not be present as a registration option either.

**Comment by realkinetix** [comment]
I would like to see this happen too - and another server beyond movim.eu showed up in the allowed registration list - aajut.cm.   Would be interesting to know how that happened.

At any rate, I have only one whitelisted XMPP server, but I have 3 showing for account registrations:

https://movim.isurf.ca/?account
