### ISSUE TITLE
Notification count and site icon incorrect

### ISSUE THREAD

**Issue by crosser** [movim/movim#774]
This might be the same problem as #654, but I observe it as the count in the notification column and in the site icon being non-zero despite no unread messages are shown. 
![screenshot from 2019-01-03 09-05-55](https://user-images.githubusercontent.com/1404921/50628549-cd645280-0f38-11e9-990c-5cfd2797afff.png)
Screenshot above happened instantly on first login of a freshly created user.

Another frequent case is a groupchat that has N messages that has been read, suddenly showing N unread messages again. This happens after a day or two.

**Comment by edhelas** [comment]
For the MUC (groupchat), this can happen after a redirect on MUC that doesn't have MAM enabled. It's a XMPP configuration issue on their side.

**Comment by crosser** [comment]
"Their" side is also my side, and yes, MAM is not enabled.
Should this be documented as a known issue, perhaps with a hint how to fix it?

**Comment by edhelas** [comment]
This is not considered as an issue on my side and I'd prefer to not over-complicate the documentation.

**Comment by crosser** [comment]
1. given that movim is currently the only application that uses xep-0060, how are movim users expected to troubleshoot a problem that _manifests_ as incorrect data in movim?
2. Not enabled feature is not a _bug_ on XMPP side, it's just a non enabled feature. It MAM is a _required_ for movim, and it is not enabled, movim should complain loudly, so the user knows what to fix. If it is not required, movim should continue to work correctly. In neither case should it continue to work but display wrong data.

I accept that this is a very minor issue, but I do not agree that it is a "not movim's problem".

**Comment by edhelas** [comment]
First MAM is not relying at all on 0060 for this case.

Secondly we provide already a minimal configuration documentation for Prosody and ejabberd https://github.com/movim/movim/wiki#xmpp-servers. Yes we can complete this configuration with all the tricks and tips, IF they are not set like this by default, with a proper explanation. And I'd be please to accept modifications on the documentation to do so.

It is kinda a Movim problem yes but I'm trying to find a balance between having 20 pages of documentation that will get outdated if the ejabberd/prosody… guys are updating their config and a simple setup that "by default" works.

The XEP-0412: XMPP Compliance Suites 2019, like several ones before ask to have MAM enabled by default https://xmpp.org/extensions/xep-0412.html .

**Comment by crosser** [comment]
In the particular case that I reported though, MUC was not involved, as can be seen on the screenshot.

I can give you access to this server if you wish.

**Comment by edhelas** [comment]
https://github.com/movim/movim/commit/31156db187f0b7b35ea09498519bfd656c794c8f fixes the issue :)
