### ISSUE TITLE
General Settings - Restrict suggestions Toggle Resets

### ISSUE THREAD

**Issue by nullatmidnight** [movim/movim#775]
I hope someone could also test this out just so this isn't just a cache/browser issue. For some reason, the toggle switches back to disabled (grayed out) when I re log back into the admin panel. Reloading the page will keep the saved state, it's only when I log out and back in.

I believe the setting is being saved because I do see the message about the restriction to only this XMPP server, however the toggle resets to disabled.

**Comment by edhelas** [comment]
@Natureshadow this fixes an old bug that you reported me a while ago I think :)

**Comment by edhelas** [comment]
Whoops, wrong issue number, the fix for that one is https://github.com/movim/movim/commit/404b99e2d9b65bd1e235d3baee5eec8f6ff48c0a
