### ISSUE TITLE
Suggestion - Change Remove Contact Icon

### ISSUE THREAD

**Issue by nullatmidnight** [movim/movim#776]
So I noticed that when you add a contact from their contact page, you see a user with a plus icon. However, if you want to remove that contact, the icon is changed to a trash can, which is confusing since you assume it's to delete a post and not the following contact user.

**Comment by edhelas** [comment]
This can easily picked up by anyone that know how to do a PR.

**Comment by nullatmidnight** [comment]
Hmm, I noticed the theme icon set provided by Google doesn't have a person_minus, only a person_add. I guess it could be possible to simplify by replacing the person_add with an add_circle and then a remove_circle?

**Comment by edhelas** [comment]
I'm not a big fan of the remove circle icon as well.

**Comment by nullatmidnight** [comment]
Yeah, I think that would be too confusing with the plus icon being used for adding a post. How about a Follow/Unfollow button?

**Comment by nullatmidnight** [comment]
I sent a request to Google for the person icon set but they're known for Google Plus, not minus, lol.

**Comment by edhelas** [comment]
Because there is no proper icon for now I'm closing the ticket, let's see how this pack evolves and reconsider the problem then.
