### ISSUE TITLE
Pubsub Community Removal Bug

### ISSUE THREAD

**Issue by nullatmidnight** [movim/movim#777]
It seems if you create a new community and do not add a post, when you return, it will send you a pop up notice "It seems that this community doesn’t exists anymore. Do you want to remove it from your subscriptions?"

If you cancel and then add a post, the pop up will go away and a no named temp community will appear in its place (with the official one you created). You can then delete the random one and everything will work.

**Comment by edhelas** [comment]
I can't reproduce this issue on my XMPP server. From what I see in the code, this pop-in is only displayed when the XMPP Pubsub, on this node explciitely, is returning an error when trying to retrieve the items (posts), this is not triggered when there's no items. So I would need more information on that side to try to understand more.

**Comment by nullatmidnight** [comment]
Found out in the log, seems that there was var error on the mod_pubsub set wrong due to a commented out line on the same line.
