### ISSUE TITLE
Cannot copy (mark) text

### ISSUE THREAD

**Issue by mirabilos** [movim/movim#779]
When I want to mark the body text of [this post](https://chat.teckids.org/?post/edhelas%40movim.eu/urn%3Axmpp%3Amicroblog%3A0/79a70bf1-42ab-4c1e-b1e6-fab35180396f) (to paste into translation service) and begin by marking the second occurrence of “Nous volons…” it does not mark the text but does a strange thing:

![screenshot](https://user-images.githubusercontent.com/861078/50704437-a8b2cc80-1057-11e9-98fc-4be55a353d5d.png)

Interestingly enough, this only happens in the `/?news` view. In the individual post view, the body begins with “J'ai”, and the “Nous…” is only the headline. The screenshot shows in how weird the `/?news` is in general: in @edhelas post, the title is also the first (but not selectable) line of the body (if it were not there, I would have started copying at the title, which incidentally enough works, but skips the second line), in the next post, the order of title and author/time is *reversed*. This is rather inconsistent.

So, I guess the fix would be to remove that title copy from the design.

**Comment by edhelas** [comment]
You're clearly missing a picture there. This is the alt text showing. Your browser blocked the load of the picture.

**Comment by mirabilos** [comment]
Jaussoin Timothée dixit:

>You're clearly missing a picture there. This is the alt text showing.

Aaaaah okay. (It was not discernible as alt text describing the
picture, and it was formatted the same way as body text, which
made it not stand out.)

>Your browser blocked the load of the picture.

If it’s from a different domain than chat.teckids.org, then,
most likely, yes, RequestPolicy blocked it.

Hm, this is a can of worms. Loading pictures from a different
server is a security and privacy problem, but perhaps also a
feature people might want. On the other hand, Movim could proxy
them, but THAT, contrary, might make problems for the server.
I have no good solution, given the decentralised nature (other‐
wise people could just upload to the server the pod is served
from).

Thanks for the explanation,
//mirabilos

PS: Maybe you can make the alt text stand out as alt text more?
-- 
(gnutls can also be used, but if you are compiling lynx for your own use,
there is no reason to consider using that package)
	-- Thomas E. Dickey on the Lynx mailing list, about OpenSSL

**Comment by edhelas** [comment]
I'm not planning to change the look of the alt texts for now.
