### ISSUE TITLE
Possible to change the "chatroom@server.com" default suggestion to "chatroom@the local MUC"?

### ISSUE THREAD

**Issue by realkinetix** [movim/movim#781]
When clicking on "Add a chatroom" dialog, the user is presented with a default suggestion of "chatroom@server.com".

Instead of "chatroom@server.com", would it be possible to have the suggestion default to "chatroom"@ the local MUC, if one exists?  ie, for my setup all users are using the 'chat.isurf.ca' XMPP service.  It has a MUC at 'conference.chat.isurf.ca', so it might be nice to have that default/suggestion of "chatroom@conference.chat.isurf.ca"

...  And looking further at widgets/Rooms/_rooms_add.tpl I see that it's supposed to be doing this... but I'm getting the suggestion of "chatroom@server.com", so I wonder if I don't have something useful set in my ejabberd config?

**Comment by edhelas** [comment]
The server part is already autocompleted when you're typing (gives you a list of suggestions). Also your server can have several MUC services and there's no notion of default so the suggested placeholder could be wrong.

**Comment by realkinetix** [comment]
OK, but I'm curious to know what/where the info needs to be set so the placeholder doesn't fall back to "chatroom@server.com", as I think I'm missing a minor piece somewhere.

The code I'm referring to is:

` {if="isset($info)"}
                    placeholder="chatroom@{$info->server}"
                {else}
                    placeholder="chatroom@server.com"
                {/if}`

So there's something that should populate $info that I'm missing somewhere, I believe.
