### ISSUE TITLE
Link to article source in atom feed are defect

### ISSUE THREAD

**Issue by reikkaps** [movim/movim#786]
The link to the article source url in atom feed of movim (example https://nl.movim.eu/?node/pubsub.movim.eu/Movim) are not correct, see: 

`<link rel="alternate" type="text/html" href="{&quot;id&quot;:330252,&quot;post_id&quot;:46007,&quot;category&quot;:&quot;open&quot;,&quot;rel&quot;:&quot;alternate&quot;,&quot;logo&quot;:null,&quot;type&quot;:null,&quot;href&quot;:&quot;https:\/\/nl.movim.eu\/?node\/pubsub.movim.eu\/Movim\/4d889c59-f3c1-4c31-b17e-484ad2e273a0&quot;,&quot;title&quot;:&quot;XMPP server hands-on comparison: ejabberd vs. Prosody&quot;,&quot;description&quot;:null,&quot;created_at&quot;:&quot;2018-06-22 23:59:57&quot;,&quot;updated_at&quot;:&quot;2018-06-22 23:59:57&quot;}"/>
`

Links to other article content like picture seem okay.

**Comment by edhelas** [comment]
Nice find, thanks!
