### ISSUE TITLE
Running on Plesk webhosts (alternative daemon?)

### ISSUE THREAD

**Issue by poVoq** [movim/movim#788]
Now that ZeroMQ isn't a dependency anymore I am trying to install Movim on my Plesk based webhosts. Installation and database migration, composer dependencies and all that works, but the final step to start the php daemon fails (as kind of expected):
```
php daemon.php start --url=https://mydomain

An error occured, check syslog for more information

Warning: Use of undefined constant CURLOPT_UNIX_SOCKET_PATH - assumed 'CURLOPT_UNIX_SOCKET_PATH' (this will throw an Error in a future version of PHP) in /movim/app/helpers/UtilsHelper.php on line 591
An error occured, check syslog for more information

Warning: curl_setopt() expects parameter 2 to be int, string given in /movim/app/helpers/UtilsHelper.php on line 591
```

Given that this is a shared host I don't have access the to syslog, so not sure what exactly goes wrong, but I suspect it is related to the fact that I can't really access much of the server internals of course.

Visiting the website itself the small error `An error occured, check syslog for more information An error occured, check syslog for more information` comes up, otherwise it seems fine.

I don't have very high hopes that it will be possible to start a continuous php process on this system, which would probably be required by this php daemon...
But this system also support Phusion Passenger to run Ruby, NodeJS and Python apps. Maybe the php daemon's functions are simple enough that they could also be run through this simple nodejs support for example?

**Comment by edhelas** [comment]
What php Version ? https://bugs.php.net/bug.php?id=72522

**Comment by poVoq** [comment]
Sort of php7.2. In my Plesk managed hosting there are multiple options for different php versions and the SSH terminal runs in yet another php version.
I configured the website to run in php7.2 and changed the shebang of the daemon.php to `#!/usr/local/php72/bin/php` which works for other php script to force a specific php version instead of the default 5.6.
But the error remains the same.

Starting it with a specific php version directly, i.e. `/usr/local/php72/bin/php daemon.php start --url=https://mydomain` also results in the same error.

**Comment by edhelas** [comment]
This constant is required to run Movim so you'll have to figure out why it's not declared on your system. Maybe a missing library or a version that doesn't includes it.

**Comment by edhelas** [comment]
Got any news on that?

**Comment by poVoq** [comment]
I tried various things, but no luck. I think unless there is another way to deamonnize Movim or run it daemon less than Ihave to admit defeat in regards to running Movim on a Plesk host. Not an expert on these matters though.

**Comment by poVoq** [comment]
Actually, it seems this might be a cURL problem? My server seems to be using 7.38.0 while according to this:
https://stackoverflow.com/questions/33869527/curl-request-to-unix-socket-from-php
it was only added in 7.40.0

Any possible work-around? I definitely can't update cURL myself.

**Comment by edhelas** [comment]
That is basically what I said in my comment 12 days ago https://github.com/movim/movim/issues/788#issuecomment-461720015 :) And there is no workaround for Movim as it is a PHP bug that it has been fixed already.

I'm closing this ticket.

**Comment by poVoq** [comment]
I still doubt that it is possible to currently run Movim on Plesk based shared hosting due to the daemon issue, but I'll give it the benefit of doubt given the identified library issue ;) Thanks for the patience with me.

**Comment by dimlau** [comment]
I got this：

```
[root@kaix movim]# php -info |grep "SSL Version"
SSL Version => OpenSSL/1.0.2k

[root@kaix movim]# php -info |grep cURL
cURL support => enabled
cURL Information => 7.64.1

[root@kaix movim]# php daemon.php start --url=http://localhost --port=8080

An error occured, check syslog for more information
PHP Warning:  Use of undefined constant CURLOPT_UNIX_SOCKET_PATH - assumed 'CURLOPT_UNIX_SOCKET_PATH' (this will throw an Error in a future version of PHP) in /movim/app/helpers/UtilsHelper.php on line 643
An error occured, check syslog for more information
PHP Warning:  curl_setopt() expects parameter 2 to be int, string given in /movim/app/helpers/UtilsHelper.php on line 643
Movim daemon launched
...
```
