### ISSUE TITLE
"Unusual" post causes strange behavior in movim

### ISSUE THREAD

**Issue by crosser** [movim/movim#789]
Steps to reporoduce:

* Have some community on a server.
* In gajim, run "discover services", find "publish-subscribe" server, "browse" it, select the community and make "new post" (content does not matter).
* Open the stream in movim. You can see the post (if you subscribed to the community).
* Open the community from movim. There is no post visible, and there is a toast message "Post deleted" (but in reality it is still there).

Example here: https://xample.average.org/ (movim from master, stock nginx, stock ejabberd).

**Comment by edhelas** [comment]
I'd be surprised that Gajim publishes Atom elements in Communities and implements XEP-0277.
I'll see what I can do.

**Comment by edhelas** [comment]
Gajim is actually putting an integer as post id (0 in my case), this is creating confusion in Movim. 
I'd need to debug more on my side but I'd really suggest the Gajim devs to generate, at least, a random hash or UUID for their new node items ids.

**Comment by edhelas** [comment]
Closing the ticket, this is more related to Gajim way of handling things.
