### ISSUE TITLE
Pressing "Next" in a community with one post suggests to delete the community

### ISSUE THREAD

**Issue by crosser** [movim/movim#790]
Steps to reporoduce:

* Create a fresh community
* Create one post in the community
* Open the community again. You will see a page with one post and "Next" button below.
* Press the "Next" button. You are presented with a toast message "Delete the community. It seems that the community does not exist anymore"

Example: https://xample.average.org/, "another community" there.
Runs movim from master, stock gninx, stock ejabberd.

**Comment by edhelas** [comment]
It seems that this issue was already fixed, closing.
