### ISSUE TITLE
first connexion issue with .dms file

### ISSUE THREAD

**Issue by Matt-Gyver** [movim/movim#793]
Hello All,

I followed your instructions to install Movim on an updated Debian stretch with mariadb 10.3 and nginx 1.10.3-1

I also configure a let's encrypt certificate (maybe it could be related)

All seems correct with sql - nginx - php7 configuration files
Nothing in the error.log or access.log

when I tried to reach the page I receive a .dms file containing : 
`<?php

/**
 * @file index.php
 * This file is part of Movim.
 *
 * @brief Prepares all the needed fixtures and fires up the main request
 * handler.
 *
 * @author Movim Project <contact@movim.eu>
 *
 * Copyright (C)2013 Movim Project
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 * @mainpage
 *
 * Movim is an XMPP-based communication platform. It uses a widget-based UI
 * system. A widget is a combination of server-side and client-side scripts that
 * interact though a custom xmlrpc protocol.
 *
 * Movim's core is designed to ease the implementation of XMPP web-based clients,
 * using massively asynchronous javascript and abstracting XMPP calls into an
 * events-based API.
 */

require 'vendor/autoload.php';

use Movim\Bootstrap;
use Movim\Controller\Front;
use Movim\Widget\Wrapper;

$bootstrap = new Bootstrap;
$bootstrap->boot();

$rqst = new Front;
$rqst->handle();

Wrapper::getInstance(false);
Wrapper::destroyInstance();`

What do I miss ?

Thank you for your time and your work !

Regards,

Mathieu

**Comment by edhelas** [comment]
Did you configured php-fpm correctly?
This looks more like an incomplete nginx or php-fpm configuration.

**Comment by Matt-Gyver** [comment]
Hello,

Problem solved after upgrading php-fpm from 7.0 to 7.3 and updating the configuration file with : 

fastcgi_pass unix:/run/php/php7.3-fpm.sock;

Thank you again !

Regards,

Mathieu
