### ISSUE TITLE
Feature reqest: from the top post box, allow to select community

### ISSUE THREAD

**Issue by crosser** [movim/movim#794]
From the box at the top of the "news" stream you can post to your own blog but not to communities. It is very un-obvious that you have to enter the community to be able to post there (and the meaning of the post button there is un-obvious too). It would be useful to have a drop-down selector of communities to post into on the common post page. The same way it is done in G+.

**Comment by edhelas** [comment]
It's already quite a complex form that I have there indeed, might need a redesign. But I'm not sure if adding another picker is the right idea UI wise.
