### ISSUE TITLE
After first installation, impossible to configure

### ISSUE THREAD

**Issue by ajira86** [movim/movim#8]
Apparently movim succed to create folders
On start screen he say "Movim cannot talk with server"
And on admin panel, I get forms like on screenshot but impossible to save configurations or update database.

![screenshot from 2015-07-05 21 18 36](https://cloud.githubusercontent.com/assets/1295025/8513029/15e77040-235c-11e5-8a77-fc3ca53b5142.png)

**Comment by edhelas** [comment]
There is some tabs on this page, created by Javascript. It seems that you have a Javascript error here that prevent them to be created and, by extension, to create the WebSocket that need to be here to talk with Movim.

Please try to give me any Javascript error that you find in the browser console to help me to debug this issue.

**Comment by ajira86** [comment]
SyntaxError: syntax error >> movim:32

``` javascript
var SECURE_WEBSOCKET= ;
```

ReferenceError: SECURE_WEBSOCKET is not defined >> movim_websocket.js:43

``` javascript
if(SECURE_WEBSOCKET) {
...
}
```

TypeError: this.connection is null >> movim_websocket.js:94

``` javascript
if(this.connection.readyState != 0) {
...
}
```

**Comment by ajira86** [comment]
My fault, all of this happens because movim daemon was not started (started to read stable documentation version to setup my server)

After daemon configured in systemd I had to run

```
php mud.php db set
```

**Comment by edhelas** [comment]
Is it possible to have the systemd script to start/stop the daemon ?

**Comment by ajira86** [comment]
Yes, @Trim give me its one ;)
To write in  /etc/systemd/system/movim.service

``` bash
[Unit]
Description=Movim daemon (dev)
After=apache2.service network.target local-fs.target

[Service]
User=www-data
Type=simple
ExecStart=/usr/bin/php daemon.php https://pod.movim.eu/ 8080
WorkingDirectory=/var/www/movim/

[Install]
WantedBy=multi-user.target
```

**Comment by Trim** [comment]
Hello,

As I've said to @ajira86 I'm not sure of all the systemd configuration, but it works on my server (I'm not sure about the last line).

**Comment by edhelas** [comment]
Thanks for the script ! It will help for the Movim Debian package :)

**Comment by Trim** [comment]
Oh, for a Debian package (good idea !), you should write this file in /lib/systemd/system instead of /etc/systemd/system. It allows a sysadmin to overwrite it just by writing its own file in /etc/.

**Comment by edhelas** [comment]
The script is now in the codebase (see https://github.com/edhelas/movim/blob/master/debian/lib/systemd/system/movim.service). I'm closing this ticket ;)
