### ISSUE TITLE
unable to create account via mobile phane browser

### ISSUE THREAD

**Issue by githubgnulinux** [movim/movim#800]
lightning, jumpgo, WebKit browsers unable to enter data in web page account creation form.

**Comment by edhelas** [comment]
I'm not planning to test nor debug Movim on thos browsers for now.
It's definitely too much work and I prefer to invest this time in other things.

**Comment by Natureshadow** [comment]
Umm... The author said WebKit. If the bug exists, this means it exists in your official Movim android app, which is a WebKit browser.
