### ISSUE TITLE
filesize(): stat failed for [..] in Movim/Picture.php

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#810]
Movim version: 8a32ba694

```
movim.ERROR: filesize(): stat failed for /usr/share/webapps/movim/cache/95d1542f8810c7a8fe0a4ae07db0ed13.jpg in /usr/share/webapps/movim/src/Movim/Picture.php
```

I had existing file cached in this folder, so maybe that's why this happens.

**Comment by edhelas** [comment]
I'd like to be able to reproduce that one exactly.

**Comment by Natureshadow** [comment]
I also get log lines like that en masse on every Movim startup.
