### ISSUE TITLE
No feedback on error when setting node configuration

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#814]
Movim version: 8a32ba694 (master)

## Steps to reproduce

- Go to node configuration
- Change some settings (maybe not even needed)
- Save

## What happens

Prosody sends back `<iq from='pubsub.foo.bar' to='foo@foo.bar/movimFoo' type='error' id='5eEtUC'><error type='modify'><not-acceptable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>`

In movim, nothing. Reopening the node configuration shows the exact same as before.

## Expected behaviour

Movim tells the user an error has occured.

## Details

https://issues.prosody.im/1328 was causing movim to be able to create a node with `pubsub#max_items` set to 1000, but prosody would send back an error when trying to change the node configuration. I have documented prosody's behaviour in [movim's wiki](https://github.com/movim/movim/wiki/Configure-Prosody/_compare/a4e7b46370a8e376e04f91626242b8549e1d7d2c...d71ff3fa26118d268ca9776e57bf8a472e075156), but in the meantime I want to know when something happens and I'm unable to do an action.

To be honest, this happens in lots of different places as well. Users generally don't get much feedback on what's happening, I have already opened a few issues about this.

**Comment by edhelas** [comment]
Movim is now displaying some feedback when some errors are caught from the Pubsub services.
This was introduced a few months ago.
