### ISSUE TITLE
MUC Participant avatar being downloaded over and over again

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#815]
Movim version: 8a32ba694 (master)

Either a Prosody module or a mix of 0084-0153 compat seems to cause the `SHA1` of the avatar to be wrongly set to the pubsub id, which causes weirdnesses like the following:

```xml
<presence [..]>[..]<x xmlns="vcard-temp:x:update"><photo>current</photo></x></presence>
```

Movim will see this, compare with an existing hash which of course doesn't exist (I assume), and query the avatar. This user has been blinking (presences) for quite some time now, and Movim queries the avatar every single time.

While this isn't really a Movim issue, and even if it will never really be possible to prevent people sending wrong hashes, it might be good to try and do something to avoid wasting more resources than necessary.

I'm not sure if this is a good solution, but maybe checking if the hash is actually a correct `SHA1` could help?

**Comment by edhelas** [comment]
Can you still reproduce the issue ? Is there a MUC that I can join to reproduce the issue ?

**Comment by edhelas** [comment]
Bump

**Comment by edhelas** [comment]
Closing the ticket
