### ISSUE TITLE
movim fails to login

### ISSUE THREAD

**Issue by nielll** [movim/movim#816]
hi there,

I'm facing some difficulties to install and running movim flawless. The browser has a working connection between the movim-deamon and the core, everything seems to be alright in the admin panel. However, when I try to log in the weird stuff happens, namely the login page starts to reload over and over again, but never really log me in. I also get status updates, like sometimes I get information at the bottom saying 'status updated' or when I write a message from another user to the 'logged in' account I get a notification at the left corner as well as in the title bar of the browser.

php version is 7.0.18 (7.0.33; 7.1.27; 7.2.16; 7.3.3 don't work together with movim!), movim version 1.14.1, i followed the install instructions, folder permissions should be fine too

I caught the following logs from movim: https://niel.site/zerobin/index.php?fa8153a76118c783#pZq86VcLS3P5H5ka/smpW7kebgN3F7MddUjbDXao9+8=

error_log:
https://niel.site/zerobin/index.php?71fca894b9d356da#AYp+eX9Qwg+lIiJqhE7XmpPivA0S/CZ+eb9sa54edjk=

Any help is much appreciated.

**Comment by nielll** [comment]
I guess the problem is mysql related. Im currently running mysql 5.7. I will try with version 5.5.

**Comment by nielll** [comment]
I guessed wrong, the same happens with postgresql 9.5.

more errors from proxy_error_log:
```
2019/03/20 22:17:39 [error] 4166#0: *5659 connect() failed (111: Connection refused) while connecting to upstream, client: 213.55.184.244, server: social.niel.site, request: "GET /ws/?path=login&offset=-60 HTTP/1.1", upstream: "http://[::1]:8080/?path=login&offset=-60", host: "social.niel.site"
```
also:
```
2019/03/20 22:44:16 [error] 19465#0: *8534 "/var/www/vhosts/niel.site/social.niel.site/ws/index.html" is not found (2: No such file or directory), client: 213.55.184.244, server: social.niel.site, request: "GET /ws/?path=admin&offset=-60 HTTP/1.1", host: "social.niel.site"
```

console when i log in:
```
Connection established!
Connection closed by the server or session closed
Navigated to https://social.niel.site/?login
```

again full errors.log
https://niel.site/zerobin/index.php?7161e98d836b9d9c#7tQtrvnZ82JBH3MLSsX8IneMebBWOF0M1Ki7gxcfTP4=

**Comment by edhelas** [comment]
It seems that the session is not saved in the DB when it should.
MySQL 5.7 should be fine. No need to downgrade.

**Comment by edhelas** [comment]
Similar as #819
