### ISSUE TITLE
Probably a stupid question but how the hell one signs up/create a new account?

### ISSUE THREAD

**Issue by Droyk** [movim/movim#818]
After downloading the app the very first screen greets me with "choose your server" I chose https://jp.mov.im/ then moving forward on the login screen I see 2 options Login & Signup. I don't have an account so I click signup and then I got greeted with this message 

> Movim is a decentralized social network, before creating a new account you need to choose a server to register.
> Your server here?
> Contact us to add yours to the officially supported servers list • https://movim.eu/

😞 

So I go to this link https://api.movim.eu/accounts/register & again got disappointed
>Account Creation currently disabled

Is there is anyway to join you guys, I would like to join jp POD!!

**Comment by nielll** [comment]
You can register on any xmpp/jabber server and use those account credentials to login to a movim server (some movim server are restricted for specific xmpp servers!) 
I can suggest this server: https://niel.site/register.php, if you want to test others pick one from here: https://list.jabber.at/ (some are outdated!)

**Comment by cutnadhifa** [comment]
Ok

**Comment by edhelas** [comment]
@daniel-dona Welcome on Movim, do you know from which country (IP) you tried to register an account on movim.eu ?

**Comment by edhelas** [comment]
Closing the issue, no reply
