### ISSUE TITLE
Support for in MUC custom widgets?

### ISSUE THREAD

**Issue by poVoq** [movim/movim#821]
Would be cool if you could configure some custom widgets (maybe as iframes?) similar to how it can be dome in Riot.im:
https://medium.com/@RiotChat/riot-im-web-0-12-7c4ea84b180a

For example embedding a video live feed in a room, or having a Etherpad for writing a document etc. For video-conferencing an external Jitsi instance also seems a more scalable option and thus a good fall-back.

**Comment by edhelas** [comment]
Yes, but actually no for now. 
It is interesting but will need a proper design and way to share those information with XMPP.
I'm closing the ticket and will reopen it if some work is planned on it.
