### ISSUE TITLE
new user question: daemon doesn't show websocket url

### ISSUE THREAD

**Issue by evert-mouw** [movim/movim#822]
Trying to install, noob question warning ;-)

When trying
`php daemon.php start --url=http://localhost/movim/ --port=8080`

In the installation document:
> If everything runs as expected you should see:
> Movim daemon launched
> Base URI : https://pod.movim.eu/
> Encrypted Public WebSocket URL : wss://pod.movim.eu/ws/

But alas, I don't get a websocket URL. Also when browsing the URL, I get a 500 internal error. The `cat cache/websocket` command returns `false`, not sure what that means though.
I'm running version 0.14.1 on Ubuntu 18.10, using PHP 7.2.15

Also proxypass for apache2 didn't work, of course, but I assume that is related to the internal error.

The full output on the console is:

```
Movim daemon launched
Base URL: http://localhost/movim/

--- Server Configuration - Apache ---
Enable the Secure WebSocket to WebSocket tunneling
# a2enmod proxy_wstunnel 
Add this in your configuration file (default-ssl.conf)
ProxyPass /ws/ ws://localhost:8080/

--- Server Configuration - nginx ---
Add this in your configuration file
location /ws/ {
    proxy_pass http://localhost:8080/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect off;
}

Unencrypted 
```
Adding "verbose" doesn't give more information. I don't know what to try next.

Edit: the log file was empty...

**Comment by edhelas** [comment]
If you have a 500 error, please check syslog or `log/errors.log` in the Movim directory.
Also the documentation was wrong, launching the daemon doesn't output the public Websocket URL.

In your case the WS URL should be `http://localhost/movim/ws` but it doesn't really matters as Movim is handling that automatically. 

Please try to check this 500 error and then apply the Apache2 configuration :)

**Comment by evert-mouw** [comment]
Again, the log was empty. No log  files were created. Not when running as www-data and also not when running as root.

```
root@ratatosk:/opt/movim/php# ls -al log
total 8
drwxr-xr-x  2 www-data www-data 4096 Apr  8 14:04 .
drwxrwxr-x 13 www-data www-data 4096 Apr  8 15:31 ..
root@ratatosk:/opt/movim/php# 
```

Also changing the Apache2 config didn't help. Connecting the browser to port 8080 (using ssh portforwording) didn't result in anything.

**Comment by edhelas** [comment]
You don't need to connect via SSH to the port 8080, it's a Websocket port.
Where is your server located ? Are you trying to setup it only locally ? So your Movim instance location is http://localhost/movim/ ?

**Comment by evert-mouw** [comment]
@edhelas Are you sure you know what SSH portforwarding _means_?
I'll give up on this.

**Comment by edhelas** [comment]
> Also when browsing the URL, I get a 500 internal error. The cat cache/websocket command returns false, not sure what that means though.

Which URL are you trying to browse to exactly there ?
The cat command returns false, it's normal.

**Comment by edhelas** [comment]
And yes I know what is SSH port forwarding

**Comment by evert-mouw** [comment]
@edhelas Well at least thanks for trying to help me, although I don't think it will work out without log files. Also the terminal doesn't produce errors or log messages. A few URLs  I tried without avail:

```
http://localhost:8080/
http://localhost:8080/movim
http://localhost:8080/movim/
http://localhost:8080/ws/movim/
https://localhost:8080/
https://localhost:8080/movim/
```

**Comment by edhelas** [comment]
Let me ask the question again just to be sure :)
You don't have any domain name pointing to Movim, nothing like evert.com/movim or things like that.
Here you are trying to setup your instance, locally, on localhost? Do we agree?

**Comment by evert-mouw** [comment]
on "ratatosk" (VM running version 0.14.1 on Ubuntu 18.10, using PHP 7.2.15)

```
sudo su
cd /opt/movim/php
php daemon.php start --url=http://localhost/movim/ --port=8080
```
on my desktop machine

```
ssh -L 8080:localhost:8080 ratatosk
```

And then

- URLs from last comment are not working in Chromkum
- no log files are created
- no error messages from the running php script

Also tried using user www-data instead of root.

Forget about the domains and Apache, if this doesn't work then that's a step too far I guess.

**Comment by edhelas** [comment]
I'm sorry I just can't help you. Except login on the server and having a look myself.
Just know that the `--url=http://…` parameter is your **public domain**, port forwarding port 8080 will not work if you'll not forward 443 or 80 as well.

On my server I do
> php daemon.php start --url=https://nl.movim.eu/ --port=8080

This is creating a **local** URL on port 8080, then the configuration generated tells Apache/nginx to handle a new uri `/ws` so `wss://nl.movim.eu/ws` in my case and forward it, locally, to the port 8080.

If this is what is setup for you then I don't know how to help you.
Try our chatroom: movim@conference.movim.eu.

**Comment by evert-mouw** [comment]
@edhelas 
Yes, I understand, the ssh portforwarding is to the local 8080 port. Anyway, really thanks a lot for trying to help me out -- much appreciated!
Maybe I'll try again later, with newer software versions or so.
