### ISSUE TITLE
Please split cache/ directory

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#829]
The `cache/` directory is used for internal things like sockets, template caching, etc., thus, it should not be readable by the webserver (or not delivered). The example nginx config disables access to `/cache/`. But this breaks Movim because the directory is also used for caching of avatars (and probably more), which are directly delivered from there.

Please split the directory into one for cached content to be delivered to the browser and one for internal caching.

**Comment by edhelas** [comment]
Done there https://github.com/movim/movim/commit/323a3bc78cd5ef5da9a5b2e161a37dd5f6225536
