### ISSUE TITLE
Render quotes visually

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#833]
It seems that quoting messages with a > character has become common practice. It would be great if Movim could visually render such quotes, like it does for /me, for example.

**Comment by kawaii** [comment]
While we're discussing parser and rendering issues - using code blocks is messy in Movim currently as it doesn't appear to append `\n` to the end of lines. This means that when you paste code from a Movim code block it all comes out on one line.

**Comment by Natureshadow** [comment]
> While we're discussing parser and rendering issues - using code blocks is messy in Movim currently as it doesn't appear to append `\n` to the end of lines. This means that when you paste code from a Movim code block it all comes out on one line.

Wouldn't that be another issue?

**Comment by edhelas** [comment]
That's another issue, and I'm not sure I'll fix it. It's a design choice that I did several years ago and was already discussed. Messages in Movim are trimmed before being sent to prevent some UI issues.

**Comment by Natureshadow** [comment]
@edhelas Trimming happens at start and end of the message. The issue described above is about missing newlines between lines of one and the same message.

**Comment by edhelas** [comment]
@kawaii it's not a Movim bug but a Firefox one https://bugzilla.mozilla.org/show_bug.cgi?id=1174452 works correctly on Chrome.

**Comment by edhelas** [comment]
@Natureshadow tried it, it's hard to dissociate several lines when handling the quote (some like me prefers to send one message with a quote and something else after, in the same body).

With the relative complexity and the bugs that could be introduced by such feature and regarding the simple "visual" addition that it brings (that could be simply handled with a ">") I'm not planning to implement that feature in Movim.
