### ISSUE TITLE
Movim replaces garlic emoji with smiley picture

### ISSUE THREAD

**Issue by mirabilos** [movim/movim#835]
When I type 🧄 (U-0001F9C4) in a chat, Movim replaces it with random large (about 128x128px) smlley images — interestingly enough, not the same… the first was https://chat.teckids.org/theme/img/emojis/svg/1f600.svg and the second was https://chat.teckids.org/theme/img/emojis/svg/263a.svg õÕ

It seems to me I’ll have to look at the replacement code again…

**Comment by mirabilos** [comment]
Just received confirmation from @Natureshadow that it also makes a foot into a cake.

I’m not sure how much of that code is still mine, but I’ll have a look as time permits, so feel free to assign this issue to me.

**Comment by debdolph** [comment]
If i send a foot emoji via Movim, a cake appears in the chat box. But in the preview bar at the left the foot is rendered correctly.
![Screenshot_20190505_161944](https://user-images.githubusercontent.com/25152803/57195372-e6fec080-6f51-11e9-868b-02e4085963de.png)
![Screenshot_20190505_162028](https://user-images.githubusercontent.com/25152803/57195373-e9f9b100-6f51-11e9-951f-1dff995f50fa.png)

**Comment by mirabilos** [comment]
Tom Teichler dixit:

>If i send a foot emoji via Movim, in the chat box a is cake displayed.
>But in the preview bar at the left the foot is rendered correctly.

OK, thanks for the extra info. I’ll have a look as time permits.

**Comment by debdolph** [comment]
Once you're there ;)... can you please add a dolphin emoji :D? 🐬

**Comment by mirabilos** [comment]
Tom Teichler dixit:

>Once you're there ;)... can you please add a dolphin emoji :D? 🐬

Emoji are added to Unicode. What Movim does here is to replace the
emoji with pictures. Those are up to edhelas, I’ve just fixed the
code (and will fix it again) that does this replacing.

Besides, garlic is more important… :þ

**Comment by Natureshadow** [comment]
>>Once you're there ;)... can you please add a dolphin emoji :D? 🐬>
>>
>Emoji are added to Unicode. What Movim does here is to replace the>
>emoji with pictures.

There *is* a dolphin emoji (which you can see by looking at the dolphin emoji in your mail).

The request probably is about the emoji drawer.

**Comment by mirabilos** [comment]
I’ve extended the tests to verify that all *other* characters (i.e. all those that are not the start point of an SVG replacement sequence) are _not_ matched, and, in git `master`, it passes for me: https://github.com/Teckids/movim/commits/fix-835-emoji

I’ll have to see what is wrong with either the Debian package or on the `chat.teckids.org` Movim instance. (Does this issue also occur on one of the other Movim pods?)

**Comment by debdolph** [comment]
If i type an arrow (←↓→↑), movim turns it into a 🙁.

Some really strange things are happen with emoji in movim :D…

**Comment by debdolph** [comment]
On de.movim.eu an arrow is turned into a cake :D.

But also here: Only in the chat box.

**Comment by mirabilos** [comment]
As far as I can verify, `\Movim\Emoji::getInstance()->replace($text)` leaves garlic and the arrows alone and turns the dolphin emoji into a graphic (dolphin image).

This means that something else must be going on, especially as I occasionally get two different replacement images for the same emoji…

**Comment by mirabilos** [comment]
I think I have it. Someone broke this with the “single emoji” code…

**Comment by mirabilos** [comment]
@DummerDelfin: can you apply the patch https://salsa.debian.org/xmpp-team/movim/blob/debian+835/debian/patches/issue-835.diff (lines 7–38) to `chat.teckids.org` in situ, so we can see if the fix is correct?

**Comment by mirabilos** [comment]
If this is the correct fix, it was definitively broken in commit 85843a09c2ad0381d9a7441de25a8eadd2733c6a (although it may or may not have been broken before).

**Comment by debdolph** [comment]
This works fine on de.movim.eu :)!

**Comment by mirabilos** [comment]
> This works fine on de.movim.eu :)!

“This” as in, the patch I referenced does fix the issue? (Because then, @edhelas can merge #837 )
