### ISSUE TITLE
Uploading image via mobile app fails while chatting via movim on pc

### ISSUE THREAD

**Issue by debdolph** [movim/movim#836]
if I try to post an image with the movim app on Android, in my open movim session on my PC the „Upload dialogue“ appears in front of my chat box and I'm no longer able to upload a photo via the mobile app.

**Comment by Natureshadow** [comment]
This is a well-known issue due to the technical design of the Movim UI.

**Comment by edhelas** [comment]
Yes the tabs are synchronized. It's an architectural decision.
