### ISSUE TITLE
Login/register fails in Firefox

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#840]
FOr some time now since I-don't-know'when, I get spurious issues trying to log in with Firefox. The login button does not do anything, neither does the register button.

In the console, I get:

```
TypeError: MovimWebsocket.connection.register is not a function
```

Everything works with Chromium, though.

**Comment by edhelas** [comment]
Can you please check your Firefox extensions ?

**Comment by Natureshadow** [comment]
Funnily, it was the WebSocket Sniffer extension I used to diagnoes a past login issue :D.

**Comment by edhelas** [comment]
![](https://media.tenor.co/images/231e2f67bc42bbfcff592d58f0e9517e/raw)
