### ISSUE TITLE
Can't change language nor activate night mode

### ISSUE THREAD

**Issue by ImaCrea** [movim/movim#841]
Hi there,
I'm new to Movim. I have my own XMPP server. I have logged in on nl.movim.eu with mynickname@myserver.co today and it seems to work. But when I got on configuration settings some changes can't be saved.

First I select "français" as language and nothing changes. I save, I refresh page, nothing changes. I get back to configuration and again it's written "english" as language.

For night mode, when I activate it the screen switches to night mode. I then save but when I go on another page, it's back to light mode. I get back to configuration, the option is switched off.

I don't know if it's some problem coming from the way I logged on it or if it's a bug :/

Btw, I have uploaded an avatar and changed my nickname and these stuffs seem to be saved well.

Cheers

**Comment by edhelas** [comment]
First, would it be possible to know which XMPP you're running?

**Comment by ImaCrea** [comment]
Hi @edhelas sorry for the delay. I've just retested now and it looks like it's working now. Meanwhile, I've updated my Yunohost instance which was serving XMPP. hooray :)
