### ISSUE TITLE
connecting and interacting with email accounts?

### ISSUE THREAD

**Issue by testbird** [movim/movim#848]
Hi,
getting to know Movim I am impressed by how it builds on existing standards and perfectly integrates existing XMPP accounts.

I imagine somebody might already also have had a thought about integrating the billions of existing e-mail accounts.

Do you have a current take on this?

Maybe these days, a prospective Movim email messaging connector could rely on the https://github.com/deltachat/deltachat-core library. A rewrite in Rust is the works, and  a browser-plugin vs. webserver-library-installation discussion also arose already:  https://support.delta.chat/t/could-delta-desktop-run-as-a-vm-on-windows/311/8

**Comment by testbird** [comment]
Unfortunately pub/sub support (for mailing lists) is not available yet in deltachat-core, but individual, self and group chat is there. https://github.com/deltachat/deltachat-core/issues/125

**Comment by edhelas** [comment]
![](https://www.dailydot.com/wp-content/uploads/2019/02/well_yes_but_actually_no_meme-e1550594965387.jpg)

I'd prefer to keep things simple in Movim, so only so XMPP and nothing else. If there's some SMTP integration somewhere it should be done on the XMPP side.

**Comment by testbird** [comment]
Thank you for answering, and explaining your position.

(I think a drawback of hooking the email-chat library into a XMPP server bridge backend would be that true e2ee support won't be possible. But that may also be the case as long as the movim apps do not run local movim instances https://github.com/movim/movim_android/issues/24 )

**Comment by testbird** [comment]
An interesting question might be if movims architecture would allow to easily work with the structure of the high level C API (or its bindings) provided by deltachat-core (an array of messages per chat), see https://c.delta.chat/  intro.

**Comment by testbird** [comment]
All the needed SMTP and IMAP messaging incl. encryption stuff etc. is part of deltachat-core lib.
For local, non-webserver apps, it shouldn't be a problem that its API is available in c, java, python, nodejs.
