### ISSUE TITLE
clean install for adlinkfly error Can not load initial data. SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by mohamed025025** [movim/movim#852]
hello

like the title say i have this issue in my clean installation for the adlinkfly script
i don't understand how to solve this error in mysql database please help me
thank you for your suporte i use hostkda free hosting plan how to solve this error

Can not load initial data. SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

thank you

**Comment by edhelas** [comment]
Which MySQL database version are you using ?

**Comment by mohamed025025** [comment]
hello
i'm using 5.6.41-84.1

**Comment by edhelas** [comment]
https://github.com/movim/movim/wiki/Install-Movim#get-started

> MySQL 5.7 or higher with utf8mb4 encoding (necessary for emojis 😃 support)

**Comment by mohamed025025** [comment]
do you meant i can't install the script ?

**Comment by mohamed025025** [comment]
if it's true can you recomend me free hosting plan that i can install the script on it thank you

**Comment by edhelas** [comment]
No sorry, I don't have any recommendation, any server that has what we require there https://github.com/movim/movim/wiki/Install-Movim should be enough.
