### ISSUE TITLE
Using movim through apache mod_proxy with ProxyPass

### ISSUE THREAD

**Issue by donfede** [movim/movim#854]
I have successful movim 0.14.1 instances running on an internal network.  Thanks, it looks like a very convenient XMPP web client tool.

Unfortunately, I'm struggling to get the internal network movim server, working on the public Internet through a "border" server running an apache 2.4 mod_proxy configuration.  Using apache [mod_proxy](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html) and ProxyPass directives I can get to other internal server test web pages from the public Internet.  However, trying to access the `movim/` URL, an HTTP 302 reply (?by movim?) tries to send web clients to the internal network server hostname.  Trying the `movim/?login` or `movim/?admin` URLs, they have broken images and report that "Movim cannot talk with the server"; the admin page can at least be logged into, but the regular XMPP login fails.  Starting the movim php daemon with alternate --url options, including the public facing hostname, does not appear to help.

Even more confusing to me, reviewing the movim HTML source, the internal network movim server hostname is used in all URLs, **without a protocol**?!?  Similarly, the movim php daemon --url option does not appear to affect the movim HTML source URLs.

### movim/?login HTML excerpt
```
<link rel="stylesheet" href="//fooxmpp.internalnet.org/movim/themes/material/css/listn.css?t=1549749266" type="text/css" />
<link rel="stylesheet" href="//fooxmpp.internalnet.org/movim/themes/material/css/grid.css?t=1549749266" type="text/css" />
<link rel="stylesheet" href="//fooxmpp.internalnet.org/movim/themes/material/css/article.css?t=1549749266" type="text/css" />
```

My environment is debian 10 Buster, with apache2 and ejabberd.  The same results came from trying both the debian 0.14.1 package and the 0.14.1 sources from here following the [Install-Movim](https://github.com/movim/movim/wiki/Install-Movim) tutorial.

Am I missing a configuration with movim or apache?  Should movim be usable via a proxy/gateway?  

I looked at the apache [mod_proxy_html](https://httpd.apache.org/docs/2.4/mod/mod_proxy_html.html) module, but believe it's getting thrown off by the lack of protocol in the HTML links.  Regardless, shouldn't the --url option negate the need for this?

I also recognize internal network movim server itself uses an apache ProxyPass directive to send traffic to its php movim daemon on ws://localhost:8080/ ... I was hoping the public Internet web clients would simply send all their traffic, including that destined for /ws/ , through the first ProxyPass.  Would a ProxyPassReverse directive be needed for the websocket traffic?  The [mod_proxy_wstunnel](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) documentation does not mention ProxyPassReverse.

**Comment by edhelas** [comment]
What is the url parameter that you gave to the daemon when starting it ?

**Comment by Nirmalsv007** [comment]
> I have successful movim 0.14.1 instances running on an internal network. Thanks, it looks like a very convenient XMPP web client tool.
> 
> Unfortunately, I'm struggling to get the internal network movim server, working on the public Internet through a "border" server running an apache 2.4 mod_proxy configuration. Using apache [mod_proxy](https://httpd.apache.org/docs/2.4/mod/mod_proxy.html) and ProxyPass directives I can get to other internal server test web pages from the public Internet. However, trying to access the `movim/` URL, an HTTP 302 reply (?by movim?) tries to send web clients to the internal network server hostname. Trying the `movim/?login` or `movim/?admin` URLs, they have broken images and report that "Movim cannot talk with the server"; the admin page can at least be logged into, but the regular XMPP login fails. Starting the movim php daemon with alternate --url options, including the public facing hostname, does not appear to help.
> 
> Even more confusing to me, reviewing the movim HTML source, the internal network movim server hostname is used in all URLs, **without a protocol**?!? Similarly, the movim php daemon --url option does not appear to affect the movim HTML source URLs.
> 
> ### movim/?login HTML excerpt
> ```
> <link rel="stylesheet" href="//fooxmpp.internalnet.org/movim/themes/material/css/listn.css?t=1549749266" type="text/css" />
> <link rel="stylesheet" href="//fooxmpp.internalnet.org/movim/themes/material/css/grid.css?t=1549749266" type="text/css" />
> <link rel="stylesheet" href="//fooxmpp.internalnet.org/movim/themes/material/css/article.css?t=1549749266" type="text/css" />
> ```
> 
> My environment is debian 10 Buster, with apache2 and ejabberd. The same results came from trying both the debian 0.14.1 package and the 0.14.1 sources from here following the [Install-Movim](https://github.com/movim/movim/wiki/Install-Movim) tutorial.
> 
> Am I missing a configuration with movim or apache? Should movim be usable via a proxy/gateway?
> 
> I looked at the apache [mod_proxy_html](https://httpd.apache.org/docs/2.4/mod/mod_proxy_html.html) module, but believe it's getting thrown off by the lack of protocol in the HTML links. Regardless, shouldn't the --url option negate the need for this?
> 
> I also recognize internal network movim server itself uses an apache ProxyPass directive to send traffic to its php movim daemon on ws://localhost:8080/ ... I was hoping the public Internet web clients would simply send all their traffic, including that destined for /ws/ , through the first ProxyPass. Would a ProxyPassReverse directive be needed for the websocket traffic? The [mod_proxy_wstunnel](https://httpd.apache.org/docs/2.4/mod/mod_proxy_wstunnel.html) documentation does not mention ProxyPassReverse.



I'm facing the same problem

**Comment by donfede** [comment]
> What is the url parameter that you gave to the daemon when starting it ?

The URL parameter appears to only affect images (such as stickers and user avatars).  I had tried both the internal xmpp hostname and border apache proxy host for URL values, with no success.

The rest of the generated HTML code doesn't include a protocol; I've not dug deep enough into the code to see why yet.  Is there a reason for that?

I was able to work around the issue for now, using iptables port forwarding instead of apache mod_proxy (though I'd still like to find a way for the latter to work).

**Comment by Nirmalsv007** [comment]
> What is the url parameter that you gave to the daemon when starting it ?

during the launch of the daemon , i didnt pass --interface and i had base url set up as localhost in some conf file that was causing my issue now its been resolved thank you
