### ISSUE TITLE
Moving my tags for r/thelittlepalace like in r/littlespace

### ISSUE THREAD

**Issue by JainJude** [movim/movim#855]
I tried looking at their stylesheet but was very confused. I want my hot, trending, etc tags to be in the middle under my banner (I removed them currently because it looked terrible with my submission text box being moved up). Can anyone help me figure out what codes I need to center the tags but keep the submission text box near the top when people click on submit a new link or submit a new text post buttons.

**Comment by edhelas** [comment]
Can I have a picture of what you're talking about ? Which part of Movim are you referring to?
