### ISSUE TITLE
Syntax error in illuminate/database with movim 0.15, php 7.0

### ISSUE THREAD

**Issue by guillaume-uH57J9** [movim/movim#858]
The following syntax error appear on a fresh movim 0.15. 
`Jul 28 21:27:28 hostname movim[3053]: movim.ERROR: ParseError: syntax error, unexpected '=' in /var/www/hostname.domain.tld/movim-0.15/vendor/illuminate/database/DatabaseManager.php (line 77)  [] []`

A second syntax error appear when fixing the first one. The second syntax error is located in : 
`movim-0.15/vendor/illuminate/database/Eloquent/Concerns/HasAttributes.php (line 641)`

Note I installed Movim 0.15 using a .tar.gz archive from the Release section. Dependency were installed using Composer as recommended in the install guide. 

This StackOverflow discussion shows this error occurs because eloquen dependency require PHP 7.1 or later. This conflict with movim claiming support for PHP 7.0. 
https://stackoverflow.com/questions/54277810/i-have-a-parse-error-using-eloquent-with-slim3

**Comment by guillaume-uH57J9** [comment]
There a more errors in a couple different dependencies with php 7.0

`ParseError: syntax error, unexpected '=' in /var/www/radole.atto.be/movim-0.15/vendor/illuminate/database/Eloquent/Concerns/HasRelationships.php (line 137)  [] []`

`ParseError: syntax error, unexpected '=' in /var/www/radole.atto.be/movim-0.15/vendor/illuminate/database/Eloquent/Concerns/HasRelationships.php (line 229)  [] []`

`ParseError: syntax error, unexpected '=' in /var/www/radole.atto.be/movim-0.15/vendor/illuminate/database/Eloquent/Concerns/HasRelationships.php (line 312)  [] []`

`ParseError: syntax error, unexpected '|', expecting variable (T_VARIABLE) in /var/www/radole.atto.be/movim-0.15/vendor/illuminate/support/Traits/ForwardsCalls.php (line 24)  [] []`

Not sure what's causing the last one, but I suspect that's another new syntax which requires php 7.1+

Update: there a way more issues.. I gave up on changing the syntax manually as a workaround

**Comment by edhelas** [comment]
Movim 0.15 requires PHP 7.3+
PHP 7.0 is not supported anymore since the beginning of the year (https://www.php.net/supported-versions.php).

**Comment by guillaume-uH57J9** [comment]
Okay. Also, thanks for updating the requirement on the Install guide
https://github.com/movim/movim/wiki/Install-Movim#dependency-installation
