### ISSUE TITLE
Can't access admin

### ISSUE THREAD

**Issue by mark4409** [movim/movim#860]
I've just installed version 0.15 and in the main, it appears to be working fine. I can log on with my XMPP account and chat. I can't however access the admin section. I enter the username and password (which has been set), but when I click validate, the screen just refreshes and I'm back at the login page again. 

Strange thing is, the very first time I tried to access it, it worked fine. Since logging out though, I'm no longer able to get back in.  I can't see any errors in the standard webserver logs, and unfortunately as I can't get back into admin, I'm unable to switch on logging there.

I have had to tinker quite a bit with the config as I have not been able to find an example of a site that's been setup behind an nginx reverse proxy. Basically, I'm proxying /ws/ to the movim websocket using the bit of code in the nginx sample config, and I'm proxying / to an apache backend to deal with the rest of it. Does anyone have a similar working setup and can help me with the config? I'm also on PHP 7.3 and using Postgresql.

**Comment by edhelas** [comment]
You can try to reset the password again using the same command as the first time 

    php daemon.php config --username=USERNAME --password=PASSWORD

For the reverse proxy, I've found that https://github.com/movim/movim/issues/230, you can still come to movim@conference.movim.eu to ask for more support.
