### ISSUE TITLE
[Suggestion] add this system to the https://fediverse.party/ listing.

### ISSUE THREAD

**Issue by WNYmathGuy** [movim/movim#862]
I found your system by accident on DuckDuckGo while looking for a federated blogging system. Later I heard about this Fediverse Party site. I was looking for "write freely". I saw you weren't listed, but Apparently, I can't add you to their list. [https://gitlab.com/fediverse/fediverse.gitlab.io/blob/master/CONTRIBUTING.md#submitting-software](https://gitlab.com/fediverse/fediverse.gitlab.io/blob/master/CONTRIBUTING.md#submitting-software)

**Comment by poVoq** [comment]
Would make sense to some extend, but Movim isn't using one of the established Fediverse protocols, but rather a federated chat protocol.
I hope that there will be interoperability bridges in the future as the pubsub component of XMPP could translate well, but for now this doesn't exist.

**Comment by edhelas** [comment]
Fediverse is based on their own protocol which is not XMPP ¯\_(ツ)_/¯
