### ISSUE TITLE
Calls do not work.

### ISSUE THREAD

**Issue by un4me** [movim/movim#867]
with the standard configuration of the ejabber server with the ejabberd_stun module on port 3478, the calls do not work, I could not find any configuration examples for movim.
Tcpdump from the jabber server, I do not see access to ports other than 5222.
Tell me what to do?

Thank you in advance for your reply!
You make a wonderful product.

**Comment by un4me** [comment]
If I'm expand the window, I can see the inscription: Movim cannot talk with the server, please try again later

**Comment by edhelas** [comment]
Those are two different issues.
First is linked with https://github.com/movim/movim/issues/480

I'll need more infos beside "it does not work" :) 
Please come to our chatroom movim@conference.movim.eu to have proper support regarding your Movim deployment.
