### ISSUE TITLE
Unable to set image alpha channel

### ISSUE THREAD

**Issue by izwx** [movim/movim#868]
I'm trying to install my own pod of the Movim.

http://13.230.196.82

It is almost complete, but I can't save the image.
daemon.php outputs the following message.

“Unable to set image alpha channel”

I think that it is an error related to ImageMagick, but it has not been solved.

Can you give me some hints?
The server's phpinfo () can be seen below.
http://13.230.196.82/pi.php

**Comment by izwx** [comment]
I found a workaround for this problem.
This error is caused by lines 224,272 in src / Movim / Picture.php. It seems that if you comment out these two lines, the problem goes away. I don't know the side effects.

**Comment by edhelas** [comment]
What is your PHP and Imagick version ?
Related to https://www.php.net/manual/en/imagick.flattenimages.php#116956

**Comment by edhelas** [comment]
Closing the ticket, this should be related to the installed Imagick version
