### ISSUE TITLE
SQlite support?

### ISSUE THREAD

**Issue by Biniou180** [movim/movim#87]
Hello!

First of all, thanks for all the job on Movim! It's quite impressive (and it's good to see that we can have FOSS with such appealing design :-) )

One question: I have seen in the wiki that MySQL and PostgreSQL were supported now. Should it be possible to install Movim on a SQLite database in the future? Is it something you think feasible?
(I would like to install movim on a RPi, with a very few number of users; If i can avoid to install mysql/postgre for this, it would be perfect :) )

Merci! :-)

**Comment by edhelas** [comment]
Thanks for the support :)

Unfortunately SQLite is a bit too "light" for Movim and Movim is relying a lot on the database, also it uses some parts of SQL that was not used in SQLite.

Also I recommend PostGreSQL, even on small devices like a RPi or a netbook. It can run smoothly (it only consume ~20Mo in memory) and the Movim database is really not big.

Regards,

edhelas

**Comment by Biniou180** [comment]
Thanks for the explanation!
Then i will see for the postgreSQL solution, i didn't know it was so effective on memory consumption.

Keep up the good work :-)
Biniou180
