### ISSUE TITLE
BASE_URI not defined in movim_websocket.js (reverse-proxy issue?)

### ISSUE THREAD

**Issue by poVoq** [movim/movim#875]
So I am finally working on updating an Apache2 based Docker image for Movim. You can see the hacked together results here: https://github.com/poVoq/movim-docker

After quite some trial and error I got it to almost work. But the websocket connection is refusing work (according to the admin interface).

The thing is the daemon reports to have started fine, and there are no substancial errors anywhere in the logs as far as I can say.

The only thing I could find is in the browser console were it says:
`ReferenceError: BASE_URI is not defined`
in `movim_websocket.js:60:23`

I have a suspicion this might be related to:
https://github.com/movim/movim/issues/330

As my dockerimage runs behind a Traefik.io reverse-proxy. Thus internally it runs on http only, but I access it through https with the reverse-proxy.

I already tried passing both http and https options to the deamon, and it reports it fine:

```
Movim daemon launched

Base URL: https://movim.example.com/
```
But the browser console error stays the same.

Any idea?

Help much appreciated :)

**Comment by vinyll** [comment]
@poVoq: I think we are have the exact same issue. I'm not running in a docker but an LXC, therefore I have a reverse proxy on my main server forwarding to the container and getting the same browser message. 🤔 

```
php daemon.php start --url=https://social.anonym.dev

Movim daemon launched
Base URL: https://social.anonym.dev/

--- Server Configuration - Apache ---
Enable the Secure WebSocket to WebSocket tunneling
# a2enmod proxy_wstunnel
Add this in your configuration file (default-ssl.conf)
ProxyPass /ws/ ws://localhost:8080/

--- Server Configuration - nginx ---
Add this in your configuration file
location /ws/ {
    proxy_pass http://localhost:8080/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect off;
}
```

The browser makes a call to `Request URL:https://social.anonym.dev/An%20error%20occured,%20check%20syslog%20for%20more%20information//social.anonym.dev/?system&t=`

and the browser console outputs `ReferenceError: BASE_URI is not defined
movim_websocket.js:60:23`

However I can't read any message on the server's logs.

As I'm not a Websocket expert and I'm not a genius into Nginx forwarding, I feel like stuck too.

**Comment by poVoq** [comment]
So this the the output of my https://movim.example.com/?system
```
var BASE_HOST = 'movim.example.com';
var BASE_URI = '//movim.example.com/';
var ERROR_URI = '//movim.example.com/?disconnect';
var SMALL_PICTURE_LIMIT = 512000;
```
I can't see anything obviously wrong with the BASE_URI :(

**Comment by vinyll** [comment]
Mine is
```
var BASE_HOST = 'social.anonym.dev';
var BASE_URI = '//social.anonym.dev/';
var ERROR_URI = '//social.anonym.dev/?disconnect';
var SMALL_PICTURE_LIMIT = 512000;
```

When testing with [wscat](https://github.com/websockets/wscat), `wscat -c https://social.anonym.dev/ws/` responded as connected, which makes me believe it might come from something else than the websocket configuration through the proxy or the container themselves.

**Comment by vinyll** [comment]
@poVoq any further luck?
I switched https://social.anonym.dev/ to [Friendica](https://friendi.ca/) which was pretty straightforward to install. However I'd really like to get further into Movim installing it in an LXC container…

**Comment by poVoq** [comment]
@vinyll no, but I am thinking about ways to proxy it directly via Traefik. Nothing I seem to do in Apache2 solves the issue. Edit: see below, works with Apache2 now. Was an unrelated bug.

OT: I recently evaluated Friendica Vs. Hubzilla quite extensively and would recommend you to install Hubzilla instead (various reasons, too long to explain here, but give it a try).

**Comment by poVoq** [comment]
This seems to be an easy way to test:
https://www.websocket.org/echo.html
By proxying directly via Trafik it connects, but somehow I need to figure out why my config broke the the rest of Movim that way.

Edit: never mind. I tried again with the Apache2 proxy setting and in fact it also connects fine to the WS through the above website. Looks the same as with nl.movim.eu. Very strange.

So it seems like my websocket connection is working fine and there in another issue all together.

**Comment by poVoq** [comment]
In the Apache log I get the following warning:
`[Tue Nov 05 16:00:42.913949 2019] [php7:warn] [pid 52] [client 172.18.0.4:51496] PHP Warning:  filemtime(): stat failed for /var/www/movim/cache/websocket in /var/www/movim/app/views/page.tpl on line 19, referer: https://movim.example.com/?admin`

Edit: a "websocket" file does not exist in my cache folder... should that be "socketapi.sock"?

**Comment by poVoq** [comment]
@edhelas 
If I change `/var/www/movim/app/views/page.tpl on line 19` from "websocket" to "socketapi.sock" it works.

Looks like a bug to me?

**Comment by edhelas** [comment]
Well that was it.
Fixed there https://github.com/movim/movim/commit/a632e5443c5b9654acb62bf8495dd9a92db3e884
On my production server and dev laptop I still had the old "websocket" file in the cache. 
But thanks for the investigation, and yes I'm wondering how it was not noticed before that.
