### ISSUE TITLE
Trying to get property of non object (API/Presence)

### ISSUE THREAD

**Issue by syntafin** [movim/movim#876]
I installed movim over git version, the daemon.php log post the following, everytime someone use the client:

`
PHP Notice:  Trying to get property 'resource' of non-object in /var/www/tenguchat/WebClient/lib/moxl/src/Moxl/API.php on line 17
PHP Notice:  Trying to get property 'presence' of non-object in /var/www/tenguchat/WebClient/app/widgets/Presence/Presence.php on line 176
`

Ubuntu 19.04, Apache and PHP 7.2 (FPM).

**Comment by c-93** [comment]
Behaviour: Movim daemon crashes ~once/ twice per day, this error might be related  
Setup: Debian 10, Nginx, PHP 7.3, current git movim version  
Log:  `movim.ERROR: Trying to get property 'presence' of non-object in app/widgets/Presence/Presence.php (line 176) Trace  [] []`  

`movim.ERROR: Error: Call to a member function contacts() on null in app/widgets/Chats/Chats.php (line 276) Trace`  
`#0 app/widgets/Chats/Chats.php(106): Chats->prepareChats()`  
`#1 src/Movim/Widget/Wrapper.php(152): Chats->ajaxHttpGet()`  
`#2 src/Movim/RPC.php(42): Movim\Widget\Wrapper->runWidget('Chats', 'ajaxHttpGet', Array)`  
`#3 src/Movim/Controller/Front.php(54): Movim\RPC->handleJSON(Object(stdClass))`  
`#4 src/Movim/Controller/Front.php(20): Movim\Controller\Front->runRequest('ajax')`  
`#5 public/index.php(50): Movim\Controller\Front->handle()`  
`#6 {main} [] []`  

Current workaround: Restarting movim service if gone

**Comment by edhelas** [comment]
The related code doesn't exists anymore
