### ISSUE TITLE
Share button does not work with MUCs

### ISSUE THREAD

**Issue by poVoq** [movim/movim#881]
The recently added share button for community pubsub posts does not allow to share a post with a MUC. The only options are individual contacts and your own blog.

Seems to me like it would make the most sense to share in on MUCs though... any reason this isn't possible?

**Comment by edhelas** [comment]
Because,
![](http://www.quickmeme.com/img/17/17e36c0a30244a99087d86b8e8f129f650611584087611392366cdfafcbdcff6.jpg)

It's some work to do :p

**Comment by edhelas** [comment]
Fixed :p
