### ISSUE TITLE
Likes and comments are only shown after clicking "read more"

### ISSUE THREAD

**Issue by poVoq** [movim/movim#882]
When scrolling through the news feed the icons for likes and comments are always showing "0" next to them as if there where now likes or comments at all.

But after reading the article via the "read more" button the likes and comments appear, and when returning to the overview are also correctly shown for that specific post.

I guess if this is done to speed up loading the overview, then maybe it would be better to hide these icons until they can actually show some correct information?

**Comment by edhelas** [comment]
Yes and no, indeed it's for performances purposes, but I still want to show those statistics in the posts lists.

**Comment by poVoq** [comment]
Ok, understandable. But as implied above, why not hide the ones that claim 0 because the data isn't available yet, or just in general hide if there are no comments or likes as it gives very limited information in those cases.

**Comment by edhelas** [comment]
Because you can like or post a comment from those buttons as well.
I've hide the counter if there is no like or comment cached  yet.
