### ISSUE TITLE
When retrieving messages from MAM they are tripled

### ISSUE THREAD

**Issue by poVoq** [movim/movim#883]
on 0.16

When joining a new MUC and the older messages are retrieved from MAM, they get tripled in the chat.
Like this:
```
Example
Example
Example
```
New messages work fine, so it is only a minor inconvenience.

**Comment by edhelas** [comment]
Would it be possible to find a way to reproduce that properly ?

**Comment by poVoq** [comment]
Haven't seen it in a while, so I guess it is fixed.
