### ISSUE TITLE
Don't reload page on status posting

### ISSUE THREAD

**Issue by subpub** [movim/movim#884]
Version 16 aplha 1 on jp.mov.im

**Comment by edhelas** [comment]
What do you mean status posting ?

**Comment by subpub** [comment]
I was using the Facebook terminology. I mean the normal blog post.

When you post the whole page reloads with the spinner showing and it's annoying to be frank and ruins the immersed  UX.

**Comment by edhelas** [comment]
Ok I got it. Seems something minor to me, I'll see if I can fix it if I got time for it.
