### ISSUE TITLE
system page JS generated with garbage

### ISSUE THREAD

**Issue by Ppjet6** [movim/movim#888]
Movim version: a63342e1f
php version: 7.4

# Steps to reproduce

- ???
- go to view-source:https://jp.mov.im/?system&t=1575484571 (link copied from the console that indicates a syntax error)
(The whole instance is currently whitelisted by IP)

# What happens

```javascript
An error occured, check syslog for more information
var BASE_HOST = 'jp.mov.im';
var BASE_URI = '//jp.mov.im/';
var ERROR_URI = '//jp.mov.im/?disconnect';
var SMALL_PICTURE_LIMIT = 512000;
```

I believe this causes the menus on the left to not show up.

**Comment by edhelas** [comment]
Do you have an actual error displayed in the logs ?
