### ISSUE TITLE
Debian package and nginx - two administrative questions / documentation

### ISSUE THREAD

**Issue by c-93** [movim/movim#889]
Hello together.  
I am having the following more basic questions concerning the debian package:  

1. Files are by default installed in /usr/share/movim with root ownership such that the movim deamon can only be started by user root. Changing them to www-data and starting as www-data would give permission denial for the websocket anyway. When installed manually I would have place the files in /var/www-data/movim. Am I missing something here?

2. Could you please provide a default nginx configuration for the debian package?
I am getting the movim deamon for the debian package up an running (movim start --url https://myHostname.com --port 8080 -vvv), but am struggling to find out how the rest of the website.conf of nginx should look.  E.g. which root should be specified - as this isn't /var/www/movim anymore.

To me the installation process of the dev-version was clearer at this point (since I moved the files manually and knew where they were).

Thanks in advance.

**Comment by Natureshadow** [comment]
How about https://github.com/movim/movim/blob/master/etc/nginx/conf.d/movim.conf ?

Also, I am not aware of permission issues. Your first point is untrue for the official Debian package.

**Comment by c-93** [comment]
Thanks for your reply - jap, point one was my lack in understanding.   
Point 2: I thought of a complete nginx conf file instead of only the snippet. A typical movim setup might use TLS encryption and might wish to use some standard set of security headers. This way admins would need to apply smaller changes to the reference instead of writing their own config. E.g. [Nextcloud](https://docs.nextcloud.com/server/15/admin_manual/installation/nginx.html) is doing this.

**Comment by Natureshadow** [comment]
> Thanks for your reply - jap, point one was my lack in understanding.   
> Point 2: I thought of a complete nginx conf file instead of only the snippet. A typical movim setup might use TLS encryption and might wish to use some standard set of security headers. This way admins would need to apply smaller changes to the reference instead of writing their own config. E.g. [Nextcloud](https://docs.nextcloud.com/server/15/admin_manual/installation/nginx.html) is doing this.

I'd suggest you report this as a wishlist bug against the nginx package
in Debian, as I think providing defaults and examples for such things
would be a good idea in general, not only for Movim in particula.
