### ISSUE TITLE
Account blocked

### ISSUE THREAD

**Issue by Notxor** [movim/movim#89]
After installing the client app Movim of Firefox, and identified with the account notxor@mijabber.es, movim crashed. Now when I try to access it says me: «Movim failed to authenticate. You entered wrong data»
The data are correct. Also, other applications (like Conversations, Xabber or Empathy) that connect to that account with these same data, they have left to do it.
What can have happened? How I can recover the access to my account?

**Comment by edhelas** [comment]
I don't see your account connected on my side. Also I have another account from your server (mijabber.es) that is connected on pod.movim.eu. Did you mistype your password ?

**Comment by Notxor** [comment]
No, the password is correct. Also the others tools (that they had the password saved) have left to be able to go in. Never I changes the password.

**Comment by edhelas** [comment]
On which Pod are you ? nl, pod, it ?

**Comment by Notxor** [comment]
I do not know. The first time, when it failed after entering the data, it open the platform and crash. I have not been able to connect never more. It would be a failure in XMPP? They fail all the applications with this account (Empathy, Xabber, Conversations...) Something that have modified the permissions, maybe.

**Comment by edhelas** [comment]
Yeah it seems that it's an issue on your XMPP server, maybe your account is blocked somehow ?
