### ISSUE TITLE
XEP-0340: COnferences with LIghtweight BRIdging (COLIBRI) support?

### ISSUE THREAD

**Issue by poVoq** [movim/movim#890]
Now that video chat is is better shape, would be cool to implement XEP-0340:
https://xmpp.org/extensions/xep-0340.html

Maybe an more lightweight audio only mode would be nice as well, especially on mobile.

**Comment by edhelas** [comment]
This is a lot of work. I'm not planning to implement such feature anytime soon, except if it's sponsored.

**Comment by edhelas** [comment]
Actually I'll close that one, because I prefer to keep things that i'm actually planning to implement. And it's definitly not into my todo list.

**Comment by poVoq** [comment]
https://github.com/conversejs/community-plugins/blob/master/audioconf/readme.md

This seems to implement a javascript only audio conferencing with Colibri and SIP. For reference :)

Edit: probably this is the relevant library: https://github.com/jitsi/lib-jitsi-meet

**Comment by edhelas** [comment]
I don't wan to rely on heavy JS librairies
