### ISSUE TITLE
SQL Error on Account Registration because using a non-ascii character

### ISSUE THREAD

**Issue by apimon** [movim/movim#891]
I tried to register on https://api.movim.eu/accounts and I get a screen with an Symfony exception, looks like it can not handle **non-ascii characters**??? Welcome to 2019!

```
(2/2) QueryException
SQLSTATE[22021]: Character not in repertoire: 7 ERREUR: séquence d'octets invalide pour l'encodage « UTF8 » : 0xfc (SQL: insert into "accounts" ("username", "ip", "country_code", "region", "city", "latitude", "longitude", "updated_at", "created_at") values (username_redacted, HERE.WAS.MY.IP, DE, 07, D�sseldorf, COORD-X_REDACTED, COORD-Y_REDACTED, 2019-12-09 22:07:40, 2019-12-09 22:07:40) returning "id")
```

Why is this screen even visible on a public website?

BTW with this error we learn that **movim is saving ip addresses and geo coordinates of users without asking** - this is a severe violation of EU data protection - because this is such a serious issue I will open a new ticket for that one.

**Comment by llebout** [comment]
@apimon Could you stop being so rude?

This issue is probably related to the database setup rather than the PHP code itself.
And yes, error logs should certainly not be displayed publicly ever.

@edhelas Are public error logs done on purpose?

**Comment by edhelas** [comment]
Alphanum and dashes characters are required for username.
I've updated the info next to the checkbox.
Disabled the debug logs.

**Comment by llebout** [comment]
> Alphanum and dashes characters are required for username.
> I've updated the info next to the checkbox.
> Disabled the debug logs.

Note that it wasnt the username that was not ASCII but the city name resolved from GeoIP, so some people (including myself) can't register because the GeoIP contains a non-ASCII city name.

**Comment by edhelas** [comment]
Ah good to know, I'll fix that then.

**Comment by edhelas** [comment]
Should be fixed by now, @leo-lb can you try again ?

**Comment by llebout** [comment]
@edhelas Works now! Thanks!
