### ISSUE TITLE
Severe violation of european user privacy laws, saving IP and geo coords without asking

### ISSUE THREAD

**Issue by apimon** [movim/movim#892]
As we can see in #891 movim is saving not only the **ip addresses** but also **geo coordinates** of users without asking - there is not one single word mentioning this in the legal [disclaimer](https://api.movim.eu/accounts/legals) for that website. 

This seems deeply unethical and dangerous - not only are you actively breaking EU law with this, but because you are advertising movim as a tool for people to self-host you are leading people to unknowingly break the law, too - this is totally inacceptable and a serious issue! 

At the very least you should publish a warning right now on the movim website that using this software might lead to criminal prosecution in EU. This is no joke, breaking eu data protection laws can be **very** expensive. If some little company would like to use Movim out of the motivation to "help people get off FB" it will run into a very big risk. What is happening here is an unbelievable demonstration of irresponsibility. 

I guess you are very young and did not have yet the opportunity to learn that unfortunately in the world of grown ups legal things are very important. Certainly your publication of movim as an open source code base happens out of generosity, but you need to understand that you also take **responsibility** by publishing a software tool. 

People could just take your software, install it on some web hosting account - and find themselves in serious legal troubles - this is, of course, possible for all kind of softwares and one might maintain an opinion that people must take care for themselves, but as you seem to be located in the EU yourself you should take notice of such really basic things like EU privacy laws - it is nearly impossible to not have noticed that major change in privacy regulation if you have not lived under a rock in the last years. 

The problem here is that you are not mentioning the fact that movim is saving these personal data right on the login - it is questionable why the software does this, but even more so not documenting this misbehavior. 

Please ask your parents about the seriousness of legal things - I am sure they can help you understand better about why the world is the way it is. 

If you are not a child - sorry, but I have no words for the level of disrespect you are demonstrating  - this is a major ethical issue, please stop coding for a while until you understand a bit more why privacy is such an important thing for many people.

**Comment by Natureshadow** [comment]
Apart from you proving yourself as a completely intolerable person, you also proved that you are incapable of understanding the issue.

What you see has nothing to do with the Movim software itself. It is an issue with the movim.eu jabber server, which is a totally separated service.

While it is true that it seems to lack a detailed privacy policy, the rest of your post is entirely not true. Most importantly, noone installing Movim can face legal consequences, as this service is not part of the Movim software, but a separate service hosted by edhelas (who looked pretty grown-up last time I checked, in case you care :)).

As for the real issue: GeoIP data is determined directly from the IP address, so we are talking about data enrichment here. It is not collected from your client. The only data collected is your IP address. Nonetheless, this should be explained in a privacy policy.

P.S.: Your abuse of the term "child" to express disrespect is reason for deep concern, and a good example for "why the world is the way it is".

**Comment by llebout** [comment]
"geo coordinates"

This is just geoip derived from your IP address, nothing more. If not by movim, it will be logged at some level anyways.

Now probably there should be a server side setting to disable storing IP addresses at the Movim level even though it's certainly stored at another level (web server logs, isp logs).

**Comment by edhelas** [comment]
Text updated https://api.movim.eu/accounts/register
