### ISSUE TITLE
Endless loop, if joining an IRC channel via transport is denied

### ISSUE THREAD

**Issue by c-93** [movim/movim#893]
Situation: Some user joins an IRC channel via a XMPP-IRC transport. Transport denies, because username is already in use.

Reaction: Movim tries in an endless loop to join the IRC channel. Transport will likely ban the entire xmpp-server.

Proposal: If the user can not join a group (because of any denial), set a counter with a limit (e.g. set to 3) to stop the endless loop.

**Comment by c-93** [comment]
Alternative proposal: Append some growing number (or sth. else) at the end of the username to solve the conflict.

**Comment by edhelas** [comment]
Do you have an IRC channel with this behavior as an example, are you using biboumi ?

**Comment by c-93** [comment]
I way trying to connect to #chaos-darmstadt on server irc.hackint.org. Obviously, their admin was not amused. I could realize another endlessloop on another irc bridge as well. So this is not only related to this specific channel/ server. Related info: I was logged-in with another xmpp client (gajim / conversations) at the same time (using my IRC username). I am not sure about biboumi.

**Comment by edhelas** [comment]
Thanks :) I'll try to reproduce it

**Comment by c-93** [comment]
Thanks :)
