### ISSUE TITLE
Day delimiters mixed up

### ISSUE THREAD

**Issue by fiaxh** [movim/movim#899]
I just got back to a Movim tab which I last interacted with two days ago. The day delimiters between the messages were very mixed up. Reloading the page fixed the issue.

Version: 0.16.2alpha1

![Screenshot from 2019-12-31 12-00-14](https://user-images.githubusercontent.com/9932450/71628193-09d39880-2bf7-11ea-84ba-92e17016f9db.png)

**Comment by edhelas** [comment]
Yes indeed, thanks ! I'll try to reproduce it.
