### ISSUE TITLE
View is cut in the bottom of the window, in Safari/Mac

### ISSUE THREAD

**Issue by Nyco** [movim/movim#9]
View is cut in the bottom of the window:
![capture d ecran 2015-07-08 a 10 42 26](https://cloud.githubusercontent.com/assets/25348/8570274/894ff01e-257f-11e5-9ad1-fe6be08c10c0.png)

Glitches:
- "+" button is less than half visible
- chat pane input field is not visible

Env:
- Safari 8.0.6
- Mac OS X Yosemite 10.10.3

**Comment by edhelas** [comment]
Thanks for the feedback, I'll need to find a Mac to debug this :p

**Comment by edhelas** [comment]
![](https://pbs.twimg.com/media/CQEWDqKW8AAqStu.png:large)

There's a rendering issue on Safari, actually Safari correctly detect the elements positions but display them wrongly. 

Let's call Tim Cook hotline!

Go to http://bugreport.apple.com/

_Please enter your Apple ID and password._

![](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.troll.me%2Fimages%2Ftarik-boss%2Fnope.jpg&f=1)

**Comment by edhelas** [comment]
Just for the curious, it will be the same with iOS. So let's wait for Apple to fix their browser.

**Comment by edhelas** [comment]
This issue was moved to movim/movim#10
