### ISSUE TITLE
Package as standalone application for Desktop usage

### ISSUE THREAD

**Issue by llebout** [movim/movim#900]
I will work on this as soon as possible. Creating this issue to remind myself.

**Comment by edhelas** [comment]
Up :3

**Comment by edhelas** [comment]
https://github.com/movim/movim_electron maybe ?

**Comment by llebout** [comment]
@edhelas I was more thinking of opening the default browser rather than doing Electron

**Comment by llebout** [comment]
And in case that was unclear, I don't want to make this depend on any server at all. I want to include movim as a whole inside that standalone application. To use it as a client as if it was local.

**Comment by edhelas** [comment]
There's no plan for that at the moment no

**Comment by llebout** [comment]
@edhelas I'm not asking you to do any of it, just to clarify, couldnt get to it yet..
