### ISSUE TITLE
Is there a way to turn off registration button?

### ISSUE THREAD

**Issue by Plasmodino** [movim/movim#901]
I am running a private chat server for the family and I would like to turn off registration.
Is there an official way to turn it off or a quick patch?

**Comment by Natureshadow** [comment]
>I am running a private chat server for the family and I would like to turn off registration.
>Is there an official way to turn it off or a quick patch?

That has nothing to do with Movim, but with your XMPP server.

**Comment by Plasmodino** [comment]
Registration is disabled in ejabberd which is why I receive a "Registration denied" response from Movim. I want to get rid of the registration button so that no one ever tries to register.

**Comment by edhelas** [comment]
No it's not possible at the moment

**Comment by Quix0r** [comment]
Isn't that easy to implement? Such as `Config::getValue('features', 'is_registration_enabled', true)` ?

Legend:
 - `Config`: class (with namespace, please!)
 - `getValue($group, $key, $default =null) : mixed`: static method signature, variable names are self-describing
