### ISSUE TITLE
Error message after starting the movim daemon

### ISSUE THREAD

**Issue by Plasmodino** [movim/movim#902]
I got the following message in the logs:

 movim.ERROR: Error: Call to a member function contacts() on null in /var/www/movim/app/widgets/Chats/Chats.php (line 276) Trace #0 /var/www/movim/app/widgets/Chats/Chats.php(106): Chats->prepareChats() #1 /var/www/movim/src/Movim/Widget/Wrapper.php(152): Chats->ajaxHttpGet() #2 /var/www/movim/src/Movim/RPC.php(42): Movim\Widget\Wrapper->runWidget('Chats', 'ajaxHttpGet', Array) #3 /var/www/movim/src/Movim/Controller/Front.php(54): Movim\RPC->handleJSON(Object(stdClass)) #4 /var/www/movim/src/Movim/Controller/Front.php(20): Movim\Controller\Front->runRequest('ajax') #5 /var/www/movim/public/index.php(50): Movim\Controller\Front->handle() #6 {main} [] []

**Comment by edhelas** [comment]
Same as #876
