### ISSUE TITLE
Can't add chatrooms on debian buster version of movim

### ISSUE THREAD

**Issue by arthurzenika** [movim/movim#903]
When using movim 14 on debian buster package, everything seems to work fine, but we can't add chatrooms. 

Tried to see some debug information in --debug --verbose but could not find any errors. 

We can search for a room, see the profile with participants but not tallk in it.

**Comment by edhelas** [comment]
0.14 is not supported anymore. Please try to use a more recent version.

**Comment by arthurzenika** [comment]
Is @Natureshadow around ?  If 0.14 is not supported anymore it's a problem that it is present in debian stable. Debian users expect software that is present there to be supported. 

I'm not saying it should and I want to congratulate the people that put the effort into getting movim into debian (I have worked on debian packages that we decided not to push to debian because of this "maintenance" window requirement, so I understand it's  complicated).

**Comment by arthurzenika** [comment]
Sorry, I'm pinging @Natureshadow because he is listed as the uploader of the movim package here : https://tracker.debian.org/pkg/movim

**Comment by Natureshadow** [comment]
>Is @Natureshadow around ?  If 0.14 is not supported anymore it's a problem that it is present in debian stable. Debian users expect software that is present there to be supported. 

I asked @edhelas to commit to supporting 0.14 with bug fixes for the lifetime of Debian buster. He did.

If that changed, I will of course get Movim removed from Debian stable.

**Comment by Natureshadow** [comment]
If you think it is a bug specific to the Debian package, please report it in the Debian BTS.
