### ISSUE TITLE
Provide a debian package for new releases

### ISSUE THREAD

**Issue by arthurzenika** [movim/movim#904]
Seeing movim reach the debian package repos was great news. Any chance of seeing more recent packages (maybe in another repo?), on salsa or some instructions to build them ?

**Comment by arthurzenika** [comment]
ping @Natureshadow since he is listed https://tracker.debian.org/pkg/movim and this issue might be related to #903

**Comment by Natureshadow** [comment]
New Debian versions will get newer Movim versions (in case Movim stays maintainable - see my comment on #903 for it).

I asked @edhelas to get in touch with me at 36c3 to help out with some issues, but that didn't happen.

**Comment by Natureshadow** [comment]
Please report Debian bugs on the Debian BTS.

**Comment by edhelas** [comment]
The package was recently updated to 0.17 https://packages.debian.org/sid/movim

**Comment by arthurzenika** [comment]
Good news for movim and debian ! Thanks @edhelas and @Natureshadow
