### ISSUE TITLE
Missing chatroom history when switch back to xmpp client after connecting to movim

### ISSUE THREAD

**Issue by arthurzenika** [movim/movim#906]
After using movim to talk in a chat room, and switch back to a traditionnal desktop based xmpp client (pidgin in this case) the history from the chat room (latest 10 messages) are not send.

**Comment by edhelas** [comment]
Pidgin does not support MAM (https://xmpp.org/extensions/xep-0313.html), this is perfectly normal. I invite you to use a more modern XMPP client such as Dino https://dino.im/ or Gajim https://gajim.org/ :)
