### ISSUE TITLE
Provide admin feature to add groupchat for other users 

### ISSUE THREAD

**Issue by arthurzenika** [movim/movim#907]
Searching and adding groupchat for some users can be a bit complicated. It would be nice to be able to setup a set of auto-join conference from an admin account for another account.

**Comment by edhelas** [comment]
This must be done on the XMPP level, not Movim level. Sorry.

**Comment by arthurzenika** [comment]
I'm not sure about that. The users are already in the chatrooms in jabber with their usual xmpp clients. 

When adding a chatroom in movim, a line is added to the `conferences` table in the movim postgresql database, that's what I would want to change for my users.

**Comment by edhelas** [comment]
This is handled by the user bookmarks, that Movim resolves when connecting.
Checkout you XMPP server plugins to see if you can inject that XMPP side.
If you inject that manually in the SQL database, they will be cleared next time, the DB is juste a cache from the XMPP network.

**Comment by arthurzenika** [comment]
Thanks for the explanation, we're  using ejabberd do you have any more specific keywords for what I would be looking for ? (the users are already invited to these  chatrooms and have auto-join in their jabber client - pidgin for example)
