### ISSUE TITLE
Add server metadata for the-federation.info to list Movim stats

### ISSUE THREAD

**Issue by stragu** [movim/movim#909]
I think it would be great to see Movim listed on the website https://the-federation.info/, in order to have a better idea of what the federated social networking landscape looks like, and also to give Movim more visibility.

The XMPP protocol is already listed, with software like Prosody: https://the-federation.info/protocol/xmpp

An issue is already open on their side: https://github.com/thefederationinfo/the-federation.info/issues/195

[This comment](https://github.com/thefederationinfo/the-federation.info/issues/195#issuecomment-526822392) gives instructions on how to make it happen.

**Comment by edhelas** [comment]
It seems that the "standard" is kinda still a WIP. I'd prefer to implement something that is stable and fully specified.

**Comment by edhelas** [comment]
As there is specific standard and it's out of the project scope I'm closing this. Another ticker could be reopened in the future if a more complete and stable standard could be presented.
