### ISSUE TITLE
movim/?admin is a blank page

### ISSUE THREAD

**Issue by cabfever** [movim/movim#91]
As the title says: my http://myurl.bla/movim/?admin is a blank page somehow.

**Comment by edhelas** [comment]
Can you please check the logs (log/php.log) and see if you have any error in there.

**Comment by dehenne** [comment]
Has you installed php5-gd and or php5-imagick?

**Comment by edhelas** [comment]
You need to install php5-gd as is it defined in the Wiki https://github.com/edhelas/movim/wiki/Install-Movim. Also blank page means most of the time fatal error. Theses errors are logued in log/php.log.
