### ISSUE TITLE
Trying to understand movim

### ISSUE THREAD

**Issue by ugintl** [movim/movim#910]
Movim sounds to be a complete messaging server. I want to create something like **Skype**. I am looking for an open source solution which is not very complicated to setup and easier to manage through a ui. Signal is very promising, but it is not easy for people like me to setup and manage.

I have few questions.

1. Does it have mobile clients?

2. Does it have capability to handle 1 million Daily Active Users (DAUs)?

3. If you were to give an example of an existing popular messaging software to compare with, which one would it be?

4. Are there any modules or plugins available to extend the functionality?

**Comment by edhelas** [comment]
1. Yes https://f-droid.org/packages/com.movim.movim/
2. No but the XMPP servers can (like ejabberd)
3. Discord/Slack/Mattermost/Rocketchat but with social features on top
4. No, it's one package
