### ISSUE TITLE
Login button disabled

### ISSUE THREAD

**Issue by Botigli** [movim/movim#912]
Hi,

I've upgraded my instance of movim today, from the v0.16.1 version to the v0.17.1.
(VPS on Ubuntu 18.04).

Since the upgrade, which seems to have worked without any issue, my "Connexion" button is disabled (I can not click on it).

In the /var/log/syslog message I can see the message multiple-times  
```
movim.ERROR: setcookie() expects parameter 3 to be integer, array given in /var/www/html/movim/src/Movim/Cookie.php (line 38) Trace  [] []
```
 I've done the `composer install` and db migration steps.

php version: `PHP 7.2.24-0ubuntu0.18.04.3`

**Comment by Botigli** [comment]
I tested a fresh install (I had some troubles with git during the upgrade of my previous folder) but I get the same result: login button disabled and same error message.

I did the following change at line 38 of src/Movim/Cookie.php and now it works.

* original line:
```
setcookie('MOVIM_SESSION_ID', $key, [
                 'expires' => self::getTime(),
                 'path' => '/',
                 'secure' => false
             ]);
```
* my change:
```
setcookie('MOVIM_SESSION_ID', $key, self::getTime(), '/', false);
```
(I don't know php programming but I think my change reflects the goal of the original code)

**Comment by edhelas** [comment]
Movim requires PHP 7.3+ to work properly. We're using a new signature for the setcookie function that was introduced in 7.3 (https://www.php.net/manual/en/function.setcookie.php).
https://github.com/movim/movim/blob/master/composer.json#L14
