### ISSUE TITLE
Manjaro Linux /movim/?admin page blank both on Apache and nginx

### ISSUE THREAD

**Issue by torels** [movim/movim#914]
Hello!
I tried installing movim on my manjaro linux machine but I get a blank page and no significant error showing anywhere.

This is my /var/log/httpd/error_log file:
```
[Wed Apr 01 18:54:09.591391 2020] [mpm_prefork:notice] [pid 4525] AH00170: caught SIGWINCH, shutting down gracefully
[Wed Apr 01 18:54:09.663388 2020] [so:warn] [pid 4647] AH01574: module proxy_module is already loaded, skipping
[Wed Apr 01 18:54:09.697627 2020] [mpm_prefork:notice] [pid 4647] AH00163: Apache/2.4.41 (Unix) PHP/7.4.4 configured -- resuming normal operations
[Wed Apr 01 18:54:09.697677 2020] [core:notice] [pid 4647] AH00094: Command line: '/usr/bin/httpd -D FOREGROUND'
```
There seems to be no critical error, right?

Using mariadb (MySql)

PHP is working correctly, all services' status is ok
PHP is not logging any issue in its log files.

tried `chmod 770` and `chmod 755`. Neither are giving expected results
The server starts fine with a `chown -R http:http /srv/http/movim`
But it fails with a `chown -R movim:http /srv/http/movim` with an Unknown Error

The page is blank,
localhost:8080/movim/ is blank as well

**Comment by torels** [comment]
I got here by navigating the raw PHP files. Seems like the daemon is not running.
It took the login data I set through the daemon.php, so that's working for sure.

I logged on the /srv/http/ directory with 
I started it with `php daemon.php start --url=http://localhost/movim --port=8080`

![Further info](https://user-images.githubusercontent.com/4458523/78176143-53cd5400-745c-11ea-8d81-cf2036494fb9.png)

**Comment by edhelas** [comment]
You're missing some configuration or dependency. Please check `log/error.log` and/or syslog.

**Comment by torels** [comment]
Settled on nginx for the sake of configuration ease, did a fresh install of nginx, php-fpm. Wiped mariadb and set up a new db. Fresh pull from movim.git & fresh install through composer.
Followed install instructions with necessary changes to adapt to Arch systems (www-data user -> http user & /var/www -> /srv/http)

navigating to localhost/movim/?admin returns a 403 Forbidden

syslog only reports this:
`[error] 32603#32603: *1 directory index of "/srv/http/movim/public/" is forbidden, client: 127.0.0.1, server: localhost, request: "GET /movim/?admin HTTP/1.1", host: "localhost"`
which is raised by nginx.service
php-fpm service and mysqld services show no errors, and neither does the movim service.

all files & dirs from /srv/http/movim down are 755 http:http

my /etc/nginx/nginx.conf server section looks like this
```
server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            #root   /usr/share/nginx/html;
            root   /srv/http;
            index  index.php index.html index.htm;
        }
        
        location ~ \.php$ {
              fastcgi_pass   unix:/var/run/php-fpm/php-fpm.sock;
              fastcgi_index  index.php;
              #root   /usr/share/nginx/html;
              root   /srv/http;
              include        fastcgi.conf;
        }


       location /ws/ {
          proxy_pass http://localhost:8080/;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto https;
          proxy_redirect off;
        }
        
        location /movim/ {
          alias /srv/http/movim/public/;

          add_header Access-Control-Allow-Origin *;
          
          location ~ \.php$ {
              fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
              include fastcgi.conf;
          }

          location /movim/ws/ {
              proxy_pass http://localhost:8080/;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "Upgrade";
              include proxy_params;
          }
        }
    }
```

proxy params looks like this
```
proxy_set_header Host $http_host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```
namei -om /srv/http/movim/
```
f: /srv/http/movim/
 drwxr-xr-x root root /
 drwxr-xr-x root root srv
 drwxr-xr-x root http http
 drwxr-xr-x http http movim
```



LEMP setup runs fine otherwise and shows phpinfo(); in /srv/http/ and in subdirectories.

If I remove the nginx.conf settings from `location /movim/` until the end of the server, I can run the PHP files in /movim/public/ but it can't find a server to connect to, so I belive it's the socketing that's raising the 403 error.

Thanks for your help :)

**Comment by edhelas** [comment]
I see two `location /movim/ws/ {` and `location /ws/ {` there, pick one of the two.
You should create a proper virtualhost specificaly for Movim.
I don't know for the 403 forbidden, this is not returned by Movim, it's a misconfiguration on your side.

And you're clearly missing PHP configuration there in your nginx config, here is an example of our prod specific config.

```
        location ~ [^/]\.php(/|$) {
                fastcgi_split_path_info ^(.+?\.php)(/.*)$;
                if (!-f $document_root$fastcgi_script_name) {
                    return 404;
                }

                fastcgi_pass unix:/var/run/php/php7.3-fpm.sock;
                fastcgi_index index.php;

                include /etc/nginx/fastcgi_params;
        }
```

This bug tracker is normally not there to do server admin support, especially when it's related to nginx/php configuration. I'd prefer to pass by our chatroom next time :) xmpp:movim@conference.movim.eu?join
