### ISSUE TITLE
Jingle Video call; session-terminate while ringing does not contain sid

### ISSUE THREAD

**Issue by iNPUTmice** [movim/movim#915]
Hi,

(Tested with what ever version is currently running on nl.movim.eu)

when I try to call someone and then hangup while it is still ringing the resulting `session-terminate` does not contain a `sid`.

On a side note I find it a bit odd that the call sends out a Jingle Init Message (`propose`); But when it is immediately hung up (without the session ever being accepted) I get a jingle IQ set with `session-terminate` instead of a Jingle Init Message `retract`.

Side note in the side note: I clicked the call button next to the specific resource (Conversations in that case); but it is still sending out a message init; As a user I would have expected that at this point I had already made the decision on what resource to talk to and I could just as well have session-initialized that resource directly.

**Comment by edhelas** [comment]
Yes indeed the retract message was not implemented it. I'll try to do it.

**Comment by edhelas** [comment]
I've replaced the reason `success` with `cancel`. I'll see if I can actually answer after that with a proper Jingle Init Message `retract`.
