### ISSUE TITLE
Session store in redis

### ISSUE THREAD

**Issue by Natureshadow** [movim/movim#919]
In order to load-balance Movim or in fallback setups (both e.g. using HAProxy), it seems the only misding part is keeping sessions in sync between nodes. This could be solved by supporting an optional session backend outside the daemon processes' memory.

@edhelas please assign me to this issue (if you can), I am currently testing this in a local setup.

**Comment by edhelas** [comment]
Sure :) Curious to know where this leads

**Comment by Natureshadow** [comment]
@edhelas Would Moxl/Movim handle XMPP sessions that were closed unexpectedly gracefully? I.e. if the socket gets closed, by the server or by whatever, would it just reconnect, go through stream resumption, and continue?

**Comment by edhelas** [comment]
No, There's nothings like that unfortunately in Movim yet.

**Comment by Natureshadow** [comment]
Ok, let's start small: In our failover scenario, if a client moves its WebSocket session from machine A to machine B, the daemon will fail to find the session in its session array in memory. This is sad, but the worst that should happen is that the session is forcefully closed and reestablished. In theory. In practice, the daemon crashes ;). Let's fix this first, PR incoming.

**Comment by edhelas** [comment]
Hey, is there some news on that one ? If not, feel free to close the ticket :)
