### ISSUE TITLE
Messages appear twice

### ISSUE THREAD

**Issue by bef0re** [movim/movim#92]
A friend and I send messages to eachother and they appear twice. Logging out and in again fixes it.
Tested on Firefox and Chrome on Mac OS X and Arch Linux.

![screen shot 2015-11-28 at 18 29 49](https://cloud.githubusercontent.com/assets/9428863/11453166/60240210-9600-11e5-9323-339bfd5d08ec.png)

**Comment by BurningNetel** [comment]
To elaborate on this report, this seems to be an client side issue. When I log out and log in again when I see this bug, and chat to desalniettemin's bugged client, my screen reports 1 message sent, and his screen reports 2 messages recieved. On the other hand, when he sends me a message, his screen reports 2 messages sent, while I recieve 1 message.

**Comment by edhelas** [comment]
I'll leave this issue open but I have to find a way to reproduce it. Thanks for the report.

**Comment by edhelas** [comment]
If you find a way to reproduce it, please tell me.

**Comment by thundergreen** [comment]
Logs deleted, not useful for this issue + contain personal JID

**Comment by thundergreen** [comment]
This appears, when i chat one to one, leave this chat and resume it.

**Comment by alexAubin** [comment]
Hi,

my two cents for this, but I had the same kind of issue on my install in Yunohost before fixing [this issue](https://github.com/src386/movim_ynh/issues/10). Basically I got disconnected every ~60 seconds, except it was not a proper clean disconnection. So after logging back in, the server seemed to think I was logged several times, and as a consequence the client displayed it several times - or at least that's my interpretation.

A way to reproduce the issue might therefore be to set a low proxy_read_timeout value in the nginx config (or the equivalent in apache ?).

**Comment by thundergreen** [comment]
I "fixed" this issue by deactivating the mod_mam_mnesia and took the mod_mam wit muc support (16.12.2015) of ejabberd 15.11

**Comment by edhelas** [comment]
This issue was moved to movim/movim#8

**Comment by edhelas** [comment]
I have a theory regarding this issue (and the issue #128). Movim handles the sessions in sub-processes, each of them synchronizes their states with the Movim database to allow raw HTTP requests to know who is logged in, maintains session and have statistics.

The Movim daemon also has a "cleaning system" here https://github.com/movim/movim/blob/master/src/Movim/Daemon/Core.php#L115 that closes the unused sessions after 2h. Normally it should close the sub-process and cleanup the session line in the database.

I suspect this little tool to only cleanup the database. Movim then thinks that the session is closed even if the process is still open. So when you reload the page (or reopen your browser) Movim redirects you to the login page. The funny thing here is that you still have the same cookie as before so the daemon can still link your "fake-disconnected session" to the daemon and the still-open sub-process.

You will then try to login again, using the same sub-process than before, and, in some way, Movim will link the new TCP-XMPP socket to the old sub-process that already got one open !
You are then logged in, with a valid session and two XMPP sessions bounded to your sub-process ! 

It's a very plausible theory that actually explains several issues that I've found and that have been reported here. I'll continue to investigate and work on a fix.

**Comment by edhelas** [comment]
I've forbid several XMPP sockets to be bound to an unique Movim linker which should prevent this issue.
