### ISSUE TITLE
More XEP-0167 description weirdness

### ISSUE THREAD

**Issue by iNPUTmice** [movim/movim#922]
Hi,

some of these I have reported privately to you so this is just a reminder to keep track of them. But there are also some new ones.

This element doesn’t exist / isn’t defined. Which I will ignore on receive; but I won’t include anything like that we sending it to you.

```
<rtcp-mux xmlns="urn:xmpp:jingle:apps:rtp:1"/>
``` 

The attribute on the `source` element is called `ssrc` not `id`.

```
<source xmlns="urn:xmpp:jingle:apps:rtp:ssma:0" id="1745057535">
  <parameter name="cname" value="07CCmuuvHXtYZPI8" xmlns="urn:xmpp:jingle:apps:rtp:ssma:0"/>
  <parameter name="msid" value="rXuVl5fV956iDiH0h2ydeugUZ1Zb1s2AOILK" xmlns="urn:xmpp:jingle:apps:rtp:ssma:0"/>
  <parameter name="mslabel" value="rXuVl5fV956iDiH0h2ydeugUZ1Zb1s2AOILK" xmlns="urn:xmpp:jingle:apps:rtp:ssma:0"/>
  <parameter name="label" value="f0006f23-9d65-4b3e-83bf-21703caaa47f" xmlns="urn:xmpp:jingle:apps:rtp:ssma:0"/>
  <parameter name="cname" value="07CCmuuvHXtYZPI8" xmlns="urn:xmpp:jingle:apps:rtp:ssma:0"/>
  <!--- … --->
</source>
```

Here are a couple of things weird/wrong.
1) the rtcp-fb elements don’t have and id tag. (The id is taken from the wrapper.) On receive I will just ignore that; but mind you that I won’t include one when sending you an offer; so don’t rely on it during parsing (and better also not include it during sending.
2) If you look at the last two `rtcp-fb` entries; What is really just one entry of type=nack, subtype=pli is split into two elements. The element that only has the type `nack` (no subtype) is redundant  and should be 'merged' with the element that has both type and subtype. In sdp that should be one line.

```
<payload-type name="VP8" clockrate="90000" xmlns="urn:xmpp:jingle:apps:rtp:1" id="96">
  <rtcp-fb type="goog-remb" xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" id="96"/>
  <rtcp-fb type="transport-cc" xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" id="96"/>
  <rtcp-fb subtype="fir" type="ccm" xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" id="96"/
  <rtcp-fb type="nack" xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" id="96"/>
  <rtcp-fb subtype="pli" type="nack" xmlns="urn:xmpp:jingle:apps:rtp:rtcp-fb:0" id="96"/>
</payload-type>
```

**Comment by edhelas** [comment]
Fixed the `id` => `ssrc` parameter

**Comment by edhelas** [comment]
The `rtcp-mux` tag is actually not standard but still present in the SDP. I followed this patch back then to add it (https://wiki.xmpp.org/web/User:Fippo#mapping_a.3Drtcp-mux) it also means that I'm handling it on the other side.

**Comment by edhelas** [comment]
I've fixed the 1., the ids are now handled from the parent element.
However I didn't fixed the 2. as it seems that those `rtcp-fb` elements are generated also like that browser wise.

From Firefox: 

```
a=rtcp-fb:120 nack
a=rtcp-fb:120 nack pli
a=rtcp-fb:120 ccm fir
a=rtcp-fb:120 goog-remb
a=rtcp-fb:121 nack
a=rtcp-fb:121 nack pli
a=rtcp-fb:121 ccm fir
a=rtcp-fb:121 goog-remb
```
From Chrome
```
a=rtcp-fb:98 goog-remb
a=rtcp-fb:98 transport-cc
a=rtcp-fb:98 ccm fir
a=rtcp-fb:98 nack
a=rtcp-fb:98 nack pli
```

Thanks for the feedback !
