### ISSUE TITLE
Impossibility to create an account on movim.eu

### ISSUE THREAD

**Issue by Reue** [movim/movim#925]
If someone chooses a user name with dashes (for instance: r.john.lennon@movim.eu) the server denies the registration with the following error message:
"The username may only contain letters, numbers, and dashes."
This is completely stupid, because the username does indeed only contain letters and dashes!

**Comment by edhelas** [comment]
To me the example you gave contains . and not - (dashes), am I wrong ? https://en.wikipedia.org/wiki/Dash
