### ISSUE TITLE
Broken indentation in RSS feeds

### ISSUE THREAD

**Issue by phoe** [movim/movim#927]
Hey,

the RSS feed for [my blog](https://nl.movim.eu/?blog/phoe%40movim.eu) currently contains the following code snippet:

```html
          <pre>
            <code class="lisp">TRIVIAL-CUSTOM-DEBUGGER&gt; (with-debugger ((lambda (condition hook)
                                           (declare (ignore hook))
                                           (format t ";; Debugging a ~S!~%" 
                                                   (type-of condition))
                                           (throw :handled t)))
                           (list (catch :handled (error 'error))
                                 (catch :handled (break))
                                 (let ((*break-on-signals* 'error))
                                   (catch :handled (signal 'error)))
                                 (catch :handled 
                                   (invoke-debugger (make-condition 'error)))))
;; Debugging a ERROR!
;; Debugging a SIMPLE-CONDITION!
;; Debugging a SIMPLE-CONDITION!
;; Debugging a ERROR!
(T T T T)
</code>
          </pre>
```

There are spaces between `<pre>` and `<code>` which are rendered when other websites try to render that HTML, such as [Planet Lisp](https://planet.lisp.org/). That causes the first line to be heavily indented to the right:

![Zrzut ekranu z 2020-04-15 22-59-10](https://user-images.githubusercontent.com/15045546/79387903-bb12fa00-7f6c-11ea-8851-7a4b3f9f2d07.png)

**Comment by phoe** [comment]
Another, more visible example:

![Zrzut ekranu z 2020-04-15 23-00-02](https://user-images.githubusercontent.com/15045546/79387976-dd0c7c80-7f6c-11ea-917a-5ae14142d637.png)

**Comment by edhelas** [comment]
Do you have a link to the faulty Pubsub article ?

**Comment by phoe** [comment]
Pubsub article? I don't understand what that is.

The two failing articles mentioned in here are:

* https://nl.movim.eu/?blog/phoe%40movim.eu/common-lisp-trivial-custom-debugger-KRBfxy
* https://nl.movim.eu/?blog/phoe%40movim.eu/0c354eac-3d8d-4d1b-8123-99d1d81d41d6

**Comment by edhelas** [comment]
Thanks, that's what I needed ;)

**Comment by edhelas** [comment]
![Capture d’écran_2020-04-16_18-51-15](https://user-images.githubusercontent.com/3726886/79484051-68404d80-8013-11ea-8aee-0bd845485997.png)

So what is actually the issue there ? To me this is looking perfectly fine.

**Comment by edhelas** [comment]
The rendering on the code looks the same on Movim and on Planet List, no ?

**Comment by phoe** [comment]
The first line is misindented due to spaces between `<pre>` and `<code>`.

![Zrzut ekranu z 2020-04-16 18-58-19](https://user-images.githubusercontent.com/15045546/79484659-4b584a00-8014-11ea-95d6-48bb3d83c37f.png)

![Zrzut ekranu z 2020-04-16 18-58-00](https://user-images.githubusercontent.com/15045546/79484629-41cee200-8014-11ea-90f1-beb94be071c7.png)

**Comment by edhelas** [comment]
Well to me it's actually Planet List that is buggy. It should look like this.
![Capture d’écran_2020-04-16_19-01-25](https://user-images.githubusercontent.com/3726886/79484979-cae61900-8014-11ea-900e-66257785ad2f.png)

**Comment by phoe** [comment]
Planet Lisp correctly implements the `<pre>` tag and renders the spaces contained within it. 

[The specification](https://www.w3schools.com/tags/tag_pre.asp) says:
> Text in a \<pre> element is displayed in a fixed-width font (usually Courier), and it preserves both spaces and line breaks.

In the Atom feed, we have the following:

![Zrzut ekranu z 2020-04-16 19-04-44](https://user-images.githubusercontent.com/15045546/79485236-2e704680-8015-11ea-9c45-6415ca1c5887.png)

These are the spaces that are rendered in Planet Lisp.

**Comment by phoe** [comment]
The issue still occurs for me after the post I have just made.

Other feeds scanned by Planet Lisp are rendered correctly - it is just the movim one.

![Zrzut ekranu z 2020-05-18 22-18-27](https://user-images.githubusercontent.com/15045546/82255790-87553680-9955-11ea-97cf-4cd13a2e581e.png)

![Zrzut ekranu z 2020-05-18 22-18-32](https://user-images.githubusercontent.com/15045546/82255805-90460800-9955-11ea-90af-a717d9efd814.png)

**Comment by phoe** [comment]
Is it possiblefor you to fix it any soon? If not, I'll need to move off Movim and to another blogging platform, since I want to post some more code snippets soon.

**Comment by edhelas** [comment]
Movim actually respects the spaces between the `<pre>` and `<code>` tag in how the XHTML and the CSS is handled.

![Capture d’écran_2020-12-19_22-59-22](https://user-images.githubusercontent.com/3726886/102700474-05601f80-424e-11eb-9d94-c87af7d50883.png)

The issue that you have here is that you're editing your code using Markdown and the "```lisp" syntax.
Movim uses the PHP Markdown reference library https://github.com/michelf/php-markdown to convert Markdown to XHTML. There's no way in Markdown to actually add spaces or carriage return from Code blocks in Markdown between those two tags , at least in this version and with this library, check https://daringfireball.net/projects/markdown/syntax#precode 

The solutions that you have there:
- Add carriage return and spaces within the "```lisp" tag, as they are not truncated they will be displayed as intended
- Edit manually the HTML using another XMPP client
- Publish Movim blog posts using a tool like https://github.com/edhelas/atomtopubsub and write the Atom from another platform.

As this is not a Movim issue by itself, and as it is not a Markdown library issue (it is working "as it is intented") I'm not planning to change anything in Movim nor open a ticket in the Markdown dependency for this issue.

**Comment by phoe** [comment]
OK - thanks for the explanation. I'll investigate the workarounds!
