### ISSUE TITLE
Unable to get going with Movim after install

### ISSUE THREAD

**Issue by davidjmorin** [movim/movim#929]
Fresh install on a local debian server.  I used the debian repository.  After install I tried to start the server and am just getting errors all over the place.  

https://hastebin.com/abeyotosuf.coffeescript

I have also run the command 
```
root@debian:/# sudo a2enmod proxy_http
Considering dependency proxy for proxy_http:
Enabling module proxy.
Enabling module proxy_http.
To activate the new configuration, you need to run:
  systemctl restart apache2
root@debian:/# movim start

Invalid or missing url parameter
root@debian:/#
```

Anyone know how to fix this?

**Comment by edhelas** [comment]
I you install Movim using the Debian package you have nothing more to do that configure your web server. 

There is no such things as a "movim" executable. The package is using systemd.

If you need help for the deployment. Please join our support chatroom at xmpp:movim@conference.movim.eu?join

**Comment by Natureshadow** [comment]
>There is no such things as a "movim" executable. The package is using systemd.

Oh, there actually is. It is installed as a wrapper script to call daemon.php from the correct directory and as the correct user (i.e. running movim --config ... from anywhere does the right thing).

-nik

**Comment by edhelas** [comment]
Ah my bad. So basically if it's a wrapper around daemon.php, then it needs the same parameters as daemon.php. Please check https://github.com/movim/movim/wiki/Install-Movim#3-start-the-daemon for more info.
