### ISSUE TITLE
Invalid parameter (missing name) in payload-type

### ISSUE THREAD

**Issue by iNPUTmice** [movim/movim#930]
Firefox payload-type id 101

When using Firefox (Chrome works fine) Movim is sending some invalid parameters for one of the payload types (the one with the id 101; can’t tell you the name; sorry; but i think it was the first one)

```xml
<parameter name="maxplaybackrate" value="48000" xmlns="urn:xmpp:jingle:apps:rtp:1"/>
<parameter name="stereo" value="1" xmlns="urn:xmpp:jingle:apps:rtp:1"/>
<parameter name="useinbandfec" value="1" xmlns="urn:xmpp:jingle:apps:rtp:1"/>
<parameter value="0-15" xmlns="urn:xmpp:jingle:apps:rtp:1"/>
```

Notice that the last parameter has no name.

My Jingle-SDP converter is extremely strict because it is very easy to crash libwebrtc without a way to recover if i provide it with invalid data. That’s why I notice these things.

(By the way Conversations should produce decent, human readable reasons in the session-terminate in cases like those; so for example in this case it would have said "parameter 101 is missing name" - so for further debugging it's worth taking a look)

FWIW: When I skip over that parameter everything works fine.

**Comment by edhelas** [comment]
So I commented the faulty code for the moment, it doesn't seems to have impact afaik.
This will need some investigation to see how the RFC handle that and if there's a gap in the XEP.
I'm keeping the ticket open for now.

**Comment by iNPUTmice** [comment]
It seems to be a gap in 0167 first discovered in 2011 (https://mail.jabber.org/pipermail/jingle/2011-March/001438.html).
But just abusing `<parameter value="…"/>` here is not a good solution IMHO. Also pointed out by Dave in the old thread.
Especially if you consider that according to https://tools.ietf.org/html/rfc4733#section-2.4
`<parameter value="0-15,66,70"/>` would be a valid value then too even though that’s clearly multiple values.
