### ISSUE TITLE
Error While installing instance using debian package

### ISSUE THREAD

**Issue by iManolin** [movim/movim#931]
Hi
This is error is happen while installing using debian package

```
apache2_invoke: Enable configuration movim
apache2_reload: Your configuration is broken. Not reloading Apache 2
apache2_reload: AH00526: Syntax error on line 1 of /etc/apache2/conf-enabled/movim.conf:
apache2_reload: Invalid command 'ProxyPass', perhaps misspelled or defined by a module not included in the server configuration
Created symlink /etc/systemd/system/multi-user.target.wants/movim.service → /lib/systemd/system/movim.service.
/usr/sbin/policy-rc.d returned 101, not running 'start movim.service'
```

Can anyone tell me how to fix this please thanks

**Comment by edhelas** [comment]
As explained in the error, you need to enable the `mod_proxy_http` module on Apache and restart the daemon. You can also report this specific error specifically to the Debian packagers https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=movim;dist=unstable .
