### ISSUE TITLE
Can't install it PLEASE HELP!!!

### ISSUE THREAD

**Issue by caww** [movim/movim#934]
Hi,
First of all, I'm very grateful to you for developing such a system. But unfortunately, I still (2 weeks) can not install it on my server. Please help me in this! I really hope for your help.
I used this manual many times
https://github.com/movim/movim/wiki/Install-Movim
and changed many variables by any ways but not working yet
Always loop in reconnecting to the server and says -- no proxy enabled
But i enabled using your nginx example
I also enabled tunnel proxy in apache but movim installing ok and database too
but not working admin -- i cant login because page reconnecting to the server unlimited as loop
Please help!!!

I have the following configuration:
1. apache2 on 8080 port 
2. Nginx as proxy on 443 port for static files only
config of apache2:
```
<VirtualHost 127.0.0.1:8080>
	ServerName address.com
	ServerAlias www.address.com
	DocumentRoot /var/www/useraaaa/data/www/address.com
	ServerAdmin webmaster@address.com
	DirectoryIndex index.php index.html
	AddDefaultCharset UTF-8
	AssignUserID useraaaa useraaaa
	CustomLog /dev/null combined
	ErrorLog /dev/null
	<FilesMatch "\.ph(p[3-5]?|tml)$">
		SetHandler application/x-httpd-php
	</FilesMatch>
	<FilesMatch "\.phps$">
		SetHandler application/x-httpd-php-source
	</FilesMatch>
	<IfModule php5_module>
		php_admin_value sendmail_path "/usr/sbin/sendmail -t -i -f webmaster@address.com"
		php_admin_value upload_tmp_dir "/var/www/useraaaa/data/mod-tmp"
		php_admin_value session.save_path "/var/www/useraaaa/data/mod-tmp"
		php_admin_value open_basedir "none"
	</IfModule>
	<IfModule php7_module>
		php_admin_value sendmail_path "/usr/sbin/sendmail -t -i -f webmaster@address.com"
		php_admin_value upload_tmp_dir "/var/www/useraaaa/data/mod-tmp"
		php_admin_value session.save_path "/var/www/useraaaa/data/mod-tmp"
		php_admin_value open_basedir "none"
	</IfModule>
	SetEnvIf X-Forwarded-Proto https HTTPS=on
ProxyPass /ws/ ws://localhost:8080/
</VirtualHost>
<Directory /var/www/useraaaa/data/www/address.com>
	Options -ExecCGI
	<IfModule php5_module>
		php_admin_flag engine on
	</IfModule>
	<IfModule php7_module>
		php_admin_flag engine on
	</IfModule>
</Directory>
```

config of nginx:
```
server {
	server_name address.com www.address.com;
	charset UTF-8;
	index index.php index.html;
	disable_symlinks if_not_owner from=$root_path;
	include /etc/nginx/vhosts-includes/*.conf;
	include /etc/nginx/vhosts-resources/address.com/*.conf;
	access_log off;
	error_log /dev/null crit;
	return 301 https://$host:443$request_uri;
	set $root_path /var/www/useraaaa/data/www/address.com;
	root $root_path;
	listen XXX.XXX.XXX.XXX:80;
	listen [XXX:XXX:XXX:XXX::X]:80;
	gzip on;
	gzip_comp_level 5;
	gzip_disable "msie6";
	gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;
	location / {
		location ~ [^/]\.ph(p\d*|tml)$ {
			try_files /does_not_exists @fallback;
		}
		location ~* ^.+\.(jpg|jpeg|gif|png|svg|js|css|mp3|ogg|mpe?g|avi|zip|gz|bz2?|rar|swf)$ {
			expires 8d;
			try_files $uri $uri/ @fallback;
		}
		location / {
			try_files /does_not_exists @fallback;
		}
	}
	location @fallback {
		proxy_pass http://127.0.0.1:8080;
		proxy_redirect http://127.0.0.1:8080 /;
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-Port $server_port;
		access_log off;
	}
	location /ws/ {
    proxy_pass https://127.0.0.1:8080/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect off;
}
}
server {
	server_name address.com www.address.com;
	ssl_certificate "/var/www/httpd-cert/useraaaa/address.com_le3.crtca";
	ssl_certificate_key "/var/www/httpd-cert/useraaaa/address.com_le3.key";
	ssl_ciphers EECDH:+AES256:-3DES:RSA+AES:!NULL:!RC4;
	ssl_prefer_server_ciphers on;
	ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
	add_header Strict-Transport-Security "max-age=31536000;";
	ssl_dhparam /etc/ssl/certs/dhparam4096.pem;
	charset UTF-8;
	index index.php index.html;
	disable_symlinks if_not_owner from=$root_path;
	include /etc/nginx/vhosts-includes/*.conf;
	include /etc/nginx/vhosts-resources/address.com/*.conf;
	access_log off;
	error_log /dev/null crit;
	set $root_path /var/www/useraaaa/data/www/address.com;
	root $root_path;
	listen [XXXX:XXXX:XXXX:XXXX::X]:443 ssl http2;
	listen XX.XX.XX.XX:443 ssl http2;
	gzip on;
	gzip_comp_level 5;
	gzip_disable "msie6";
	gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript application/javascript;
	location / {
		location ~ [^/]\.ph(p\d*|tml)$ {
			try_files /does_not_exists @fallback;
		}
		location ~* ^.+\.(jpg|jpeg|gif|png|svg|js|css|mp3|ogg|mpe?g|avi|zip|gz|bz2?|rar|swf)$ {
			expires 8d;
			try_files $uri $uri/ @fallback;
		}
		location / {
			try_files /does_not_exists @fallback;
		}
	}
	location @fallback {
		proxy_pass http://127.0.0.1:8080;
		proxy_redirect http://127.0.0.1:8080 /;
		proxy_set_header Host $host;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_set_header X-Forwarded-Port $server_port;
		access_log off;
	}
	location /ws/ {
    proxy_pass https://127.0.0.1:8080/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect off;
}
}
```

**Comment by ooptimum** [comment]
It seems your Apache and Movim daemon share the same 8080 port. This won't work. Do you really need Apache to run Movim? Anyways, if you do need it for something else, I can help you to configure Nginx to handle Movim in a subdirectory, like https://yourdomain.tld/movim or something.

**Comment by caww** [comment]
Hi @ooptimum !
Thanks for answer. I ready to listen any way for have success.
I use apache + nginx in my os and will continue to use like this but if its possible to use just nginx for only this virtualhost/nginx server for only this separated domain then i ready of course

I mean if possible to use any configuration of nginx and not use apache then i ready --- but i dont want to use php-fpm

if you say that is possible to use movim without apache then i ready but i dont understand how php language will work without apache and without php-fpm?

**Comment by ooptimum** [comment]
Hi @caww!

I didn't say that php-fpm wouldn't be used. If you don't want to use it, that leaves only your approach involving Apache. Just make sure you don't use the same port for the Apache and the Movim demon. By the way, do you start this daemon at all? This is described in step 3 of the Movim Installation Guide. I wonder how no Apache nor Movim is complaining that port 8080 is already taken by some other program.

**Comment by caww** [comment]
I tried it many times
i changed port from 7777 to 8888 
its not solution 
and yes i starting server in ssh
i did all as in instruction many times by different ways
but not working

**Comment by ooptimum** [comment]
@caww,  this should help you:
1. Remove the "ProxyPass /ws/ ws://localhost:8080/" line from the Apache config;
2. Change the "/ws/" location in the Nginx config, so it reads as:
```
    location /ws/ {
        proxy_pass http://127.0.0.1:8000/;
```
3. Reload both web servers;
4. Start the Movim daemon with  --port=8000.

**Comment by caww** [comment]
Interesting... thanks for advices! Going to try it. Will get back with results.

**Comment by caww** [comment]
Tried but same error in console of chrome
by the way in this time tester without ssl

WebSocket connection to 'ws://address.com/public/ws/?path=admin&offset=-420' failed: Error during WebSocket handshake: Unexpected response code: 404
init @ movim_websocket.js?t=1589557128:89
movim_websocket.js?t=1589557128:147 Connection error!
movim_websocket.js?t=1589557128:284 Try to reconnect

**Comment by caww** [comment]
and i installed movim using composer install 
so path is not standard 
in /movim/ nothing folder name is other

**Comment by ooptimum** [comment]
Look, your browser tries to connect to a listening websocket at the '/public/ws/' while in the Nginx configuration you expect incoming connections at the '/ws/', i.e. without this '/public' prefix. So make it listening at the '/public/ws/' in the proxied location. That's it. Just be scrupulous with the settings and it'll work.

I mean replace this:
`location /ws/ {`
with that:
`location /public/ws/ {`

**Comment by ooptimum** [comment]
It seems you haven't fully understood the architecture of the Movim server. The server itself can be located anywhere, I suppose there is no any "standard" location.

In the Movim architecture there are two servers to handle users requests, an http server and the Movim daemon.

The "public" folder inside your Movim server's root folder is a responsibility of your Apache server, and it should be either the root folder of a virtual host or a virtual path (alias) in the config. This (/ vs. /some/path) also affects the "url" parameter you specify when starting the Movim daemon. I guess you specified the root folder of the Movim server as a DocumentRoot, which is incorrect.

The daemon itself is listening for websocket connections on the port you specify when it starts. Actually all incoming connections will come on the url (from the above) + "/ws/" path. These connections (on this path prefix) you have to proxy to the port your Movim daemon is listening on. You do this in the appropriate "location" in the Nginx config, which we have discussed already.

**Comment by caww** [comment]
:) wow - its started working!!! Exacly your right about my error. I confused exacly with nginx config... I though about but decided to ask help! You helped me - i understood issue
And now i can configure easy without public folder in the end of url because i know issue!!!
Many thanks!

**Comment by edhelas** [comment]
Well looks like it's resolved :)
