### ISSUE TITLE
Invalid or missing url parameter

### ISSUE THREAD

**Issue by BenjiHVG** [movim/movim#935]
Hello sorry for my englsih is very bad im french but i have installed with depencies movim and prosody on my debian 10 system with apt-get install i configured everthing but the deamon indicated Invalid or missing url parameter
 with a command i have make everthing i dont understand ^^

please help im worried im work that with 1 month but i undersatnd 

Thanks you

**Comment by BenjiHVG** [comment]
with the command with php deamon php

**Comment by edhelas** [comment]
Well, as it says, you have to provide the `--url` parameter as it is explained in the "One page only documentation" https://github.com/movim/movim/wiki/Install-Movim#3-start-the-daemon
