### ISSUE TITLE
Jingle Message Propose from a JID whose localpart contains a backslash never receives a reply

### ISSUE THREAD

**Issue by singpolyma** [movim/movim#940]
Movim will "ring" and allow to refuse or reply to the phone call, but the proceed or reject message never makes it back to the caller if the have a JID such as `boop\40thing.xyz@sip.cheogram.com` -- it seems in my tests that any presence of a backslash triggers this bug, whereas JIDs with no backslash in the localpart are handled by Movim as expected.

**Comment by edhelas** [comment]
What SIP - Jingle transport are you using ? With which SIP client on the other side ? (simple curiosity)
Is it possible to have a test account then I can reproduce ?

**Comment by singpolyma** [comment]
>What SIP - Jingle transport are you using ? With which SIP client on the 
>other side ? (simple curiosity)
>Is it possible to have a test account then I can reproduce ?

I am developing one.  It is public (if incomplete) you may use it.

To reproduce, use any sip client to call:

sip:your%40jid.tld@sip.cheogram.com

I am testing with linphone on debian, but most any sip client should do.

**Comment by edhelas** [comment]
It seems that Movim can handle properly calls coming from and to JIDs with backslashs in them.
The issue has been fixed.

![image](https://user-images.githubusercontent.com/3726886/194427496-c01834db-eb72-4738-86ca-4d798ec3d9d3.png)
