### ISSUE TITLE
Some messages don't show bubbles info flying by the mouse

### ISSUE THREAD

**Issue by eyome** [movim/movim#944]
With bubble info:
![With bubble info](https://user-images.githubusercontent.com/1254269/94734455-8e5f6d00-0369-11eb-9f8e-a85074b954d3.png)

Without bubble info:
![Without bubble info](https://user-images.githubusercontent.com/1254269/94734467-91f2f400-0369-11eb-8b7e-f58eeee0d803.png)

Without bubble info, it's not possible to edit or delete a message.

**Comment by edhelas** [comment]
Except for the pictures its possible on all the messages now
