### ISSUE TITLE
Lost password

### ISSUE THREAD

**Issue by eapo** [movim/movim#945]
I there any way to recover lost passwords on https://api.movim.eu/accounts/register ?

**Comment by edhelas** [comment]
Nope, not yet, but it could be a nice feature yes. The only issue is that it would require another way to authenticate people (like an email) :/

**Comment by trymeouteh** [comment]
I would like a optional feature to attach an email address to your account to be able to reset your password

**Comment by edhelas** [comment]
This has been implemented https://api.movim.eu/accounts

**Comment by nicfab** [comment]
> This has been implemented https://api.movim.eu/accounts

I lost my password, but the page is unusable as the image I attached.

![CleanShot 2022-07-11 at 17 15 56](https://user-images.githubusercontent.com/24752671/178297889-f11c1bfd-ade0-4e85-a593-673c37a09120.png)
Can you please let me know how to retrieve my password?
