### ISSUE TITLE
Not able to connect through alpn nginx stream port 443

### ISSUE THREAD

**Issue by 12aw** [movim/movim#947]
Hi,
as discussed it was not or just randomly possible to log in to movim when the xmpp server is using and nginx alpn stream or with sslh like described here: 
https://wiki.xmpp.org/web/Tech_pages/XEP-0368
I tested this with other clients and didn't have a a problem. The problem is that movim doesn't recognize the error and still endlessly tries to login trough 443 instead falllback to 5222.

Maybe there could be a hint in the installation instructions / wiki that this could cause problems.

**Comment by edhelas** [comment]
I am not supporting ALPN in Movim.
