### ISSUE TITLE
"Frequent contacts" panel doesn't show frequent contacts

### ISSUE THREAD

**Issue by eyome** [movim/movim#949]
It shows, in fact, contacts whom the conversation has been closed pushing the cross below:

![image](https://user-images.githubusercontent.com/1254269/102013741-4938bd80-3d52-11eb-8058-b17405827081.png)

**Comment by edhelas** [comment]
It show contacts that has the most messages exchanged recently, if you only have a few it might look weird in the beginning but will get more accurate with time.
