### ISSUE TITLE
ERROR Declaration should be compatible with Illuminate\Database\Eloquent\Model(...) on fresh movim 0.18 install

### ISSUE THREAD

**Issue by guillaume-uH57J9** [movim/movim#953]
Movim 0.18 is broken right after doing a fresh installation.
Movim installation: release tarball fetch from github.
Dependencies installation: today's latest fetched by composer. 
OS: Debian 10.7. 

The following error appear in logs: 
> Dec 26 18:15:12 HOSTNAME movim[29416]: movim.ERROR: Declaration of Movim\Model::setKeysForSaveQuery(Illuminate\Database\Eloquent\Builder $query) should be compatible with Illuminate\Database\Eloquent\Model::setKeysForSaveQuery($query) in /var/www/HOSTNAME/movim-0.18/src/Movim/Model.php (line 104) Trace  [] []

Modifying src/Movim/Model.php as follows seems to fix that issue: 
```
// Before
    protected function setKeysForSaveQuery(Builder $query)
// After
    protected function setKeysForSaveQuery($query)
```

**Comment by guillaume-uH57J9** [comment]
I suspect this broke because of a change in setKeysForSaveQuery within Illuminate\Database.
See https://github.com/laravel/framework/issues/34578

For information, here is an extract of the output of "composer show -i"

> illuminate/collections           v8.20.1   The Illuminate Collections package.
> illuminate/container             v8.20.1   The Illuminate Container package.
> illuminate/contracts             v8.20.1   The Illuminate Contracts package.
> illuminate/database              v8.20.1   The Illuminate Database package.
> illuminate/macroable             v8.20.1   The Illuminate Macroable package.
> illuminate/support               v8.20.1   The Illuminate Support package.

**Comment by edhelas** [comment]
Similar to #951

Hi, it seems that this was fixed on master. 
I'll tag a new release candidate soon if you want to jump to that version.

**Comment by guillaume-uH57J9** [comment]
Thanks for the reply.

I applied a quickfix locally so there's no hurry for me to jump to another version. 
However a release (candidate) may help others, since someone doing a fresh 0.18 install (ie latest release) may encounter this blocking bug.
