### ISSUE TITLE
Do not display both summary and full content on Atom-generated pubsub nodes

### ISSUE THREAD

**Issue by raspbeguy** [movim/movim#955]
Hello

Atom feeds enables to have 2 fields on each entries:

- `summary` which is a one-line-or-so summary of the post.
- `content` which is the full post content.

It happens that both fields are presents.

Some feed generators takes the first few dozen of characters from the posts and put it in `summary`. So when Movim shows an entry, it shows the summary followed by the content, which is quite annoying in this case. Check [this page](https://nl.movim.eu/?node/pubsub.gugod.fr/atomtest) for example.

**Comment by edhelas** [comment]
https://tools.ietf.org/html/rfc4287#page-25
```
   It is not advisable for the atom:summary element to duplicate
   atom:title or atom:content because Atom Processors might assume there
   is a useful summary when there is none.
```

**Comment by raspbeguy** [comment]
Not advisable but still applied on many atom feeds.
