### ISSUE TITLE
Need confirmation before deleting post

### ISSUE THREAD

**Issue by baraganx** [movim/movim#956]
When I wanted to edit a post I wrote, I slipped a few mm and deleted my post. As it was immediate, I didn't understand it right away and I looked for it for a while...
I think a confirmation message before deletion would not be too much.
![Capture d’écran de 2021-01-14 22-02-38](https://user-images.githubusercontent.com/77464564/104649176-347e7b00-56ac-11eb-804b-b98783afb6d0.png)

**Comment by edhelas** [comment]
![Capture d’écran_2021-01-17_19-20-59](https://user-images.githubusercontent.com/3726886/104852125-2e310e80-58f9-11eb-8b9e-333203c7b8fe.png)
It was already the case, I forgot that there was this feature :)

**Comment by baraganx** [comment]
thank you :)
