### ISSUE TITLE
Can't use adhoc commands within admin account only "close" Button there

### ISSUE THREAD

**Issue by thundergreen** [movim/movim#96]
When I try to use the admin adhoc commands, a windows opens, but no "send" button appears. Can't use the adhoc commands

Server: Ejabberd 15.11 self built.

**Comment by edhelas** [comment]
Can I have a screenshot of the issue + which AdHoc Ejabberd command you exactly launched ?

**Comment by thundergreen** [comment]
http://pasteboard.co/1Nyqqcg.png
![Image of Movim AdHoc Admin](http://pasteboard.co/1Nyqqcg.png)

![Image of Movim AdHoc Admin](http://pasteboard.co/1NDWx7i.png)

**Comment by thundergreen** [comment]
![image](https://cloud.githubusercontent.com/assets/13320319/11783076/6ac7b654-a275-11e5-8e01-d8f14f39254d.png)

**Comment by thundergreen** [comment]
![image](https://cloud.githubusercontent.com/assets/13320319/11783086/759da87c-a275-11e5-928d-3c7f8ae3bc44.png)

**Comment by thundergreen** [comment]
![image](https://cloud.githubusercontent.com/assets/13320319/11783095/8372b488-a275-11e5-9794-b2dc98a335b6.png)

**Comment by thundergreen** [comment]
![image](https://cloud.githubusercontent.com/assets/13320319/11783118/9fefe8d8-a275-11e5-92b9-bc57aa3fed47.png)

**Comment by thundergreen** [comment]
![image](https://cloud.githubusercontent.com/assets/13320319/11783128/a8dd03cc-a275-11e5-9c16-dd823e0996e6.png)

**Comment by thundergreen** [comment]
Did u check this issue or do u need some further info?

Thorsten Fröhlich
Am 14.12.2015 13:36 schrieb "Jaussoin Timothée" notifications@github.com:

**Comment by edhelas** [comment]
This issue was moved to movim/movim#7
