### ISSUE TITLE
Messages in chat not sent with entry button

### ISSUE THREAD

**Issue by EchedelleLR** [movim/movim#963]
* Web browser: Pale Moon 28.17.0
* Instance: https://mov.im/
* Other information: new lines are added instead and no issues in other webapps like Element.

**Comment by EchedelleLR** [comment]
It seems that when I put the web browser in desktop on side screen (enabling responsive mode) I cannot send with entry button but when I put the browser in full screen, I can perfectly.

I use to work with the browser in side screen. Is there no possibility to maintain this behavior for desktop in side screen?

A friend told me that this behavior could be expected given that it is not needed on mobile, for which the responsive mode is designed but I don't think enabling this behavior on this mode would affect negatively to mobile users as Element when loaded in the same way doesn't cause any issue.

**Comment by edhelas** [comment]
This has been fixed with https://github.com/movim/movim/pull/973
