### ISSUE TITLE
Attached images are shown as links

### ISSUE THREAD

**Issue by adbenitez** [movim/movim#964]
when you attach an image to your post, it is not show at the bottom of the post, instead a card with a "weird" link is shown, to be able to show the image I had to copy the link and use markdown then the image is shown and the link is hidden, on mobile copying the link is almost impossible without first publishing the post, and having to use markdown to make the image visible is unexpected and hard to do for most users.

if the attached image is not used in the markdown it should be shown instead of its link.

## Current behavior:
![image](https://user-images.githubusercontent.com/24558636/106394036-5ffda700-63c8-11eb-996a-3bbb2f8da1a0.png)

## Expected behavior:
![image](https://user-images.githubusercontent.com/24558636/106394073-9f2bf800-63c8-11eb-87c3-ff7dd20d947f.png)

**Comment by edhelas** [comment]
This was fixed in https://github.com/movim/movim/commit/9eed62d90f073b29ed10ab856fe14e1d3cb49a2e
