### ISSUE TITLE
Is there still a way to add a new contact by JabberID?

### ISSUE THREAD

**Issue by singpolyma** [movim/movim#965]
The UI seems to want to search local directories now instead...

**Comment by singpolyma** [comment]
I have been through the flow a few times now and figured it out. I seems that if I type a "normal looking" JID into the search box, that it will show an option to add that.  But if I type something like `cheogram.com`, which is a valid JID and definitely something you can chat with, it does not consider that worth showing as addable.

**Comment by edhelas** [comment]
Yes the search too doesn't allow you to actually search for contacts that are not having a "username" part.
I'm not sure if it's an actual issue to me.

**Comment by poVoq** [comment]
This is sometimes needed when adding transports.
