### ISSUE TITLE
Can't accept incoming call on Movim connected with a "conversations.im" account

### ISSUE THREAD

**Issue by baraganx** [movim/movim#966]
Conversations: 2.9.6+fcr on Android 7.0 with a quicksy account

### Movim -> Conversations 
- tested Movim with an account "conversations.im" and "movim.eu".
- tested with Chromium and Firefox
Everything is OK

### Movim1 -> Movim2 :
- tested Movim2 with an account "conversations.im" and "movim.eu".
- tested with Chromium and Firefox
Everything is OK

#### from Firefox (78.7.0esr on Linux Debian 10)
with an account "movim.eu" and "conversations.im" : does not work ([issue](https://github.com/movim/movim/issues/957)), probably a Firefox problem

#### from Chromium (87.0.4280.141-0.1 linux debian):
Movim with an account "movim.eu : OK
Movim with a "conversations.im" account :
##### audio call
OK

##### video call
when you pick up the handset on the movim side, the webcam is activated and the window starts to display with a time countdown, but on the Conversations side, the phone is not aware that movim has picked up the handset and is waiting for an answer.

**Comment by edhelas** [comment]
Looks similar to #957 no ?

**Comment by baraganx** [comment]
It's not the same bug because I'm not under firefox. 

Otherwise I did the test again, it made the same problem. I tried it again and it worked this time... I don't know what to think about it.

**Comment by edhelas** [comment]
I was not able to reproduce the issue. I works for me using Firefox calling from Conversations.
