### ISSUE TITLE
Upload Failed - Images - Blocked by CORS Policy

### ISSUE THREAD

**Issue by imattau** [movim/movim#967]
When attempting to upload images, Movim gives an Upload Failed error...

Browser output shows

`Access to XMLHttpRequest at 'https://xmpp-upload.example.com/upload/image.type' from origin 'https://subdomain.example.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.`

*Note - Upload works from all other XMPP clients*

**Comment by imattau** [comment]
Additional browser error information (might be of assistance?)
`
PUT https://xmpp-upload.example.com/upload/gjgDqyedNjaj8117/icon.png net::ERR_FAILED

  | request | @ | Upload_upload.js?t=1612482308:226
-- | -- | -- | --
  | handle | @ | movim_websocket.js?t=1612482308:274
  | connection.onmessage | @ | movim_websocket.js?t=1612482308:127

`

**Comment by citronalco** [comment]
Are you using Prosody and the share.php script?
I've had the same issue with it: For some reason Movim does an OPTION request (I haven't seen that with any other client so far), but the share.php script which sets the appropriate headers is only called on GET and POST requests. So you have to set the headers for OPTION requests on your own.

In Apache this is:
```
SetEnvIf Request_Method "^OPTIONS$" METHOD_OPTIONS
Header always set Access-Control-Allow-Origin "*" env=METHOD_OPTIONS
Header always set Access-Control-Allow-Headers "Content-Type" env=METHOD_OPTIONS
Header always set Access-Control-Allow-Methods "OPTIONS, PUT, GET" env=METHOD_OPTIONS
```
"SetEnfIf" is required to avoid sending duplicate Headers on GET and POST, otherwise you get those "header contains multiple values of ..." errors.

As using the OPTION request is not that common in XMPP clients, some other HTTP Upload providers beside Prosody's share.php might have the same issue.

**Comment by baraganx** [comment]
@imattau Which account do you log in with? and your recipient?
I use a conversations.im account and no problem.
A friend has a similar problem using a chapril.org account and it works with another web client (xabber for example).

![](https://i65.servimg.com/u/f65/20/26/58/89/erreur10.png)

same problem when he tries to include an image in a blog post.

**Comment by imattau** [comment]
> Are you using Prosody and the share.php script?
> I've had the same issue with it: For some reason Movim does an OPTION request (I haven't seen that with any other client so far), but the share.php script which sets the appropriate headers is only called on GET and POST requests. So you have to set the headers for OPTION requests on your own.
> 
> In Apache this is:
> 
> ```
> SetEnvIf Request_Method "^OPTIONS$" METHOD_OPTIONS
> Header always set Access-Control-Allow-Origin "*" env=METHOD_OPTIONS
> Header always set Access-Control-Allow-Headers "Content-Type" env=METHOD_OPTIONS
> Header always set Access-Control-Allow-Methods "OPTIONS, PUT, GET" env=METHOD_OPTIONS
> ```

Thanks. I'm running nginx, but it appears that it has the OPTIONS set....

**Comment by imattau** [comment]
> @imattau Which account do you log in with? and your recipient?
> I use a conversations.im account and no problem.
> A friend has a similar problem using a chapril.org account and it works with another web client (xabber for example).
> 
> ![](https://camo.githubusercontent.com/8a20346ab90cd8b91a8750ff6787a55db9129a3330bb44a7b1cf54ffed601f59/68747470733a2f2f6936352e73657276696d672e636f6d2f752f6636352f32302f32362f35382f38392f65727265757231302e706e67)
> 
> same problem when he tries to include an image in a blog post.

I'm self hosting my own XMPP server and Movim pod.... I also have no issues when using another client, but then they're not web based either...

**Comment by M-Stenzel** [comment]
Maybe this is a solution:

put this (and replace the old entries) in your apache configuration file:

Header always set Access-Control-Allow-Origin "*"
Header always set Access-Control-Allow-Methods "OPTIONS, HEAD, GET, PUT"
Header always set Access-Control-Allow-Headers "*"
Header always set Access-Control-Allow-Credentials "true"

This solved the problem for me,

best luck,

Martin.
