### ISSUE TITLE
OOB or URL-in-body fallbacks for stickers?

### ISSUE THREAD

**Issue by singpolyma** [movim/movim#968]
Just like for GIFs right now.

**Comment by edhelas** [comment]
It's already the case

```xml
<?xml version="1.0" encoding="UTF-8"?>
<message xmlns="jabber:client" to="edhelas@movim.eu" type="chat" id="421133eb-d87d-4bea-aea9-28b3557a925d">
   <thread>add43958-02ff-4288-9903-d7fe459a881a</thread>
   <active xmlns="http://jabber.org/protocol/chatstates" />
   <body>https://media.tenor.com/videos/c2730765d5f362e9e4e5c0de6a29e0b6/webm</body>
   <request xmlns="urn:xmpp:receipts" />
   <markable xmlns="urn:xmpp:chat-markers:0" />
   <reference xmlns="urn:xmpp:reference:0" type="data">
      <media-sharing xmlns="urn:xmpp:sims:1">
         <file xmlns="urn:xmpp:jingle:apps:file-transfer:4">
            <media-type>video/webm</media-type>
            <name>https://tenor.com/x6mD.gif</name>
            <size>40012</size>
            <thumbnail xmlns="urn:xmpp:thumbs:1" media-type="image/png" uri="https://media.tenor.com/images/28617706a0fbdf557723b70bd89f93ba/tenor.png" width="320" height="160" />
         </file>
         <sources>
            <reference xmlns="urn:xmpp:reference:0" type="data" uri="https://media.tenor.com/videos/c2730765d5f362e9e4e5c0de6a29e0b6/webm" />
         </sources>
      </media-sharing>
   </reference>
   <x xmlns="jabber:x:oob">
      <url>https://media.tenor.com/videos/c2730765d5f362e9e4e5c0de6a29e0b6/webm</url>
   </x>
   <origin-id xmlns="urn:xmpp:sid:0" id="00f2e113-abee-46b2-8d41-3f739cf61d8b" />
</message>
```

**Comment by edhelas** [comment]
Oh no sorry, it's for stickers.
Well no, it's not planned sorry.

**Comment by singpolyma** [comment]
>Oh no sorry, it's for stickers.
>Well no, it's not planned sorry.

Can I ask why not? What makes stickers special such that they should not be 
allowed fallbacks like other media?

**Comment by edhelas** [comment]
Because those Stickers are sent using https://xmpp.org/extensions/xep-0047.html
This a client-to-client protocol, there's no such thing as OOB or URL hosted links for those.
It's not that they are not available, it's just that there's no public URL to get them.

**Comment by singpolyma** [comment]
>It's not that they are not available, it's just that there's no public URL 
>to get them.

But aren't all the sticker images in the public/ folder of the movim pod?  
That's how they get embedded in the web UI so the user can select them, 
right? So could send that public URL... or did I miss something and those 
URLs are not public?

**Comment by edhelas** [comment]
Yes, but is this public folder actually public ? Those resources are actually available to the Movim users only.
There's a lot of Movim pods that are not public, all the files shared by Movim are not coming from Movim. I will not bother to implement HTTP Upload if I can simply host those files on Movim :p
