### ISSUE TITLE
Documentation of privacy aspects

### ISSUE THREAD

**Issue by devurandom** [movim/movim#97]
I could not find any information about this:
- When logging in using the Android app, for example, where will the JID and password be stored? Are you using a XMPP gateway architecture, where these credentials are transferred to the Movin Pod? Or will the client application connect to my own XMPP server and just inform the Movim server about my JID?
- You advertise "synchronised conversations". Does that mean that the content of my conversations are sent to the Movim Pods? Or do you mean: "We support MAM, if the server advertises it"?

**Comment by edhelas** [comment]
This issue was moved to movim/movim#5

**Comment by Ppjet6** [comment]
1. If I'm not mistaken, your credentials will go from your browser to the daemon listening on the pod via websockets, and then from the daemon to your xmpp server it's a regular tcp connection.
2. I think it refers to MAM.

**Comment by edhelas** [comment]
As explained in the documentation https://github.com/movim/movim/wiki/Install-Movim#general-behaviour Movim is between you and your XMPP server.  Movim is using MAM (http://www.xmpp.org/extensions/xep-0313.html) and Carbon (http://xmpp.org/extensions/xep-0280.html) to synchronize the conversations. The messages are also stored in a SQL database as a cached version.

When you login, you will send your JID and password and Movim will use it to login on the XMPP server. The password is never stored on Movim side (only kept in memory during the login process and then destroyed).
