### ISSUE TITLE
Unable to login to movim when using direct TLS

### ISSUE THREAD

**Issue by raspbeguy** [movim/movim#971]
When I enable direct TLS on my prosody server, movim can't login (shows a message "Le serveur met trop de temps à répondre"). This is on official instance mov.im.

I have to disable my _xmpps-client._tcp record to make it work again.

My log in prosody:

```
Feb 10 10:35:09 socket  debug   server.lua: auto-starting ssl negotiation...
Feb 10 10:35:09 socket  debug   server.lua: attempting to start tls on tcp{client}: 0x5581b0496c48
Feb 10 10:35:09 socket  debug   server.lua: accepted new client connection from 94.16.111.188:53516 to 5223
Feb 10 10:35:09 socket  debug   server.lua: ssl handshake done
Feb 10 10:35:09 c2s5581b0910210 info    Client connected
Feb 10 10:35:09 socket  debug   server.lua: client 94.16.111.188:53516 read error: closed
Feb 10 10:35:09 c2s5581b0910210 info    Client disconnected: closed
Feb 10 10:35:09 c2s5581b0910210 debug   Destroying session for (unknown) ((unknown)@(unknown)): closed
Feb 10 10:35:09 socket  debug   server.lua: closed client handler and removed socket from list
```

**Comment by edhelas** [comment]
Is it possible to have a test account then I can try to reproduce the issue ?

**Comment by lyn1337** [comment]
Prosody didn't support direct TLS back when this issue was posted, and will only with coming version 0.12.  (source: https://prosody.im/doc/configure)

**Comment by edhelas** [comment]
:+1:

**Comment by lyn1337** [comment]
prosody 0.12 with direct TLS support has just been released (used when srv records are present): https://blog.prosody.im/prosody-0.12.0-released/

**Comment by edhelas** [comment]
Movim supports DirectTLS for a few years now:

    uRq7ukOQ7unwW9ewQ9dE7YN9yMxbroFX : Picked DirectTLS
    uRq7ukOQ7unwW9ewQ9dE7YN9yMxbroFX : Connect to tls://nl.movim.eu:5223
    uRq7ukOQ7unwW9ewQ9dE7YN9yMxbroFX : XMPP socket launched
