### ISSUE TITLE
Images from "theme" directory fail when hosting Movim in subdirectory

### ISSUE THREAD

**Issue by citronalco** [movim/movim#972]
I noticed that when loading the login page "logo.svg" does not load when Movim is hosted not in the webroot but in a subdirectory (e.g. https://example.com/movim/). Same happens with the "empty.png" on the chat page.

In the CSS files an absolute URL is used instead of a relative for images from the "theme" subdirectory.
So instead of 
`background-image: url(/theme/img/logo.svg);`
it should probably (I'm not familiar with the Movim source) be
`background-image: url(../theme/img/logo.svg);`

A quick search revealed several places where absolute URLs are used, most likely not working when serving Movim from a subdirectory:
```
Snap/snap.css:    background-image: url(/theme/img/movim_cloud.svg);
Login/login.css:        background: url(/theme/img/logo_cloud.svg), radial-gradient(circle farthest-corner at right bottom,#5265ce 0,#213399 100%);
Login/login.css:    background-image: url(/theme/img/logo.svg);
Visio/visio.css:    background-image: url('/theme/img/movim_cloud.svg');
Onboarding/onboarding.css:    background-image: url(/theme/img/public.svg);
Onboarding/onboarding.css:    background-image: url(/theme/img/popups.svg);
```

**Comment by edhelas** [comment]
Thanks for the bug ;)
