### ISSUE TITLE
Wrong certificate expected when using SRV records

### ISSUE THREAD

**Issue by citronalco** [movim/movim#974]
I think there's something wrong with certificate validation when connecting to a server's SSL port ("legacy" SSL/directTLS) that got resolved via a SRV record:

Example DNS entry:
`_xmpps-client._tcp.jabberdomain.net.                 300 IN SRV 0 5 5225 xmpp.example.com.`

As far as I know in that case the connection should be made to xmpp.example.com, port 5225. But the certificate must be valid for jabberdomain.net.
Movim expects a certificate valid for xmpp.example.com instead. And in consequence fails to connect to the server.

I have no RFC/XEP at my hands, but that's what Gajim expects and what Prosody's documentation states ("your certificate simply needs to match whatever you have in your VirtualHost and Component definitions", https://prosody.im/doc/certificates).

Haven't checked what happens when using Movim with STARTTLS and SRV records. https://xmpp.org/extensions/xep-0368.html states it must be handled the same way.

**Comment by citronalco** [comment]
#971 seems to be the same issue, maybe also #947

https://xmpp.org/extensions/xep-0368.html ("SRV records for XMPP over TLS") references https://tools.ietf.org/html/rfc6120#section-3.2.1, which states that when using SRV records, the TLS certificate must belong to the "origin domain", not to the destination.
Movim does it the other way round and checks if the TLS certificate belongs to the destination, which is wrong and fails on correctly configured servers.

Edit: Seems like commit https://github.com/movim/movim/commit/d71b7320952f4b675d82dc3d2a2c6880a507549a is a dirty workaround for this issue, hiding this bug as long as the server offers other connection methods.

**Comment by citronalco** [comment]
Unfortunately Movim still does the cert checking wrong if SRV records are used.

**Example:**
I have a JID "user@jabberdomain.net"
If `jabberdomain.net` has a  `_xmpps-client`  SRV record pointing to `example.com`,
then `example.com` must have a valid TLS cert for **jabberdomain.net** and not for example.com. Movim expects the latter and fails on correctly set up servers that do not have both hostnames in a single cert by chance.

**Fix (not really):**
I barely can read PHP, so the code below is some sort of pseudo code and does not work (yes, $session is still undefined at this level).
In `linker.php`
```
$connector = new React\Socket\HappyEyeBallsConnector(
    $loop,
    new React\Socket\Connector([
        'timeout' => 5.0,
        'tls' => [
            'SNI_enabled' => true,
            'allow_self_signed' => false,
            'peer_name' => $session->get('host')  //  <- add this line to check the cert correctly
        ],
    ]),
    $dns
);
```

**Comment by aereaux** [comment]
I believe I'm running into this problem with my own server.  Is there some workaround I can apply on prosody's side?

**Comment by Neustradamus** [comment]
To follow

**Comment by edhelas** [comment]
Bump

**Comment by aereaux** [comment]
Any idea if this fix should be applied to https://mov.im/?  I'm still getting the same error when trying to connect to my instance.
