### ISSUE TITLE
Blog post disappears

### ISSUE THREAD

**Issue by archerships** [movim/movim#976]
JID:  archerships@movim.eu
URL:  https://mov.im
Description:  

When I updated a blog post, the text disappeared from the blog post, even though the the text was still in the editing form when I edited it.  I've confirmed that the error 1) happens in new blog posts, 2) happens even if Brave shields are turned off and UBlock Origin is turned off 3) happens even after logging out and logging back in.  Not all blog posts disappear though--for example, a blog post about the specific text below was published normally. 

Here's the post's public URL:

[https://mov.im/?blog/archerships/cf51af03-ce5c-43d1-bacf-44b540a3ac90](https://mov.im/?blog/archerships/cf51af03-ce5c-43d1-bacf-44b540a3ac90) 

Here's a screenshot of the text in the edit window: 

![Screenshot of text in edit window](https://upload.movim.eu/files/05425fca065746d3692f7c2e643536a4e1dfedda/RVuZSXCl0e13/Screenshot_from_2021-02-12_03-48-00.png)

Here is the text (everything below the horizontal rule):

-----

Playing with Mov.im.  So far it seems very nice.  I'll post questions (and answers) as I find them here: 

Open Questions:
* Can I set up my own subdomain (movim.abue.la) to point to my  Mov.im hosted account? 
* Can I purchase more space to store more of my own photos/videos/media? 
* How much server space are we allocated for image/message storage?  
* Is there a wiki for collecting/storing the answers to these questions?
* Can we purchase more storage space for images / video? 
* I run a FB group with 6000+ members.  Public channels seem to be the way to go, if I wanted to move them over, but chatrooms / channels are currently limited to 200 members.  Is the size of the public channels a hard limit?    Can that be increased? 
* What's the difference between a chatroom, channel, and community? 

Answered 
* Is the [Official Movim Chatroom] the best place to ask newbie questions? "All questions are good, be patient for the answer."
* Is OMEMO implemented yet?  No
* Do Mov.im and Dino clients sync with each other?  For example, if I subscribe to a chatroom in Dino with the same account, do I also become subscribed in mov.im?  No
* Is there a way to mute notifications on a community by community basis?  No
* How long can we expect our Mov.im posts to stay up?  Indefinitely
* What's the degree of privacy in the private chatrooms?  Can server admins read messages?  Server admins read messages in both public/private chatrooms, except if you use OMEMO
* Is Patreon your preferred donation method? Yup, or PayPal. 
* Is there an IRC <-> Movim gateway? 
* Is there a Matrix <-> Movim gateway? 
* Standard Notes <-> Movim sync.  
* Is there an html/CSS only UI?  (For use with Tor sites)

Bug Reports
* Updating a large note appears to have caused the note to disappear.  Preview shows "version="1" and no other text.  However, when I edit the post, the missing text is there. 
* Links to blog posts published to Facebook are munged.  

Feature Requests

* After updating a new blog post, the UI should take me to the blog post, not the feed. 
* Make it possible to mute notifications for chatrooms/channels/communities individually. 
* Allow people to use custom domain for movim hosted service. 
* Remove limit on number of allowed members in chatrooms.  Allow number of chat participants to grow to purchased bandwidth/storage 
* FB to Mov.im web clipping extension, i.e. turn FB post into Movim Markdown and post. 
* Twitter to Mov.im web clipping extension, i.e. turn FB post into Movim Markdown and post.
* Keep version history of blog posts.

**Comment by edhelas** [comment]
As I'm only handling one issue per ticket, can you please remove everything that is not related to the bug itself in your description. Feel free to open some other tickets for bugs (that can be reproduced) or features that you would like to see (do not spam with everything that you have in mind :p)

**Comment by edhelas** [comment]
(sorry, misunderstanding, this is actually the text from your post, not from the ticket)
