### ISSUE TITLE
Facebook breaks links to Movim blog posts

### ISSUE THREAD

**Issue by archerships** [movim/movim#977]
Facebook breaks links to Movim blog post links.  If you post a link to a Movim blog post on Facebook, the content and preview are posted, but if you click the link to go back to blog post, you get a 404 error from Movim.  I believe it's the same issue described in this PrivateBin bug report:   

https://github.com/PrivateBin/PrivateBin/issues/396

I realize that you're under no obligation to try to deal with FB's shenanigans.  But I would like to invite my friends to switch from FB to Movim.  And if they find that they can't share their Movim blog posts to their friends who stay on FB, most will likely just give up and go back to FB.  In any case, thanks for taking the time to review my bug report.  

Here's the link on Movim:

https://mov.im/?blog/archerships/f8e62cb7-715f-436a-8822-124f57dc499c

Here's how a Facebook post with the link looks: 

https://www.facebook.com/archerships/posts/10159511205415312

Here's what the FB link looks like before clicking: 

https://l.facebook.com/l.php?u=https%3A%2F%2Fmov.im%2F%3Fblog%252Farcherships%252Ff8e62cb7-715f-436a-8822-124f57dc499c%26fbclid%3DIwAR3MA-QLi6jOjCf_zbE7iqYgjF30_Af9RhgDJbGG31-QQHFOhShH2WWrSMg&h=AT3qEWu5ZChimLPbHoUh8EJ0g1WktPppdsjgC5dQ94z-EpDAsoJkqDCu3ywmXOhd8LC7kcYoue9sLELg19lPuxibQGu7TIlRiP9q9zNi_AbvkeiIkXFfT_eA9NaPyIjupA&__tn__=%2CmH-R&c[0]=AT3snUgbDrjgQHaJ1Hn_I4xexWG-Lup9q68LclNuH62iB0lhB4Bk6QOoznA91y6TMzbnXzUZiwCZH-XJv-TwJ0XBLNPUrL1EDrrY9IQTiPOcY3XE1eQ9_IPgcKWvCGSLKPCY

Here's the link that is sent to movim: 

https://mov.im/?blog%2Farcherships%2Ff8e62cb7-715f-436a-8822-124f57dc499c&fbclid=IwAR3MA-QLi6jOjCf_zbE7iqYgjF30_Af9RhgDJbGG31-QQHFOhShH2WWrSMg

The links works if you put it behind a link shortener first: 

http://bit.do/mv1test

**Comment by edhelas** [comment]
Is it really a Movim bug ?

**Comment by edhelas** [comment]
Well those Movim blog URLs are perfectly valid to me and I'm already share them around in many place successfully.
It seems that Facebook doesn't like them (maybe the ? in them, I don't know). As I'm not planning to change the whole URL design to comply with Mark Zuckenberg social network I'll close that one. Feel free to find his bug tracker and file a bug there :D
