### ISSUE TITLE
Handle Jingle Proposals in Carbons

### ISSUE THREAD

**Issue by psycotica0** [movim/movim#980]
While testing some things I had Gajim open. My Gajim has a priority greater than 0, and so all messages sent to me during that time were sent to Gajim, but were forwarded to my Movim. Everything is working fine.

But, when a jingle call came in, the [Jingle Message Initiation](https://xmpp.org/extensions/xep-0353.html) message was sent to Gajim, which didn't know anything about it, and only forwarded to Movim. This didn't cause any ringing, and the caller just thought I hadn't picked up.

To clarify, here's what Movim received:

```xml
<message to='[redacted]' from='[redacted]' type='chat'>
  <received xmlns='urn:xmpp:carbons:2'>
    <forwarded xmlns='urn:xmpp:forward:0'>
      <message to='[redacted]' xmlns='jabber:client' from='[redacted]' id='proposal%215be5e3740f1d48' type='chat'>
        <propose id='215be5e3740f1d48' xmlns='urn:xmpp:jingle-message:0'>
          <description media='audio' xmlns='urn:xmpp:jingle:apps:rtp:1'/>
        </propose>
        <stanza-id xmlns='urn:xmpp:sid:0' by='[redacted]' id='FUlsaSEOfjK2iI1a'/>
      </message>
    </forwarded>
  </received>
</message>
```

**Comment by edhelas** [comment]
If i remember the first message need to be sent to the bare-jid. There's is no Jingle Message Initiation handling within carbon in Movim.

**Comment by psycotica0** [comment]
Yeah, the first message is sent to the bare-jid, but since Gajim has priority, that means it receives the message instead of Movim.

It's good to know that this isn't expected to work, but I think it would be nice if it did work.
So consider this a feature request :wink:
