### ISSUE TITLE
Client has stopped working on UbuntuTouch

### ISSUE THREAD

**Issue by mass34** [movim/movim#981]
Shows a black screen at startup
[open-store](https://open-store.io/app/eu.movim.ut.movim)

![image](https://user-images.githubusercontent.com/18635003/111882337-1a238f00-89c6-11eb-8b33-b92ab50f5633.png)

**Comment by edhelas** [comment]
I don't do Ubuntu Touch support unfortunately. Try the find the person in charge of the package.
