### ISSUE TITLE
Please, provide full Nginx configuration example

### ISSUE THREAD

**Issue by Revertron** [movim/movim#988]
As the title says. It is impossible to find one working example of Nginx configuration for Movim on the Internet.
Is it a secret of some sort?

**Comment by Natureshadow** [comment]
>As the title says. It is impossible to find one working example of Nginx configuration for Movim on the Internet.
>Is it a secret of some sort?
>

What's wrong with the example shipped with Movim?

**Comment by Revertron** [comment]
It's not an example, it is a piece of config.

**Comment by kawaii** [comment]
That's because there simply is no one-size-fits-all solution or config to account for all infrastructure setups.

For example, here's my own - but I expect it's useless for you and won't work.
```nginx
index index.php index.html;

root /var/www/html/public;

location / {
    try_files $uri /index.php?$args;
}

location ~ \.php$ {
    try_files $uri =404;
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    fastcgi_pass movim-http;
    fastcgi_index index.php;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
}

location /ws/ {
    proxy_pass http://movim-ws;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect off;
}

location /picture {
    include fastcgi_params;
    add_header X-Cache $upstream_cache_status;
    fastcgi_ignore_headers "Cache-Control" "Expires" "Set-Cookie";
    fastcgi_cache nginx_cache;
    fastcgi_cache_key $request_method$host$request_uri;
    fastcgi_cache_valid any 1h;
}
```

**Comment by Natureshadow** [comment]
>It's not an example, it is a piece of config.

It **is** an example, obviously.

What is your expectation? Maybe define what an "example" is in your world?

I am the de facto maintainer of nginx support in Movim and as it currently stands, as long your behaviour does not change, I refuse to help you. Should you find a way to ask a specific question or otherwise communicate in an appropriate way, feel free to come back.

**Comment by Revertron** [comment]
Okay, I'll just give a number of examples, how it is appropriate to show users an example of Nginx config:
https://docs.mattermost.com/install/config-proxy-nginx.html
https://docs.nextcloud.com/server/21/admin_manual/installation/nginx.html
https://github.com/matrix-org/synapse/blob/master/docs/reverse_proxy.md

Or even like this will be enough:
https://pve.proxmox.com/wiki/Web_Interface_Via_Nginx_Proxy

Do you, @Natureshadow, think, that `location /ws/` part is enough to configure for Movim? And how users are supposed to find that `proxy_pass` for PHP is needed too? And what about `root` part? How can we get that it needs to point to `movim/public/` directory?

**Comment by Natureshadow** [comment]
> Okay, I'll just give a number of examples, how it is appropriate to show users an example of Nginx config:

These are not examples, these are configuration guides. They do contain some examples (which are of the same sort as the example shipped with Movim).

You can find such a guide here: https://github.com/movim/movim/wiki/Install-Movim

(Do mind that, as explained in the guide, the web server configuration for Apache and nginx is printed on startup of the Movim daemon, readily filled in with dynamic information like paths, etc.).

> Do you, @Natureshadow, think, that `location /ws/` part is enough to configure for Movim?

Of course not. That's why there is more config in the example. You also need the other parts.

> And how users are supposed to find that `proxy_pass` for PHP is needed too?

Well, any `proxy_pass` directive needed can be found in the example config. That's how users are supposed to find it.

> And what about `root` part? How can we get that it needs to point to `movim/public/` directory?

By copying/pasting/reading/whatever the configuration generated by Movim on first start and printed to console.


If you think you can write a better guide, do it. But stop offending developers here.

**Comment by Revertron** [comment]
> By copying/pasting/reading/whatever the configuration generated by Movim on first start and printed to console.

If you are referring to daemon start, then you are wrong. It contains the same snippet from a repo. Yes, with modified port.
This is all I've got:
```
--- Server Configuration - nginx ---
Add this in your configuration file
location /ws/ {
    proxy_pass http://127.0.0.1:8888/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_redirect off;
}
```
_Add this in your configuration file_ - but I have no configuration file!
As of your guide, do you think I didn't read it? I've lost about 4-5 hours in that "guide".

**Comment by Natureshadow** [comment]
> _Add this in your configuration file_ - but I have no configuration file!

You should go find a general tutorial on how to use nginx and PHP, then. Learning the basics is a precondition for hosting any software, and it is not necessary for each and every project to repeat basics like "how do I make a webserver serve a directory".

**Comment by Revertron** [comment]
> serve a directory

Did you write somewhere which directory it should be?

**Comment by Natureshadow** [comment]
>Did you write somewhere which directory it should be?

No, not explicitly.

Now that you figured it out, just go and edit the wiki and everyone will be thankful.

Still no need to passive-aggressively rant at maintainers.

**Comment by edhelas** [comment]
I think that the discussion was pretty clear. There is no "one-size-fit-all config" for nginx or Apache when you setup Movim. We can provide some hints and "default" config extracts (like the one generated when you launch the daemon).

If such config exists and we provide it, we have lot of chances that it will break and/or confuse a big majority of the admins that will think that "this config must work".

I prefer to give hints and explain what is actually done :)

In a way, you already have those "default" configs there https://github.com/movim/movim/tree/master/etc 
Those are actually telling you "how it should look like". If you think that some things are missing, feel free to do a pull request on those files.
