### ISSUE TITLE
Disconnect issue on Windows Phone 8.1 + IE

### ISSUE THREAD

**Issue by src386** [movim/movim#99]
Logged on Movim,
Click on the menu icon -> Click on my Name.
Nothing happens.
Click anywere, the status window appears. 
Click on "Se déconnecter", nothing happens.

Tester on nl.movim.eu pod.

**Comment by edhelas** [comment]
This only happens on Windows Phone 8.1 or also in Chrome/Firefox… ?

**Comment by src386** [comment]
Only on Windows Phone 8.1 + IE.
On a desktop with Firefox it's working.

**Comment by edhelas** [comment]
This issue was moved to movim/movim#4
