### ISSUE TITLE
Clicking on "write a new post..." crash the audio connection

### ISSUE THREAD

**Issue by ghost** [movim/movim#994]
# Platform
Operating System: Gentoo
Ejabberd version: 21.04
Movim version: 0.19
Browsers: Firefox and Brave

# Summary
Clicking on "write a new post..." as owner of a publish-subscribe node, the audio connection crash, the floating window is closed and the user session is closed. 

# Steps to Reproduce
- Select an user in the chats list and establish an audio call.
- In a new tab on your instance open https://movim.domain.tld/?explore/servers ( Communities servers - Discover, follow and share )
- Select a publish-subscribe communities server
- Select a community node
- As owner of the node click on "write a new post"

# Actual Result:
- Audio connection crash, floating window closed and user session closed.

# Reproducible 
Yes. On both sides with Firefox and Brave

**Comment by edhelas** [comment]
I can't actually reproduce the issue. There is no link at all between the two features. I'm more thinking that you simplify have a crash on the PHP side while trying to write a post, please check the `log/errors.log` file to find some fatar errors :)
