### ISSUE TITLE
Display adult content doesn't works as expected

### ISSUE THREAD

**Issue by ghost** [movim/movim#995]
# Description
When "Display adult content" from the Movim Configuration settings is not enabled, some URLs are still displayed and available in clear text.

# Actual Result
URLs are still displayed and available in clear text.

# Expected Result
URLs should not be displayed at all.

# Enhancement Proposal
It should be possible to blacklist a Publish-Subscribe root node ( nsfw.domain.tld ) related to Adult content and not only blur the content of a PubSub node.

**Comment by edhelas** [comment]
Which URLs are we talking about, you mean URLs that are in the post contents ? 
Filtering adult content are based on a few rules:
- Posts that are tagued as #nsfw and that are coming from "nsfw.server.tld" are considered NSFW
- When filtering is enabled, those communities and public suggestions are hidden in the UI
- If you are subscribed to a community, the posts published are showed, but blurred

If there is something different than that, it could be a bug.

**Comment by ghost** [comment]
Some posts contain URLs which are preceded by a trombone type symbol. These URLs are available in clear text and you can click or copy/paste the URL to access to the content available on external website.

EDIT:

> "When filtering is enabled, those communities and public suggestions are hidden in the UI"

Do you mean that I should not be able to see the nsfw node from the https://movim.domain.tld/?explore/servers . It should be hidden ? because it's not the case when "Display adult content" is not enable from my configuration setting on my instance.

**Comment by edhelas** [comment]
If the rules above doesn't apply I don't have a way to detect what is NSFW and what is not without going Zuckerberg style and process the actual content of the posts. 

Anyway, it seems that here we're talking about posts with attachments that are URLs to NSFW content. To me that's a non issue. 

If you have an actual example that doesn't respect the 3 rules posted previously, feel free to open a new ticket with the example then I can try to reproduce the issue.

**Comment by edhelas** [comment]
I had an issue in the NSFW tag detection. This might have been your issue in the end https://github.com/movim/movim/commit/4620f729ee86d87a23c80aad207236838ce44346 :)
