### ISSUE TITLE
Setting the option "XMPP URI of Associated Publish-Subscribe Node" fails

### ISSUE THREAD

**Issue by ghost** [movim/movim#996]
# Platform
Movim version: 0.19

# Description
In the Configuration of room, setting the option "XMPP URI of Associated Publish-Subscribe Node" fails

# Steps to Reproduce
- In a chatroom go to Administration
- Fill up the field "XMPP URI of Associated Publish-Subscribe Node" as explained in the XEP https://xmpp.org/extensions/inbox/pubsub-uri.html in my case as an example "xmpp.pubsub:home.syntazia.org/"

# Actual Result
- "bad value of field muc#room_config_pubsub of ty..." The end of message is unfortunately cut

# Expected Result
- Unless I'm mistaken it should work.

# Enhancement Proposal
- If it turns out that the error actually comes from my side, as an example display in the field what the URI should look like.

**Comment by edhelas** [comment]
The actual URI that you need to enter is the following one I think https://xmpp.org/extensions/xep-0060.html#impl-uri

**Comment by edhelas** [comment]
Yes, I confirm :) For the Movim blog it is `xmpp:pubsub.movim.eu?;node=Movim`. Once this is configured Movim will directly display a link to the related community in the Chatroom header.

**Comment by ghost** [comment]
Thanks, I will test this.
